APSIMInitiative/ApsimX

Models/Summary.cs
=> Use row indices that are correct for newly created datastores.

ApsimNG/Utility/FindAndReplaceForm.cs
=> Allowed the find and replace form to be closed via the escape key.

Models/Plant/Organs/Leaf.cs
=> force leaf to recalculate biomass outputs when leaf is cleared.

Setup/apsimx.iss
=> Include the Bin\Tools folder in the Windows distribution.

ApsimNG/Views/GraphView.cs, Models/Core/IStorageReader.cs, Models/Core/Runners/RunOrganiser.cs, Models/Core/Simulation.cs, Models/Factorial/Experiment.cs, Models/PostSimulationTools/PredictedObserved.cs, Models/Storage/DataStore.cs, Models/Storage/Table.cs, Tests/UnitTests/MockStorage.cs, Tests/UnitTests/TestDataStore.cs
=> Add units to graphs again and fix placement of labels on Event Graphs

Models/Plant/Organs/RootZoneState.cs
changing the DM initializing method in root zone, make it depends on root length
=> initializing dry mass in zone 

Models/Summary.cs
=> Fix problem of no dates showing in summary file

ApsimNG/Presenters/FactorControlPresenter.cs, Models/Factorial/Experiment.cs
=> Fixed simulation display names

Models/PostSimulationTools/ExcelInput.cs
=> Allowed shared reading when opening Excel input files.

Tests/UnitTests/APITest.cs
=> Removed unit test.

ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Views/MainView.cs
=> Call Application.Quit only if the Application loop is actually running.

Models/Core/ApsimFile/Converter.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Plant.cs
=> Right, let's try yet again!!!!

Prototypes/Grapevine/grapevine.apsimx
=> setting up the interrow

ApsimNG/Commands/BibTeX.cs
=> Fixed autodoc references for PhD theses.

Models/Core/Runner.cs
=> Added _Factors table back into .db file

Models/Plant/Organs/Leaf.cs
Added removeNodeNumber argument into BiomassRemove type and made leaf use this to remove cohorts when defoliated resolves #2421
=> Implement stuff to remove leaves on defoliation

Models/Soils/InitialWater.cs
=> Fixed problem of not being able to add InitWater model to soil

ApsimNG/Presenters/FactorControlPresenter.cs, ApsimNG/Views/FactorControlView.cs
Resolves #2344 
Just right click on the simulation(s) you want to run, and select 'run this simulation' from the context menu.
=> Added the ability to run a single simulation from the experiment table.

ApsimNG/Commands/MoveModelUpDownCommand.cs, Tests/UnitTests/APITest.cs
=> Avoid pulling Gtk into the API unit tests.

Models/Summary.cs
=> Fix summary file problem after .db conversion from old format

Models/Plant/Phenology/BuddingPhase.cs, Prototypes/Grapevine/grapevine.apsimx
=> updating the grapevine model, fix the bug of apexnum

Models/Plant/Arbitrator/OrganArbitrator.cs, Models/Plant/PlantTypes.cs
A new supply demand ratio that does not include storage demand which is useful when calculating carbon stress
=> A new supply demand ratio that does not include storage demand

Models/Factorial/Factor.cs
=> Fixed bug with some compound factorials not working.

ApsimNG/Views/GridView.cs, ApsimNG/Views/IntellisenseView.cs
=> Fix intellisense bug in grid: not remembering selected intellense item.

Prototypes/Oats/Oats.apsimx
=> Turning N limitation on photosynthesis back on

ApsimNG/Views/MainView.cs
=> Try to ensure that all instances exit cleanly.

Tests/Simulation/SoilNitrogenPatch/PseudopatchTesting.apsimx
=> Added pseudopatch test simulation

Models/Plant/Organs/PerennialLeaf.cs
=> Added leaf detachment to perrenial leaf

ApsimNG/Commands/ExportNodeCommand.cs
=> Show ApsimX version string in auto-docs.

Models/Plant/Organs/Leaf.cs
=> Export leaf cohort variables

ApsimNG/Interfaces/IExplorerView.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Views/ExplorerView.cs
Resolves #2485 
Option is accessible via the right click context menu on any node.
=> Added an option to show IncludeInDocumentation status of each node.

Models/Plant/Organs/Leaf.cs
=> fixing infinite loop issue in leaf

ApsimNG/Views/GridView.cs
=> Immediately save enum property change

ApsimNG/Presenters/ExplorerPresenter.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/RootZoneState.cs
Resolves #2393 
Also removed an (unrelated) unused field from ExplorerPresenter.
=> Renamed a root zone state property

ApsimNG/Views/GridView.cs
=> Fixed a crash when shift clicking a column header

ApsimNG/Views/GridView.cs
=> Stability improvements for the GridView.

ApsimNG/Classes/GridCell.cs, ApsimNG/Classes/GridColumn.cs, ApsimNG/Utility/Configuration.cs, ApsimNG/Views/EditorView.cs, ApsimNG/Views/GridView.cs
=> Editor styles

APSIM.bib
=> Update bib File to include references for Eucalypt model.

ApsimNG/Views/GridView.cs
Working on #2400 
I'm not really working on that issue, this is a fix for the crash that Peter described in a comment on that issue.
=> Fixed a crash when clicking on a column header in the data store.

ApsimNG/Views/EditorView.cs
=> Editor style sub menu now uses ticks.

Models/Plant/Organs/Root.cs
=> Restore Nconc for root

Models/Grazplan/Supplement.cs, Models/Settings.StyleCop, Models/Stock/animgrp.cs, Models/Stock/graztype.cs, Models/Stock/stock.cs, Models/Stock/stock_ent.cs, Models/Stock/stock_intf.cs, Models/Stock/stock_manage.cs, Models/Stock/stock_padd.cs, Models/Stock/stock_vars.cs, Tests/Simulation/Animals/StockFeedlot.apsimx
=> Refactoring code. Many name changes and style fixes.

Models/AgPasture/AgPasture.PastureSpecies.Organs.cs, Models/Plant/Biomass.cs
=> Added Live and Dead properties to AgPasture ready for STOCK

Models/AgPasture/AgPasture.PastureSpecies.Organs.cs
=> Added grazing biomass removal to AgPasture organs

ApsimNG/Commands/ChangeProperty.cs, ApsimNG/Presenters/MapPresenter.cs, ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Presenters/XYPairsPresenter.cs, ApsimNG/Views/MapView.cs, Models/Map.cs
=> Use Command pattern to allow undo-redo of map changes.

Docs/content/ModelDocumentation/_index.md
=> Fix model documentation link

ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Forms/UpgradeForm.cs
=> Use https when accessing resources on apsim.info site.

APSIM.bib
=> Updated bib file for oats documentation.

ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs, Models/Core/Attributes/DisplayAttribute.cs, Models/SurfaceOrganicMatter.cs
=> Select surface OM types from a drop-down list.

Models/Summary.cs
=> Provide a link to the start of the simulation log in the summary.

ApsimNG/Commands/ExportNodeCommand.cs, Models/Soils/Analysis.cs, Tests/Validation/Wheat/Wheat.apsimx
=> Widen map in auto-documentation so entire world just fits.

Models/Lifecycle/Lifecycle.cs
=> Warn when no initial population for the cohort

APSIM.bib
=> Added missing reference for Eucalypt model.

Models/Stock/stock.cs
=> Fix biomass removal in RemoveHerbageFromPlant()

Models/AgPasture/AgPasture.PastureSpecies.Organs.cs, Models/Stock/stock.cs, Models/Stock/stock_padd.cs
=> Stock biomass removal of AgPasture

ApsimNG/Views/GridView.cs
Working on #2567 
Not a perfect solution, but at least a slight improvement.
=> Add an arrow to indicate drop-down entries.

Models/Stock/stock_padd.cs
=> Removal proportions calculated better

ApsimNG/ApsimNG.csproj, ApsimNG/Views/MapView.cs, Setup/Linux/BuildDeb.bat
=> Fix little typos causing problems on Mono-based systems.

ApsimNG/Presenters/IntellisensePresenter.cs, ApsimNG/Presenters/OperationsPresenter.cs, ApsimNG/Views/EditorView.cs
=> Stability improvement for intellisense in operation presenter.

ApsimNG/Presenters/IntellisensePresenter.cs, ApsimNG/Presenters/OperationsPresenter.cs, Models/Operations.cs, Models/Report/Report.cs
=> Allow a "//" to comment out lines in Report and Operations

ApsimNG/Presenters/CultivarPresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs
=> Fix crash caused by intellisense in cultivar presenter.

Models/Plant/Functions/TrackerFunction.cs
=> Small fix to get TrackerFunction working correctly

Models/Plant/Organs/Leaf.cs
=> Reset apexGroupSize

ApsimNG/Presenters/IntellisensePresenter.cs
=> Avoid use of the "??" operator, as it is not supported in VS 2015.

Models/Plant/Organs/LeafCohort.cs
=> Fix SLA is less than minimum SLA

ApsimNG/ApsimNG.csproj, ApsimNG/Commands/SupplementCommands.cs, ApsimNG/Presenters/SupplementPresenter.cs, ApsimNG/Views/SupplementView.cs, Models/Grazplan/GrazSupp.cs, Models/Grazplan/Supplement.cs
=> Get undo/redo of supplement edits working.

ApsimNG/Resources/Glade/SupplementView.glade
=> Clarified units on Supplement user interface

Models/Storage/DataStore.cs, Models/Storage/Table.cs
=> Improve compatibility with old .db files.

ApsimNG/Interfaces/IInitialWaterView.cs, ApsimNG/Presenters/InitialWaterPresenter.cs, ApsimNG/Views/InitialWaterView.cs, Models/Soils/InitialWater.cs
=> Improve editing of initial soil water.

Models/Core/Model.cs, Models/Lifecycle/Cohort.cs, Models/Lifecycle/Lifecycle.cs, Models/Lifecycle/Lifestage.cs, Models/Lifecycle/LifestageProcess.cs, Models/Lifecycle/LifestageReproductionProcess.cs
=> Modify life cycle class names

ApsimNG/Resources/Glade/MemoView.glade, ApsimNG/Views/MemoView.cs
=> Added a help button on MemoView to take user to Markdown documentation.

Models/IIrrigation.cs, Models/Irrigation.cs, Tests/UnitTests/MockIrrigation.cs
=> Added in fertigation optional arguments to irrigation.apply

APSIM.bib, ApsimNG/Classes/HtmlToMigraDoc.cs, Models/Core/AutoDocumentation.cs, Models/Memo.cs
Working on #2655 
Still a bit more to do to get Blockquotes and list elements with wrapped text or multiple paragraphs rendering correctly.
=> Do a better job of converting Markdown to PDF.

ApsimNG/Presenters/PropertyPresenter.cs
=> Fixed GUI category strings

Models/Plant/Phenology/Phenology.cs
=> Only rewind phenology if the plant is in a phase that can be rewound

ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Views/GraphView.cs
=> Prevent crash in graph view when selecting a string variable.

Models/Clock.cs
=> Change the event ordering for DoStock 

Models/Stock/animprm.cs
=> Ensure peak milk calculation works for dairy breeds

ApsimNG/ApsimNG.csproj
=> Lifecycle images renamed

Models/Stock/stock_intf.cs
=> Wean all/both

Models/AgPasture/AgPasture.PastureSpecies.cs, Models/Core/Attributes/LinkAttribute.cs, Models/Core/IPlant.cs, Models/Core/IVariable.cs, Models/Core/Links.cs, Models/Core/Variable.cs, Models/Core/VariableComposite.cs, Models/Core/VariableExpression.cs, Models/Core/VariableMethod.cs, Models/Core/VariableProperty.cs, Models/Plant/OilPalm/OilPalm.cs, Models/Plant/Plant.cs, Models/Plant/SimpleTree/SimpleTree.cs, Models/Sugarcane/Sugarcane.cs
=> Allow links to be properties and added AboveGround to IPlant

ApsimNG/Views/EditorView.cs
=> Don't generate intellisense for numbers in manager scripts.

Prototypes/Grapevine/grapevine.apsimx
=> the effect of temperature before budburst on flower no was updated

ApsimNG/Views/EditorView.cs, ApsimNG/Views/IntellisenseView.cs
=>  Don't use language features that aren't compatible with VS2015.

Models/Lifecycle/Lifestage.cs, Models/Lifecycle/LifestageProcess.cs
=> Accumulate mortality when more than one mortality process used

Models/SurfaceOrganicMatter.cs
=> Part one of refactoring, will do more next friday

ApsimNG/Classes/HtmlToMigraDoc.cs, Docs/content/Usage/Memo.md, Models/Resources/Chicory.xml, Models/Resources/Plantain.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml, Tests/Validation/Slurp/Slurp.apsimx
=> Improve table formatting in Markdown HTML to PDF conversion.

Models/AgPasture/AgPasture.PastureSpecies.cs
=> update logic to partition biomass on RemovedDM

ApsimNG/Views/GridView.cs
=> Stability improvements for copy/pasting to/from grids.

ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs
=> Make grid insensitive rather than invisible when no data is present.

ApsimNG/Presenters/MainPresenter.cs
=> Display inner exception when reporting an error.

ApsimNG/Views/GridView.cs
=> Fix grid control not showing data. Undo fix of Eric a few days ago.

ApsimNG/Presenters/DataStorePresenter.cs
=> Fix problem with datastore values not being displayed

Examples/SWIM.apsimx, Models/Soils/SWIM/Swim.cs
=> Get SWIM working with cover and crops.

Setup/Linux/BuildDeb.bat
=> Get a "Models" command working from the Linux shell

Models/Clock.cs
=> Remove testing code.

Models/Weather/Weather.cs
=> Add UTF-8 BOM so degree character is read correctly

ApsimNG/Menus/ContextMenu.cs
=> Added check for null reference

ApsimNG/Presenters/AzureJobDisplayPresenter.cs, ApsimNG/Presenters/CLEMFileSQLiteGRASPPresenter.cs, ApsimNG/Views/CloudJobDisplayView.cs, ApsimNG/Views/DirectedGraphView.cs, ApsimNG/Views/MainView.cs, Docker/Jenkinsfile, Docker/build/compileng.bat, Docker/runtests/master.bat
=> Minor documentation syntax fixes.

ApsimNG/Commands/SupplementCommands.cs, ApsimNG/Interfaces/ISupplementView.cs, ApsimNG/Presenters/SupplementPresenter.cs, ApsimNG/Views/SupplementView.cs, Models/Core/ApsimFile/Converter.cs, Models/Grazplan/GrazSupp.cs, Models/Grazplan/Supplement.cs, Models/Stock/animgrp.cs, Models/Stock/grazparam.cs, Models/Stock/stock.cs, Models/Stock/stock_intf.cs, Models/Stock/stock_padd.cs, Models/Stock/stock_vars.cs, Tests/Simulation/Animals/Stock.apsimx, Tests/Simulation/Animals/StockFeedlot.apsimx
=> Refactor GrazPlan Supplement improving class names, layout and var names

ApsimNG/Presenters/DataStorePresenter.cs, ApsimNG/Resources/Glade/GridView.glade, ApsimNG/Views/GridView.cs, Models/Storage/DataStore.cs
=> Made improvements to display of "fixed" grid columns

ApsimNG/Commands/RunCommand.cs, Models/Clock.cs, Models/Core/Runner.cs, Models/Core/Runners/RunOrganiser.cs, Models/IClock.cs, Tests/UnitTests/MockClock.cs
=> Enabled tracking of progress within simulations.

Models/Core/Model.cs, Models/Models.csproj, Models/Plant/Organs/Leaf.cs, Models/Plant/Phenology/Phases/BuddingPhase.cs, Models/Plant/Phenology/Phases/EmergingPhase.cs, Models/Plant/Phenology/Phases/EndPhase.cs, Models/Plant/Phenology/Phases/GenericPhase.cs, Models/Plant/Phenology/Phases/GerminatingPhase.cs, Models/Plant/Phenology/Phases/GotoPhase.cs, Models/Plant/Phenology/Phases/IPhase.cs, Models/Plant/Phenology/Phases/LeafAppearancePhase.cs, Models/Plant/Phenology/Phases/LeafDeathPhase.cs, Models/Plant/Phenology/Phases/NodeNumberPhase.cs, Models/Plant/Phenology/Phenology.cs, Models/Plant/Phenology/Responses/Vernalisation.cs, Models/Plant/Structure/Structure.cs, Models/Resources/Chicory.xml
=> Phenology refactor

Models/Core/ApsimFile/Converter.cs
=> Fix bug with factors showing on graph.

Models/Core/Interfaces/ISimulationEngine.cs, Models/Core/Runners/RunSimulation.cs, Models/Core/Simulation.cs, Models/Core/Simulations.cs, Models/Factorial/Experiment.cs, Models/Morris/Morris.cs
=> Refactored slightly to avoid issuing an unnecessary "Loaded" event.

Models/Plant/Biomass/Biomass.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/RootZoneState.cs
=> Refactor of Biomass Class

Models/Core/ApsimFile/Converter.cs
=> Graph fix again

Tests/Validation/System/LincolnRotation2017/RainshelterRotationSim.apsimx
=> fixed ref in manager

Models/Irrigation.cs
=> final clean up of Irrigation

Models/Core/ApsimFile/Converter.cs, Models/Plant/Plant.cs, Models/Resources/Maize.xml, Models/Resources/Potato.xml
=> Refactoring Plant.cs

Models/Core/Checkpoints.cs, Models/Core/Simulations.cs, Models/Models.csproj, Models/Plant/Organs/Leaf.cs
=> Checkpoints

Models/Stock/stock.cs
=> Stock events logged to the Summary.

Models/Grazplan/Supplement.cs, Models/Stock/stock.cs, Models/Stock/stock_intf.cs, Models/Stock/stock_padd.cs
=> Allow feeding/consumption of the supplement before grazing. 

Docker/build/compileng.bat
=> Reduce nuget verbosity in jenkins builds.

ApsimNG/Attributes/ContextMenuAttribute.cs, ApsimNG/Interfaces/IMenuView.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Views/MenuView.cs
=> Reorganise explorer context menu items.

Models/Plant/Arbitrator/OrganArbitrator.cs, Models/Plant/Phenology/Phases/EmergingPhase.cs, Models/Plant/Phenology/Phases/GerminatingPhase.cs, Models/Plant/Plant.cs, Models/Plant/Structure/Structure.cs, Prototypes/Barley/Barley.apsimx
working on #1820   Tidied up some doc stuff
=> Barley completion

Models/Core/ISimulationGenerator.cs, Models/Core/Simulation.cs, Models/Core/SimulationGeneratorFactors.cs, Models/Graph/Series.cs, Models/Storage/DataStore.cs
=> Fix vary by zone in graphs

ApsimNG/Presenters/SupplementPresenter.cs, ApsimNG/Views/SupplementView.cs
More changes to keep Val happy. Working on #2901
=> Fix bug with editing of supplement values

Models/Grazplan/Supplement.cs, Models/Stock/stock.cs
=> Stock doco

ApsimNG/Views/GridView.cs
=> Minor bugfixes to keep Val happy

Prototypes/Barley/Barley.apsimx
=> Small changes to fix barley auto-doc

ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs
=> Call correct attach method when displaying a property presenter.

ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs
=> Fix grid cell editing

Prototypes/Barley/Barley.apsimx
=> Fixed up issues in Barley validation file

ApsimNG/Views/GridView.cs
=> Fix scrolling in report/data stores after changing tables.

Models/CLEM/Groupings/RuminantFilterGroup.cs
Working on #2916 
This is a test pull request. In theory, the CreateInstallation job on Jenkins should be triggered when this gets merged.
=> Fixed a minor typo in documentation.

Models/Main.cs
=> Add command line switch to models.exe which outputs its version.

Models/Fertiliser.cs, Models/IIrrigation.cs, Models/Irrigation.cs, Tests/UnitTests/MockIrrigation.cs
=> Add option to suppress output from application of irrigation/fertiliser.

Docker/CreateInstallation/Dockerfile
=> Install curl into create installation docker container.

Models/Graph/EventNamesOnGraph.cs
Resolves #2868 
This should also hopefully reduce the overlap in the event names.
=> Fix display of EventNamesOnGraph

Docker/CreateInstallation/CreateInstallations.bat, Setup/Linux/BuildDeb.bat, Setup/osx/BuildMacDist.sh
=> Fix more problems in create installer scripts.

Docker/CreateInstallation.Jenkinsfile
Working on #2916 
This pull request should hopefully be the final one needed to get the installation system back online.
=> Jenkins: don't bother archiving installers

Models/PostSimulationTools/Probability.cs
=> Fix probability model.

ApsimNG/Presenters/MainPresenter.cs
=> Add help button to home screen.

Docker/CreateInstallation.Jenkinsfile, Docker/Deploy/deploy.bat
=> Remember to upload documentation when creating a new version.

Docker/CreateInstallation.Jenkinsfile, Docker/Deploy/deploy.bat, Docker/Documentation/dockerfile, Docker/Documentation/doco.bat, Docker/build/compileng.bat, Docker/runtests/dockerfile, Docker/runtests/master.bat, Tests/UnitTests/UnitTests.csproj, test.bat
=> More work on create installers/documentation

Models/Graph/EventNamesOnGraph.cs
=> Don't attempt to space out event names on graph.

APSIM.bib
=> Add more references for Eucalyptus autodocs.

ApsimNG/Presenters/ExperimentPresenter.cs, ApsimNG/Views/ExperimentView.cs
=> Remove old sensiivity analysis buttons from experiment view.

Models/Plant/Organs/Leaf.cs
=> Update the function name

Models/Plant/Organs/LeafCohort.cs
=> Fixed the potential area growth 

Docker/CreateInstallation.Jenkinsfile, Docker/Deploy/deploy.bat, Setup/Linux/BuildDeb.bat, Setup/osx/BuildMacDist.sh
=> Hopefully a fix for Unix installers

ApsimNG/Utility/FileDialog.cs
=> Don't use bitwise and with enumeration.

Models/Core/Checkpoints.cs, Models/Core/Events.cs, Models/Soils/Sample.cs
=> Changed to always checkpoint a whole simulation.

ApsimNG/Presenters/XYPairsPresenter.cs
=> Make XY Pairs presenter inherit from Grid presenter.

ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Presenters/TreeProxyPresenter.cs
=> Allow deletion of entire rows of data in grids.

ApsimNG/Presenters/FactorPresenter.cs, ApsimNG/Utility/FileDialog.cs, Models/Report/ReportColumn.cs
Resolves #2996 but I've also included some other minor bugfixes.
=> Multiple spaces before keyword "as"

ApsimNG/Forms/UpgradeForm.cs
=> Don't let download errors during update kill the application.

ApsimNG/Views/GridView.cs
=> Grids should always have at least one row, even if that row is empty.

Docker/Documentation/dockerfile, Docker/Documentation/doco.bat, Docker/Documentation/ie.reg
=> Add registry entry before creating documentation.

Models/Grazplan/GrazSupp.cs, Models/Stock/stock.cs, Models/Stock/stock_intf.cs, Models/Stock/stock_padd.cs, Models/Stock/stock_vars.cs
=> Significant cleanup and refactor, variable and function naming.

ApsimNG/ApsimNG.csproj, ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Presenters/MorrisPresenter.cs, ApsimNG/Presenters/TablePresenter.cs, ApsimNG/Views/GridView.cs, Models/Interfaces/IModelAsTable.cs, Models/Morris/Morris.cs, Models/Utilities/R.cs
=> Fixed display of Morris view.

Docker/CreateInstallation/CreateInstallations.bat, Setup/Linux/BuildDeb.bat, Tests/Validation/Plantain/Plantain.apsimx
=> More work on create installation/documentation system

ApsimNG/Utility/FileDialog.cs
=> Added a null check to file chooser dialog.

Setup/Linux/BuildDeb.bat
=> Removed unwanted space which broke Linux installs

Docker/CreateInstallation/CreateInstallations.bat
=> Bugfix for Linux installer creation on Jenkins

ApsimNG/Presenters/DataStorePresenter.cs
=> Allow filtering of multiple columns in the data store

ApsimNG/Views/HTMLView.cs, Docker/CreateInstallation.Jenkinsfile
=> Fixed a minor bug in the HTMLView which killed upgrade operations on Windows

ApsimNG/ApsimNG.csproj, ApsimNG/Presenters/LinearAfterThresholdPresenter.cs, ApsimNG/Views/DataStoreView.cs, ApsimNG/Views/GridView.cs, Models/Functions/LinearAfterThresholdFunction.cs
=> Use XYPairs view to display LinearAfterThresholdFunction.

ApsimNG/ApsimNG.csproj, ApsimNG/Resources/Glade/BrowserFind.glade, ApsimNG/Utility/FindInBrowserForm.cs, ApsimNG/Views/HTMLView.cs
=> Get Find working on Linux and Mac HTMLView

Docker/CreateDocumentation.bat
=> Unzip results to correct directory before generating documentation.

Models/Graph/Series.cs
=> Varybyseries

Docker/CreateDocumentation.bat, Docker/Documentation/UploadDocumentation.bat
=> Removed some testing code to get installer system working again

ApsimNG/Views/UpgradeView.cs
=> Use correct name for Upgrade View's glade file.

Models/Plant/Organs/ReproductiveOrgan.cs
=> Fix the documentation of variable in the ReproduciveOrgan.

Docs/content/Usage/GraphFilters.md
=> Update graph filter documentation.

Models/Storage/DataStore.cs, Models/Storage/Table.cs
=> Further work on Firebird support

Models/Core/ApsimFile/Converter.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Resources/Chicory.xml, Models/Resources/Plantain.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml
=> Sorghum devt

Setup/apsimx.iss
=> Add MonoMac.dll to Windows installer.

ApsimNG/Presenters/ExperimentPresenter.cs, Models/Factorial/Experiment.cs, Models/Factorial/Factor.cs, Models/Factorial/FactorValue.cs, Tests/Validation/Wheat/Wheat.apsimx
=> Fix display of experiments when some of the factors have only a single level.

Models/Plant/Interfaces/IApex.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Structure/ApexBase.cs, Models/Plant/Structure/Structure.cs
=> Restructure the apex model

Examples/Morris.apsimx, Models/Core/IStorageReader.cs, Models/Morris/Morris.cs, Models/Storage/DataStore.cs, Tests/UnitTests/MockStorage.cs
=> Fixes to morris to get it working with changes in R

Models/Core/Simulations.cs, Models/Storage/DataStore.cs
=> Update DB filename whenever the simulations' filename changes.

Models/Factorial/Factor.cs
=> Add another edge case to factor code.

ApsimNG/Menus/ContextMenu.cs, Examples/Morris.apsimx, Models/Morris/Morris.cs
Also fixed MuStar graph
Working on #2984
=> Fixed problem with no simulationname in morris Report table

ApsimNG/Commands/RunCommand.cs, ApsimNG/Menus/ContextMenu.cs, Examples/Morris.apsimx, Models/Clock.cs, Models/Morris/Morris.cs
=> Progressbar

ApsimNG/EventArguments/NeedContextItemsArgs.cs, ApsimNG/Views/GridView.cs
=> Cache xml documentation files to speed up intellisense.

ApsimNG/ApsimNG.csproj, ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Interfaces/IGridView.cs, ApsimNG/Presenters/BiomassRemovalPresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs, Models/Plant/Library/BiomassRemoval.cs
Resolves #3114, Resolves #3115, Resolves #3116 
These memos will be documented after the table generated by the BiomassRemoval object, unless the memo contains a heading.
=> Make BiomassRemoval models document all child memos.

Docker/CreateInstallation.Jenkinsfile, Models/Plant/Cultivar/Cultivar.cs
=> Fix cultivar documentation when the cultivar makes no model changes.

ApsimNG/Presenters/PropertyPresenter.cs, Models/PostSimulationTools/Probability.cs, Tests/UnitTests/TestIndexedDataTable.cs
=> Made probability more flexible wrt grouping of datasets

ApsimNG/Views/SummaryView.cs, Models/Plant/Cultivar/Cultivar.cs
=> Improved error message in cultivar when property not found.

ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Views/GraphView.cs
=> Add whitespace between graph axes and annotations.

Models/Graph/Series.cs
=> Fix for event names on graphs not always working

Docker/CreateInstallation.Jenkinsfile, Docker/build/compileng.bat
=> Add some testing diagnostics to Jenkins' create installer job.

Models/Plant/Structure/ApexBase.cs
=> Adjust the tiller senescence in the apex model

Models/Plant/Organs/LeafCohort.cs
=> Reduce the live stem number according to leaf size multiplier

ApsimNG/Resources/Glade/TabbedMetDataView.glade
=> Allow met data plot starting year to be entered directly.

Models/Functions/SupplyFunctions/CanopyPhotosynthesis.cs, Models/Weather/Weather.cs
=> Read diffuse fraction from weather file

Models/Plant/Organs/LeafCohort.cs
=> Fix the live stem number

ApsimNG/Main.cs, Models/Main.cs, Models/Manager.cs
=> More robust method for generating manager temp files

APSIM.bib
=> References for Eucalyptus model documentation

ApsimNG/Menus/ContextMenu.cs
=> Added exception handlign to excel export functionality.

Models/Resources/SCRUM.xml
=> Fix SCRUM bug

Models/Core/AutoDocumentation.cs, Models/Functions/DemandFunctions/StorageNDemandFunction.cs, Models/Functions/LessThanFunction.cs, Models/Functions/MovingAverage.cs, Models/Functions/MovingSum.cs, Models/Functions/PhaseLookupValue.cs, Models/Plant/Biomass/CompositeBiomass.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Tests.cs, Tests/UnitTests/DocumentationTests.cs, Tests/UnitTests/UnitTests.csproj
=> Added a unit test for the autodocs

ApsimNG/Views/TabbedMetDataView.cs
=> Improved exception handling in the weather view.

ApsimNG/Commands/AddModelCommand.cs
=> Improved error message for add model command.

Docker/runtests/APSIM.PerformanceTests.Collector/APSIM.PerformanceTests.Collector.exe.config, Jenkins/APSIM.PerformanceTests.Collector.exe.config, Jenkins/build.bat, Jenkins/performanceTests.bat, Jenkins/runTests.bat, SWIMFrame/Fluxes.cs, SWIMFrame/SoilData.cs
=> Reduced Jenkins' verbosity

ApsimNG/Commands/RunCommand.cs, Models/Core/Runners/JobRunnerMultiProcess.cs
Resolves #3229 
Working on #3163
=> Fixed a few bugs in the asynchronous and multi-process job runners.

Models/Morris/Morris.cs
=> Make Morris only run post simulation analysis if it has actually been run.

Models/Manager.cs
=> Fix for F6 experimental APSIM runner passing scripts to runner.

Models/Plant/Arbitrator/OrganArbitrator.cs
=> WaterAllocation must be updated every day, even if demand is zero.

Examples/MorrisExample.apsimx, Models/AgPasture/AgPasture.PastureSpecies.Organs.cs, Models/Interfaces/INutrient.cs, Models/Soils/Nutrients/Nutrient.cs, Prototypes/Nutrient/Nutrient.apsimx
=> Incremental merge for Soil Nutrient work

Models/Plant/Structure/ApexBase.cs
=> Adjust tiller senescence in the apex model

Models/Soils/CERESSoilTemperature.cs
=> adjust soil temperature threshold

ApsimNG/Menus/ContextMenu.cs, Models/Core/Runners/RunOrganiser.cs, Models/Morris/Morris.cs
=> Allow Morris analyses to be run via the experimental job runner.

Models/Morris/Morris.cs
=> Implemented a better way of checking if a Morris model has run.

Models/Core/Runners/JobRunnerMultiProcess.cs
=> Updated JobRunnerMultiProcess to reflect recent changes to APSIM.Shared.

APSIM.bib
=> Fixed a synatx error in the .bib file.

ApsimNG/Presenters/GraphPresenter.cs
=> Fixed a minor bug in the graph presenter.

ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Presenters/ManagerPresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs
=> More graceful error handling in managers.

ApsimNG/Utility/Graph.cs
=> Updated soil water graphs to use new deserialisation method.

ApsimNG/Presenters/OperationsPresenter.cs
=> Allow changes to Operations to actually have an effect.

ApsimNG/Presenters/CultivarPresenter.cs, ApsimNG/Presenters/MemoPresenter.cs, ApsimNG/Presenters/TitlePresenter.cs
=> Allow changes to memos to actually have an effect.

ApsimNG/Presenters/FactorPresenter.cs
=> Made factor presenter more forgiving of nulls.

APSIMRunner/Program.cs, ApsimNG/Commands/RunCommand.cs, Models/Core/Runners/JobRunnerMultiProcess.cs, Models/Storage/DataStore.cs
=> Fixed display of errors in the multi-process job runner.

Models/PostSimulationTools/ExcelInput.cs
=> Added a null check to excel input's sheet names setter.

Setup/osx/BuildMacDist.bat
=> Remember to delete windows binaries before creating osx installer.

Models/AgPasture/AgPasture.PastureSpecies.cs
=> Ensure few variables are zeroed after an EndCrop is raised

Jenkins/PullRequest/Jenkinsfile, Models/Soils/SWIM/Swim.cs, Tests/Validation/System/Hudson/HudsonSWIM3.apsimx
=> Don't run performance tests if validation tests failed.

ApsimNG/Resources/Toolboxes/StandardToolbox.apsimx, Examples/Eucalyptus.apsimx, Examples/EucalyptusRotation.apsimx
=> Fixed problems with Eucalyptus examples

ApsimNG/Interfaces/IAxisView.cs, ApsimNG/Interfaces/IGraphView.cs, ApsimNG/Presenters/AxisPresenter.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Views/AxisView.cs, ApsimNG/Views/GraphView.cs, Models/Graph/Axis.cs
=> Allow users to edit min/max/interval on date axes.

ApsimNG/Classes/HtmlToMigraDoc.cs, Tests/UserInterfaceTests/MemoImage.cs
=> Added a test for case-insensitive image search.

Documentation/DocumentExamples.bat, Documentation/GenerateDocumentation.bat, Models/Utilities/R.cs
=> Fixed bug in R script when username contained whitespace.

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
=> Improved the handling of dates and fertiliser types

ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Presenters/XYPairsPresenter.cs, Models/Core/VariableProperty.cs, Models/Soils/SoilCrop.cs, Prototypes/FieldPea/FieldPeaValidation.apsimx
=> Fixed propagation of certain exceptions which were getting buried.

Models/Core/Simulation.cs, Models/Graph/Series.cs, Tests/UnitTests/GraphTests.cs, Tests/UnitTests/UnitTests.csproj
=> Fixed graphing of reports directly under a simulation.

ApsimNG/App.config, ApsimNG/ApsimNG.csproj, ApsimNG/packages.config, Tests/UnitTests/app.config
=> Updated Microsoft.Data.OData nuget package.

ApsimNG/Presenters/PropertyPresenter.cs, Models/Core/VariableProperty.cs
Resolves #3369 
APSIMInitiative/APSIM.Shared#74 should be merged before this.
=> Allow users to set/use an array of dates in a manager script.

LICENSE.md
=> Updated license.

Models/Plant/Organs/PerennialLeaf.cs, Tests/Simulation/Initialisation/EucalyptusRotation.apsimx
=> Fixed initialisation in perrenial leaf

Models/Core/ApsimFile/Converter.cs, Tests/UnitTests/MorrisTests.cs, Tests/UnitTests/Resources/MorrisBroken.apsimx, Tests/UnitTests/UnitTests.csproj
=>  Added a converter to rename sensitivity parameters. 

ApsimNG/Menus/ContextMenu.cs, Models/Core/ApsimFile/Converter.cs, Models/Core/ApsimFile/XmlToJson.cs, Models/Soils/Soil.cs, Tests/UnitTests/StructureTests.cs
=> Bugfixes for copying soils from Apsim Classic.

ApsimNG/Presenters/ProfilePresenter.cs
=> Convert relative paths to absolute paths in soil water graphs.

ApsimNG/Presenters/ProfilePresenter.cs
=> Only rename soil water graph series if the graph is not null.

Docs/content/Usage/Memo.md
=> Updated memo documentation

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
=> Added TreeManagement script to management toolbox.

ApsimNG/Resources/Glade/UpgradeView.glade, ApsimNG/Views/UpgradeView.cs
=> Added the ability to downgrade to older versions.

ApsimNG/Presenters/ReportPresenter.cs, Models/Report/ReportColumn.cs, Tests/UnitTests/TestReport.cs
Working on #3316 
Resolves #3305
=> Testing some changes to report aggregation

Models/Core/Zone.cs, Models/MicroClimate/MicroClimate.cs, Models/MicroClimate/MicroClimateScience.cs, Models/MicroClimate/ZoneMicroClimate.cs, Models/Models.csproj, Models/Zones/StripCropZone.cs, Tests/Validation/MicroClimate/MicroClimate.apsimx
=> Strip crop

Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/HIReproductiveOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/Nodule.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Organs/SorghumLeaf.cs, Models/Plant/Plant.cs
=> Remove one of the PlantEnding methods in Root

Models/Weather/Weather.cs
=> Added Daylength to met file

ApsimNG/Views/GridView.cs
Working on #3110 - I fixed the stack overflow exception, and the issue where the grid would snap back to its original position after releasing page up/down.
=> Improved scrolling in grids.

ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Interfaces/IAxisView.cs, ApsimNG/Interfaces/IGraphView.cs, ApsimNG/Presenters/AxisPresenter.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Presenters/LinearAfterThresholdPresenter.cs, ApsimNG/Presenters/MetDataPresenter.cs, ApsimNG/Presenters/XYPairsPresenter.cs, ApsimNG/Resources/Glade/AxisView.glade, ApsimNG/Views/AxisView.cs, ApsimNG/Views/GraphView.cs, Models/Graph/Axis.cs, Models/PostSimulationTools/PredictedObserved.cs
=> Add error columns to predicted observed tables.

ApsimNG/Utility/Configuration.cs
=> Allow FilesInHistory property to be set by user.

Models/Soils/Soil.cs, Tests/UnitTests/StructureTests.cs
=> Don't automatically add soil temp/nitrogen nodes to soils.

Models/Core/ApsimFile/Converter.cs
=> Only add initial water nodes to Soil nodes.

Models/Core/ApsimFile/XmlToJson.cs, Tests/UnitTests/Resources/XMLToJSONTests_EnsureResidueTypesConverts.json, Tests/UnitTests/XMLToJSONTests.cs
=> Fixed bug in xml to json conversion for single-child text nodes.

Models/Factorial/Factor.cs
=> Factors should ignore model replacements of the wrong type.

ApsimNG/Presenters/PropertyPresenter.cs, Models/Core/Attributes/Separator.cs
=> Allow properties to have multiple separator attributes.

Examples/Sugarcane.apsimx
=> Weather file in sugarcane example should point to install directory.

Models/Resources/GetPackage.R, Models/Sensitivity/Morris.cs, Models/Sensitivity/Sobol.cs
=> Updated R CRAN mirror.

Models/Core/ApsimFile/XmlToJson.cs
=> Fixed xml to json conversion of soil crops.

ApsimNG/Presenters/MetDataPresenter.cs
Resolves #3488 (as does APSIMInitiative/APSIM.Shared#79)
=> Improved error messages in met data presenter.

Models/CLEM/Groupings/RuminantFilter.cs, Models/CLEM/Resources/RuminantType.cs
=> Minor changes for vs2015 compatibility.

Models/Graph/Series.cs
=> Fixed display of graphs from excel inputs.

Models/Plant/Phenology/Scales/ZadokPMF.cs
=> Zadok Stage 30 Error

Models/Core/ApsimFile/Converter.cs, Models/Core/ApsimFile/JsonUtilities.cs, Models/Soils/Soil.cs, Models/Soils/SoilNitrogen.cs, Models/Soils/SoilOrganicMatter.cs, Tests/Validation/System/Hudson/HudsonSWIM3.apsimx
=> Soil nutrient increment

Models/Interfaces/IHasSolutes.cs, Models/Interfaces/ISolute.cs, Models/Models.csproj, Models/Plant/Arbitrator/RelativeAllocation.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Organs/Root.cs, Models/Resources/Eucalyptus.json, Models/Resources/Wheat.json, Models/Soils/Nutrients/Chloride.cs, Models/Soils/Nutrients/Solute.cs, Models/Soils/SoilNitrogen.Variables.cs, Models/Soils/SoilNitrogen.cs, Models/Soils/SoilNitrogenNH4.cs, Models/Soils/SoilNitrogenNO3.cs, Models/Soils/SoilNitrogenPlantAvailableNH4.cs, Models/Soils/SoilNitrogenPlantAvailableNO3.cs, Models/Soils/SoilNitrogenUrea.cs, Models/SoluteManager.cs, Tests/UnitTests/FertiliserTests.cs
=> Speed up jenkins

ApsimNG/Presenters/AddFunctionPresenter.cs, ApsimNG/Presenters/AddModelPresenter.cs, ApsimNG/Views/ListButtonView.cs
Working on #3498 
This is a case-sensitive search - is that ok?
=> Added a filter to the add model/function view.

Models/Report/ReportColumn.cs, Models/Surface/SurfaceOrganicMatter.cs
=> code changed to deal with new sum method

ApsimNG/Presenters/SeriesPresenter.cs, ApsimNG/Views/ColourDropDownView.cs, Models/Graph/Series.cs
=> Undo recent changes to series

Jenkins/build.bat
=> Jenkins needs to manually restore APSIM.Shared nuget pacakges (for now).

ApsimNG/Presenters/ExperimentPresenter.cs
=>  Implemented a better algorithm for determining which simulations are disabled.

ApsimNG/Presenters/SeriesPresenter.cs, ApsimNG/Views/DropDownView.cs, ApsimNG/Views/GraphView.cs, ApsimNG/Views/MainView.cs
Resolves #3548 
Resolves #3549
=>  Added some better error messages to series presenter. 

Models/Agroforestry/TreeProxy.cs
=> Fixed calculations and clarified units in outputs and equations

Jenkins/Installation/Jenkinsfile, Jenkins/PullRequest/Jenkinsfile
=> Jenkins should immediately exit if compilation fails.

ApsimNG/Presenters/GraphPresenter.cs
=> Fixed a bug where y-axis settings are incorrectly displayed as dates.

Models/Plant/Organs/LeafCohort.cs
resolves #3581 
Add comments for easier understanding of equation.
=> Add comments for functional nitrogen concentration

Jenkins/performanceTests.bat
=> Added a workaround for a bug in a Jenkins plugin.

Models/Core/Events.cs
=> Event connection speed up

Examples/MorrisExample.apsimx, Models/Core/VariableProperty.cs, Tests/UnitTests/APITest.cs
=> Fixed bug in variable property when setting a single element in an array.

ApsimNG/Main.cs, Models/Main.cs, Models/Manager.cs
=> Redo the way manager cleans up its temporary files

ApsimNG/Presenters/ProfilePresenter.cs
=> GUI Fix to enable editing of Water tab

Jenkins/createInstaller.bat
Resolves #3620 
Resolves #3496
=> Sign the Windows installer.

ApsimNG/Views/MainView.cs
=> Fixed problems with setting up tabs and associated menu.

ApsimNG/ApsimNG.csproj, ApsimNG/Presenters/CLEM/PivotTablePresenter.cs, ApsimNG/Resources/Glade/PivotTableView.glade, ApsimNG/Views/CLEM/PivotTableView.cs, Models/CLEM/Reporting/PivotTable.cs, Models/Models.csproj
Should now account for the refactor of the DataStore. Resolves #3600.
=> CLEM Add a PivotTable model for basic manipulation of resource ledger data

Jenkins/createInstaller.bat
=> Fixed syntax in jenkins batch script

ApsimNG/Views/MainView.cs, ApsimNG/Views/TreeView.cs
=> Fixed minor problem with cleaning up memory on destruction of a TreeView

.gitignore
=> Prevent git from tracking .db-shm and .db-wal files.

ApsimNG/Views/UpgradeView.cs
=> Fix problems with "downgrading"

Models/Plant/Phenology/Phenology.cs
=> Fix rewind so it works for leaf death phase

ApsimNG/Interfaces/IAxisView.cs, ApsimNG/Presenters/AxisPresenter.cs, ApsimNG/Views/AxisView.cs, ApsimNG/Views/GraphView.cs
=> Improved axis display

Examples/Factorial.apsimx
=> Fixed case of weather file referenced by factorial example.

Models/Report/ReportColumn.cs, Tests/UnitTests/Report/ReportTests.cs
=>  Fixed bug in report aggregation. 

Models/Plant/Structure/ApexBase.cs
=> Scale up infertile tiller number into population scale

ApsimNG/ApsimNG.csproj, ApsimNG/Commands/ReplaceModelCommand.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Resources/Glade/SoilDownload.glade, ApsimNG/Utility/SoilDownloadDialog.cs, Models/Core/ApsimFile/FileFormat.cs
Working on #3655 
This is a rather rough first pass, and needs a bit of polishing, but is good enough for user testing purposes. Currently only the ASRIS web services are used. ISRIC should be coming later, but this might benefit from waiting for Andrew Moore to complete the work in this area that he's doing for the DARPA World Modellers project.
=> Allow user to import soils using the ASRIS web services.

Models/Graph/Graph.cs
=> Only graph series if they are enabled.

Models/Plant/Organs/Leaf.cs
=> Check respiration

ApsimNG/Presenters/DataStorePresenter.cs, Models/Core/Simulations.cs, Models/Storage/DataStore.cs, Tests/UnitTests/Sensitivity/MorrisTests.cs, Tests/UnitTests/Storage/DataStoreTests.cs, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/Utilities.cs
=> Update DataStore's filename whenever the simulations object's filename changes.

Jenkins/createInstaller.bat
=> Sign the updater.

Models/Utilities/R.cs
The race condition still exists, but it's a lot less likely to trigger.
Resolves #3678
=> Alleviated potential race condition in RComponent

ApsimNG/Presenters/PropertyPresenter.cs, Models/Plant/Organs/LeafCohort.cs
=>  PropertyPresenter should show units in description column, if possible. 

ApsimNG/Commands/RunCommand.cs, Models/PostSimulationTools/ExcelInput.cs
=> ExcelInput should generate errors for bad filenames.

Models/Soils/SoilWater.cs
=> Fixed incorrect canopy data in soilwater model

Models/Resources/Eucalyptus.json, Tests/Validation/Eucalyptus/Eucalyptus.apsimx
=> Added CO2 Impact on SLA and Stomatal Conductance

Models/Core/ApsimFile/FileFormat.cs, Models/Core/ApsimFile/XmlToJson.cs, Tests/UnitTests/Core/ApsimFile/XMLToJSONTests_EnsureParentChildRelationshipConverts.json
=> Use invariant culture in xml-json converter.

Models/Resources/Eucalyptus.json
=> Eucalyptus k value

Models/Resources/Eucalyptus.json
=> Eucalyptus

ApsimNG/Presenters/MetDataPresenter.cs, ApsimNG/Views/GraphView.cs
=> Fixed monthly rainfall graph in weather data presenter.

Prototypes/Soybean/Soybean.apsimx
=> Converted Soybean prototype to use Nutrient

ApsimNG/Views/GraphView.cs
=> Fixed graph export to clipboard

ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs
=> PropertyPresenter should update dropdowns after changing a value.

Tests/Validation/MicroClimate/MicroClimate.apsimx
=> Change microclimate validation set to use soil nutrient model

Models/Core/ApsimFile/Converter.cs, Models/Resources/Nutrient.json, Models/Soils/Soil.cs, Models/Soils/SoilNitrogen.CNPatch.Processes.cs, Models/Soils/SoilNitrogen.Variables.cs, Models/Soils/SoilNitrogen.cs, Models/Soils/SoilOrganicMatter.cs, Tests/Validation/Eucalyptus/Eucalyptus.apsimx, Tests/Validation/Maize/Maize.apsimx, Tests/Validation/Oats/Oats.apsimx, Tests/Validation/Sugarcane/Sugarcane.apsimx
=> Allow soil C:N on a layered basis

Models/Core/ApsimFile/Converter.cs, Tests/Validation/Eucalyptus/Eucalyptus.apsimx, Tests/Validation/Maize/Maize.apsimx, Tests/Validation/Oats/Oats.apsimx, Tests/Validation/Sugarcane/Sugarcane.apsimx
=> Don't allow opening of files which have been opened in a more recent verson.

Models/Core/ApsimFile/XmlConverters.cs, Models/Storage/DeleteRowsCommand.cs, Models/Summary.cs
=> Added SimulationName column to _InitialConditions

APSIMRunner/Program.cs, Models/Core/Run/SimulationDescription.cs, Models/Core/Runners/JobRunnerMultiProcess.cs, Models/PostSimulationTools/ExcelInput.cs, Models/PostSimulationTools/Input.cs
=> Get the multi-process job runner working with Input/ExcelInput

Models/Factorial/CompositeFactor.cs, Tests/UnitTests/Factorial/ExperimentTests.cs
=> When there are two operations under a factor, the second is ignored.

Models/Plant/Organs/Root.cs
=> Root N Error

Models/Core/VariableProperty.cs
=> VariableProperty should allow for floats.

Documentation/CreateModelDocumentation.cs
=> Fixed syntax error in jenkins script.

Models/Core/Runners/RunOrganiser.cs, Models/Core/Simulations.cs, Models/Storage/IStorageReader.cs, Tests/UnitTests/Storage/DataStoreReaderTests.cs, Tests/UnitTests/TextStorageReader.cs
=> Refresh storage reader after running sims

Documentation/DocumentFile.cs
=> Fixed variable name in jenkins script.

Models/PostSimulationTools/Probability.cs
=> Improved error messages in probability model.

ApsimNG/Views/GraphView.cs
=> Fixed font colour for graphs with dark theme disabled

Models/Storage/DeleteRowsCommand.cs, Tests/UnitTests/Storage/DataStoreWriterTests.cs
=> Fix: cleanup old columns from DB files where possible

ApsimNG/Views/GraphView.cs
Working on #3748 
Working on #3762 
Bit of a crude hack which I'll want to revisit later but it will keep people happy for now
=> Fixed graph background colour.

Prototypes/Chickpea/ChickPea.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/Nutrient/Nutrient.apsimx, Prototypes/Soybean/Soybean.apsimx
=> Fixed broken links in variable references

Tests/Validation/System/Hudson/Hudson.apsimx, Tests/Validation/System/Tarlee Rotation Trial/TarleeRotationTrial.apsimx, Tests/Validation/System/Wagga/Wagga.apsimx
=> Converted some System tests to Soil Nutrient

Models/Core/Runners/RunOrganiser.cs, Tests/UnitTests/Core/PostSimulationTool.apsimx, Tests/UnitTests/Core/PostSimulationToolTests.cs, Tests/UnitTests/UnitTests.csproj
=>  Don't abort early when running post sim tools 

ApsimNG/Views/ExperimentView.cs, ApsimNG/Views/ListView.cs
Resolves #3772 
Resolves #3766
=> Bugfix for experiment view

ApsimNG/Views/UpgradeView.cs
=> Download progress dialog should be updated from main thread.

ApsimNG/Presenters/PropertyPresenter.cs, Models/Core/Attributes/DisplayAttribute.cs, Models/Graph/EventNamesOnGraph.cs, Models/Graph/Series.cs
=> Enhancements to event names on graph

Models/Graph/Series.cs, Models/Storage/EmptyCommand.cs
=> Fix: Empty DataStore can throw.

ApsimNG/Presenters/CompositeFactorPresenter.cs, ApsimNG/Presenters/FactorPresenter.cs, ApsimNG/Views/EditBoxView.cs, Models/Factorial/Factor.cs
=> Fix: Problem creating factors from scratch

Models/Sensitivity/Sobol.cs
=> Upgraded SOBOL to show first order and total indices

Models/Importer/APSIMImporter.cs
This was causing problems in auto-converted manager scripts.
Working on #572
=> Fixed display type enum in importer.

Models/Graph/Series.cs
=> Fix: XYGraphs not working

Models/Graph/SeriesDefinition.cs
=> Fix: Filter on series presenter not working due to duplicate field names

ApsimNG/Views/GraphView.cs
=> Added: Ability to condense graph legends

Models/Graph/Series.cs
=> Fix: Change colours assignment back to the way it was originally.

ApsimNG/Commands/ExportNodeCommand.cs
=> Fixed nutrient autodocs

ApsimNG/Utility/SoilDownloadDialog.cs
=> Get rid of unused variable warnings.

ApsimNG/ApsimNG.csproj, ApsimNG/Presenters/PropertyAndTablePresenter.cs, Models/Sensitivity/Morris.cs
=> Made TableName and aggregation variable user inputs

ApsimNG/Presenters/PropertyAndTablePresenter.cs
=> Morris: Removed fixed num dec places in grid

Models/Sensitivity/Morris.cs
=> Fixed Morris Tables setter to match using PropertyPresenter for top grid.

ApsimNG/Views/FactorView.cs
=> Removed unneeded code from factor view.

Models/Plant/Arbitrator/SorghumArbitratorN.cs, Models/Plant/Organs/SorghumLeaf.cs
=> Fixed spelling mistake to keep Neil happy

ApsimNG/Presenters/MainPresenter.cs, Models/Importer/APSIMImporter.cs, Tests/UnitTests/ImporterTests.cs, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/defective.apsim
=> Importing old .apsim files should not cause a UI crash

Models/Core/ApsimFile/Converter.cs, Models/Plant/Arbitrator/RetranslocateNonStructural.cs, Models/Plant/Organs/GenericOrgan.cs
=> Removed an optional link from generic organ. 

ApsimNG/Presenters/MainPresenter.cs
=> Added null check to crop converter code.

ApsimNG/Views/HTMLView.cs
=> Webkit browser should respect system-wide gtk theme.

ApsimNG/Views/DataStoreView.cs
Resolves #3840
I'm surprised no one picked up on this bug until now - I guess not many people use this feature.
=> Bugfixes for DataStoreView

ApsimNG/Presenters/DataStorePresenter.cs
=> Fixed bug in max number of records option.

Models/Plant/Phenology/Phenology.cs
=> Phenology should update its phases on start of simulation.

Models/Plant/Arbitrator/SorghumArbitratorN.cs, Models/Plant/Organs/SorghumLeaf.cs, Prototypes/Sorghum/Sorghum.apsimx, Prototypes/Sorghum/SorghumLeaf.apsimx
=> Sorghum bugfixes

Models/Graph/MultiDescriptorPainter.cs, Models/Graph/Series.cs, Models/Graph/SeriesDefinition.cs, Tests/UnitTests/Graph/SeriesTests.cs, Tests/UnitTests/TextStorageReader.cs
=> Fix: Filter not working in some situations.

Models/Graph/SeriesDefinition.cs
=> Fixed bug which occurs after removing a graph filter.

ApsimNG/Commands/ExportNodeCommand.cs
=> Two bugfixes for autodocs

Models/Graph/SeriesDefinition.cs, Tests/UnitTests/Graph/SeriesTests.cs
=> Fix error bars on graphs

Models/Functions/HoldFunction.cs, Models/Plant/Phenology/Phenology.cs, Tests/UnitTests/Functions/HoldFunctionTests.cs, Tests/UnitTests/UnitTests.csproj
=> Make HoldFunction handle exceptions

Models/Plant/Organs/Leaf.cs
=> Checked whether leaf respiration is more than double.Epsilon

Models/Core/ApsimFile/Converter.cs, Tests/UnitTests/Core/ApsimFile/ConverterTests.cs, Tests/UnitTests/ImporterTests.cs, Tests/UnitTests/ImporterTestsOldAPSIM.xml, Tests/UnitTests/UnitTests.csproj
=> Fix old APSIM file importer

Models/Core/Events.cs, Models/Irrigation.cs, Models/Models.csproj, Models/Soils/Nutrients/INutrientPool.cs, Models/Soils/Nutrients/Nutrient.cs, Models/Soils/Nutrients/NutrientPool.cs, Models/Soils/SoilWater.cs, Models/Soils/SoilWaterBackend/SoilWaterDataTypes.cs, Models/Soils/SoilWaterBackend/SoilWaterEvap.cs, Models/Soils/SoilWaterBackend/SoilWaterSurface.cs, Tests/UnitTests/IrrigationTests.cs, Tests/UnitTests/Soils/MockNutrientPool.cs, Tests/UnitTests/UnitTests.csproj
=> Fix irrigation efficiency

Documentation/GenerateDocumentation.bat, Jenkins/UploadDocumentation.bat, Setup/Linux/BuildDeb.bat, Setup/apsimx.iss, Setup/osx/BuildMacDist.bat, Setup/osx/BuildMacDist.sh
=> Add UnderReview directory to installed version

ApsimNG/Presenters/SeriesPresenter.cs, Models/Storage/DataStoreReader.cs, Tests/Validation/SCRUM/SCRUM.apsimx
Working on #3893 (probably resolves the issue but won't know for sure until this gets merged).
~Note that I've changed data store code to throw an exception if table name does not match an existing table, whereas we previously returned null. I'm still not sure if this is a good idea, but returning null usually just leads to a null reference exception anyway.~
=> Fixed SCRUM autodocs

Examples/Chicory.apsimx, Examples/ControlledEnvironment.apsimx, Examples/Eucalyptus.apsimx, Examples/Maize.apsimx, Examples/OilPalm.apsimx, Examples/Plantain.apsimx, Examples/Sugarcane.apsimx
=> Improved simulation names in examples

Documentation/GenerateDocumentation.bat
=> Fixed env var name in jenkins script.

Documentation/GenerateDocumentation.bat, Jenkins/UploadDocumentation.bat
=> Jenkins install script (attempt #3)

Prototypes/Sorghum/Sorghum.apsimx, Prototypes/Sorghum/SorghumLeaf.apsimx
=> Added sorghum grain heat stress function.

Models/AgPasture/AgPasture.PastureSpecies.cs
Resolves #3914 
Fixing two bugs in the code (calculation of AboveGround biomass and plant height) and add a minor change to root calculation
=> Issue/agpasture fixes#3914

Jenkins/UploadDocumentation.bat
=> Fixed minor bug in Jenkins script.

Models/Storage/DataStore.cs
=> Create connection to sqlite

APSIMRunner/StorageViaSockets.cs, Models/Core/Simulation.cs, Models/Factorial/Experiment.cs, Models/PostSimulationTools/PredictedObserved.cs, Models/Report/Report.cs, Models/Storage/DataStoreWriter.cs, Models/Storage/IStorageWriter.cs, Models/Storage/ReportData.cs, Tests/UnitTests/Report/ReportTests.cs, Tests/UnitTests/Storage/DataStoreWriterTests.cs, Tests/UnitTests/Storage/MockStorage.cs
=> Fix _Factors and _Simulations table

ApsimNG/Resources/Glade/UpgradeView.glade, ApsimNG/Views/UpgradeView.cs
=> Upgrade view should not ask for street address/city info

Examples/FodderBeet.apsimx, Tests/UnderReview/FodderBeet/FodderBeet.apsimx
=> Added Example

ApsimNG/Views/HTMLView.cs, ApsimNG/Views/MainView.cs
=> Fixed browser font on Windows

Models/Graph/EventNamesOnGraph.cs
=> Fixed bug in event names on graph.

ApsimNG/Presenters/ExperimentPresenter.cs, Models/Factorial/Experiment.cs
=> Fixed bug in experiment presenter.

ApsimNG/Utility/SoilDownloadDialog.cs
=> Added support for download of ISRIC soil descriptions.

ApsimNG/Utility/SoilDownloadDialog.cs
=> Added correction for ISRIC soil carbon.

Models/Plant/Structure/ApexBase.cs
=> Check the floating error

ApsimNG/Views/UpgradeView.cs
Also retry updating the registrations DB if it fails the first time.
Resolves #3956
=> When upgrading, update rego DB before downloading installer.

Models/Weather/Weather.cs
Resolves #3953, provided a pull request in APSIM.Shared is merged as well.
=> Added test and exception for bad headers in a weather file

ApsimNG/Classes/Intellisense/CSharpCompletion.cs, ApsimNG/Main.cs, ApsimNG/Presenters/FactorPresenter.cs, ApsimNG/Presenters/IntellisensePresenter.cs, ApsimNG/Views/EditBoxView.cs, ApsimNG/Views/EditorView.cs, ApsimNG/Views/MethodCompletionView.cs
Resolves #3819 
I've also fixed the issue where some views (those which use intellisense) take a long time to load the first time you click on them. This is due to a one-time initialisation process which takes a long time. This initialisation now gets run in a background thread when we first start the program.
=> Intellisense bugfixes and one-time speedup

ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Views/HTMLView.cs, ApsimNG/Views/MainView.cs
=> Added some null checks to HTMLView.

Models/Resources/Nutrient.json, Prototypes/Nutrient/Nutrient.apsimx
=> Clean up autodoc for Nutrient

APSIM.bib, Prototypes/Nutrient/Nutrient.apsimx
=> Cleanup of Nutrient Validation Sets

ApsimNG/Utility/Configuration.cs
=> Mru list size on home screen should never be 0.

Jenkins/PullRequest/Jenkinsfile
=> Jenkins should checkout APSIM.Shared master branch before running tests.

ApsimNG/Views/UpgradeView.cs
=> Separate product/version/platform info when writing to registrations db.

Models/Soils/Arbitrator/SoilArbitrator.cs
Remove zone as valid parent and add test to throw if arbitrator is anywhere other than under simulation.  Resolves #3981
=> Check position of SoilArbitrator

Models/Plant/Organs/SimpleLeaf.cs
=> Added test for null LightProfile.

Models/Core/Simulations.cs
=> Resolve links before generating autodocs.

Models/Core/Simulation.cs
=> Certain properties of Simulation do not need to be serialized.

Models/Storage/DataStore.cs
=> Fixed DataStore filename update algorithm

ApsimNG/Cloud/AzureResultsDownloader.cs, ApsimNG/Presenters/CLEM/MessagePresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Utility/SoilDownloadDialog.cs, ApsimNG/Views/TreeProxyView.cs, Models/CLEM/FileCrop.cs, Models/CLEM/FileGRASP.cs, Models/CLEM/FileSQLiteCrop.cs, Models/CLEM/FileSQLiteGRASP.cs
Along with APSIMInitiative/APSIM.Shared#101, this resolves #4036
=> Use invariant culture where possible.

ApsimNG/Presenters/MetDataPresenter.cs
Resolves #4019 (#4041 must also be merged to fix this issue)
=> Fixed bug in met file presenter.

ApsimNG/Views/DropDownView.cs
=> Fixed crash when clicking on report.

Models/Graph/SeriesDefinition.cs
Resolves #4023 
@hol353...do we have any unit tests for this regex which I've changed?
=> Improved regular expression for graph filter.

ApsimNG/Commands/ExportNodeCommand.cs, Models/Core/Simulations.cs
=> Fixed link resolution for autodocs.

Models/Graph/EventNamesOnGraph.cs
=> Added int/double support for event names on graph.

Models/Utilities/R.cs
=> Added more diagnostics to R component.

ApsimNG/Views/TreeView.cs
=> Fixed bug where clem view shows its version tab in a popup window

Docs/content/Development/Model/2 CodingStyle.md
=> Added code formatting guide to code style doco.

Models/Sensitivity/Morris.cs, Models/Sensitivity/Sobol.cs, Models/Utilities/R.cs
=> Users of R component should not have to specify lib.loc path.

Models/Stock/stdmath.cs
=> Fixed #4062 serialization error on System Random object

Models/Soils/Soil.cs, Models/Soils/SoilOrganicMatter.cs
Resolves #4064 
These variables do not need to be saved to apsimx file
=> Add attribute [XmlIgnore] to soil variables 

ApsimNG/Views/TreeProxyView.cs
=> Don't use invariant culture for dates in tree proxy view.

ApsimNG/Commands/ExportNodeCommand.cs, Jenkins/createDocumentation.bat, Models/Core/Simulations.cs
=> Fixed autodocs on website

ApsimNG/EventArguments/NeedContextItemsArgs.cs, ApsimNG/Presenters/IntellisensePresenter.cs, Models/Core/Events.cs
@peter-devoil this should help with the intellisense-related item in your todo list in #4060
Working on #3890
=> Added intellisense method to find all event publishers in simulations tree

Models/Soils/Soil.cs
=> Restore function needed for charting of initial soil water

Models/Soils/Sample.cs, Models/Soils/Soil.cs, Models/Soils/Standardiser/Layers.cs, Models/Soils/Standardiser/SoilStandardiser.cs, Models/Soils/Standardiser/SoilUnits.cs, Tests/UnitTests/Soils/SoilStandardiserTests.cs
=> Get compiling again. Remove NUnitsEnum - not needed

ApsimNG/Views/GraphView.cs
=> Removed monotonous monotonic warnings.

Models/Core/Events.cs, Models/Core/Scope.cs
=> Speed up event connections.

Models/Resources/Slurp.json, Tests/Validation/Slurp/Slurp.apsimx
resolves #4089.  Lots of changes in Slurp.apximx from converter.  Only real change is some redundant graphs deleted
=> Slurp update

ApsimNG/Classes/Grid/GridColumn.cs, ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Views/GridView.cs
=> Fixed grid cell colours

Models/Core/Apsim.cs
=> Allow any model to be added as a child of CompositeFactor.

Models/Core/ApsimFile/Converter.cs, Models/Core/ApsimFile/JsonUtilities.cs, Models/Core/ApsimFile/ManagerConverter.cs, Models/Plant/Interfaces/IHasWaterDemand.cs, Models/Plant/Interfaces/IOrgan.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Resources/FodderBeet.json, Models/Resources/Nutrient.json, Models/Resources/WhiteClover.json
=> WIP simple leaf refactor

Models/Plant/Interfaces/IArbitration.cs, Models/Plant/Interfaces/IFunction.cs, Models/Plant/Interfaces/IHasWaterDemand.cs, Models/Plant/Interfaces/IOrgan.cs, Models/Plant/Interfaces/IRemovableBiomass.cs, Models/Plant/Interfaces/IRetranslocateMethod.cs, Models/Plant/Interfaces/IWaterNitrogenUptake.cs, Models/Plant/Organs/EnergyBalance.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/PerennialLeaf.cs
=> Perennial leaf

ApsimNG/Views/FormattedGridView.cs
Resolves #4126. This is more of a bandaid solution until I get some other grid changes merged in.
=> Fixed deletion of cells in profile grid.

ApsimNG/Commands/AddModelCommand.cs
=> Avoid conflict between local and class variables.

Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Nodule.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Organs/SorghumLeaf.cs
=> Cloned StartLive

ApsimNG/ApsimNG.csproj
=> Ignore errors in optional ApsimNG build steps.

APSIM.Shared/JobRunning/JobRunner.cs, Models/Core/Run/Runner.cs, Models/Core/Run/SimulationDescription.cs
Working on #4015.
Note that this does not yet handle the case of multi-process runs.
=> Show progress of partially completed simulations.

Docs/content/Development/Contribute/Compile/linux.md
=> Updated Linux compilation instructions.

Models/Interfaces/ICanopy.cs, Models/Interfaces/ILeaf.cs, Models/Interfaces/INutrient.cs, Models/Interfaces/ISoil.cs, Models/Interfaces/ISoilTemperature.cs, Models/Interfaces/ISoilWater.cs, Models/Interfaces/IUptake.cs, Models/Interfaces/IVisualiseAsDirectedGraph.cs, Models/Interfaces/IWeather.cs, Models/Plant/Cultivar/Cultivar.cs, Models/Plant/Phenology/Phases/IPhase.cs, Models/Plant/Phenology/Phases/IPhaseWithTrarget.cs, Models/Soils/Arbitrator/CropUptakes.cs, Models/Soils/Arbitrator/Estimate.cs, Models/Soils/Arbitrator/SoilArbitrator.cs, Models/Soils/Arbitrator/SoilState.cs, Models/Soils/Arbitrator/ZoneWaterAndN.cs, Models/Soils/InitialWater.cs, Models/Soils/WaterModel/EvaporationModel.cs, Models/Soils/WaterModel/LateralFlow.cs, Models/Soils/WaterModel/Runoff.cs, Models/Soils/WaterModel/SaturatedFlow.cs, Models/Soils/WaterModel/UnsaturatedFlow.cs, Models/Soils/WaterModel/WaterBalance.cs, Models/Soils/WaterModel/WaterTable.cs
=> Removed unnecessary lines

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx, Models/Soils/Nutrients/Solute.cs
=> Manager toolbox

Models/Soils/Nutrients/Solute.cs
=> Fixed reference to NO3 in solute

APSIM.Shared/JobRunning/JobManager.cs, ApsimNG/Menus/ContextMenu.cs, Models/Core/Run/EmptyJob.cs, Models/Core/Run/JobRunnerMultiProcess.cs, Models/Core/Run/SimulationGroup.cs, Models/Models.csproj, Tests/UnitTests/Core/Run/RunnerTests.cs
=> adding an empty job object to force jobs finished event to fire

ApsimNG/Presenters/InitialWaterPresenter.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Presenters/ManagerPresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Presenters/SeriesPresenter.cs, ApsimNG/Views/GraphView.cs, ApsimNG/Views/MethodCompletionView.cs, ApsimNG/Views/SeriesView.cs, Models/Manager.cs, Tests/UserInterfaceTests/DeleteDBFile.cs
=> Fixed some memory leaks

ApsimNG/Commands/AddModelCommand.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/AddFunctionPresenter.cs, ApsimNG/Presenters/AddModelPresenter.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Utility/SoilDownloadDialog.cs, ApsimNG/Utility/WeatherDownloadDialog.cs
=> Quick refactor of add model code

APSIM.Shared/JobRunning/JobRunner.cs, Models/Core/Run/JobRunnerMultiProcess.cs
=> Fixed cancelling of simulations in the gui.

ApsimNG/Presenters/DataStorePresenter.cs, Models/Storage/DataStoreReader.cs
=> Fixed data store row filter.

Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Nodule.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Plant.cs
=> Remove PopulationFactor and associated references

Models/Plant/Library/BiomassRemoval.cs
=> Updated BiomassRemoval doco text at suggestion of Val.

Examples/WhiteClover.apsimx
=> Renamed WhiteClover example sim name from WhiteClover -> Simulation.

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
Resolves #2907 
- Mineral N content in new apsim (defined in Nutrient.cs) doesn't seem to take urea into account as it did in the old script
- Fertiliser amount is a per-application amount
- Tried adding event name option but there are currently a number of infrastructure bugs stopping this from working. Will add this feature if and when these get fixed
=> Added advanced version of fertilise on fixed date script.

Examples/FodderBeet.apsimx, Examples/Maize.apsimx, Examples/Potato.apsimx, Examples/SCRUM.apsimx, Examples/Slurp.apsimx, Examples/Sugarcane.apsimx
=> Changed manager scripts in examples to use drop down for cultivar name.

ApsimNG/Presenters/PropertyAndTablePresenter.cs, Models/Sensitivity/Sobol.cs
=> Improved deletion/addition of rows in morris/sobol grids.

Models/Soils/Physical.cs
=> Fixed units for Physical.Depth (mm -> cm).

ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Views/ExplorerView.cs, ApsimNG/Views/GridView.cs, Tests/UnitTests/ApsimNG/Resources/SampleFiles/BasicSimulation.apsimx, Tests/UnitTests/ApsimNG/UITestsMain.cs, Tests/UnitTests/ApsimNG/Utilities/GtkUtilities.cs, Tests/UnitTests/ApsimNG/Utilities/UITestUtilities.cs, Tests/UnitTests/ApsimNG/Views/GridViewTests.cs, Tests/UnitTests/UnitTests.csproj
Working on #4140
This adds two basic tests for the grid view along with several gtk utility methods which allow for these ui tests to work. I've put this into a new folder in the UnitTests project called ApsimNG. Not sure if we want this to live here but it can easily be moved if need be.
=> Proof-of-concept unit tests for grid view

Models/Weather/Weather.cs
=> Add Qmax property to Weather class

Examples/Potato.apsimx
=> Potato Example Cleanup

ApsimNG/Menus/ContextMenu.cs
=> Automatically open excel file after export to Excel operation.

ApsimNG/Views/GridView.cs, Tests/UnitTests/ApsimNG/Utilities/GtkUtilities.cs, Tests/UnitTests/ApsimNG/Views/GridViewTests.cs
=> Fixed arrow keys while grid is in edit mode.

APSIM.Shared/JobRunning/JobManager.cs, APSIM.Shared/JobRunning/JobRunner.cs, Models/Core/Run/Runner.cs, Tests/UnitTests/CommandLineArgsTests.cs, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/Utilities.cs
=> Fixed export to CSV command line switch (and added unit test).

Tests/Validation/SoilWater/Sensibility/Test_Each_Process_Separately.apsimx
Working on #4195 
Thought I'd separate this from the main pull request #4188 as it may be sitting there for a while.
=> 'Fixed' soils in soil water sensibility test.

ApsimNG/Resources/Glade/MemoView.glade, ApsimNG/Views/HTMLView.cs, ApsimNG/Views/MemoView.cs
=> Hide the markdown editor on initial view of the memo component

ApsimNG/Presenters/PropertyPresenter.cs
=> When parsing text into enums, try using the description text.

Models/Core/Events.cs, Models/Fertiliser.cs, Models/Report/Report.cs, Tests/UnitTests/Report/ReportOnEvents.apsimx, Tests/UnitTests/Report/ReportTests.cs, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/Utilities.cs
- Adds fertilised event to fertiliser
- Fixed reporting on irrigated event
- Implemented // for commenting report events
Resolves #4253 Resolves #4254 Resolves #4255
=> Report improvements

ApsimNG/ApsimNG.csproj, ApsimNG/Presenters/ManagerPresenter.cs, ApsimNG/Presenters/ReportPresenter.cs, ApsimNG/Resources/SyntaxHighlighting/Report.xml, ApsimNG/Views/EditorView.cs
=> Implemented syntax highlighting for report component.

ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Views/CLEM/ModelDetailsWrapperView.cs, ApsimNG/Views/HTMLView.cs, ApsimNG/Views/HelpView.cs, ApsimNG/Views/UpgradeView.cs, Jenkins/UploadDocumentation.bat, Jenkins/build.bat, Jenkins/createInstaller.bat, Jenkins/deploy.bat, Jenkins/performanceTests.bat, Models/Properties/Resources.Designer.cs, Models/Resources/GetPackage.R, Models/Sensitivity/Morris.cs, Models/Sensitivity/Sobol.cs
So it seems that due to a bug in R(?) that when we load a package via library('asdf', lib.loc = '/packages/'), lib.loc is ignored in certain circumstances (maybe while loading dependencies or if dependencies are installed to a different location?). The simplest solution is to add this path to .libPaths for the current session.
Working on #4275
=> Fixed bug in R component (I hope)

Models/AgPasture/AgPasture.PastureSpecies.cs, Tests/UnderReview/AgPasture/AgPastureExample.apsimx
working on #3689 
Will add later a Manager component for experts to use and change these parameters.
=> Remove parameters from the AgPasture UI that most users should not access. 

APSIM.Shared/Utilities/ApsimTextFile.cs, APSIM.Shared/Utilities/ExpressionEvaluator.cs, Models/Core/VariableExpression.cs, Models/Functions/ExpressionFunction.cs
=> Eliminate use of ArrayList and generic Stack.

Jenkins/PullRequest/Jenkinsfile, Jenkins/performanceTests.bat
=> If performance tests collector runs red, Jenkins should too.

Models/Core/Locater.cs, Models/Manager.cs
=> Fixed bug in manager parameter reader

Models/Report/Report.cs
=> Fixed zone name in report

ApsimNG/Views/DropDownView.cs, ApsimNG/Views/GraphView.cs, Tests/UnitTests/ApsimNG/Utilities/GtkUtilities.cs, Tests/UnitTests/ApsimNG/Views/GraphViewTests.cs
=> Added unit tests for box plot and fixed default colour.

ApsimNG/Resources/dark.gtkrc, ApsimNG/Views/MainView.cs, Bin/.gtkrc
Resolves #4294, resolves #2137
Second screenshot is not very good...the unselected tabs are darker than in the screenshot.
=> Fixed tab colours so it's easier to tell which tab is selected.

Models/Storage/ReportData.cs, Tests/UnitTests/Report/ReportTests.cs
=> Cast enum values to strings for storage in database.

Models/Importer/APSIMImporter.cs
=> When importing old .apsim files, add fert/irrigation nodes if needed.

Models/Grazplan/Supplement.cs
=> Added FeedBegin and FeedEnd methods to supplement

Models/Surface/SurfaceOrganicMatter.cs
=> SurfaceOM implements IRemovableBiomass

Models/Plant/Organs/Root.cs
=> Check pawc and paw

ApsimNG/Presenters/CLEM/ReportActivityLedgerPresenter.cs, ApsimNG/Presenters/DataStorePresenter.cs, ApsimNG/Presenters/ReportPresenter.cs
=> Implement zone filtering for reports.

ApsimNG/Menus/ContextMenu.cs
=> Improved exception handling in context menu event handlers.

ApsimNG/Presenters/AddModelPresenter.cs
=> Fixed bug in add model code.

Models/AgPasture/PastureSpecies.cs
=> Tidy up of the code

ApsimNG/Views/TreeView.cs
=> Prevent tree view from scrolling sideways when moving nodes up/down.

APSIM.Shared/Utilities/ExpressionEvaluator.cs
=> ln function should return log base e (not log base 2).

ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/ProfileGridPresenter.cs, Models/Soils/Soil.cs, Tests/UnitTests/ApsimNG/Presenters/ProfileGridTests.cs, Tests/UnitTests/ApsimNG/Resources/SampleFiles/NullSample.apsimx, Tests/UnitTests/ApsimNG/Utilities/UITestUtilities.cs, Tests/UnitTests/Soils/SoilsTests.cs, Tests/UnitTests/UnitTests.csproj
=> Fixed bug in soil sample view grid

Models/Clock.cs, Models/Storage/IDataStore.cs
=> Moved EndOfSimulation event trigger to correct location in Clock

Models/AgPasture/PastureSpecies.cs, Models/Interfaces/ICanopy.cs, Models/Manager.cs, Models/Models.csproj, Models/Plant/OilPalm/OilPalm.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Plant.cs, Models/Sugarcane/Sugarcane.cs, Prototypes/LeafApex/CanopyPhotosynthesis.apsimx, Prototypes/LeafApex/LeafApex.apsimx, Tests/Validation/Barley/Barley.apsimx
=> Implemented ReduceCanopy in damage interface

APSIM.Shared/Utilities/DBMerger.cs, APSIM.Shared/Utilities/DirectoryUtilities.cs, Models/Core/Run/Runner.cs, Models/Main.cs
=> Directory name should not be necessary when running from command line

Models/Clock.cs, Models/Lifecycle/Lifecycle.cs, Models/Lifecycle/PlantAssimilateConsumption.cs, Models/Lifecycle/PlantMortality.cs, Models/Lifecycle/PlantOrganConsumption.cs, Models/Lifecycle/PlantOrganFunctionalDimensionReduction.cs, Models/Models.csproj
working on #4374 
Added damage methods to Pest/Disease model
=> Pest disease

Models/CLEM/Activities/ActivityTimerCropHarvest.cs, Models/CLEM/Activities/CropActivityManageCrop.cs, Models/CLEM/Activities/CropActivityManageProduct.cs, Models/CLEM/Resources/RuminantType.cs
=> CLEM fixed applying pasture growth nitrogen from a file crop reader

Models/AgPasture/GenericTissue.cs, Models/AgPasture/PastureAboveGroundOrgan.cs, Models/AgPasture/PastureBelowGroundOrgan.cs, Models/AgPasture/PastureSpecies.cs, Models/AgPasture/RootTissue.cs, Models/Plant/Organs/Root.cs, Models/Plant/Plant.cs
=> Damage interface

Models/Functions/VariableReference.cs, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/LeafApex/CanopyPhotosynthesis.apsimx, Prototypes/Soybean/Soybean.apsimx
=> Check for Null Variable References

ApsimNG/Presenters/CLEM/MessagePresenter.cs, ApsimNG/Views/CLEM/ModelDetailsWrapperView.cs, Models/CLEM/Activities/LabourActivityFeed.cs, Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/FileCrop.cs, Models/CLEM/FileSQLiteGRASP.cs, Models/CLEM/Resources/CLEMResourceTypeBase.cs
=> Updated help links in CLEM to new website

Jenkins/UploadDocumentation.bat
=> Some error checking/diagnostics for uploading autodocs.

Models/CLEM/Reporting/ConceptionStatusChangedEventArgs.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantFemale.cs, Models/CLEM/Resources/RuminantHerd.cs
=> Fixed initial setup of breeding females in CLEM to correct conception reporting

Models/Stock/stock.cs
=> Addded a GenotypeNamesAll()

Models/CLEM/Activities/LabourActivityFeedTarget.cs, Models/CLEM/Activities/LabourActivityFeedToTargets.cs, Models/CLEM/Activities/LabourActivityFeedToTargetsV1.cs, Models/CLEM/Resources/HumanFoodStoreType.cs, Models/CLEM/Resources/LabourType.cs, Models/CLEM/Resources/ResourceRequests.cs, Models/Models.csproj
=> Updated human consumption and excess food selling rules

Models/Plant/Arbitrator/SorghumArbitrator.cs, Models/Plant/Organs/SorghumLeaf.cs
=> fix reset of variables in SorghumLeaf and the Arbitrator

Models/Plant/Organs/Leaf.cs
=> Reduced the amount of reporting from leaf on biomass removal

Models/Plant/Organs/GenericOrgan.cs, Models/Resources/Chicory.json, Models/Resources/FodderBeet.json, Models/Resources/Plantain.json, Models/Resources/RedClover.json, Models/Resources/WhiteClover.json
=> Make TapRoot below ground

Models/Soils/SoilWaterBackend/SoilWaterSoil.cs, Models/Soils/WaterModel/WaterBalance.cs
=> Fixed soil wat generating millions of warnings.

Tests/UnderReview/Nutrient/Nutrient.apsimx
=> Fixed faulty soil in Nutrient tests

Models/Soils/SoilWaterBackend/SoilWaterSoil.cs, Models/Soils/WaterModel/WaterBalance.cs
=> Fixed faulty soils in lucerne validation set.

Tests/UnitTests/IrrigationTests.cs
=> Fixed soil in soilwat unit tests.

ApsimNG/Views/GridView.cs
=> Fixed multi-cell selection when selecting up to bottom row in grid.

ApsimNG/Resources/Glade/AddModelView.glade, ApsimNG/Views/TreeView.cs
=> Allow scrolling via up/down keys in add model view.

Models/Factorial/Factor.cs
=> Allow for disabling composite factors and their model overrides.

Models/Functions/LessThanFunction.cs
=> LessThanFunction should not cache its child functions.

Models/Weather/Weather.cs
=> Fix weather.co2 to allow co2 to be set from experiment factor

Models/Stock/stock.cs, Models/Stock/stock_intf.cs
resolves #4426
Fixed function. Improved function by using already created StockList parameter set.
=> Improve the GenotypeNamesDefined() function

ApsimNG/Presenters/PropertyPresenter.cs, Models/Core/Attributes/DisplayAttribute.cs
=> Implemented DisplayAttribute.PlantName property

ApsimNG/Views/GridView.cs
=> Fixed separator rows in grids preventing editing.

ApsimNG/Interfaces/IMainView.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Utility/Configuration.cs, ApsimNG/Views/MainView.cs
=> Remember previous location of split-screen divider.

ApsimNG/Views/SeriesView.cs
=> Series help button should proc on mouse release rather than mouse press.

ApsimNG/Views/StockView.cs
=> Remove unused variables.

ApsimNG/Presenters/IntellisensePresenter.cs
=> Don't show intellisense if object name is a number.

ApsimNG/Presenters/CLEM/PropertyTablePresenter.cs, Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/Activities/RuminantActivityWean.cs, Models/CLEM/Common.cs, Models/CLEM/Groupings/RuminantFilter.cs, Models/CLEM/Groupings/RuminantFilterGroup.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/ZoneCLEM.cs
=> Added weaning style to CLEM ruminant wean activity

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
=> Fixed and improved the auto irrigation script in the Management toolbox

Models/CLEM/Activities/RuminantActivityBreed.cs, Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/Activities/RuminantActivityTrade.cs, Models/CLEM/Reporting/ConceptionStatusChangedEventArgs.cs
=> Implements Minimum number of breeders kept

Tests/Validation/Eucalyptus/Eucalyptus.apsimx
=> Fixed Eucalyptus Sensibility Tests

APSIM.Shared/Utilities/SQLite.cs, Models/Storage/EmptyCommand.cs
=> "Vacuum" only on a full database cleanup.

Models/Core/ApsimFile/Converter.cs, Models/Core/ApsimFile/JsonUtilities.cs
=> Added json utility functions to rename models

APSIMRunner/APSIMRunner.csproj, APSIMRunner/Properties/AssemblyInfo.cs, ApsimNG/Properties/AssemblyInfo.cs, Jenkins/build.bat, Models/Importer/Importer.csproj, Models/Importer/Properties/AssemblyInfo.cs, Models/Properties/AssemblyInfo.cs, Models/Properties/AssemblyVersion.cs, Tests/UnitTests/Properties/AssemblyInfo.cs, Tests/UnitTests/UnitTests.csproj, Updater/Properties/AssemblyInfo.cs, Updater/Updater.csproj
Resolves #4540 
I've changed all projects to use Models.exe's AssemblyVersion.cs file. This is the approach which was previously used for ApsimNG.
=> Update copyright info and add version info for Updater/Importer/etc.

Documentation/DocumentFile.cs
Working on #4315 
First commit was necessary because I was getting out of memory errors when generating sorghum autodocs.
=> Fixed Jenkins' create documentation script

ApsimNG/Presenters/ManagerPresenter.cs
=> Fixed crash in manager when reformatting code which doesn't compile.

APSIM.Shared/Utilities/DataTableUtilities.cs, Models/Core/Locater.cs, Models/Core/VariableProperty.cs, Models/Report/ReportColumn.cs, Models/Storage/ReportData.cs, Tests/UnitTests/Report/ReportDataTests.cs
=> Fix several reporting defects

Examples/MorrisExample.apsimx
=> Fix graphs in Morris Example

APSIM.Shared/Utilities/Firebird.cs, APSIM.Shared/Utilities/IDatabaseConnection.cs, APSIM.Shared/Utilities/SQLite.cs, ApsimNG/Presenters/SeriesPresenter.cs, ApsimNG/Views/GraphView.cs, Models/Graph/Series.cs, Models/Storage/DataStoreReader.cs, Models/Storage/IStorageReader.cs, Tests/UnitTests/ApsimNG/Views/GraphViewTests.cs, Tests/UnitTests/Graph/SeriesTests.cs, Tests/UnitTests/Storage/MockStorage.cs, Tests/UnitTests/TextStorageReader.cs
=> Box plot can now work with wider range of X variables

Models/Utilities/R.cs
=> Fixed crash when attempting to install R on windows.

Models/Sensitivity/Morris.cs, Models/Sensitivity/Sobol.cs
=> Sensitivity

Models/Core/ApsimFile/Converter.cs, Models/Functions/DemandFunctions/AllometricDemandFunction.cs, Models/Resources/AGPBrownTop.json, Models/Resources/AGPCocksfoot.json, Models/Resources/AGPKikuyu.json, Models/Resources/AGPLucerne.json, Models/Resources/AGPPaspalum.json, Models/Resources/AGPPhalaris.json, Models/Resources/AGPRedClover.json, Models/Resources/AGPRhodes.json, Models/Resources/AGPRyegrass.json, Models/Resources/AGPTallFescue.json, Models/Resources/AGPWhiteClover.json, Models/Resources/Barley.json, Models/Resources/Chicory.json, Models/Resources/Eucalyptus.json, Models/Resources/FodderBeet.json, Models/Resources/Maize.json, Models/Resources/Nutrient.json, Models/Resources/Oats.json, Models/Resources/OilPalm.json, Models/Resources/Plantain.json, Models/Resources/Potato.json, Models/Resources/RedClover.json, Models/Resources/SCRUM.json, Models/Resources/Slurp.json, Models/Resources/SurfaceOrganicMatter.json, Models/Resources/Wheat.json, Models/Resources/WhiteClover.json
working on #4423.  Change allometric demand function to use variable reference instead of having its own locator code
=> Tidy up variable referencing

Models/PostSimulationTools/PredictedObserved.cs
Resolves #4563 
Working on #4131
=> Refactoring to improve PredictedObserved performance

Models/Core/ApsimFile/Structure.cs
=> Clear the scope cache after adding/removing/renaming models

ApsimNG/Views/TreeView.cs
=> Fixed bug where right hand view sometimes gets stuck

Models/Resources/AGPBrownTop.json, Models/Resources/AGPCocksfoot.json, Models/Resources/AGPKikuyu.json, Models/Resources/AGPLucerne.json, Models/Resources/AGPPaspalum.json, Models/Resources/AGPPhalaris.json, Models/Resources/AGPRedClover.json, Models/Resources/AGPRhodes.json, Models/Resources/AGPTallFescue.json
working on #4583 
Fixed Maintenance respiration coefficient (old APSIM files were in %)
=> AgPasture species

ApsimNG/Views/IntellisenseView.cs
=> Fixed intellisense not appearing in property presenter

ApsimNG/Commands/CreateModelDescriptionDocCommand.cs, Models/Core/ModelCollectionFromResource.cs
=> Added input parameters to model description auto-doc

ApsimNG/Presenters/FactorPresenter.cs, ApsimNG/Presenters/SeriesPresenter.cs, ApsimNG/Views/EditBoxView.cs, ApsimNG/Views/EditorView.cs, ApsimNG/Views/IntellisenseView.cs
=> Improved insertion of intellisense suggestions

Jenkins/Installation/Jenkinsfile
=> Fixed path in jenkins file

Docs/CreateDocumentation/CreateDocumentation.csproj
=> Change the release build path so jenkins can find it in bin

Docs/CreateDocumentation/Program.cs
=> Trying to determine why auto-doc is failing while getting apsim version

Docs/CreateDocumentation/CreateDocumentation.csproj, Docs/CreateDocumentation/Program.cs
=> Create documentation: Prefer 64bit for release mode

Docs/CreateDocumentation/Program.cs, Docs/content/ModelDocumentation/_index.md
=> Change netlify link to model documentation

ApsimNG/Presenters/InitialWaterPresenter.cs, ApsimNG/Presenters/ProfilePresenter.cs
=> Fixed a few bugs in profile presenter

ApsimNG/Presenters/ProfileGridPresenter.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs
=> Fixed some minor bugs in grids

Docs/CreateDocumentation/Program.cs
=> Refactor documentation

Docs/CreateDocumentation/Program.cs
=> Auto-doc: Make links open in new tab

Docs/CreateDocumentation/Documentation.json, Docs/CreateDocumentation/Program.cs
=> AutoDoc updates following review

Tests/UnitTests/.runsettings, Tests/UnitTests/UnitTests.csproj
=> Added .runsettings file for unit tests

ApsimNG/Menus/ContextMenu.cs
=> Show errors when refreshing data store

Models/Core/Model.cs, Models/Core/Simulations.cs, Models/Main.cs, Models/Summary.cs
=> Moved ApsimVersion property into Simulations and made it serializable.

Models/Soils/Nutrients/NFlow.cs, Models/Soils/Standardiser/SoilStandardiser.cs
=> Fixed a few issues in soil code

Models/Weather/Weather.cs
=> Allow weather to be put into a zone for zone level weather
