APSIMInitiative/ApsimX

Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Phenology/VernalisationCW.cs, Models/Plant/Plant.cs, Models/Plant/Structure.cs, Models/Weather.cs
=> Remove all warnings messages which are caused by comment styles.

Models/Core/Apsim.cs, Models/Factorial/FactorValue.cs, Tests/Factorial/Factorial.apsimx
=> Fix factorial bug with manager scripts

Tests/UnitTests/APITest.cs, Tests/UnitTests/Resources/Test3.apsimxForUnitTest, Tests/UnitTests/UnitTests.csproj, UserInterface/Commands/AddModelCommand.cs, UserInterface/Commands/DeleteModelCommand.cs, UserInterface/Commands/MoveModelUpDownCommand.cs, UserInterface/Commands/RenameModelCommand.cs, UserInterface/Commands/SelectNodeCommand.cs, UserInterface/Interfaces/IExplorerView.cs, UserInterface/Menus/ContextMenu.cs, UserInterface/Presenters/ExplorerPresenter.cs, UserInterface/Views/ExplorerView.Designer.cs, UserInterface/Views/ExplorerView.cs
=> Fixed GUI move up down bug.

Models/Core/Simulations.cs, UserInterface/Views/ExplorerView.Designer.cs, UserInterface/Views/ExplorerView.cs
=> Clear old error messages before start of run. Resolves #69.

UserInterface/Classes/HTMLToRTF.cs, UserInterface/Classes/RTFToHTML.cs, UserInterface/Views/SummaryView.Designer.cs, UserInterface/Views/SummaryView.cs
Use StringBuilder for HTML - RTF conversion (much faster)
Quote backslashes
Add a scrollbar
Addresses #43
=> Fix several issues with SummaryView:

Models/Weather.cs, UserInterface/Presenters/MetDataPresenter.cs
=> Handle errors or missing values in met files a little more robustly.

Models/Report/Report.cs, Tests/Defects/Issue76.apsimx, UserInterface/Presenters/GraphPresenter.cs
=> Fix for graph series colours not different for multiple zones.

UserInterface/Views/HTMLView.Designer.cs, UserInterface/Views/HTMLView.resx
=> Small fix for anchors of summary view in user interface

UserInterface/Classes/PMFDocumentation.cs
=> Small fix to PMF auto doc code

Models/Plant/Organs/SimpleLeaf.cs
=> Fix #19: Potential failure in SimpleLeaf.cs

Models/Plant/Cultivar.cs, Models/Plant/Functions/Constant.cs, Models/Resources/MCSP.xml, Models/Resources/Maize.xml, Models/Resources/Potato.xml, Models/Resources/Wheat.xml, Tests/PMFSlurp/PMFSlurp.apsimx, Tests/Potato/PotatoValidation.apsimx, UserInterface/Resources/Toolboxes/StandardToolbox.apsimx
=> Fix cultivar overrides in PMF

UserInterface/Presenters/ExplorerPresenter.cs
=> Fix problem with pasting of soil nodes. 

Models/Importer/APSIMImporter.cs
=>   Use InvariantCulture when converting doubles during import.

Models/Core/Attributes/DoNotDocumentAttribute.cs, Models/Graph/Graph.cs, Models/Models.csproj, Models/Plant/Functions/DemandFunctions/AllometricDemandFunction.cs, Models/Plant/Functions/DemandFunctions/InternodeDemandFunction.cs, Models/Plant/Functions/DemandFunctions/PartitionFractionDemandFunction.cs, Models/Plant/Functions/DemandFunctions/PopulationBasedDemandFunction.cs, Models/Plant/Functions/DemandFunctions/PotentialSizeDemandFunction.cs, Models/Plant/Functions/PhaseLookup.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Phenology/EmergingPhase.cs, Models/Plant/Phenology/GenericPhase.cs, Models/Plant/Phenology/GerminatingPhase.cs, Models/Plant/Phenology/LeafAppearancePhase.cs, Models/Plant/Phenology/Phenology.cs, Models/Plant/Structure.cs, UserInterface/Classes/PMFDocumentation.cs, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Interfaces/ISeriesEditorView.cs, UserInterface/Menus/ContextMenu.cs, UserInterface/Presenters/ExplorerPresenter.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/Presenters/MemoPresenter.cs, UserInterface/Presenters/SeriesPresenter.cs, UserInterface/Resources/Export.css, UserInterface/Views/GraphView.cs, UserInterface/Views/HTMLView.Designer.cs, UserInterface/Views/HTMLView.resx, UserInterface/Views/SeriesEditorView.Designer.cs, UserInterface/Views/SeriesEditorView.cs
=> Improvements to the PMF and validation auto-documentation

Models/Summary.cs, UserInterface/Classes/HTMLToRTF.cs, UserInterface/Views/SummaryView.cs
Improves RTF generation. Addresses #106, but doesn't deal with the table issue.
=> Better handling of curly braces and other special characters.

UserInterface/Interfaces/IGraphView.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/Views/GraphView.cs
Resolves #108. It may also fix #110, but I would like to let Hamish test it first.
=> Use a better mechanism to update axes maxima and minima. Resolves #108.

UserInterface/MainForm.cs
=> Fixed problem with saving normal position of window. Resolves #116.

Models/DataStore.cs, UserInterface/Presenters/GraphPresenter.cs
=> Some graph speedups.

UserInterface/Interfaces/IGridView.cs, UserInterface/Presenters/PropertyPresenter.cs, UserInterface/Views/GridView.Designer.cs, UserInterface/Views/GridView.cs
=> Changes to allow GridViews to automatically resize.

UserInterface/Interfaces/IExplorerView.cs, UserInterface/Presenters/ExplorerPresenter.cs, UserInterface/Views/ExplorerView.cs
Resolves issue #131 . Adds type name toooltip to PMF nodes on hover
=> PMF node tooltip

Models/Plant/Organs/Root.cs
=> Added test for missing soil arbitrator with Plant2 crops.

Setup/apsimx.iss, Setup/changes.html
=> Changes to ApsimX setup.

Documentation/CreateModelDocumentation.cs, Documentation/GenerateDocumentation.bat, Models/Resources/OilPalm.xml, Prototypes/Maize/MaizeValidation.apsimx, Tests/OilPalm/OilPalmValidation.apsimx, Tests/Wheat/WheatValidation.apsimx, UserInterface/Classes/PMFDocumentation.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Improvements to model documentation

Models/MicroClimate.cs, Models/Plant/OilPalm/OilPalm.cs, Models/Resources/OilPalm.xml, Models/Resources/ResidueTypes.xml
=> Oil Palm Changes

Models/Models.csproj, Models/Plant/Cultivar.cs, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/FodderBeet/FodderBeetTest.apsimx, Prototypes/Tef/Tef.apsimx, Tests/ReadExternalFiles/ReadFileTest.apsimx
=> Changes to get Jenkins to run clean.

Models/Core/Attributes/DisplayAttribute.cs, Models/PostSimulationTools/ExcelInput.cs, UserInterface/Classes/GridCell.cs, UserInterface/Interfaces/IExplorerView.cs, UserInterface/Interfaces/IGridCell.cs, UserInterface/Interfaces/IGridView.cs, UserInterface/Presenters/ExplorerPresenter.cs, UserInterface/Presenters/PropertyPresenter.cs, UserInterface/Views/ExplorerView.Designer.cs, UserInterface/Views/ExplorerView.cs, UserInterface/Views/ExplorerView.resx, UserInterface/Views/GridView.Designer.cs, UserInterface/Views/GridView.cs
=> Changed path handling plus added Browse button for ExcelInput component.

Models/Core/Simulation.cs, Models/Core/Simulations.cs, Models/Summary.cs, UserInterface/Presenters/GraphPresenter.cs
=> Get user interface to show errors.

UserInterface/Presenters/GraphPresenter.cs, UserInterface/Presenters/XYPairsPresenter.cs
=> Stop graphs appearing under XYPairs in Model XML

UserInterface/Classes/GridCell.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/Presenters/XYPairsPresenter.cs, UserInterface/Views/GridView.Designer.cs
=> Fix picturebox on all gridviews. It is getting in the way of the grid control.

Models/Core/Locater.cs, Models/Plant/Plant.cs, Models/Plant/PlantTypes.cs
=> Fixed output of Plant.SowingData.RowSpacing

Models/Plant/OilPalm/OilPalm.cs, UserInterface/Classes/PMFDocumentation.cs
=> PMF Automatic documentation improvements

Documentation/CreateModelDocumentation.cs, Documentation/GenerateDocumentation.bat, Models/Memo.cs, Models/Plant/Functions/Constant.cs, Models/Plant/Functions/LinearInterpolationFunction.cs, Models/Plant/OldPlant/PlantSpatial1.cs, Models/Plant/OldPlant/Root1.cs, Prototypes/Maize/MaizeValidation.apsimx, UserInterface/Classes/RTFToHTML.cs, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Menus/ContextMenu.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/UserInterface.csproj, UserInterface/packages.config
=> Change to use MigraDoc PDF rendering rather than relying on external app

Models/Core/AutoDocumentation.cs, Models/Core/Model.cs, Models/Memo.cs, Models/Plant/Functions/BellCurveFunction.cs, Models/Plant/Functions/Constant.cs, Models/Plant/Functions/DemandFunctions/FillingRateFunction.cs, Models/Plant/Functions/DemandFunctions/PopulationBasedDemandFunction.cs, Models/Plant/Functions/LinearInterpolationFunction.cs, Models/Plant/Functions/PhaseBasedSwitch.cs, Models/Plant/Functions/PhaseLookupValue.cs, Models/Plant/Functions/PhotoperiodFunction.cs, Models/Plant/Functions/StructureFunctions/HeightFunction.cs, Models/Plant/Functions/SupplyFunctions/RUECO2Function.cs, Models/Plant/Functions/WeightedTemperatureFunction.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Phenology/Phase.cs, Models/Plant/Plant.cs, Models/Plant/Structure.cs, Models/Plant/Summary.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Lots of small changes to improve the auto-documentation.

APSIM.bib, Models/Core/AutoDocumentation.cs, Prototypes/Maize/MaizeValidation.apsimx, UserInterface/Commands/BibTeX.cs, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/UserInterface.csproj
=> Added bibliography functionality.

ApServer/Program.cs, UserInterface/Classes/HtmlEditor.cs, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Presenters/TabbedExplorerPresenter.cs
=> Get rid of some Windows-specific path handling.

Models/Plant/OilPalm/OilPalm.cs, Models/Resources/OilPalm.xml
=> Fixed bug in oil palm water uptake that gave div by zero

UserInterface/Classes/HTMLToRTF.cs, UserInterface/Classes/RTFToHTML.cs
=> Small changes to the RTF HTML converters to stop the eating of line feeds

Models/Core/Folder.cs, Models/Graph/Series.cs, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Interfaces/ISeriesView.cs, UserInterface/Presenters/FolderPresenter.cs, UserInterface/Presenters/SeriesPresenter.cs, UserInterface/Resources/InitialWaterGraph.xml, UserInterface/Resources/WaterGraph.xml, UserInterface/UserInterface.csproj, UserInterface/Utility/Graph.cs, UserInterface/Views/FolderView.Designer.cs, UserInterface/Views/FolderView.cs, UserInterface/Views/FolderView.resx, UserInterface/Views/SeriesView.Designer.cs, UserInterface/Views/SeriesView.cs
=> Fixes to auto-doc title page and soil graph problem.

Models/Core/Folder.cs, UserInterface/Presenters/FolderPresenter.cs, UserInterface/UserInterface.csproj, UserInterface/Views/FolderView.Designer.cs, UserInterface/Views/FolderView.cs, UserInterface/Views/FolderView.resx
=> Created ability for folders in user interface to show multiple graphs.

Models/Soils/Arbitrator/SoilArbitrator.cs, Tests/SoilArbitrator/SoilArbitrator.apsimx
=> Cleaning up soil arbitrator doco

APSIM.bib
=> Changes to APSIM bibliography.

Documentation/GenerateDocumentation.bat
=> First part of continuous release system to get Jenkins to run.

Prototypes/Maize/MaizeValidation.apsimx
Simplified the thermal time model to remove complexity from the model documentation
working on #136
=> Cleaning up maize xml file

Models/Plant/Functions/PhotoperiodFunction.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Structure.cs, Prototypes/Maize/MaizeValidation.apsimx, UserInterface/Commands/ExportNodeCommand.cs
=> Cleaning up maize model documentation

UserInterface/Presenters/XYPairsPresenter.cs, UserInterface/Resources/XYPairsGraph.xml
=> Fixed PMF XYGraphs

UserInterface/Views/HTMLView.cs
=> Fixed summary file showing RTF codes

Models/Graph/Series.cs
=> Fix graph series colours when graph is sitting on a simulation.

UserInterface/Commands/RunCommand.cs, UserInterface/Interfaces/IExplorerView.cs, UserInterface/Presenters/ExplorerPresenter.cs, UserInterface/Views/ExplorerView.Designer.cs, UserInterface/Views/ExplorerView.cs
=> Added progress bar when running simulations.

UserInterface/Commands/RunCommand.cs
=> Avoid accessing null timer object. Resolves #248

UserInterface/Presenters/ManagerPresenter.cs
=> Added script formatting to Manager when user clicks away from script.

Builds/Builds.Service/Builds.svc.cs, Builds/Builds.Service/IBuildProvider.cs
=> Fix for Product Registration form not showing APSIM Next Gen

Models/Core/Simulations.cs, UserInterface/Commands/RunCommand.cs
=> Adding a check for duplicate simulations

UserInterface/Interfaces/IGridView.cs, UserInterface/Presenters/ProfilePresenter.cs, UserInterface/Presenters/PropertyPresenter.cs, UserInterface/Views/GridView.cs
=> Fixed: Grid control doesn't save until user clicks away

UserInterface/Presenters/ExplorerPresenter.cs
=> Reshow the right hand panel after user clicks Save

Models/Plant/Functions/Constant.cs
=> Added optional units for Constant functions.

UserInterface/Views/HTMLView.Designer.cs, UserInterface/Views/HTMLView.cs
=> In HtmlView, added F12 as a toggle character between edit/preview

Models/Factorial/Factors.cs, Models/Graph/Series.cs, UserInterface/Views/GraphView.cs
according to experiment / treatments. Resolves #98
=> Assign colours, line types and marker types more sensibly 

Models/DataStore.cs, Models/Plant/Functions/ExpressionFunction.cs, Models/Report/ReportColumn.cs, Prototypes/Maize/MaizeValidation.apsimx
=> Added YieldBuPerAcre output to Maize and fixed bug in report

CONTRIBUTING.md, readme.md
=> Read me file with pull request process

Models/Core/AutoDocumentation.cs, UserInterface/Classes/HtmlToMigraDoc.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Fixes for auto documentation of SCUM and other models.

UserInterface/Classes/HtmlToMigraDoc.cs
=> Unit formatting problem in autodoc

Models/Core/Simulation.cs, Models/Factorial/Factor.cs, UserInterface/Presenters/ExplorerPresenter.cs
=> Fixed some drag / drop allowances

Models/Core/Apsim.cs, Models/Graph/Series.cs
=> Graphs now plot multiple zones correctly.

Models/Plant/Interfaces/IOrgan.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/GenericAboveGroundOrgan.cs, Models/Plant/Organs/HIReproductiveOrgan.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleLeaf.cs, Tests/BiomassRemoval/BiomassRemovalTests.apsimx
resolves #273 
To resolve this I have implemented a biomass removal interface for all PMF organs so the issue name is not really a good description of the outcome and should be renamed?
I have put some default values in for the amount of organs removed and passed to residue for each organ class but these number should probably go past reference pannel?
Anyway this issue can be closed if you are happy to merge this pull request
=> Specify harvest remove proportions

Models/Graph/Series.cs, Models/Summary.cs, UserInterface/Presenters/SeriesPresenter.cs
=> Fixed empty datasource drop down in graph series.

Prototypes/Chickpea/ChickPea.apsimx
=> Chickpea unique simulation names

Models/Weather.cs
=> Weather Module - read in "evap" column as PanEvaporation

Models/Plant/Phenology/EndPhase.cs, Models/Plant/Phenology/GenericPhase.cs, Models/Plant/Phenology/GerminatingPhase.cs, Models/Plant/Phenology/LeafAppearancePhase.cs, Models/Plant/Phenology/LeafDeathPhase.cs, Models/Plant/Phenology/NodeNumberPhase.cs, Models/Plant/Phenology/Phase.cs
=> Added XMLIgnore to fractioncomplete method in phases.

Models/Plant/Phenology/Phase.cs
=> Added XMLIgnore to TTInPhase in Phase.cs

Models/SugarCane/SugarCane.cs
=> Add comment advising that sugarcane does not do Retranslocation

UserInterface/Resources/InitialWaterGraph.xml, UserInterface/Resources/WaterGraph.xml
Added new XML to correctly draw water graphs. Resolves #324.
=> Fixed incorrect series names on water graphs.

Models/DataStore.cs, Models/Report/Report.cs, UserInterface/Presenters/ReportPresenter.cs, UserInterface/Views/ReportView.Designer.cs, UserInterface/Views/ReportView.cs
Resolves #327 by adding a user settable display limiter to reduce the number of rows that need to be read from the database.
=> Report view

Models/Core/Simulation.cs, Models/Core/Simulations.cs, Models/Project.cs, Tests/UnitTests/APITest.cs
=> Fix for getting Jenkins to show all errors.

Models/Models.csproj, Models/packages.config, Packages.dgml, SWIMFrame/SWIMFrame.csproj, SWIMFrame/packages.config, Tests/UnitTests/UnitTests.csproj
Resolves #348 Updated package manager to use correct version of DLL.
=> Fix mathnet

Tests/UnitTests/TestSoils.cs, Tests/UnitTests/UnitTests.csproj
=> Added a soils unit test.

Models/Report/Report.cs, Models/Report/ReportColumn.cs
Added a 'DoOutput' method to Report model so that Manager and other models can call it. Resolves #320
=> Added a 'DoOutput' method to Report 

UserInterface/Commands/BibTeX.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Fixed author citation and duplication in Reference section of auto-doc.

Models/Graph/Series.cs
=> Changed the enum graph series iteration to avoid 'None' marker types.

UserInterface/Presenters/GraphPresenter.cs, UserInterface/Utility/LineSeriesWithTracker.cs, UserInterface/Views/GraphView.cs
=> Enhanced tool tip for graphs

Models/Report/ReportColumn.cs
=> Fix to REPORT to allow spaces in expressions.

UserInterface/EventArguments/NeedContextItemsArgs.cs
=> Fixed intellisense to work with the 'Replacements' folder.

Models/Resources/ResidueTypes.xml
=> Added Gliricidea to surface organic matter types

UserInterface/Views/TreeProxyView.Designer.cs, UserInterface/Views/TreeProxyView.cs
=> Support pasting of data into time series tab

Models/DataStore.cs, Models/PostSimulationTools/PredictedObserved.cs
=> Fix pred / obs graphs when multiple zones exist.

UserInterface/Presenters/ExplorerPresenter.cs
=> Allow any model to be dropped on a Replacements node in the GUI.

Models/DataStore.cs
=> Trap exception when querying data and return null DataTable.

UserInterface/Presenters/ExplorerPresenter.cs
=> Allow crops to be dropped on a zone (rectangular or otherwise) properly.

Models/PostSimulationTools/PredictedObserved.cs
=> Fixed PredictedObserved class to output matching field names properly.

Models/Plant/Cultivar.cs
=> Fix 'Document' method to stop an 'object not set to an instance... error

Models/Graph/Regression.cs
=> Fix to avoid null pointer error from regression

UserInterface/Classes/HtmlToMigraDoc.cs, UserInterface/Commands/BibTeX.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Allow for PHD and Masters thesis in .bib file. Fix URLs in .bib file.

UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Presenters/GraphPresenter.cs
+ get rid of empty headings in pdf. Also fixed a bug where graph PNG files were being overwritten.
Resolves #409
=> Changed auto-doc to recurse into Windbreak system 

UserInterface/Commands/BibTeX.cs
=> Added support for tech mems in .BIB file.

Models/Plant/OldPlant/Leaf1.cs
=> Allow wheat model in resource xml file to be serialised.

Models/Agroforestry/AgroforestrySystem.cs, Models/Agroforestry/LocalMicroClimate.cs, Models/Agroforestry/TreeProxy.cs
=> Moved wind functions to Agroforestry model.

Models/Graph/Series.cs, UserInterface/Interfaces/ISeriesView.cs, UserInterface/Presenters/SeriesPresenter.cs, UserInterface/UserInterface.csproj, UserInterface/Views/EditBoxView.Designer.cs, UserInterface/Views/EditBoxView.cs, UserInterface/Views/EditBoxView.resx, UserInterface/Views/SeriesView.Designer.cs, UserInterface/Views/SeriesView.cs
=> Added filter to graph series.

Models/Clock.cs
=> Added start/end week events to Clock.

Setup/apsimx.iss
=> Add model.xml to release so that auto-doc works in release.

UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Views/GraphView.cs
=> Improve formatting of dates on graphs and in auto-doc graphs.

Models/Graph/IGraphable.cs
=> Reorder graph series symbols - filled symbols first.

Models/Core/Model.cs, UserInterface/Views/FolderView.cs, UserInterface/Views/GraphView.Designer.cs, UserInterface/Views/GraphView.cs
=> Made FolderView more readable when showing lots of controls.

Prototypes/Maize/MaizeValidation.apsimx
=> Maize validation clean up

Models/Core/Apsim.cs, Models/Core/Simulations.cs, Models/Summary.cs, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/PMFSlurp/PMFSlurp.apsimx, Prototypes/WheatPMFPrototype/WheatPMFtest.apsimx, Tests/BiomassRemoval/BiomassRemovalTests.apsimx, UserInterface/Commands/RunCommand.cs
=> Fix ResolveLink function to correctly resolves [Link]s

Models/Core/Simulations.cs, UserInterface/Presenters/FolderPresenter.cs
=> Speed up graph editing.

Models/PostSimulationTools/Probability.cs
=> Fixed the probability post simulation model.

Models/Graph/Series.cs, UserInterface/Presenters/SeriesPresenter.cs
=> Fix drag and drop of Graph folders from one .apsimx to another.

Models/Soils/Arbitrator/Estimate.cs, Models/Soils/Arbitrator/SoilArbitrator.cs
=> Speed improvement in SoilArbitrator.

APSIM.bib, Models/Core/Model.cs, Models/Importer/Resources/Types.xml, Models/Models.csproj, Models/Plant/Functions/OnEventFunction.cs, Models/Plant/Functions/StructureFunctions/MainStemFinalNodeNumberFunction.cs, Models/Plant/Phenology/ZadokPMF.cs, Models/Plant/Structure.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Progress with wheat.  Added Zadok model, fixed FLN predictions

Models/Factorial/FactorValue.cs, Models/Graph/Series.cs
=> Fix for graphs inside Experiments that have property setting factors.

UserInterface/Classes/HtmlToMigraDoc.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Added in-line code support in Memos

UserInterface/Classes/HtmlToMigraDoc.cs
=> Fixed spacing around bullet list.

UserInterface/Presenters/SeriesPresenter.cs
=> Sorted the variable names in SeriesPresenter.

Models/Plant/Organs/Leaf.cs, Prototypes/Maize/MaizeValidation.apsimx
=> Added row spacing effect

Prototypes/Maize/MaizeValidation.apsimx
=> Changed grain number function

Models/Factorial/Experiment.cs, Models/Factorial/Factor.cs, Models/Factorial/FactorValue.cs, Models/Models.csproj, Models/Report/Report.cs, Models/Report/ReportColumn.cs, Models/Report/ReportColumnConstantValue.cs, UserInterface/Presenters/DataStorePresenter.cs
=> Added factor values to report tables.

UserInterface/Views/GridView.cs
=> Fixed invalid char in GridView

Models/Core/Apsim.cs
=> Stop dragging of Simulations.

Models/Graph/IGraphable.cs, Models/Graph/Series.cs, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Interfaces/IGraphView.cs, UserInterface/Interfaces/ISeriesView.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/Presenters/MetDataPresenter.cs, UserInterface/Presenters/SeriesPresenter.cs, UserInterface/Views/GraphView.cs, UserInterface/Views/SeriesView.Designer.cs, UserInterface/Views/SeriesView.cs, UserInterface/Views/TreeProxyView.cs
Increment marker type if run out of colours. Resolves #485
=> Added marker size and line thickness to graph series. 

UserInterface/Presenters/MetDataPresenter.cs
=> Fixed ordering of columns in met file.

APSIM.bib, Models/Plant/Functions/MaximumFunction.cs, Models/Plant/Functions/MinimumFunction.cs, Models/Plant/Functions/SupplyFunctions/RUECO2Function.cs, Models/Plant/Functions/SupplyFunctions/RUEModel.cs, Prototypes/Maize/MaizeValidation.apsimx
=> clean up maize doco

Prototypes/Maize/MaizeValidation.apsimx
=> fixed misnamed sample nodes

Models/AgPasture.cs, Models/AgPasture/AgPasture1.PastureSpecies.cs, Models/AgPasture/AgPasture1.Sward.cs, Models/Interfaces/ICanopy.cs, Models/MicroClimate.cs, Models/MicroClimateScience.cs, Models/Plant/OilPalm/OilPalm.cs, Models/Plant/OldPlant/Leaf1.cs, Models/Plant/OldPlant/Plant15.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Organs/TreeCanopy.cs, Models/Plant/PlantTypes.cs, Models/Plant/SimpleTree/SimpleTree.cs, Models/SugarCane/SugarCane.cs
=> First iteration of a MicroClimate refactor

UserInterface/Views/DataStoreView.Designer.cs
=> Report view layout problem fixed.

UserInterface/Views/FolderView.Designer.cs, UserInterface/Views/FolderView.cs, UserInterface/Views/GraphView.Designer.cs, UserInterface/Views/GraphView.cs
=> Improve folder view. Allow enable/disable graph legends.

UserInterface/Presenters/PropertyPresenter.cs
=> Fix property presenter to save enum drop down selections.

UserInterface/Presenters/ManagerPresenter.cs
=> Changed manager presenter to say when a script compiles successfully.

Models/Graph/Series.cs, UserInterface/Interfaces/ISeriesView.cs, UserInterface/Presenters/SeriesPresenter.cs, UserInterface/Views/SeriesView.Designer.cs, UserInterface/Views/SeriesView.cs
=> Optionally allow series names in graph legend text.

Models/Graph/IGraphable.cs, Models/Graph/Series.cs
=> Speed up graphs

UserInterface/Presenters/ManagerPresenter.cs, UserInterface/Presenters/PropertyPresenter.cs, UserInterface/Views/GridView.cs
=> Fix property grid to update properties tab with changed manager script.

APSIM.bib, UserInterface/Commands/BibTeX.cs
=> Fix exception from autodoc - bad bib file format.

UserInterface/Presenters/PropertyPresenter.cs
=> Fixed cultivar drop down to work with replacements.

UserInterface/Views/HTMLView.cs
=> Refresh Memo control when 'Preview' clicked on by user.

ApServer/ApServer.csproj, Models/Importer/Importer.csproj, Models/Models.csproj, SWIMFrame/SWIMFrame.csproj, Tests/UnitTests/UnitTests.csproj, Updater/Updater.csproj, UserInterface/UserInterface.csproj
=> Fix for x86 / AnyCPU configuration in project files.

Models/Graph/Series.cs
=> Dean's changes to fix bug in graphing component

Models/Agroforestry/AgroforestrySystem.cs, Models/Agroforestry/LocalMicroClimate.cs
=> Fixed bug for zero tree water use

Models/Core/Zone.cs, Models/DataStore.cs, Models/Factorial/FactorValue.cs, Prototypes/PMFSlurp/PMFSlurp.apsimx
=> Jenkins was crashing during it's run of PMFSlurp.

UserInterface/Classes/HtmlToMigraDoc.cs
=> Fixed autodoc crash when using code blocks.

Models/Graph/Series.cs
=> Readded zonename bug fix.

Models/Plant/Functions/LinearInterpolationFunction.cs, UserInterface/Presenters/XYPairsPresenter.cs, UserInterface/Resources/XYPairsGraph.xml, UserInterface/Utility/Graph.cs
=> Put units on Y axis for PMF Model graphs.

UserInterface/Presenters/AddModelPresenter.cs, UserInterface/Presenters/ExplorerPresenter.cs, UserInterface/Views/ButtonView.cs, UserInterface/Views/ListBoxView.Designer.cs, UserInterface/Views/ListBoxView.cs
=> Add double click to AddPresenter.

Prototypes/SugarCane/Validation/SugarcaneValidation - Correct Harvest Dates.apsimx, Prototypes/SugarCane/Validation/SugarcaneValidation.apsimx
=> Tweaks to the Sugarcane Validation 

Models/Plant/Functions/PowerFunction.cs
=> Modified power function to take a function for an exponent

Models/SurfaceOrganicMatter.cs
=> Fixed resizing of Fpool arrays

Models/Factorial/Experiment.cs, Models/Tests.cs, Prototypes/Agroforestry/AgroforestrySystem.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/Maize/MaizeValidation.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Tests/MultiZoneManagement/MultiFieldMultiZoneManagementBasic.apsimx, Tests/SCUM/SCUM.apsimx, Tests/Slurp/Slurp.apsimx
=> Experiment / treatment column bug

Tests/SCUM/SCUM.apsimx
=> fix problems in SCUM validation simulations

Models/Manager.cs, UserInterface/Attributes/ContextMenuAttribute.cs, UserInterface/Commands/RunCommand.cs, UserInterface/Interfaces/IExplorerView.cs, UserInterface/Interfaces/IGraphView.cs, UserInterface/Interfaces/IInitialWaterView.cs, UserInterface/Menus/ContextMenu.cs, UserInterface/Menus/MainMenu.cs, UserInterface/Presenters/AddModelPresenter.cs, UserInterface/Presenters/ExplorerPresenter.cs, UserInterface/Presenters/FolderPresenter.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/Presenters/TabbedExplorerPresenter.cs, UserInterface/Presenters/TreeProxyPresenter.cs, UserInterface/Views/ExplorerView.cs, UserInterface/Views/FolderView.cs, UserInterface/Views/GraphView.cs, UserInterface/Views/ListButtonView.cs, UserInterface/Views/TabbedExplorerView.cs, UserInterface/Views/TreeProxyView.cs
=> Reduce use of Windows.Forms. Resolves #637.

Models/Core/Runner.cs, Models/Core/Simulations.cs, Models/Models.csproj, Models/Project.cs, UserInterface/Commands/RunCommand.cs
=> Changed to multi-process when running multiple .apsimx files.

Models/Core/Runner.cs, UserInterface/Commands/RunCommand.cs, UserInterface/Views/ExplorerView.cs
=> Fix for not showing errors and progress bar in GUI.

Models/Importer/APSIMImporter.cs, Models/Project.cs, Tests/UnitTests/UnitTests.csproj
Also fixed duplicating error messages and command line. Resolves #652
=> Speed up unit tests.

Models/Resources/Maize.xml
Resolves #597 
Have added African maize varieties into Maize resource file to enable work in African agroforestry projects.
=> Added African cultivars

LICENSE.md
=> Added license file.

Models/PostSimulationTools/ExcelInput.cs
=> Stop ExcelInput from loading XLS files.

Models/Tests.cs, UserInterface/Presenters/PropertyPresenter.cs
Also changed the 'X' to  'FAIL' in the fail column.
Resolves #613
=> Changed number precision in Tests node

UserInterface/Commands/ExportNodeCommand.cs
=> Fixed PDF graph sizes and made sensibility node top level.

UserInterface/Commands/ExportNodeCommand.cs
=> Added page break before main headings.

Prototypes/Chickpea/ChickPea.apsimx
=> Fixed graphs and added tests node

Models/Core/Runner.cs
=> Fix problem where simulation wasn't being cloned when run.

Models/Core/Runner.cs, Models/Core/Simulations.cs, UserInterface/Commands/RunCommand.cs
=> Fix running of single simulations again.

Models/Graph/Series.cs
=> Fixed graph filter.

Models/Resources/Maize.xml
=> New variety added to maize model

UserInterface/Presenters/MetDataPresenter.cs, UserInterface/UserInterface.csproj, UserInterface/Views/TabbedMetDataView.Designer.cs, UserInterface/Views/TabbedMetDataView.cs
resolves #495.  Added additional charts for displaying of weather/met data.
=> Weather graph

Setup/apsimx.iss
=> Fixed version in setup file.

UserInterface/Forms/UpgradeForm.Designer.cs, UserInterface/Forms/UpgradeForm.cs
=> Minor fixes in Upgrade form.

UserInterface/Forms/UpgradeForm.Designer.cs
=> Anchored floating buttons on Upgrade form.

Models/Importer/APSIMImporter.cs, UserInterface/Presenters/AddModelPresenter.cs, UserInterface/Presenters/ExplorerPresenter.cs
=> Speed up pasting of soil nodes and adding models into GUI

Models/Graph/Series.cs
=> Graph throwing SimulationName not found bug in filter.

UserInterface/Forms/UpgradeForm.cs
=> Fixed bug in upgrade form throwing a Device Not Ready error.

UserInterface/Presenters/MetDataPresenter.cs, UserInterface/Views/TabbedMetDataView.cs
Work Resolves #700 …Graphs and associated data loading on tab click event (not on form load)
=> Graphs and associated data loading on tab click event (not on form load)

Models/Core/Runner.cs, Models/Factorial/Experiment.cs, Models/Factorial/Factor.cs, Tests/UnitTests/UnitTests.csproj
=> Updated Experiment / Factor functionality

Models/Resources/Wheat.xml
=> Austrian cultivars

UserInterface/Menus/ContextMenu.cs
=> Remove write to CSV. Too slow. Memory intensive.

Models/Graph/Graph.cs, Models/Graph/Series.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/Presenters/SeriesPresenter.cs, UserInterface/Views/GraphView.cs
=> Change SeriesPresenter to only show column names that are in scope.

Models/AgPasture.cs, Models/AgPasture/AgPasture1.PastureSpecies.cs, Models/AgPasture/AgPasture1.Sward.cs, Models/Core/ICrop.cs, Models/Manager.cs, Models/Plant/OilPalm/OilPalm.cs, Models/Plant/OldPlant/Plant15.cs, Models/Plant/Plant.cs, Models/Plant/SimpleTree/SimpleTree.cs, Models/Sugarcane/Sugarcane.cs, UserInterface/Presenters/TabbedExplorerPresenter.cs, UserInterface/Resources/Toolboxes/ManagementToolbox.apsimx
=> Added a management toolbox.

Models/Resources/Wheat.xml
=> put austrain cultivars back

Prototypes/Wheat/WheatValidation.apsimx
=> Nitrogen and Canopy model improvements

UserInterface/Views/GridView.cs
=> Fixed paste within a grid cell.

Models/Manager.cs
=> Small fix to Manager to handle blank scripts coming from converter

Prototypes/Wheat/WheatValidation.apsimx
=> no message

Models/Graph/Graph.cs, Models/Graph/Series.cs
=> Added missing markers on graph.

Models/Soils/Soil.cs
=> Fixed problem with bad soils when importing old .apsim file.

APSIM.bib, Prototypes/Wheat/WheatValidation.apsimx
=> Started documenting experiments

Prototypes/Egrandis/Egrandis.apsimx
=> Euc model now uses simple leaf

Models/Core/AutoDocumentation.cs, Models/Tests.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Added statistics to auto-doc

Models/Plant/Functions/PhotoperiodFunction.cs, Models/Plant/Functions/SupplyFunctions/RUEModel.cs, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/Leaf.cs, UserInterface/Presenters/XYPairsPresenter.cs
=> Model description graph throws error.

UserInterface/Views/GridView.cs
=> Fix grid cell delete while editing.

Prototypes/Wheat/WheatValidation.apsimx
=> validation improved

UserInterface/Presenters/SeriesPresenter.cs
=> Added series types into SeriesEditor.

Models/Core/Runner.cs
=> Fix problem where a single simulation run from an experiment

Prototypes/Wheat/WheatValidation.apsimx
=> Model improvements (or not)

Prototypes/Wheat/WheatValidation.apsimx
=> Mouse work

Models/Plant/Phenology/Phenology.cs
=> Minor bug fix with potential fall out

Models/Summary.cs
=> Format HTML summaries a bit more nicely.

Models/Operations.cs, UserInterface/Utility/Configuration.cs
=> Fixed operations to handle multiple methods with the same name

Models/Memo.cs
=> Fix for Memo crashing when it is clicked on

ApsimNG/Presenters/MemoPresenter.cs, Models/Memo.cs, UserInterface/Presenters/MemoPresenter.cs
=> Use a MemoView to view memos, not an HTMLView.

UserInterface/Classes/HtmlToMigraDoc.cs
=> Fixed HtmlToMigraDoc.AddHeader to check for a Paragraph as well as a Section

Models/Memo.cs, UserInterface/Presenters/MemoPresenter.cs
Working on #834 
Reverses most changes made in #831
=> Revert earlier changes, and go back to using HTMLView to display a memo.

Models/Weather/Weather.cs, UserInterface/Presenters/MetDataPresenter.cs, UserInterface/Views/TabbedMetDataView.cs
Resolves #16 - enabling use of excel files for weather data
=> Working on Issue #16 - enabling use of excel files for weather data

Models/MicroClimate.cs
=> Add description text for parameters.

ApsimX.sln, UserInterface/Presenters/MetDataPresenter.cs, UserInterface/Views/TabbedMetDataView.cs
resolves issue #851 - Object Reference error when loading met file
=> Issue #851 re met weather files

Models/Operations.cs, UserInterface/Presenters/OperationsPresenter.cs
Resolves #837 Date format dd-mmm now works in Operations
=> Issue 837 dates in operations

Models/Plant/Phenology/QualitativePPEffect.cs
=> Added missing file from Neil Huth for chickpea model

Models/Plant/Organs/SimpleLeaf.cs
=> Fixes bug in SimpleLeafCode

Prototypes/Chickpea/ChickPea.apsimx
=> Merged mariana's apsimx file with the new HI approach

Models/Plant/Organs/Leaf.cs
=> Reduced the length of MaximumMainStemLeafNumber

Models/Core/VariableProperty.cs
=> Fix setting of boolean from experiment factor

Models/Soils/SoilCrop.cs
=> Fix units for KL and XF

UserInterface/Views/EditorView.cs
=> Better intellisense when entering equations into report

ApsimNG/Presenters/MapPresenter.cs, ApsimNG/Views/EditorView.cs, ApsimNG/Views/HTMLView.cs, ApsimNG/Views/MapView.cs, Models/DataStore.cs, Models/Map.cs, UserInterface/Presenters/MapPresenter.cs, UserInterface/Views/MapView.Designer.cs, UserInterface/Views/MapView.cs
=> Save and restore zoom level and position of maps

Models/MicroClimate.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Organs/TreeCanopy.cs, Models/Plant/Plant.cs, Models/Plant/PlantTypes.cs, Models/Plant/SimpleTree/SimpleTree.cs, Models/Resources/Maize.xml, Models/Resources/SCUM.xml, Models/Resources/Slurp.xml, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/Chicory/Chicory.apsimx, Prototypes/Chicory/Sensibility/Chicory.apsimx, Prototypes/Egrandis/Egrandis.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/FodderBeet/FodderBeetTest.apsimx, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Tests/Simulation/BiomassRemoval/BiomassRemovalTests.apsimx, Tests/Validation/SCUM/SCUM.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator V2.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
Working on #65  - Chicory model
1) Set maximum green cover sent to MicoClimate to 1-10^-9, and set the test in microClimate to this value. This is a bit less stringent than before, which was based of float not double type (Talked to Val about this)
2) Added outputs for DetachedWt and DetachedN (the amounts send by plant to either SurfaceOM or SoilFOM). So one can now track mass balance more easily
3) Change the SetFraction method in plant to allow setting the biomass type (live or dead). I've added the extra argument as optional, with default on 'live' (as it seems most organs were using only live (only leaf seem to have explicitly consider both live and dead). Several simulations had to be updated to account for this change. I expect some diffs in this first merge attempt.
4) Organised …
=> Feature/chicory model#65

ApsimNG/Views/EditorView.cs, ApsimNG/Views/ExplorerView.cs, ApsimNG/Views/MapView.cs
=> Minor updates for Gtk# version of the GUI

Models/Core/Runner.cs, Models/Project.cs, Models/Tests.cs, UserInterface/Commands/RunCommand.cs
=> Don't run Tests nodes from GUI when simulations are run.

Models/Graph/Series.cs
=> Changed graph legend to only show series that have data.

ApsimNG/Commands/RunCommand.cs
=> Update Gtk# version with recent changes to RunCommand

Prototypes/Wheat/WheatValidation.apsimx
=> Fixed sowing dates in Gatton2009

UserInterface/Views/SeriesView.Designer.cs, UserInterface/Views/SeriesView.cs, UserInterface/Views/SeriesView.resx
=> Added a help button to graph series filter box.

Models/Core/Runner.cs, Models/Core/Simulations.cs, Models/Factorial/Experiment.cs, Models/Project.cs
=> Moved replacements to before an experiment sets the report factors.

Models/Plant/Functions/Exponential.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Wheat model tuning

Models/Core/Runner.cs, Models/Core/Simulation.cs, Models/Project.cs, UserInterface/Commands/RunCommand.cs
=> New job manager

Prototypes/Wheat/WheatValidation.apsimx
=> wheat fitting

ApsimNG/Commands/RunCommand.cs
=> Keeping ApsimNG in sync with UserInterface

Prototypes/Wheat/WheatValidation.apsimx
=> working on #933 Add a new cultivar Suntop into wheat validation.

Models/Plant/Functions/SupplyFunctions/CanopyPhotosynthesis.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Prototypes/Wheat/CanopyPhotosynthesis/CanopyPhotosynthesisTest.apsimx
=> Photosynthesis

Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Organs/TreeCanopy.cs
=> Fixed OnDoDailyInitialisation not being called in BaseOrgan

Documentation/CreateModelDocumentation.cs, Documentation/GenerateDocumentation.bat, UserInterface/Presenters/MainPresenter.cs
=> Fix auto-documentation

Prototypes/Wheat/WheatValidation.apsimx
=> Fixed SW graphs

UserInterface/Presenters/CultivarPresenter.cs
=> Fixed intellisense in cultvar view

Models/Plant/Structure.cs, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/WheatValidation.apsimx
=> Fixed bug in leaf branching timing

Models/Plant/Phenology/Phenology.cs, Prototypes/Chicory/Chicory.apsimx
=> Fix Days After Sowing variable

Models/Agroforestry/TreeProxy.cs, Models/Core/Model.cs, Models/Importer/APSIMImporter.cs, Models/Interfaces/ISoilWater.cs, Models/Models.csproj, Models/Soils/MultiPoreWater.cs, Models/Soils/Soil.cs, Models/Soils/SoilWater.cs, Tests/Validation/SoilWater/ResiduesTrial.apsimx
=> Add SoilWater Interface

ApsimNG/Commands/RunCommand.cs, ApsimNG/Presenters/CultivarPresenter.cs
=> Keeping in sync with WIndows.Forms version. Also a minor change for Mac.

Models/AgPasture.cs, Models/Interfaces/ISoilWater.cs, Models/Models.csproj, Models/Soils/MultiPoreWater.cs, Models/Soils/MultiPoreWater/MultiPoreWater.cs, Models/Soils/MultiPoreWater/Pore.cs
=> Remove redundant members of soilwaterinterface

ApsimNG/Resources/Glade/GraphView.glade, ApsimNG/Views/FolderView.cs, ApsimNG/Views/GraphView.cs, ApsimNG/Views/SummaryView.cs
=> Implement display of graphs in FolderView

Models/Sugarcane/Sugarcane.cs
Still does not work. Had to turn all the headings into just Bold font.
Bullet Lists of bullet lists do not work either.
working on #575
=> Update the documentation in the Summary tag at the top of the code.

Models/Plant/Interfaces/IArbitration.cs, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleRoot.cs, Models/Soils/SoilNitrogen.cs, Prototypes/MultiZoneRoots/MultiRootZone.apsimx
Working on #985 
This pull request is actually for PMF not AgPasture but it will provide code that may be used in AgPasture to do the same thing
=> Multi zone root

UserInterface/Commands/ExportNodeCommand.cs
=> Fix case sensitivity issue with auto-doc

UserInterface/Presenters/FactorPresenter.cs
=> Remove blank factor specifications under an Experiment.

ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Presenters/FactorPresenter.cs
=> Keep Gtk# version in sync with recent changes.

Models/Core/AutoDocumentation.cs, Models/Sugarcane/Sugarcane.cs
=> Fix auto-doc issues with formating of headings.

Examples/SCRUM.apsimx
=> Added Scrum Example

Models/Graph/EventNamesOnGraph.cs, Models/Graph/IGraphable.cs
=> Attempt at fixing DataView serialization problems on Jenkins

Models/Irrigation.cs, Models/Soils/IrrigationApplicationType.cs, Tests/UnitTests/MockIrrigation.cs
=> Adding Duration property into irrigation

Models/Weather/Weather.cs
=> Adding RainfallHours property into weather file handling

Models/Graph/Series.cs
=> Fix problem with locating the Soil model.

Models/Core/Apsim.cs
=> Restore parent after serialization, as intended.

Models/Resources/ResidueTypes.xml
=> Creation pure fom types

Models/Soils/MultiPoreWater/MultiPoreWater.cs, Models/Soils/MultiPoreWater/Pore.cs, Prototypes/MultiPoreWater/ReportDetail.apsimx, Prototypes/MultiPoreWater/Test.apsimx
=> Multi pore water model

Prototypes/Wheat/WheatValidation.apsimx
=> Neil's file with optimistation on

Models/DataStore.cs, Models/Summary.cs, UserInterface/Menus/ContextMenu.cs
=> Reinstated option to export datastore to text files

Prototypes/Wheat/WheatValidation.apsimx
=> Extinction coefficient for batten winter

Models/Report/ReportColumn.cs
=> Fixes to get report expressions working more reliably

UserInterface/Menus/ContextMenu.cs
=> Displays an message when export to ... completes

Models/Core/Events.cs, Models/Core/Simulation.cs, Models/Models.csproj
=> Speed up event connections

Models/Plant/Organs/Root.cs, Models/Resources/Maize.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/Chicory/Chicory.apsimx, Prototypes/Egrandis/Egrandis.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator V2.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
=> Make Senescence Rate madatory

Models/Core/Runners/RunOrganiser.cs, Models/DataStore.cs, Models/Report/Report.cs
=> Speed up cleaning of .db files

ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Presenters/XYPairsPresenter.cs, Models/Core/IVariable.cs, Models/Core/Model.cs, Models/Core/Variable.cs, Models/Core/VariableComposite.cs, Models/Core/VariableExpression.cs, Models/Core/VariableProperty.cs, Models/Plant/Functions/LinearInterpolationFunction.cs, Models/Summary.cs, UserInterface/Presenters/ProfilePresenter.cs, UserInterface/Presenters/XYPairsPresenter.cs
=> Add a new "UnitsLabel" property which provides the formatted units text in parentheses

Models/Core/Model.cs, Models/Soils/Soil.cs
Resolves #32 
Added soil area and polygon properties. Area calculations can be added later if required.
=> Added soil area and polygon properties.

Models/Core/Model.cs, Models/Soils/HydraulicProperties.cs, Prototypes/MultiPoreWater/ReportDetail.apsimx, Prototypes/MultiPoreWater/Test.apsimx
=> Kdu llayer

Models/Core/Runners/RunAllCompletedEvent.cs, Models/DataStore.cs, Models/PostSimulationTools/PredictedObserved.cs, UserInterface/Commands/RunCommand.cs, UserInterface/Commands/SaveApsimJob.cs, UserInterface/Menus/ContextMenu.cs, UserInterface/Presenters/ExperimentPresenter.cs, UserInterface/UserInterface.csproj
=> Slow apsim

Models/Models.csproj, Models/packages.config, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/packages.config
=> Update ExcelDataReader and NUnit NuGet packages to .Net 4.5.

Models/Plant/Organs/Root.cs, Prototypes/Wheat/WheatValidation.apsimx
=> moved senescence rate out of zones

Models/Plant/Organs/Root.cs
=> Root class refactoring

Models/Plant/Interfaces/IArbitration.cs, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/RootSWIM.cs, Models/Plant/Organs/SimpleRoot.cs
=> trying removing some complexity in uptake calculations and data comms

ApsimNG/ApsimNG.csproj, ApsimNG/Commands/RunCommand.cs, ApsimNG/Commands/SaveApsimJob.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExperimentPresenter.cs
Try to commit the right files this time...
Working on #626
=> Incorporate speedup changes made in WindowsForms GUI into GtkSharp.

Models/Plant/Organs/Root.cs
=> Root Refactoring

Models/Core/Apsim.cs, Models/Core/Simulation.cs, UserInterface/Commands/WriteDebugDoc.cs, UserInterface/Menus/ContextMenu.cs, UserInterface/Resources/DebugDoc.xsl, UserInterface/UserInterface.csproj
=> Simulation doc

Models/Plant/Organs/Root.cs, Prototypes/Chicory/Chicory.apsimx, Prototypes/Chicory/Sensibility/Chicory.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/FodderBeet/FodderBeetTest.apsimx
=> Remove LayerMidPoint from Root.cs

Models/Plant/Interfaces/IArbitration.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Models/Resources/Slurp.xml, Prototypes/Chicory/Chicory.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator V2.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
=> Removed MaxNConc, folded in Val's changes and some refactoring

Prototypes/Wheat/WheatValidation.apsimx
=> Wheat stem retrans work

Models/Plant/Organs/Root.cs, Prototypes/FodderBeet/FodderBeet.apsimx
=> Refactoring of root continued

Models/Plant/Interfaces/IArbitration.cs, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleRoot.cs
=> Combined NO3NSupply and NH4Supply into single method

Models/Core/Locater.cs, Models/Core/VariableExpression.cs, Models/Core/VariableProperty.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/Root.cs
=> Made root zones public and enhanced report to output zone properties.

Models/Plant/Interfaces/IArbitration.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/Root.cs, Models/Resources/Maize.xml, Models/Resources/Slurp.xml, Models/Soils/Soil.cs, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/Egrandis/Egrandis.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/FodderBeet/FodderBeetTest.apsimx, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Sorghum/SorghumValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/CanopyPhotosynthesis/CanopyPhotosynthesisTest.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Prototypes/Wheat/WheatValidationInPreperation.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator V2.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
=> Rearranged root and made MaximumRootDepth non optional

ApsimNG/ApsimNG.csproj, ApsimNG/Commands/WriteDebugDoc.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Resources/DebugDoc.xsl
=> Port changes for "DebugDoc" into GtkSharp GUI.

APSIM.bib, Prototypes/Wheat/WheatValidation.apsimx
=> Fixing documentation

APSIM.bib, Prototypes/Wheat/WheatValidation.apsimx
=> Adding memos

Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml, Prototypes/Chicory/Chicory.apsimx, Prototypes/Chicory/Sensibility/Chicory.apsimx, Prototypes/Egrandis/Egrandis.apsimx, Prototypes/Sorghum/SorghumValidation.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator V2.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
=> Removed unnecessary comments etc

Models/Plant/Organs/BelowGroundOrgan.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/HIReproductiveOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/Nodule.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/SimpleLeaf.cs
=> Class inheritance cleanup

Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Resources/Maize.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/Chicory/Chicory.apsimx, Prototypes/Chicory/Sensibility/Chicory.apsimx, Prototypes/Egrandis/Egrandis.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/FodderBeet/FodderBeetTest.apsimx, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Sorghum/SorghumValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/CanopyPhotosynthesis/CanopyPhotosynthesisTest.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Prototypes/Wheat/WheatValidationInPreperation.apsimx, Tests/Validation/Maize/Maize.apsimx, Tests/Validation/Slurp/Slurp.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator V2.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
=> Making functions unoptional (sic)

Models/Plant/Interfaces/IArbitration.cs, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/SimpleLeaf.cs
=> Cleaning up simple leaf

Models/Plant/Organs/Nodule.cs, Models/Resources/SCRUM.xml, Prototypes/Chickpea/ChickPea.apsimx
=> Cleanup spelling etc

Models/Core/Apsim.cs
=> Allow functions to be inserted anywhere.

Models/Core/Model.cs, Models/Importer/Resources/Types.xml, Models/Models.csproj, Models/Plant/Functions/DemandFunctions/TEWaterDemandFunction.cs, Models/Plant/Organs/SimpleLeaf.cs, Prototypes/Sorghum/SorghumValidation.apsimx
=> simple leaf refactoring

Models/Plant/Organs/SimpleLeaf.cs
=> See if this causes issues.

Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Organs/TreeCanopy.cs
=> Refactoring of Base Organ Class

Models/Plant/Biomass.cs
=> fix bug in biomass class

Models/Plant/CompositeBiomass.cs, Models/Plant/Functions/Constant.cs, Models/Plant/Functions/DivideFunction.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/HIReproductiveOrgan.cs, Models/Plant/Organs/Nodule.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Phenology/GenericPhase.cs
=> removing unnecessary text

Prototypes/Wheat/WheatValidation.apsimx
=> Improving soil description in Lincoln2010

Models/Plant/Functions/AddFunction.cs, Models/Plant/Functions/AgeCalculatorFunction.cs, Models/Plant/Functions/AirTemperatureFunction.cs, Models/Plant/Functions/BellCurveFunction.cs
=> clean up functions

Models/Plant/Organs/Nodule.cs, Models/Resources/SCRUM.xml
=> make fixation cost non optional

Models/Plant/Organs/Nodule.cs, Models/Resources/SCRUM.xml, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx
=> Move optional functionality into xml

Models/Core/Apsim.cs, Models/Plant/OldPlant/Leaf1.cs, Models/Plant/OldPlant/Pod.cs, Models/Resources/Maize.xml, Models/Resources/Slurp.xml, Models/Resources/Wheat.xml, Prototypes/Agroforestry/AgroforestryExample.apsimx, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/Chicory/Chicory.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/FodderBeet/FodderBeetTest.apsimx, Prototypes/MultiZoneRoots/MultiRootZone.apsimx, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/CanopyPhotosynthesis/CanopyPhotosynthesisTest.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Prototypes/Wheat/WheatValidationInPreperation.apsimx, Prototypes/Wheat/WheatValidationPhenologyTest.apsimx, Tests/Validation/Maize/Maize.apsimx
=> Fix for ResolveLink method

Models/Plant/Organs/SimpleLeaf.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Cleaning up wheat doco

Models/Core/Model.cs, Models/Importer/Resources/Types.xml, Models/Models.csproj, Models/Plant/Organs/PerennialLeaf.cs
=> Added perennial leaf class

Prototypes/Gliricidia/Gliricidia Validation.apsimx
=> Cleaning up Gliricidia validation set starting point

Models/Plant/Organs/PerennialLeaf.cs, Prototypes/Gliricidia/Gliricidia Validation.apsimx
=> Changed Gliricidia to use the Perennial Leaf class

Models/Plant/Organs/BaseOrgan.cs, Prototypes/Gliricidia/Gliricidia Validation.apsimx
=> Implemented harvesting of Gliricidia

UserInterface/Forms/UpgradeForm.cs
=> Kill updater exe if it is already running.

UserInterface/UserInterface.csproj
=> A reference to MathNet.Numerics was added to the UserInterface project file in a recent merge from SwimFrame.

Models/Plant/Organs/Leaf.cs
=> Zero TipsAtEmergence

Models/Core/Apsim.cs, Models/Core/Events.cs, Models/Core/Locater.cs, Models/Core/ModelNode.cs, Models/Core/Scope.cs, Models/Core/Simulation.cs, Models/Models.csproj, Models/Plant/Organs/Root.cs, Prototypes/Chicory/Chicory.apsimx, Tests/UnitTests/APITest.cs, Tests/UnitTests/ScopeTests.cs, Tests/UnitTests/UnitTests.csproj
=> Refactored scoping rule code. Now one way of doing scoping

Prototypes/Egrandis/Egrandis.apsimx
=> replaced euc leaf class

ApsimNG/Presenters/SeriesPresenter.cs, ApsimNG/Presenters/XYPairsPresenter.cs, Models/DataStore.cs, Models/Graph/Series.cs, UserInterface/Presenters/SeriesPresenter.cs, UserInterface/Presenters/XYPairsPresenter.cs
=> Fix some graph issues

UserInterface/EventArguments/NeedContextItemsArgs.cs
=> Fixed GUI crash when invalid variable typed into REPORT

Models/Plant/Organs/SimpleLeaf.cs
=> removed redundant code

Models/Core/Folder.cs, Models/Core/Simulation.cs, Models/Map.cs, Prototypes/Potato/PotatoValidation.apsimx, Tests/Validation/SCRUM/SCRUM.apsimx
=> Changed map model to honour scope

ApsimNG/ApsimNG.csproj, ApsimNG/packages.config, NuGet.config, UserInterface/UserInterface.csproj, UserInterface/packages.config
=> Use pre-release versions of OxyPlot dlls.

Models/Plant/Organs/PerennialLeaf.cs
=> Gliricidia

Models/Models.csproj, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Plant.cs, Models/Plant/RemoveBiomassFromOrgan.cs
=> Changed GenericOrgan to inherit from IOrgan rather than BaseOrgan

Models/Graph/Series.cs, UserInterface/Presenters/XYPairsPresenter.cs
=> Fixed graph x/y bug in models

Models/Graph/Series.cs, UserInterface/Presenters/SeriesPresenter.cs
=> Fixed bugs and sped up graph rendering

Models/Models.csproj, Models/Plant/Interfaces/IArbitration.cs, Models/Plant/Interfaces/IHasWaterDemand.cs, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Organs/SimpleLeaf.cs, Models/Plant/Plant.cs
=> Moved WaterDemand and WaterAllocation into IHasWaterDemand PMF interface

Models/Plant/Plant.cs
=> Add error check in EndCrop

ApServer/Program.cs
=> Eliminate unused variable in ApServer (eases Mono compilation)

ApsimNG/ApsimNG.csproj
=> Ensure that Gtk DLLs are copies to the Bin directory

Prototypes/Bambatsi/Bambatsi.apsimx
=> bambatsi validation work

Models/Plant/Organs/PerennialLeaf.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Removed White Space

Models/Core/Links.cs, Models/Core/Model.cs, Models/Models.csproj, Models/Plant/Library/BiomassRemoval.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Plant.cs, Models/Resources/Maize.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml, Prototypes/Bambatsi/Bambatsi.apsimx, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/Chicory/Chicory.apsimx, Prototypes/Egrandis/Egrandis.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/FodderBeet/FodderBeetTest.apsimx, Prototypes/Gliricidia/Gliricidia Validation.apsimx, Prototypes/Grapevine/grapevine.apsimx, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Sorghum/SorghumCompareModels.apsimx, Prototypes/Sorghum/SorghumValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/CanopyPhotosynthesis/CanopyPhotosynthesisTest.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Prototypes/Wheat/WheatValidationInPreperation.apsimx, Tests/Simulation/BiomassRemoval/BiomassRemovalTests.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator V2.apsimx, Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
=> Create a BiomassRemoval model to go in organs

Models/Plant/Organs/Leaf.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Removing redundant parameter

Models/Plant/Structure.cs, Prototypes/Grapevine/grapevine.apsimx
=> Coverting the old grapevine model to APSIMx mainly phenology

Prototypes/FodderBeet/FodderBeet.apsimx
=> Place holder to set target thermal-time for bolting. Delete not used cv

Prototypes/FodderBeet/FodderBeet.apsimx
=> Fodder beet doc

Prototypes/FodderBeet/FodderBeet.apsimx
=> Improvement in documentation and change lag phase for germination

Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Prototypes/Grapevine/grapevine.apsimx
=> Improving the annotation in the user interface

APSIMRunner/APSIMRunner.csproj, APSIMRunner/App.config, APSIMRunner/Program.cs, APSIMRunner/Properties/AssemblyInfo.cs, ApsimNG/Commands/RunCommand.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExperimentPresenter.cs, ApsimX.sln, Models/Clock.cs, Models/Core/Runners/JobManagerMultiProcess.cs, Models/DataStore.cs, Models/Manager.cs, Models/Models.csproj, UserInterface/Commands/RunCommand.cs, UserInterface/Menus/ContextMenu.cs, UserInterface/Presenters/ExperimentPresenter.cs
=> Multi process job manager

ApsimNG/Views/ColourDropDownView.cs
=> Fixed bug in setting value of colour drop down

Prototypes/WholeFarm/AdamsPrototype.apsimx
=> Fix the graphs variable name to refer to Date rather than Clock.Today

Models/Plant/Organs/Leaf.cs
Working on #1194 
Refactor of Leaf.cs
=> Refactor leaf.

ApsimNG/Views/ListBoxView.cs
=> Added paths into the MainView opening screen.

Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs
Working on #1194 
A few more changes to reduce code.
=> Refactor Leaf and LeafCohort

APSIMRunner/Program.cs, ApsimNG/Commands/RunCommand.cs, Models/Core/Runners/JobManagerMultiProcess.cs, Models/DataStore.cs, UserInterface/Commands/RunCommand.cs
=> Stabilise MultiProcess runner

ApsimNG/Views/ExplorerView.cs, ApsimNG/Views/GraphView.cs, Bin/.gtkrc
=> Remove bevel edge around graph stats box

Models/Soils/SoilNitrogen.cs, Models/SurfaceOrganicMatter.cs
=> Resetting now working

ApsimNG/Views/FolderView.cs
=> Improved graph folder rendering - look and feel

ApsimNG/Views/ListBoxView.cs, ApsimNG/Views/MainView.cs
Test of changes on Scoop to allow building of OS X distributions. 
Working on #1351
=> Simply some recent Gtk changes.

Updater/Program.cs
=> Change default GUI from "UserInterface" to "ApsimNG".

Models/Graph/Series.cs
=> Graph simulation name

ApsimNG/Presenters/ExperimentPresenter.cs, UserInterface/Presenters/ExperimentPresenter.cs
=> Fixed updating of db when only 1 simulation is run.

ApsimNG/Menus/ContextMenu.cs, UserInterface/Menus/ContextMenu.cs
=> Trap errors when exporting DataStore to csv

ApsimNG/Menus/ContextMenu.cs, Models/DataStore.cs, Models/Graph/Series.cs, UserInterface/Menus/ContextMenu.cs
=> Output to csv

ApsimNG/Views/GridView.cs, ApsimNG/Views/XYPairsView.cs
=> Changed numeric format on xypairs grid to null.

ApsimNG/Menus/ContextMenu.cs, Models/Core/Simulations.cs, UserInterface/Menus/ContextMenu.cs
=> Fix object not found ... error on create doc in simple simulations

Models/Graph/Series.cs
=> Added a new way to paint graph series that have two vary by factors

ApsimNG/Presenters/SeriesPresenter.cs, UserInterface/Presenters/SeriesPresenter.cs
=> Field field drop down list in graph series views

ApsimNG/Interfaces/IGraphView.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Views/GraphView.cs
=> Add popup menu to charts

ApsimNG/Forms/UpgradeForm.cs, ApsimNG/Resources/Glade/UpgradeForm.glade, Updater/Program.cs
=> Add first pass of support for doing Updates on Linux

Updater/Program.cs
=> Get the case correct in Linux filename

Models/MicroClimate/CanopyType.cs, Models/MicroClimate/MicroClimate.cs, Models/MicroClimate/MicroClimateScience.cs, Models/MicroClimate/MicroClimateZone.cs, Models/Models.csproj
=> Renaming properties

ApsimNG/Views/GridView.cs
=> Display text properly in "fixed" grid columns

ApsimNG/Forms/UpgradeForm.cs, Updater/Program.cs
=> First attempt at handling Upgrades on Mac OS X.

Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/CanopyPhotosynthesis/CanopyPhotosynthesisTest.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Prototypes/Wheat/WheatValidationInPreperation.apsimx
Working on #1194 
Testing this batch for breaking changes. Expect there will be some.
=> Removed some unused variables and optional links.

Models/Plant/Interfaces/IHasWaterDemand.cs, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Organs/SimpleLeaf.cs, Prototypes/Chickpea/ChickPea.apsimx, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx, Prototypes/Grapevine/grapevine.apsimx, Prototypes/Potato/Potato.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Teff/Teff.apsimx, Prototypes/Wheat/WheatValidationInPreperation.apsimx
Working on #1194 
Testing new mandatory field.
=> Refactor leaf

Models/Plant/Plant.cs
=> Stopped crop being ended due to low pop

Models/Plant/Plant.cs
=> Clean up if statement

Updater/Program.cs
=> Do a better job of requesting sudo password when doing LInux upgrades

Models/Plant/OldPlant/RUEModel1.cs, Models/Resources/Wheat.xml
Resolves #1451 
Changed RUEFactor to public property. Updated Wheat model.
=> Added public RUEFactor property for Plant15

Models/Plant/OilPalm/OilPalm.cs, Models/Resources/OilPalm.xml, Tests/Validation/OilPalm/OilPalm.apsimx
=> fixed bugs in Oil Palm

APSIMRunner/Program.cs, Models/Core/Runners/JobManagerMultiProcess.cs, Models/DataStore.cs, Models/Models.csproj, Models/Report/IReportColumn.cs, Models/Report/Report.cs, Models/Report/ReportColumn.cs, Models/Report/ReportColumnConstantValue.cs, Models/Report/ReportColumnWithValues.cs, Models/Report/ReportTable.cs, Models/Summary.cs
=> Increased stability for multi-process run option

Models/Models.csproj, Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/RootZoneState.cs, Prototypes/FieldPea/FieldPeaValidation.apsimx, Prototypes/MultiZoneRoots/MultiRootZone.apsimx
=> Refactoring RootZoneState

Models/Plant/OrganArbitrator.cs, Models/Plant/Organs/Root.cs
=> removed unnecessary method

Models/Plant/OrganArbitrator.cs
=> remove unused function

ApsimNG/Presenters/InputPresenter.cs, ApsimNG/Views/ExplorerView.cs, ApsimNG/Views/HTMLView.cs, ApsimNG/Views/InputView.cs, ApsimNG/Views/MainView.cs, ApsimNG/Views/TabbedMetDataView.cs, ApsimNG/Views/ViewBase.cs
=> Use native file open/save dialogs.

ApsimNG/Main.cs
=> Give system adequate time to delete the old "temp" folder, if present.

ApsimNG/Utility/FindAndReplaceForm.cs
=> Fix several issues with text searches in manager scripts.

Models/MicroClimate/MicroClimate.cs, Models/MicroClimate/MicroClimateScience.cs, Prototypes/Agroforestry/AgroforestrySystem.apsimx, Prototypes/Potato/PotatoValidation.apsimx, Prototypes/Wheat/WheatValidation.apsimx, Tests/Validation/Maize/Maize.apsimx, Tests/Validation/SCRUM/SCRUM.apsimx, Tests/Validation/Slurp/Slurp.apsimx, Tests/Validation/Wheat/Wheat.apsimx
=> Fix day references so they are pointing at Clock.Today.DayOfYear

APSIMRunner/Program.cs, ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Interfaces/ISeriesView.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Presenters/ManagerPresenter.cs, ApsimNG/Presenters/MapPresenter.cs, ApsimNG/Presenters/SeriesPresenter.cs, ApsimNG/Presenters/SummaryPresenter.cs, ApsimNG/Views/EditBoxView.cs, ApsimNG/Views/EditorView.cs, ApsimNG/Views/GridView.cs, ApsimNG/Views/SeriesView.cs, ApsimNG/Views/SupplementView.cs, ApsimNG/Views/TreeProxyView.cs, ApsimNG/Views/ViewBase.cs, Updater/Program.cs
=> Reduce number of Mono compiler warnings

ApsimNG/Views/InitialWaterView.cs
=> Catch invalid entries in edit control.

APSIMRunner/Program.cs, Models/DataStore.cs, Models/Report/IReportColumn.cs, Models/Report/Report.cs, Models/Report/ReportColumn.cs, Models/Report/ReportColumnConstantValue.cs, Models/Report/ReportColumnWithValues.cs, Models/Report/ReportTable.cs, Models/Summary.cs, Tests/UnitTests/TestReport.cs, Tests/UnitTests/UnitTests.csproj
=> Multi process

Models/Plant/Organs/PerennialLeaf.cs
=> Fixed N Arbitrator Error

ApsimNG/Views/GridView.cs
=> Display numeric values in grid with the correct format.

ApsimNG/Presenters/PropertyPresenter.cs
=> Make test results grid readonly

Models/Plant/Phenology/EndPhase.cs, Models/Plant/Phenology/Phenology.cs, Tests/Simulation/BiomassRemoval/BiomassRemovalTests.apsimx
=> Phenology fixes

ApsimNG/CommandHistory.cs
=> Get Undo/Redo working a bit better. Still has room for improvement.

Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Organs/Root.cs, Models/Plant/Structure.cs
Resolves #1525
Added ability to track leaf apex numbers.
Some minor code cleaning in related models.
=> Leaf apex model

Models/Resources/SCRUM.xml
=> Changed some more parameters on new SCRUM crops

Models/Core/Locater.cs, Models/Core/VariableComposite.cs, Models/Core/VariableMethod.cs, Models/Models.csproj, Models/Plant/Functions/Variable.cs
=> Fix for constant function not showing in GUI correctly.

Models/Plant/Organs/Leaf.cs
=> Restore the variable AreaLargestLeaf

Models/Core/Model.cs, Models/Models.csproj, Models/Plant/Functions/MovingSum.cs, Models/Plant/Organs/Leaf.cs, Models/Weather/Weather.cs
=> Calculate the daily Photothermal Quotient with moving sum

ApsimNG/Views/GridView.cs
=> Make the grid used for reports more responsive.

Models/Factorial/Factor.cs
=> Added ability to have an array like DUL as a factor.

Models/Plant/Arbitrator/OrganArbitrator.cs
=> Check for null references in property getters.

Models/Plant/Functions/LinearInterpolationFunction.cs, Models/Plant/Functions/SubtractFunction.cs, Models/Plant/Functions/Variable.cs, Models/Plant/Functions/WeightedTemperatureFunction.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Removed unwanted LinearInterp functions - turned some to constants

ApsimNG/Views/SummaryView.cs
=> Attach event handler for changing selected simulation in Summary view

UserInterface/Presenters/GraphPresenter.cs, UserInterface/Views/GraphView.cs
=> Fixed display of stats on graph

Models/Core/AutoDocumentation.cs, Models/Core/Folder.cs, Models/Graph/Graph.cs, Models/Graph/GraphPage.cs, Models/Models.csproj, Prototypes/Wheat/WheatValidation.apsimx, Tests/Validation/Maize/Maize.apsimx, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Interfaces/IGraphView.cs, UserInterface/Presenters/GraphPresenter.cs, UserInterface/Views/GraphView.cs, UserInterface/Views/TreeProxyView.cs
=> Muliple graph pages implemented in auto-doc

Models/Core/Folder.cs, UserInterface/Commands/ExportNodeCommand.cs, UserInterface/Views/MapView.cs
=> Fix map in autodoc

ApsimNG/Commands/RunCommand.cs, Models/Core/Runners/JobManagerMultiProcess.cs, UserInterface/Commands/RunCommand.cs
=> Free up memory when running lots of simulations

Prototypes/Nutrient/Nutrient.apsimx
=> Updated soil nutrient graphs

Models/Core/Model.cs, Models/Models.csproj, Models/Soils/Nutrient/CFlow.cs, Models/Soils/Nutrient/NFlow.cs, Models/Soils/Nutrient/Nutrient.cs, Models/Soils/Nutrient/Solute.cs, Models/Soils/Soil.cs, Models/SoluteManager.cs, Prototypes/Nutrient/Nutrient.apsimx
=> Added solutes to soil nutrient

Prototypes/Nutrient/Nutrient.apsimx
=> Updated soil Nurtient test graphs

Prototypes/Wheat/WheatValidation.apsimx
=> Get the observation files working for pendleton

ApsimNG/Views/ExplorerView.cs
=> Added hack to get around problem with drag-and-drop on OS X.

Models/Soils/Soil.cs
=> Added sub soil constraints for wheat.

Models/Operations.cs, Models/Plant/Phenology/GenericPhase.cs, Models/Plant/Phenology/GerminatingPhase.cs
Allow setting of phenology phase number of days.
Working on #453
=> Allow operations to have set commands +

ApsimNG/Views/ExplorerView.cs
=> Get drag-and-drop working on both OS X and Window

Models/AgPasture/AgPasture.PastureSpecies.cs, Models/AgPasture/AgPasture.Sward.cs
=> Fix valid parents for AgPasture Sward and PastureSpecies

ApsimNG/Forms/UpgradeForm.cs, ApsimNG/Views/HTMLView.cs
=> Display licence argreement more efficiently.

Prototypes/Wheat/WheatValidation.apsimx
=> cleaned up turkish dataset and wongan 83

Prototypes/Egrandis/wwepp.met
=> Added longitude to Wagga met file

Models/AgPasture/AgPasture.PastureSpecies.Organs.cs, Models/AgPasture/AgPasture.PastureSpecies.cs, Models/Core/Zone.cs, Prototypes/AgPasture/AgPastureTest.apsimx
=> Ag pasture roots

Models/Soils/Arbitrator/SoilState.cs
=> Fix problem with SoilArbitrator sending NO3 negative.

Models/Fertiliser.cs, Models/Interfaces/ISoil.cs, Models/Models.csproj, Models/Soils/Soil.cs, Models/SoluteManager.cs, Models/SurfaceOrganicMatter.cs, Prototypes/SugarCane/Validation/SugarcaneValidation.apsimx, Tests/UnitTests/FertiliserTests.cs, Tests/UnitTests/MockSummary.cs, Tests/UnitTests/ScopeTests.cs, Tests/UnitTests/UnitTests.csproj
=> Fixed fertilise at depth.

ApsimNG/EventArguments/GridCellsChangedArgs.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs, ApsimNG/Views/MainView.cs, ApsimNG/Views/MemoView.cs
Working on #1649
Resolves #1656
=> Support running the model on a single experiment

Models/Core/VariableProperty.cs
=> Allow enumerated types to be settable from strings

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx, ApsimNG/Resources/Toolboxes/TrainingToolbox.apsimx, Models/Core/APSIMFileConverter.cs, Models/Interfaces/ISoilWater.cs, Models/Soils/MultiPoreWater/WEIRDO.cs, Models/Soils/SoilWater.cs, Models/Soils/SoilWaterBackend/SoilWaterSoil.cs, Tests/UnitTests/TestConverter.cs, UserInterface/Resources/Toolboxes/ManagementToolbox.apsimx, UserInterface/Resources/Toolboxes/TrainingToolbox.apsimx
=> Turned ESW from scalar output to an array output

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Views/ExplorerView.cs, UserInterface/Menus/ContextMenu.cs
=> Added menu items for include/exclude graph from documentation.

ApsimNG/Presenters/PropertyPresenter.cs, Models/Core/VariableProperty.cs, UserInterface/Presenters/PropertyPresenter.cs
=> Handle DateTime objects when setting values from strings

Models/Soils/SoilOrganicMatter.cs
=> Fix error in calculation of HumC.

ApsimNG/Views/GridView.cs
=> Implement pasting into grids

ApsimNG/Views/GridView.cs
=> Implement copy and delete in grids,

ApsimNG/Views/ListBoxView.cs
=> Use a small, light font, rather than gray colour, for file path.

Models/Tests.cs
=> Restore view and presenter for Tests

Models/DataStore.cs
=> FIx SQL error when running one sim out of 1000s

ApsimNG/Interfaces/IGridView.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/GridView.cs
=> When displaying properies, left-align the "values" column.

ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Views/GraphView.cs
These properties don't necessarily "get" the value to which they've been "set".
Resolves #1735
=> Don't rely on Width and Height properties

ApsimNG/Attributes/ContextMenuAttribute.cs, ApsimNG/Interfaces/IExplorerView.cs, ApsimNG/Main.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Views/ExplorerView.cs
=> Improve appearance of popup menu on OSX

Models/DataStore.cs, Models/Weather/Weather.cs
=> Better and safer approach for inserting  values into units database

ApsimNG/Views/GridView.cs
=> When objects implementing ICrop are to be displayed, use their name.

ApsimNG/Presenters/ExperimentPresenter.cs
=> Report number of experiments correctly.

ApsimNG/Presenters/ProfilePresenter.cs, Models/Soils/SoilCrop.cs, UserInterface/Presenters/ProfilePresenter.cs
=> Add crop LL values to the soil water plot

ApsimNG/Presenters/MetDataPresenter.cs, ApsimNG/Views/ExplorerView.cs, UserInterface/Presenters/MetDataPresenter.cs
=> Close the weather data file after reading its contents for the GUI.

ApsimNG/Views/GridView.cs
Working on #1775 
This isn't perfect, but should make data entry a bit easier. The new behaviour is that if a user is editing a cell and presses either enter or tab, the current values are saved and the editing focus moves to the next editable cell. Using enter moves the focus down the column (shift-enter moves it up). Using tab moves the focus along the row (and although I'd like shift-tab to move left along the row, shift-tab turns out to be surprisingly hard to capture).
=> Try to make editing of cells a bit more Excel-like.

Models/Manager.cs
=> Workaround for weird problem with Manager script variables.

Models/Resources/Wheat.xml
=> Added two cultivars from APSIM Classic

ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Utility/Configuration.cs, ApsimNG/Views/ListBoxView.cs, ApsimNG/Views/MainView.cs
Resolves #1792 
@hol353 - some changes to the way the most-recently-used files are handled and manipulated. (You now get a context menu on right click; opening an already-open file takes to you the already open tab, etc..) I think its an improvement, but would welcome feedback.
=> Modifications to most-recently-used file display.

Models/Soils/SoilNitrogen.CNPatch.Processes.cs, Models/Soils/SoilNitrogen.Variables.cs, Models/Soils/SoilNitrogen.cs, Prototypes/Wheat/WheatValidation.apsimx
Working on #1799 
Step 01, change only sw_dep
=> Change sw_dep for a direct link to Soil.SoilWater.SWmm

ApsimNG/Views/GridView.cs
Working on #1775
This concludes work on part 2 of the original issue. Part 1 is not yet resolved, but I'm not so sure that it should be.
=> Move left in grid on Shift+Tab pressed.

Models/Plant/Organs/PerennialLeaf.cs, Prototypes/Nutrient/Nutrient.apsimx
=> Fixed Perrenial Leaf N conc errors in logic

Prototypes/Nutrient/Nutrient.apsimx
=> Removed unused XML node

Models/Core/Model.cs, Models/Models.csproj, Models/Plant/Functions/DemandFunctions/InternodeCohortDemandFunction.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/Root.cs, Prototypes/Grapevine/grapevine.apsimx
=> updating Grapevine

Models/Plant/CompositeBiomass.cs
=> Auto Documentation for composite biomass class

ApsimNG/Commands/ExportNodeCommand.cs, Models/Plant/Cultivar.cs, Models/Plant/CultivarFolder.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Updated autodoc for cultivars and cultivar folders

ApsimNG/Commands/MoveModelCommand.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Views/ExplorerView.cs, UserInterface/Commands/MoveModelCommand.cs, UserInterface/Presenters/ExplorerPresenter.cs
=> Fixed problems with move operations in both GUIs.

Models/Resources/ResidueTypes.xml
=> Added fodder beet and kale to residual types

Models/Core/APSIMFileConverter.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Resources/Chicory.xml, Models/Resources/Maize.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml
=> Remove optionals

APSIM.bib, Models/Plant/Arbitrator/PriorityAllocation.cs, Models/Plant/Arbitrator/PriorityThenRelativeAllocation.cs, Models/Plant/Arbitrator/RelativeAllocation.cs, Models/Plant/Arbitrator/RelativeAllocationSinglePass.cs, Models/Plant/Functions/AirTemperatureFunction.cs, Models/Plant/Functions/PhaseLookup.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Phenology/EmergingPhase.cs, Models/Plant/Phenology/EndPhase.cs, Models/Plant/Phenology/LeafAppearancePhase.cs, Models/Plant/Phenology/LeafDeathPhase.cs, Models/Plant/Phenology/Phenology.cs, Models/Plant/Structure.cs, Prototypes/Potato/PotatoValidation.apsimx
=> Potato doco progress

ApsimNG/Views/HTMLView.cs, ApsimNG/Views/MemoView.cs
=> Enable word wrapping when editing memo text.

Prototypes/Lucerne/LucerneValidation.apsimx
=> Node number update

Models/Plant/Phenology/ZadokPMF.cs
=> new meta data for zadokpmf class

Models/Plant/Phenology/Phenology.cs
=> Added table of phenology stages to phenology model autodoc

Models/Plant/Organs/Leaf.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Clarified leaf organ description metadata

Models/Core/Folder.cs
=> added experiments table to autodoc for folders

ApsimNG/Views/GraphView.cs
=> Fix some graph display problems

Models/Plant/Phenology/Phenology.cs
=> add autodoc section for phenology model to group phases for doco

ApsimNG/Commands/ExportNodeCommand.cs, Models/Core/Folder.cs, Models/Plant/Phenology/Phenology.cs, Models/Plant/Plant.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Turn Neil's Markdown tables into proper tables.

Models/Plant/Organs/Leaf.cs, Prototypes/Wheat/WheatValidation.apsimx
=> Working on Leaf Doco method

ApsimNG/Views/GraphView.cs, Models/DataStore.cs, Models/Graph/Series.cs, Models/PostSimulationTools/PredictedObserved.cs, UserInterface/Views/GraphView.cs
=> Added units to predicted / observed graphs

Models/Plant/Organs/Leaf.cs
=> Remove OnCut method that was clearing the leaf

ApsimNG/Commands/ExportNodeCommand.cs, Models/DataStore.cs, Models/PostSimulationTools/PredictedObserved.cs, Models/Tests.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Allow a predicted / observed table to be in a folder.

ApsimNG/Commands/ExportNodeCommand.cs, Models/Factorial/Experiment.cs, Models/Resources/OilPalm.xml, Tests/Validation/OilPalm/OilPalm.apsimx
=> Fixes for oil palm autodoc

ApsimNG/Presenters/AddFunctionPresenter.cs, ApsimNG/Presenters/AddModelPresenter.cs, ApsimNG/Presenters/AxisPresenter.cs, ApsimNG/Presenters/CultivarPresenter.cs, ApsimNG/Presenters/DataStorePresenter.cs, ApsimNG/Presenters/ExperimentPresenter.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/FactorPresenter.cs
=> Style fixes

Prototypes/Oats/Oats.apsimx
=> Fix a few more graphs

Models/Core/APSIMFileConverter.cs, Models/Core/APSIMFileConverterUtilities.cs, Models/Importer/Resources/Types.xml, Models/Plant/Organs/Leaf.cs, Models/Plant/Phenology/LeafAppearancePhase.cs, Models/Plant/Phenology/LeafDeathPhase.cs, Models/Plant/Structure/Structure.cs, Models/Resources/Maize.xml, Prototypes/Wheat/WheatValidationPhenologyTest.apsimx, Tests/UnitTests/TestConverter.cs
MainStemFinalNodeNumber to FinalLeafNumber in Structure.
Resolves #1889
=> Rename MainStemNodeAppearanceRate to Phyllochron AND

Models/Soils/OutputLayers.cs
=> Add change to Layer outputs

Models/Core/AutoDocumentation.cs, Models/Plant/Organs/Leaf.cs
=> Fix leaf documentation

Models/Core/AutoDocumentation.cs
=> Fixed spacing issue in AutoDoc

CONTRIBUTING.md
Creating this pull request without a pre-existing issue to test if it will trigger a build. This fix resolves #1965.
=> Typos in contributing.

ApsimNG/Commands/ExportNodeCommand.cs, UserInterface/Commands/ExportNodeCommand.cs
=> Fix wrong graphs in PDF

Models/Plant/Organs/GenericOrgan.cs, Prototypes/Nutrient/Nutrient.apsimx, Tests/Validation/Wheat/Wheat.apsimx
=> protected divides

Models/Report/Report.cs
=> Add ParentType to allow dropping reports at top level (God Level)

Models/Graph/Series.cs
=> Fix issue sometimes caused when copying graphs to another node in GUI

Tests/Validation/Wheat/Wheat.apsimx
=> Add PO Tables into regions for wheat

Models/Plant/Organs/LeafCohort.cs
=> rename DeltaWaterConstrainedArea to DeltaStressConstrainedArea

APSIMRunner/Program.cs, APSIMRunner/StorageViaSockets.cs, Models/Core/Runners/JobManagerMultiProcess.cs, Models/Core/Runners/RunAllCompletedEvent.cs, Models/Core/Runners/RunSimulation.cs, Models/PostSimulationTools/TimeSeriesStats.cs, Models/Storage/DataStore.cs, Models/Storage/Table.cs
=> New data store speedups, multi process runs and bug fixes

Models/Storage/DataStore.cs
=> Attempted fix for race condition on Jenkins

ApsimNG/Views/GridView.cs, ApsimNG/Views/ViewBase.cs
=> Fixed problems with display of grid column headings

Models/Core/APSIMFileConverter.cs, Models/Core/Model.cs, Models/Models.csproj, Models/Plant/Functions/ArrayFunction.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Models/Resources/Maize.xml, Models/Resources/Wheat.xml, Prototypes/LeafApex/LeafApex.apsimx
Resolves #1984 
Added new tillering model to Leaf.
=> Leaf tiller model

Models/Storage/DataStore.cs, Models/Storage/Table.cs
=> Greatly reduced the amount of work that the .db writer has to do

ApsimNG/Views/ExplorerView.cs, ApsimNG/Views/GraphView.cs, ApsimNG/Views/GridView.cs, ApsimNG/Views/ListBoxView.cs
=> Improve cleanup of popup menu handlers

ApsimNG/Commands/RunCommand.cs
=> Update status information when simulations have been aborted by the user

Models/Core/Runners/RunOrganiser.cs, Models/Core/Simulation.cs, Models/Plant/Organs/Root.cs, Models/Report/Report.cs, Tests/UnitTests/TestReport.cs
=> Fixes to DoOutput method call in Report and speed up a Root property

Models/Core/APSIMFileConverter.cs, Models/Core/APSIMFileConverterUtilities.cs, Models/Plant/Arbitrator/BiomassArbitrationType.cs, Models/Plant/Arbitrator/OrganArbitrator.cs, Models/Plant/Interfaces/IArbitration.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/HIReproductiveOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/RootSWIM.cs, Models/Resources/Chicory.xml, Models/Resources/Maize.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml, Models/Resources/Wheat.xml, Tests/UnitTests/Resources/Continuous_Wheat.apsimx
=> Refactored Live and Dead to not be CompositeBiomass classes.

Models/Plant/Organs/LeafCohort.cs
=> #2031 Update IsSenescing variable

Models/Plant/Organs/Root.cs, Models/Soils/Arbitrator/SoilArbitrator.cs, Models/Soils/Arbitrator/SoilState.cs
=> Attempt to speed runtime of new wheat model

Models/AgPasture/AgPasture.PastureSpecies.Organs.cs, Models/AgPasture/AgPasture.PastureSpecies.cs, Models/Core/APSIMFileConverter.cs, Models/Interfaces/ISoilWater.cs, Models/Plant/Functions/SoilWaterScale.cs, Models/Plant/OilPalm/OilPalm.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/Root.cs, Models/Plant/Phenology/GerminatingPhase.cs, Models/Plant/Phenology/Phenology.cs, Models/Plant/SimpleTree/SimpleTree.cs, Models/Soils/CERESSoilTemperature.cs, Models/Soils/Soil.cs, Models/Soils/SoilNitrogen.CNPatch.Processes.cs, Models/Soils/SoilWater.cs, Models/Soils/SoilWaterBackend/SoilWaterSoil.cs, Models/Sugarcane/Sugarcane.cs
=> Speedups to wheat

Examples/ControlledEnvironment.apsimx, Examples/Wheat.apsimx
=> Get Wheat examples working again.

Models/Report/ReportColumn.cs, Models/Storage/DataStore.cs
=> Fix problems with storage of Units information

Models/Plant/Organs/ReproductiveOrgan.cs
=> Avoid having null values for Live and Dead

Models/Plant/Organs/Leaf.cs
=> Update the allocated variable in Leaf class

Models/Plant/Organs/Leaf.cs
=> Export new variable for CohortMaxArea

ApsimNG/Views/MapView.cs
=> Fixed problem with storage of map zoom level.

Models/Plant/Phenology/Phenology.cs, Models/Soils/SoilWater.cs
=> Use a faster technique for case-insensitive string comparison

Models/PostSimulationTools/Input.cs, Models/Storage/DataStore.cs
=> Restore some order to Report tables

Models/Plant/Functions/LinearInterpolationFunction.cs, Models/Plant/Functions/SupplyFunctions/RUEModel.cs, Models/Plant/Functions/Variable.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs, Models/Plant/Phenology/Phenology.cs, Prototypes/Nutrient/Nutrient.apsimx
=> Speedups to APSIMx

Prototypes/Fathen/Fathen.apsimx, Prototypes/FodderBeet/FodderBeet.apsimx
=> Try and remove instability on Jenkins

Models/Plant/Organs/Root.cs
=> Correct a spell in root.cs

Models/Plant/Functions/SoilWaterScale.cs
=> Check layer index in the SoilWaterScale

ApsimNG/Resources/Glade/ReportView.glade
=> Swamp Data and Properties panels in the report

ApsimNG/Views/ProfileView.cs
=> Display 3 decimal places in profile grids.

Models/Plant/Organs/ReproductiveOrgan.cs
=> Update Allocated variables

Models/Plant/Organs/Leaf.cs
=> Add new variable for specific leaf nitrogen

ApsimNG/ApsimNG.csproj, ApsimNG/packages.config
Working on #2127. Fixed the immediate OxyPlot problem.
=> Updated version of OxyPlot nuget packages

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Utility/FindAndReplaceForm.cs
Working on #2123 
I think this will correct the issue, but don't want to close this completely until further testing by @HamishBrownPFR, as I'm not sure I've correctly replicated the original problem.
=> Ensure previous presenter is cleared before displaying the AddModelPresenter

Models/Plant/Organs/Leaf.cs
=> Export new variables of delta leaf area

Models/AgPasture/AgPasture.PastureSpecies.cs
Resolves #2126 
Few changes to ensure that Nconc will not go above maximum due to over-uptake when using GLFSoilFertility <1.0. This involved using this factor whithin the N calculations, i.e. adjusting the potential N demand.
=> Add consideration for GLFSoilFertility when computing demand

Models/Plant/Organs/Root.cs
=> Export growth respiration in root

ApsimNG/ApsimNG.csproj, ApsimNG/packages.config, Models/Models.csproj, Models/packages.config, SWIMFrame/SWIMFrame.csproj, SWIMFrame/packages.config, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/packages.config
=> Update some of the nuget packages.

ApsimNG/Presenters/InitialWaterPresenter.cs, ApsimNG/Views/AxisView.cs, ApsimNG/Views/GraphView.cs, ApsimNG/Views/TreeProxyView.cs, ApsimNG/packages.config, ApsimX.sln, Examples/OilPalm.apsimx, Models/Agroforestry/TreeProxy.cs, Models/Core/APSIMFileConverter.cs, Models/Core/VariableExpression.cs, Models/Plant/ArrayBiomass.cs, Models/Plant/Functions/ArrayFunction.cs, Models/Plant/Functions/ExpressionFunction.cs, Models/Plant/Functions/SplineInterpolationFunction.cs, Models/Plant/Functions/Variable.cs, Models/Plant/Phenology/Phenology.cs, Models/PostSimulationTools/TimeSeriesStats.cs, Models/Report/ReportColumn.cs, Models/Stock/grazparam.cs, Models/Stock/typedval.cs, Models/Sugarcane/Sugarcane.cs, Models/Summary.cs, Models/Tests.cs, Models/Weather/Weather.cs, Tests/Validation/Maize/Maize.apsimx
=> Culture invariant

Models/Plant/Organs/Root.cs, Models/Plant/Organs/RootZoneState.cs
=> Remove variable Root.Length

Models/Core/Runners/RunOrganiser.cs
=> Fix bug where db is cleared when a single simulation is run.

Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Root.cs
=> Adjust calling order

Models/Plant/Structure/Structure.cs
Resolves #2164 
Remove remove crop ending actions from Structure OnHarvest which are duplicated in OnCropEnding
=> Fix problem with leaf biomass being zeroed on harvest

Models/Plant/Organs/LeafCohort.cs, Models/Plant/Structure/Structure.cs
=> Adjust stem population and cohort population

Models/Plant/Arbitrator/OrganArbitrator.cs
=> Organ arbitrator

Models/Plant/Organs/GenericOrgan.cs
resolves #2200 
Added some code to reallocate and retranslocate N from generic organ
=> Generic organ

ApsimNG/ApsimNG.csproj, ApsimNG/Interfaces/IAxisView.cs, ApsimNG/Interfaces/IButtonView.cs, ApsimNG/Presenters/AxisPresenter.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Presenters/XYPairsPresenter.cs, ApsimNG/Settings.StyleCop, ApsimNG/Views/AxisView.cs, ApsimNG/Views/ButtonView.cs
=> Stylecop fixes

Models/Stock/animgrp.cs, Models/Stock/stock.cs, Models/Stock/stock_ent.cs, Models/Stock/stock_intf.cs, Models/Stock/stock_padd.cs, Models/Stock/stock_vars.cs
working on #877
Other changes to sync with pascal source.
=> Added EnergyUse property.

ApsimNG/ApsimNG.csproj, ApsimNG/Classes/DirectedGraph/BezierCurve.cs, ApsimNG/Classes/DirectedGraph/DGArc.cs, ApsimNG/Classes/DirectedGraph/DGNode.cs, ApsimNG/Classes/DirectedGraph/DGObject.cs, ApsimNG/Commands/ExportNodeCommand.cs, ApsimNG/Presenters/DirectedGraphPresenter.cs, ApsimNG/Views/DirectedGraphView.cs, Models/Graph/DirectedGraph.cs, Models/Interfaces/IVisualiseAsDirectedGraph.cs, Models/Models.csproj, Models/Plant/Functions/Bound.cs, Models/Soils/Nutrient/Nutrient.cs, Prototypes/Nutrient/Nutrient.apsimx
=> Directed Graph working for Nutrient model

Models/Core/APSIMFileConverter.cs, Models/Plant/Organs/BaseOrgan.cs, Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/PerennialLeaf.cs, Models/Plant/Organs/ReproductiveOrgan.cs, Models/Plant/Organs/Root.cs, Models/Resources/Chicory.xml, Models/Resources/Maize.xml, Models/Resources/SCRUM.xml, Models/Resources/Slurp.xml, Models/Resources/Wheat.xml, Tests/UnitTests/TestConverter.cs
=> Update unit for respiration

Models/Soils/SoilOrganicMatter.cs
working on #1205 
Please merge if acceptable
=> Update units for SoilOrganicMatter

Models/Core/Runner.cs
=> Fix for runner handing jobs to job runner

Models/Core/Attributes/LinkAttribute.cs, Models/Core/Links.cs, Models/Core/Locater.cs, Tests/UnitTests/LinksTests.cs, Tests/UnitTests/MockIrrigation.cs, Tests/UnitTests/MockSoil.cs
=> Added a [LinkByPath] attribute

Models/Core/Model.cs, Models/Models.csproj, Models/Plant/Functions/TrackerFunction.cs, Models/Plant/Plant.cs, Tests/UnitTests/TrackerFunctionTests.cs, Tests/UnitTests/UnitTests.csproj
=> Added a tracker function to PMF and a Flowering event to PLANT

Models/Plant/Organs/Leaf.cs, Models/Plant/Organs/LeafCohort.cs
=> Fixed the live stem number

APSIMRunner/APSIMRunner.csproj, APSIMRunner/App.config, ApsimNG/App.config, ApsimNG/ApsimNG.csproj, ApsimNG/Properties/Resources.Designer.cs, Models/Importer/Importer.csproj, Models/Importer/Properties/Resources.Designer.cs, Models/Importer/app.config, Models/Models.csproj, Models/Properties/Resources.Designer.cs, Models/app.config, SWIMFrame/SWIMFrame.csproj, SWIMFrame/app.config, Setup/apsimx.iss, Tests/UnitTests/Properties/Resources.Designer.cs, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/app.config, Updater/Properties/Resources.Designer.cs, Updater/Properties/Settings.Designer.cs, Updater/Updater.csproj, Updater/app.config
=> Updated each project to use v4.5.2 of the .NET framework.

Models/Plant/Organs/GenericOrgan.cs, Models/Plant/Organs/Root.cs, Models/Plant/Organs/RootZoneState.cs, Models/Plant/Utility.cs
=> Root refactor

Models/AgPasture/AgPasture.PastureSpecies.cs, Models/Core/ApsimFile/Converter.cs, Models/Core/ApsimFile/ConverterUtilities.cs, Models/Core/ApsimFile/Format.cs, Models/Core/ApsimFile/ManagerConverter.cs, Models/Core/ApsimFile/Reader.cs, Models/Core/ApsimFile/Writer.cs, Models/Core/Simulations.cs, Models/Fertiliser.cs, Models/Models.csproj, Models/Plant/OilPalm/OilPalm.cs, Models/Plant/Organs/Root.cs, Models/Plant/SimpleTree/SimpleTree.cs, Models/Soils/Nutrient/CFlow.cs, Models/Soils/Nutrient/NFlow.cs, Models/Soils/Soil.cs, Models/Soils/SoilNitrogen.Variables.cs, Models/Soils/SoilWater.cs, Models/Soils/Swim.cs, Models/SoluteManager.cs, Models/Sugarcane/Sugarcane.cs, Models/SurfaceOrganicMatter.cs, Models/WaterModel/ISoil.cs, Models/WaterModel/Soil.cs, Tests/UnitTests/APSIMFileReaderTests.cs, Tests/UnitTests/FileFormatTests.cs, Tests/UnitTests/ManagerConverterTests.cs, Tests/UnitTests/TestConverter.cs, Tests/UnitTests/UnitTests.csproj
=> In SoluteManager.SetValue added argument for the calling model type

APSIMRunner/APSIMRunner.csproj, Models/Models.csproj
=> Change build settings for Release builds as well as Debug builds.

Examples/OilPalm.apsimx, Tests/Validation/OilPalm/OilPalm.apsimx
=> Oil palm et

Prototypes/Oats/Oats.apsimx
=> changed manager logic

Updater/Program.cs
Working on #2289.
This should resolve the issue, but it's difficult to test without using system generated builds.
=> Try looking in a few likely places for the new installation.

ApsimNG/App.config, ApsimNG/ApsimNG.csproj, ApsimNG/packages.config, Models/Models.csproj, Models/PostSimulationTools/ExcelInput.cs, Models/packages.config, SWIMFrame/SWIMFrame.csproj, SWIMFrame/packages.config, Tests/UnitTests/UnitTests.csproj, Tests/UnitTests/app.config, Tests/UnitTests/packages.config
Resolves #2127.
When merging, note that there is a parallel pull request in APSIM.Shared.
=> Update most of the NuGet packages

ApsimNG/Menus/MainMenu.cs
=> Point to netlify help

ApsimNG/Presenters/MainPresenter.cs
@hol353 - note that there is an accompanying change in APSIM.Shared.
Resolves #2300
=> Display the inner exceptions of parsing errors.

Models/Core/AutoDocumentation.cs, Models/Core/Simulations.cs, Models/Lifecycle/Cohort.cs, Models/Lifecycle/Lifecycle.cs, Models/Lifecycle/Lifestage.cs, Models/Lifecycle/LifestageProcess.cs, Models/Lifecycle/LifestageReproductionProcess.cs
=> Changes to get lifecycle autodoc working a bit better

Models/Core/Model.cs, Models/Models.csproj, Models/Plant/Functions/AccumulateByDate.cs
resolves #2314 working on #1822 
Adding a common function for accumulating certain property by date, like the day of year in southern hemispheres
Signed-off-by: Junqi_zhu <junqi108@gmail.com>
=> Accumulate by date

Prototypes/Sorghum/SorghumValidation.apsimx
=> Changed TT function after flowering to weighted air temp

Models/Core/AutoDocumentation.cs
=> Don't store empty paragraphs from autodoc

ApsimNG/ApsimNG.csproj, ApsimNG/packages.config
=> Fix problems with FastMember.Signed NuGet package

ApsimNG/ApsimNG.csproj, ApsimNG/EventArguments/IntellisenseItemSelectedArgs.cs, ApsimNG/Interfaces/IGridView.cs, ApsimNG/Presenters/PropertyPresenter.cs, ApsimNG/Views/EditorView.cs, ApsimNG/Views/GridView.cs, ApsimNG/Views/IntellisenseView.cs
=> Added Intellisense to the GridView
