ApServer/ApServer.csproj
Models/Importer/Importer.csproj
Models/Models.csproj
Models/Report/ReportColumn.cs
SWIMFrame/SWIMFrame.csproj
Tests/UnitTests/UnitTests.csproj
UserInterface/UserInterface.csproj

I have trapped the exception to produce a better error message. Report cannot handle reporting Functions. If you add a .Value to the end of the variable you can report a functions value.
Resolves #20

Fixes exception thrown when a Function is reported through Report model.

---

Models/Core/Apsim.cs
Models/Core/Locater.cs
Models/DataStore.cs
Models/Report/ReportColumn.cs

Resolves #13. However, it does so by making ALL property lookups case-insensitive in Locater.GetInternal. This may have undesired side effects.

Make lookup of model names and properties case-insensitive.

---

UserInterface/Presenters/DataStorePresenter.cs
UserInterface/Presenters/ProfilePresenter.cs
UserInterface/Presenters/ReportPresenter.cs
UserInterface/Views/GridView.cs

Fixed Report, Profile and DataStore presenters  that were not adjusting the size of the Grid when attached to a view. Resolves #125

Fixed Report, Profile and DataStore presenters 

---

Models/Agroforestry/LocalMicroClimate.cs
Models/Agroforestry/StaticForestrySystem.cs
Prototypes/Agroforestry/Agroforestry.apsimx
UserInterface/Presenters/StaticForestrySystemPresenter.cs
UserInterface/UserInterface.csproj
UserInterface/Views/StaticForestrySystemView.Designer.cs
UserInterface/Views/StaticForestrySystemView.cs
UserInterface/Views/StaticForestrySystemView.resx

Added dynamic wind equations to replace user entered values. Modified UI to allow user to add tree heights over time. Working on #56

Add wind eqn

---

UserInterface/Views/GridView.cs

Resolves #334 The error occurred any time a user tried to copy from a grid cell while the cell was in edit mode. This would cause the GetClipboardContent method to return null. Added code to handle the user being in edit mode when copying.

Fix for grid cell copy crash

---

Models/Graph/Series.cs

Problem occurred when an experiment had only 2 factors and no child factor values.
Resolves #360

Graph fix for potato validation 

---

Models/Core/Simulations.cs

Working on #359. Added better error message where auto docs can't find the model to document.

Null reference in auto documentation

---

UserInterface/Presenters/ExplorerPresenter.cs
UserInterface/Views/TreeProxyView.cs

Resolves #387 
Selections can now be deleted with the Delete key.
Better error message when trying to paste invalid XML to the Explorer view.

Empty cells can now be pasted in AgroForestry grids.

---

Models/Core/Simulation.cs

Resolves #539 
Simulation run time is now output to console when running from the command line.

Add timing information to simulations.

---

Models/Graph/Series.cs

resolves #558 
Gets filter working for expressions that only use one column but will not work if there is a second column in the expression.

Added partial fix to filtering in graphs

---

ApServer/Program.cs
Models/Core/Runner.cs
Models/Models.csproj
Setup/apsimx.iss

Old Model.xml still being refered to instead of new Models.xml
This causes a problem with the Create Documentation tool.
You should delete out any binaries in your Bin folder that start with "Model." when updating past this commit.
Resolves #576

Old Model.xml still being refered to instead of new Models.xml

---

Models/Weather/Weather.cs

Fix for TAV/AMP calculation when they don't exist in weather file.

---

Models/Core/Runner.cs

files to run. 
Working on #626.

Tell the runner to ignore ApsimNG folder when looking for .apsimx

---

Models/PostSimulationTools/ExcelInput.cs
UserInterface/Classes/GridCell.cs
UserInterface/Presenters/PropertyPresenter.cs
UserInterface/Resources/Toolboxes/StandardToolbox.apsimx
UserInterface/Views/GridView.cs

Resolves #813 .
This small change fixes the immediate problem, which was a consequence of bad syntax in the file filter being passed to the FIleOpen dialog, but I don't want to mark it as resolved just yet, because what's really needed is a mechanism for passing in the correct file filter. In this specific case, we want to be able to look for *.xlsx files, not all files.

Use proper syntax for file filter.

---

Models/Plant/Organs/GenericOrgan.cs
Models/Plant/Organs/Root.cs
Models/Plant/Organs/SimpleLeaf.cs
Models/Plant/Plant.cs

Working on #65  - Chicory model
1) I've changed Population from a field to property, this allows to check the value being set, if population is zero then clear the SowingData (effectively setting IsAlive to False).
2) I've changed the methods DMSupply and NSupply on GenericOrgan (and so in SimpleLeaf) so that retranslocation can be set to leaf too. I did this by removing the calculations from those methods and created functions to compute reallocated and retranslocated (N and DM), which are called. For consistency I did it too for NUptake. I am not sure not whether these function should be set to overrideable. Ideally Root and Leaf would also have the retranslocation enables, but I did not do it now. Should they inherit GenericOrgan and so have that capability?

Allow plant to die as population decrease and retranslocation on SimpleLeaf

---

ApsimNG/Commands/ChangeProperty.cs
ApsimNG/Presenters/ExplorerPresenter.cs
ApsimNG/Presenters/ProfilePresenter.cs
ApsimNG/Views/GridView.cs
Models/Core/VariableProperty.cs
Models/Soils/Soil.cs
UserInterface/Commands/ChangeProperty.cs
UserInterface/Presenters/ExplorerPresenter.cs
UserInterface/Presenters/ProfilePresenter.cs

Resolves #836 
Although this patch eliminates the uncaught exception, there is plenty of scope for improvement. The general problem is one of dealing with a incomplete set of input data (soil water data in this case). Its incompleteness is an error, but we need to be careful how we flag that error if the user is in the midst of entering more data.
I also made some small changes in exception handling. With TargetInvocationExceptions, what we normally want to see are the attributes of the inner exception, not the outer one.

Changes to let the user enter new rows of soil water data.

---

Models/WholeFarm/Resources.cs

Fix Resources so that it can only appear under a Zone.
Most of this was fixed in the previous commit.
Resolves #1016

Prevent WholeFarm modules appearing in the Add list everywhere

---

Models/Core/Model.cs
Models/Models.csproj
Models/Soils/HydraulicProperties.cs
Models/Soils/MultiPoreWater/MultiPoreWater.cs
Prototypes/MultiPoreWater/Test.apsimx

resolves #1075 
New Class (Hydraulic Properties) contains:
- private parameters for the spline to fit moisture release curve to soil data (SAT, DUL, Ll15) and fit hydrulic conductivity using moisture release and kSat.  This h
- private methods to set these parameters when the soil properties are set 
- public methods to return theta and ks for specified suctions, thetas (respectively) and layers
- Links dirrectly to the Water node under soil to get SAT, DUL, Ll15 and Ksat data
- Has two parameters, suction at DUL and ks at DUL which are entered on the grid view for the class
This class must be added onto the soil node to be available to soil water models and the soil water model must call the SetHydraulicProperties() method to initialise the class.  I have done it like this rather than …

Hydraulic properties

---

UserInterface/Commands/ExportNodeCommand.cs
UserInterface/Presenters/ExplorerPresenter.cs
UserInterface/Presenters/MainPresenter.cs
UserInterface/Views/ExplorerView.cs
UserInterface/Views/MainView.Designer.cs
UserInterface/Views/MainView.cs

Use "short" names on tabs, with the full path displayed as a tooltip.

---

Models/Core/VariableProperty.cs

Return null rather than "()" when no units apply.

---

ApsimNG/Views/GraphView.cs

Correct silly markup bug, which triggered error messages on Linux

---

Models/Stock/animgrp.cs
Models/Stock/stddate.cs
Models/Stock/stdstrng.cs

But mainly to test some changes in the windows deployment on Scoop, 
working on #1390

Get rid of unused variables which trigger Mono compiler warnings.

---

ApsimNG/ApsimNG.csproj
ApsimNG/packages.config
UserInterface/UserInterface.csproj
UserInterface/packages.config

Looks like the earlier OxyPlot version is no longer in the repository, so switching to the most recent.
Resolves #1474

Bump OxyPlot version to 2.0.0-unstable0960

---

Models/Resources/SCRUM.xml
Tests/Validation/SCRUM/SCRUM.apsimx

resolves #1633.  
This changes has improved the stats for N leaching predictions in the tests which is good.  It has made the soil water stats look worse but this is also a good thing, honestly.  The soil water stats are comming from the Lincoln maize rainshelter test with two irrigation and 3 N treatments.  SCRUM does not predict N effects on canopy so should only be predicting the high N treatment well.  Prior to this change it was under predicting soil water content in the full N treatment but was closer to the low N treatments, giving good stats.  This change gives better predictions for the high N treatment (the one that should work) but poorer fits for the two low N treatments.  This is expected but it makes the stats look worse.

Changed GSmax parameter in scrum from 0.015 to 0.01

---

Models/AgPasture/AgPasture.PastureSpecies.cs

Working on #1001 
There was an issue with the partition of light to pasture species. In classic Apsim this partition was handled by AgPasture itself, but in ApsimX the communication between MicroClimate and the Species is direct; and this was causing an underestimation of plant growth. This was due to the way AgPasture species compute photosynthesis (they need light at top of canopy instead of intercepted light, witch is supplied by MicroClimate). This fix uses actual radiation as the input in AgPasture, and uses the intercepted light from Microclimate to adjust the light extinction coefficient of each species, thus ensuring the appropriate partition of radiation.

Fix issue with light partition in competing AgPasture species

---

ApsimNG/Presenters/PropertyPresenter.cs

Use a more generic format when displaying user-provided property values.

---

ApsimNG/Commands/ExportNodeCommand.cs
UserInterface/Commands/ExportNodeCommand.cs

Stop autodoc from including the first TitlePage memo it finds.

---

Models/Soils/SoilNitrogen.CNPatch.Processes.cs
Tests/Validation/Maize/Maize.apsimx

Resolves #1797 
This is a simple fix for an error introduced a couple of years back, this changed a bit the calculation of the variable used to distribute residues decomposed in to the soil, the efffect was small and causes more stuff to be added deeper in the profile than it used to be.  This only affected simulation with thin layers, as the maximum depth used in this calculation is 100mm (this was the case of one simulation (Ames) in the maize.apsim tests)

Issue/fraclayer soil nitrogen#1797

---

Models/Soils/SoilNitrogen.CNPatch.Processes.cs
Models/Soils/SoilNitrogen.CNPatch.cs
Models/Soils/SoilNitrogen.CNPatchHandlers.cs
Models/Soils/SoilNitrogen.Variables.cs
Models/Soils/SoilNitrogen.cs
Prototypes/Plantain/Plantain.apsimx
Prototypes/SugarCane/Validation/SugarcaneValidation.apsimx
Prototypes/Wheat/WheatValidation.apsimx

Working on #1798 
Changed how OC is defined in the calculation of urea hydrolysis, previously it used resetOC (which is the OC at initialisation), now it used current OC values

Enable hydrolysis to used actual OC

---

UserInterface/Presenters/DataStorePresenter.cs

Fix a typo that was causing problems for Output node in the tree of the GUI. 
Only effects WindowsForms version of Output node not GTK.
resolves #1817

Fix a typo that was causing problems for Output node in the tree of the GUI

---

Models/Soils/SoilNitrogen.CNPatch.Processes.cs
Models/Soils/SoilNitrogen.CNPatch.cs
Models/Soils/SoilNitrogen.Variables.cs
Models/Soils/SoilNitrogen.cs

Resolves #1823 
When new patches were added to SoilNitrogen a few variables were not correctly handled. dlayer was not passed on to the new patches and the N variables (urea, nh4, and no3) were kept linked, so they changed in all patches whenever one was changed.
The variable nLayers (number of layers) in patches is now linked to that of SoilNitrogen, so there is no need to 'manually' pass it to each patch.  The problem with the N variables was the way there were set in their respective properties in SoilNitrogen. In there the array in each patch was simple pointed to the new array ('value'), and as this was done for all patches, they all pointed to the same object and were in fact 'linked'. I have added an extra loop to copy the values for each layer separately so no link is created... …

Issue/variables in new patches soil nitrogen#1823

---

Models/AgPasture/AgPasture.PastureSpecies.cs

Resolves #2025 
Added a correction for soil N demand so that N uptake is limited when using the generic GLFSoilFertility factor. This can still result in N concentration going above maximum, due to N fixation and remobilised from senesced tissues. This should be minor and rare, and a full fix would entail refactor these calcualtion which is a big job and may not be necessary...

Add consideration for generic SoilFertility when computing N demand

---

Models/PostSimulationTools/ExcelInput.cs

When importing from Excel, use only the Date portion of DateTime fields.

---

Models/Core/APSIMFileConverter.cs
Models/Plant/Functions/MovingAverage.cs
Models/Plant/Phenology/NodeNumberPhase.cs
Models/Resources/Wheat.xml

resolves #2189 
It seems the existing moving average function was causing some problems.  
- Initial value was assigned on the day of simulation commencing to all members in the array and then they were replaced 1 by 1 each day following.  In functions that wheat was using it for this could be placing zero values into the array before sowing.  I have modified the code so that it now has a StartMovingAverageStage on which it adds a single member to the array with the value for that day and keeps adding members each day until the array is at the size specified in the NumberOfDays parameter and then drops the last one off each day.
- Initial value for phyllochron should change with cultivar but it has not been set to do so.  Removing initialValue and having the function pick up the first …

Altered moving average function and wheat.xml

---

Models/Soils/SoilNitrogen.Variables.cs

Resolves #2258 
Added code to newly instated methods: SetUrea, SetNH4, and SetNO3 in SoilNitrogen. Now these will call the PartitionDelta method, which aportions the values passed (delta N) to the SoilCNPatches.  This is only relevant when using the SoilCNPatches capability.

Add code to enable partittioning delta N among CNPatches

---

ApsimNG/Interfaces/IExplorerView.cs
ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/ExplorerPresenter.cs
ApsimNG/Views/ExplorerView.cs

Resolves #2237
Right clicking on a node and pressing copy will now serialise the node and put the XML onto the clipboard, which may then be pasted into a text editor.
After making any changes in the text editor, just copy the XML, right click on a node in the APSIM UI and click paste (or ctrl + v).

Added the ability to copy/paste nodes to and from the clipboard.

---

ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/MainPresenter.cs
ApsimNG/Views/MainView.cs
ApsimNG/Views/ViewBase.cs
Models/Factorial/Experiment.cs

Resolves #2286 
Added the ability to generate a set of .apsimx files for each simulation under the selected node. This option is accessible via the right-click context menu. 
I also added functionality to select a directory (rather than a file) to the ViewBase class. Similarly to the file choosing methods already existing in that class, it uses an API appropriate to the user's OS (e.g. Windows.Forms, MonoMac, etc.). 
If someone could test this code on OSX, that'd be great. All you would need to do is open an .apsimx file and right click on a node -> generate .apsimx files.

Generate model files

---

ApsimNG/Presenters/ModelDetailsWrapperPresenter.cs

Resolves #2441 
Certain presenters (e.g. XYPairsPresenter) were not being detached.

Make ModelDetailsWrapperPresenter call its lower presenter's detach method.

---

ApsimNG/Views/GridView.cs

Resolves #1775
Working on #2399 
This should make data entry slightly easier. Just click on a cell and start typing. The cell won't appear to be selected/editable until you start typing, which is something I will try to address in the near future.

Allow user to initiate cell editing by clicking on a cell and typing.

---

ApsimNG/Views/GridView.cs

Working on #2399 
Also included a fix for another small bug caused by rows still responding to keyboard input even after being unselected. The workaround isn't so great but this will need to be redone anyway if/when individual cell selection is implemented.

Reset grid cell backgrounds manually when no handler is available to do it for us

---

ApsimNG/Presenters/PropertyPresenter.cs
ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
ApsimNG/Views/ActivityLedgerGridView.cs
ApsimNG/Views/GridView.cs
Models/AgPasture/AgPasture.PastureSpecies.Organs.cs
Models/AgPasture/AgPasture.PastureSpecies.cs
Models/AgPasture/AgPasture.Sward.cs
Models/Core/ApsimFile/Converter.cs
Models/Core/IPlant.cs
Models/Manager.cs
Models/Models.csproj
Models/Plant/Interfaces/IOrgan.cs
Models/Plant/Interfaces/IRemovableBiomass.cs
Models/Plant/OilPalm/OilPalm.cs
Models/Plant/Organs/BaseOrgan.cs
Models/Plant/Organs/GenericOrgan.cs
Models/Plant/Organs/HIReproductiveOrgan.cs
Models/Plant/Organs/Leaf.cs
Models/Plant/Organs/PerennialLeaf.cs
Models/Plant/Organs/ReproductiveOrgan.cs
Models/Plant/Organs/Root.cs
Models/Plant/Organs/RootSWIM.cs
Models/Plant/Plant.cs
Models/Plant/SimpleTree/SimpleTree.cs
Models/Stock/stock.cs
Models/Sugarcane/Sugarcane.cs

Added Legumosity and IsC4 properties to ICrop and rename ICrop to IPlant

---

Models/Plant/Organs/ReproductiveOrgan.cs

ReproductiveOrgan autodocs should display the organ's name.

---

Models/Plant/Organs/Root.cs
Prototypes/Grapevine/grapevine.apsimx

suppress the maintenance respiration due to errors in respiration larger than storage supply and interrow competition due to an error in N allocation. 
Focus on the climate effects on yield components for the moment.
Signed-off-by: Junqi_zhu <junqi108@gmail.com>

suppress the maintenance respiration

---

ApsimNG/Classes/Intellisense/EntityCompletionData.cs
ApsimNG/EventArguments/NeedContextItemsArgs.cs
ApsimNG/Views/IntellisenseView.cs
Models/Grazplan/GrazSupp.cs

Working on #2617 
Fixed a bug in which no completion options were generated for array/list elements. This fix should work for dictionaries as well, but I make to guarantees.
I also added the type column back in, and removed the declaration syntax from the description column in manager scripts.

Intellisense: return of the type column (and other bugfixes).

---

ApsimNG/Presenters/AddFunctionPresenter.cs

Use fully-qualified name when locating clicked function.

---

Docker/CreateInstallation/Dockerfile
Setup/osx/BuildMacDist.sh

Working on #2916 
I also reduced chocolatey's verbosity - the log file for the previous run had almost 40 000 lines of output.

Bugfix for create macOS installation

---

Docker/Deploy/deploy.bat

Resolves #2916 
~~Please don't merge this just yet, as there also appears to be a problem in APSIM.Builds.Service which I will need to fix before this works.~~
Edit: This is now safe to merge, once it runs green on Jenkins.

Fix date/time format when adding a build to the builds DB.

---

ApsimNG/Presenters/DataStorePresenter.cs
ApsimNG/Presenters/ExplorerPresenter.cs
ApsimNG/Presenters/IntellisensePresenter.cs
ApsimNG/Presenters/SeriesPresenter.cs
ApsimNG/Views/EditBoxView.cs

Resolves #948 
Resolves #2209 
Working on #2966 
I'm not sure what a typical use case is for the column filter, so I haven't been able to extensively test this feature. That said, it works for examples similar to the one Hamish provided in #948.
I'm marking #2209 as resolved, as we don't really need 2 issues describing the same bug. I'll leave #2966 open until we get a patch out allowing users to click on graphs for simulations not being run.

Intellisense for column filter in DataStore and Series

---

Setup/osx/BuildMacDist.sh

Working on #2916 
This should get the Mac installers working, but there are still some issues with the Linux installer which need to be ironed out.

Add MonoMac.dll to osx installer.

---

Docker/Documentation/doco.bat

Working on #3001
Do these conference papers even belong in source control?
```
ApsimX\Tests\Validation\Maize\Ciampitti Maize Population N Dynamics.pdf
ApsimX\Tests\Validation\System\Hudson\SR08104.pdf
ApsimX\Tests\Validation\System\Tarlee Rotation Trial\EA9950865.pdf
ApsimX\Tests\Validation\System\Wagga\Chan et al 2002.pdf
ApsimX\Tests\Validation\System\Wagga\Heenan et al 1994.pdf
ApsimX\Tests\Validation\System\Wagga\Heenan et al 1995.pdf
```

Don't upload conference papers alongside model documentation

---

Models/Plant/Cultivar/Cultivar.cs

Resolves #3074 
@AllanPeake @hol353 this will make cultivars generate documentation similar to this. Is this what we want?

Cultivars should document their changes.

---

Models/Core/ApsimFile/Converter.cs
Models/Plant/Organs/SimpleLeaf.cs
Models/Resources/Chicory.xml
Models/Resources/Plantain.xml
Models/Resources/SCRUM.xml
Models/Resources/Slurp.xml

working on #572
Is it preferred to write an undo function in the converter, or manually update the resource files and remove the previous converter function - it added a constant function that nobody should have used in the couple of days it was in the code base.

removing slnDemandFunction as it has been made unnecessary.

---

ApsimNG/Commands/WriteDebugDoc.cs
ApsimNG/Presenters/IntellisensePresenter.cs
ApsimNG/Presenters/ManagerPresenter.cs
Models/Manager.cs
Models/Utilities/R.cs

Resolves #3165 
After modifying and recompiling a manager script, the old binary is still not deleted, because we cache the old binaries to speed up access if the user undoes a change. This shouldn't be a big problem, unless the user compiles more than 65, 536 assemblies in one session without restarting the UI.

Be more thorough about cleaning up temp files.

---

Models/Plant/Organs/GenericOrgan.cs

Working on #3186 
This provides a resolution of the immediate problem, but I'm not sure it's the "right" way to fix it. When GenericOrgan was generating its documentation, it was assuming that child links to things like DMReallocationFactor had been resolved. I've modified things so that the documentation generation for this unit now works without full link resolution, but perhaps it would be better to somehow ensure that links have been resolved before generating the documentation for a simulation. I'm not quite sure how all that stuff is meant to work, though.

Don't assume full link resolution has occurred when generating documentation.

---

Models/Storage/DataStore.cs
Tests/UnitTests/StorageTests.cs
Tests/UnitTests/UnitTests.csproj

Convert .db path to short path on Windows if it contains non-ascii characters

---

Models/Manager.cs

Resolves #3230 
This fixes the memo not being saved, but not the crash, which I have not been able to reproduce.

Managers should not remove all children after rebuilding script model.

---

Examples/Wheat.apsimx
Models/Core/Model.cs
Models/Functions/SupplyFunctions/CanopyPhotosynthesis.cs
Models/Plant/Arbitrator/OrganArbitrator.cs
Models/Plant/Organs/GenericOrgan.cs
Models/Plant/Organs/Leaf.cs
Models/Plant/Organs/LeafCohort.cs
Models/Plant/Organs/Nodule.cs
Models/Plant/Organs/PerennialLeaf.cs
Models/Plant/Organs/ReproductiveOrgan.cs
Models/Plant/Organs/Root.cs
Models/Plant/Organs/SimpleLeaf.cs

Resolves #3243
Working on #2797
- The flag **needToRecalculateLiveDead** was missing/misplaced in a couple of organs. **Fixed**.
- When there is some maintenance respiration to be deducted from leaves, **needToRecalculateLiveDead** is now set TRUE to make sure **Leaf** live and dead biomass pools are up-to-date when final check is done.
- In all organs, some checking rules were added to make sure no **MaintenanceRespiration** is assigned to an organ with zero live storage and metabolic biomass.

Leaf live and dead biomass are updated after maintenance respiration is deducted

---

Models/Surface/SurfaceOrganicMatter.cs

Resolves #3376 
When **InitialResidueMass**=0 and organic matter is to be reset, an exception is thrown. The reason is that if **InitialResidueMass**=0, the subroutine **ReadParam** does not fill the object **SurfOM**.
Can someone have a look at this change?

When InitialResidueMass=0 and Organic Matter is to be reset, an exception is thrown

---

Models/Main.cs

Resolves #3475 
Works for multiple files (*.apsimx) and is compatible with /Recurse command line switch to operate on files in subdirectories as well. It writes a success message after converting each file. Should this be reworked so that it only writes a success message when using /Verbose?

Added the ability to upgrade apsimx files to the latest version.

---

ApsimNG/Views/GridView.cs

Allow users to move text editor cursor via arrow keys while editing a grid cell.

---

ApsimNG/Presenters/CLEM/ModelDetailsWrapperPresenter.cs
ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/XYPairsPresenter.cs
Jenkins/build.bat

Resolves #3651 
Resolves #3650 
The root cause was the same as in #3602 - whenever a presenter is instantiated from code, it needs to have its links resolved. I can't think of a simple way to enforce this.

Added a fallback for finding datastore from graph presenter.

---

ApsimNG/Views/GraphView.cs

When exporting a graph, use default gtk background colour.

---

ApsimNG/Views/UpgradeView.cs

Resolves #3669 
Haven't tested on Mac...not that there's a whole lot which could go wrong.
Only reason I removed the `if (version.Major == 0)` check is that we already perform this check inside MainPresenter, in the event handler for clicking on the upgrade button.

Show download progress when upgrading.

---

ApsimNG/ApsimNG.csproj
ApsimNG/Classes/Intellisense/CSharpCompletion.cs
ApsimNG/Presenters/MainPresenter.cs
Models/Manager.cs

Resolves #3673 
Unfortunately, because the intellisense lives in ApsimNG, I've had to add a MathNet.Numerics reference to ApsimNG. Not Ideal, but it should keep Val happy for now. Might be worth moving a lot of the intellisense code into Models one day...and maybe making the intellisense/manager compilation code figure out for itself which assemblies it needs.

Added MathNet.Numerics to ApsimNG/Intellisense

---

ApsimNG/Views/GraphView.cs

Previously, we used the main widget's background colour, which is not necessarily the same as the graph's background colour.
Working on #3671

When exporting a graph, use its background colour

---

ApsimNG/Views/IntellisenseView.cs

Resolves #3724 
This resolves the issue at hand, but I wonder if it would be better to allow the user to continue typing into the primary input field (report, grid cell, manager, or whatever), and simply narrow down the list of options shown based on what the user types. This would be similar to how visual studio handles it. That way, the user doesn't need to press anything to close the popup  - they can just continue typing and ignore the intellisense if they want.

Add an empty row at top of intellisense popup

---

ApsimNG/Views/GraphView.cs

Resolves #3762
Resolves #3779
This will fix the bug where regression equation doesn't show up.

If graph annotation has no colour, use default.

---

ApsimNG/Views/FileConverterView.cs

Resolves #3765 
I think this should fix the problem where the dialog doesn't show in the middle of the screen - it fixes it for me on Windows anyway. I've found in the past that the window position property can be a bit sketchy though, so let me know if the dialog still pops up in weird places.

Crop converter tool should show in center of screen. 

---

APSIMRunner/StorageViaSockets.cs
ApsimNG/Presenters/CLEM/MessagePresenter.cs
ApsimNG/Presenters/CLEM/PropertyTablePresenter.cs
ApsimNG/Presenters/DataStorePresenter.cs
ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/PropertyPresenter.cs
Models/Graph/Series.cs
Models/PostSimulationTools/PredictedObserved.cs
Models/Sensitivity/FactorialAnova.cs
Models/Storage/AddCheckpointCommand.cs
Models/Storage/DataStore.cs
Models/Storage/DataStoreReader.cs
Models/Storage/DataStoreWriter.cs
Models/Storage/DatabaseTableDetails.cs
Models/Storage/DeleteRowsCommand.cs
Models/Storage/EmptyCommand.cs
Models/Storage/IDataStore.cs
Models/Storage/IStorageReader.cs
Models/Storage/InsertQuery.cs
Models/Storage/RevertCheckpointCommand.cs
Models/Storage/WriteTableCommand.cs
Tests/UnitTests/Storage/DataStoreReaderTests.cs
Tests/UnitTests/Storage/DataStoreWriterTests.cs
Tests/UnitTests/Storage/MockStorage.cs
Tests/UnitTests/TextStorageReader.cs
Tests/UnitTests/Utilities.cs

Working on #2821.
This patch allows the use of Firebird databases for the datatore, although to do so requires the user to manually modify the .apsimx file. Firebird support should still be regarded as "test" only. There is no good reason to switch to it, as performance is a bit poorer than that of the existing SQLite implementation. However, I think it's still worth having it present, as it could easily be adjusted to allow the database to reside on a remote server rather than the local machine, and this might be useful for bulk Condor or Docker runs.

Modifications to support Firebird databases.

---

Models/Plant/Organs/Root.cs

Working on #572
@jbrider can you have a look at this? This fixes a bug I ran into - to reproduce, just set sowing depth to 15 in any of the sorghum leaf simulations. This fixes the problem, but I have no idea if this is the best way to fix it or not.
Also seems odd that this code is only used by sorghum since it's in Root.cs.

Guard clause for sorghum code.

---

Models/Importer/APSIMImporter.cs

Working on #3804 
This will make the importer automatically add irrigation/fertiliser nodes as siblings to an operations node. Is this ok?

Improved importing of operations nodes from old Apsim

---

Models/Core/Replacements.cs

Resolves #3802 
This will prevent calls to `Apsim.FindAll(...)` from finding models under the replacements node.

Replacements should be a scoped model.

---

ApsimNG/Presenters/MainPresenter.cs
ApsimNG/Views/MainView.cs

Working on #3748 
Apsim on Linux should now give no option to change themes, but will respect the system-wide gtk theme. I've tested this with a few of the different stock themes shipped with gnome and it seems to work ok.

Don't give Linux users the ability to switch themes.

---

ApsimNG/Interfaces/IGraphView.cs
ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/SeriesPresenter.cs
ApsimNG/Views/GraphView.cs
Models/Graph/IGraphable.cs

Working on #3843 
This implements an area series (colouring area under a curve) however it may be of limited usefulness because the colours we use in the colour palette are not transparent, so if you have a graph with multiple series, each series draws over the top of the previous series. 
e.g. in this screenshot, the 'eighth' series does not show because it is above all of the other series and so it gets drawn first and all other series draw over the top of it. If I move the 'eighth' below all of the other series in the tree, it shows up.

Added area series

---

Models/MicroClimate/MicroClimate.cs

Resolves #3920 by making dayLengthEvap the maximum of the 15 degree value and 2.3 of dayLengthLight. Should fix the issue with the Danish simulations. Reconsider this work around when MicroClimate is next cleaned up (and it is probably overdue).

Temp fix daylength

---

Models/Manager.cs
Models/Operations.cs

Resolves #3947 
Not sure this is the best way to resolve this problem.  It resolves the specific issue and > 90% of experiment set ups are overwriting a manager or operations model so this should facilitate setting up of experiments from the GUI in most cases.  However there are cases where a soil, or clock or water or weather or something else is overwritten in experiment structures.  Should we put valid parent tags in all the models that are occasionally dropped on factors as well?  or can we change factor and composite factor so they will accept all drops?

Make Factor and CompositFactor valid parents for Manager and Opperations

---

ApsimNG/Presenters/ExplorerPresenter.cs
ApsimNG/Presenters/MainPresenter.cs
ApsimNG/Views/ExplorerView.cs

Previously, some event handlers for the context menu were not being detached, which was keeping alive a reference to the context menu, which contains a link to the data store. This caused the data store to not be garbage collected when closing a tab.
Working on #3989

Context menu should be disposed of when closing a tab.

---

ApsimNG/Classes/Grid/GridColumn.cs
ApsimNG/Presenters/ProfilePresenter.cs
ApsimNG/Views/FormattedGridView.cs
ApsimNG/Views/GridView.cs

Resolves #4098 
There's one problem I didn't fix - if you change a cell in the profile grid, then immediately hit undo, the change will not be undone. This is because we don't actually change the model until we call the presenter's `Detach()` method when the user clicks on another node. I've touched this stuff on another branch so am hesitant to fix it here.

Improvements to soil water profile view

---

Models/Sensitivity/Morris.cs
Models/Sensitivity/Sobol.cs

Working on #3678
Calls to library(...) should specify library location, which, if installed by the R component, will not be in any of the libPaths.

Fixed potential bug in R component

---

ApsimNG/Presenters/SummaryPresenter.cs
Models/Core/Scope.cs

If the summary is placed under a simulation or experiment it will still only show data for that node.
Resolves #1574

Allow summary nodes to show summary for all simulations in scope

---

ApsimNG/Views/GridView.cs

Ensure the grid resets when combobox editing has been cancelled.

---

Models/Core/VariableComposite.cs
Models/Main.cs
Tests/UnitTests/BasicFile.apsimx
Tests/UnitTests/CommandLineArgsTests.cs
Tests/UnitTests/UnitTests.csproj
Tests/UnitTests/Utilities.cs

Resolves #4262 
From commit message:
This allows the user to specify an .apsimx file and a config file when running Models.exe. The .apsimx file will not be run but instead, the changes listed in the config file will be applied to the .apsimx file, which will then be written to disk under the same filename.
The config file should contain lines of the form 'path = value'
e.g.
```
[Clock].StartDate = 2019-1-20
.Simulations.Sim1.Name = SimulationVariant35
.Simulations.Sim2.Enabled = false
.Simulations.Sim1.Paddock.Soil.Thickness[1] = 50
```
Notes:
- Command line arguments should look like:
Models.exe file.apsimx /Edit /path/to/config/file.conf
- Relative paths will be resolved to the first match. ie
[Clock].StartDate will match the first clock found in the file.
- Dates can be specified as …

Edit file from terminal feature

---

ApsimNG/Interfaces/IGraphView.cs
ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/SeriesPresenter.cs
ApsimNG/Views/CheckBoxView.cs
ApsimNG/Views/DropDownView.cs
ApsimNG/Views/GraphView.cs
Models/Graph/IGraphable.cs

Working on #4285 
@sno036 Not sure exactly how you want it to work but here you go. It will ignore the x variable and only use the y variable to create the plot. Marker size/type also has no effect.
You can create multiple box plots on the same x axis by adding multiple series to the graph node, or by setting colour/line type to vary by simulation name. Each box plot will be graphed at x = 0, x = 1, etc. Width of each plot is hardcoded to 0.5 - do we want to expose this somehow to the user? Let me know what you want changed.

Prototype box and whisker plot feature

---

Jenkins/performanceTests.bat

Working on #4275 (not really but does this really need its own issue?)
This should give a sensible error message if the user enters a typo into the initial pull request comment (e.g. "Workign on #xxxx").

Improved Jenkins error reporting before running performance tests.

---

ApsimNG/Resources/WaterGraph.xml

Don't show LL15 region series in soil profile graph legend.

---

ApsimNG/Menus/ContextMenu.cs

Resolves #4349 
I also changed this so that the option only shows up after right clicking on the Simulations node. Don't know that it really makes sense otherwise since it's not context-sensitive.

Rename create documentation context menu option.

---

ApsimNG/Presenters/MainPresenter.cs
ApsimNG/Views/UpgradeView.cs

working on #4167 
There are a couple problems I can't solve
1. I don't understand the GTK# render order. I can't change the settings before the widgets render. Thus there is a pause with the rego setup while the upgrades list is generated before it updates with the the custom build warning and disabled button. This is the same issue with the HTML view #3934
2. All sorts of strange things happen if a simulation is open when you then try to upgrade.
- I used to get an error on close of the upgrade window, but this has gone away
- The open simulation disappears from the tab
- When you try open another or same simulation get a null ref error line 797 of MainPresenter.cs as the APSIMXFile is null

Move custom build check to upgrade button in popup rather than menu

---

ApsimNG/Menus/ContextMenu.cs

Resolves #3010
This feature will no longer attempt to find links which resolve to the target model because this will usually fail if under replacements. Instead, just look for variable references which point to the target. Still recommended that you disable 'break on exceptions' if debugging.

Cleaned up 'find all references' feature

---

APSIM.Shared/Utilities/ExpressionEvaluator.cs

Divide function in report should guard against division by 0.

---

Models/Sensitivity/Morris.cs
Models/Sensitivity/Sobol.cs

Fixed a bug where morris/sobol parameter array never gets emptied.

---

Models/Soils/Chemical.cs
Models/Soils/Organic.cs
Models/Soils/Sample.cs
Models/Soils/SoilWaterBackend/SoilWater.cs

These were incorrectly labelled as mm. Thicknesses are stored in mm, but there is a conversion to cm applied when converting thicknesses to depths in SoilUtilities.ToDepthStrings().
Resolves #4587

Fixed soil depth units

---

Models/Report/ReportColumn.cs

Working on #4593
This change will cause report to ignore the "from" or "to" keywords if only one is provided. Note this doesn't help at all if the model name contains "as" or "of".

Added a hack to allow for zone names containing "from" and "to"

---

ApsimNG/Commands/RunCommand.cs
ApsimNG/Utility/Configuration.cs

Working on #4674
This option is stored in the config file and so will be persistent across restarts of apsim. There is no mechanism to change this from the UI.

Allow users to mute the sound played after simulations finish in the UI

---

Models/Irrigation/Irrigation.cs

Negative irrigation warning should not appear unless amount is negative.

---

Models/PostSimulationTools/ExcelMultiInput.cs

ExcelMultiInput should only remove special columns if they exist.

---

Models/PostSimulationTools/ExcelMultiInput.cs

ExcelMultiInput should allow for spaces between filenames.

---

ApsimNG/Commands/CreateParamsInputsOutputsDocCommand.cs
Models/Core/AutoDocumentation.cs

This is in addition to the contents of the summary tag, which is already included in the autodocs.
Resolves #1726

Autodocs should include remarks tags where they exist.

---

Setup/apsimx.iss

Add Apsim to start menu, mistakenly removed in earlier commit.

---

ApsimNG/Classes/PDFWriter.cs

Resolves #3184 
@zur003 - would you be able to test the autodocumentation on macos when there's a map in the simulation?

Add small time-based delay when exporting map to PDF

---

ApsimNG/Presenters/DataStorePresenter.cs
ApsimNG/Views/FolderView.cs

Resolves #5153 
To keep the legends hidden, disable them in the series settings.

Changed folder view so it doesn't hide legends by default

---

APSIM.Shared/Utilities/ApsimTextFile.cs
APSIM.Shared/Utilities/ExcelUtilities.cs
ApsimNG/Presenters/MetDataPresenter.cs

This also allows for excel files in the old binary format (.xls).
I think this should resolve #5109. @lie112 see my change to ExcelUtilities.cs, where we've got an array of accepted file formats. Feel free to add any you think are missing. When reading a file, if the file format does not match any of these formats, we will attempt to read the file using the openXML file reader.

Improved ability to recognise various excel file formats

---

ApsimNG/Presenters/MainPresenter.cs
Models/Grazplan/GrazSupp.cs

Resolves #5260
@her123 @zur003 this crash was caused by an error in GrazSupp.cs:1611, which happens when opening the standard toolbox on windows with French regionalisation settings. The error message is `Error reading supplement library - line for Green maize forage is invalid`. I've fixed the crash, and I've added a quick and dirty fix to GrazSupp to allow the standard toolbox to be opened, but I suspect there may still be an issue with GrazSupp which may be worth looking into.

Improved error handling in main presenter

---

APSIMRunner/StorageViaSockets.cs
Models/Core/Run/SimulationGroup.cs
Models/PostSimulationTools/PredictedObserved.cs
Models/PostSimulationTools/Probability.cs
Models/Sensitivity/FactorialAnova.cs
Models/Sensitivity/Morris.cs
Models/Sensitivity/Sobol.cs
Models/Storage/DataStoreWriter.cs
Models/Storage/IStorageWriter.cs
Tests/UnitTests/Core/Run/RunnerTests.cs
Tests/UnitTests/Storage/MockStorage.cs

Resolves #3808
This allows data store writer to keep track of which tables have been modified during a simulations run. This is used by post-simulation tools such as Probability and PredictedObserved, so that they only get run if their predicted/observed data table has been modified.
Unsure if this is the best solution to the problem, but the only other solution I can think of is to close the issue as "not a bug".

Allow data store writer to keep track of which tables have been modified

---

Tests/UserInterfaceTests/DeleteDBFile.cs

If this runs green on jenkins, then it resolves #3989.
@zur003 @hol353 this *appears* to fix the problem with the failing DeleteDBFile test (although I'm not totally clear on why this is necessary). It doesn't fix the performance tests issue with stock giving slightly different numbers each time it's run.

Force garbage collection before trying to delete .db file

---

ApsimNG/Menus/ContextMenu.cs
Models/Core/Run/EmptyJob.cs

Working on #5257 
It's not a perfect fix - the progress bar is always at 100%, although the status message will correctly show which IPostSimulationTool is currently running so you do have some idea of progress. Fixing the progress bar will require a fairly major rework of the job running code, specifically in regards to SimulationGroup and how the IPostSimulationTools are run.

GUI should remain responsive while running post-simulation tools

---

Models/CLEM/FileCrop.cs
Models/CLEM/Resources/RuminantTypeCohort.cs

resolves #5315 
This problem was resolved by throwing a suitable error as rather than address the SQL query type mismatch from ascii table creation, the problem relates to the land id provided not being present in the production data.

CropReader traps invalid land id being used

---

Models/Grazplan/GrazSupp.cs

Add lock when loading default supplement constants.

---

ApsimNG/Presenters/ProfileGridPresenter.cs

After a user changes a cell, we will now remove any empty rows. Previously, a user had to delete the entire row in one go to trigger this check. Resolves #5400

Simplify deletion of rows in profile grids

---

ApsimNG/Utility/Configuration.cs
ApsimNG/Utility/ConfigurationConverter.cs
ApsimNG/Views/ListButtonView.cs
ApsimNG/Views/MainView.cs

This also improves the robustness of the font resolution algorithm, which should be helpful if switching between the master and netcore3 branches.
Working on #5344

Store font as a string rather than Pango.FontDescription

---

.gitignore
Docs/docfx/api/index.md
Docs/docfx/articles/intro.md
Docs/docfx/articles/toc.yml
Docs/docfx/docfx.json
Docs/docfx/index.md
Docs/docfx/toc.yml
Jenkins/deploy.bat

Resolves #5537 
The docs are available at https://apsimdev.apsim.info/apsimx-docs/. There should be an initial version already there, which will be updated whenever a pull request is merged. To change the homepage, edit `ApsimX/Docs/docfx/index.md` and/or `ApsimX/Docs/docfx/api/index.md`. To add articles, add markdown (.md) files under `ApsiMX/Docs/articles/`.

Add API docs to website

---

.github/stale.yml

This will automatically add the stale label to all issues with the question label which have had no activity in the last 30 days, and closes all issues with the stale label which have had no activity in the last 7 days.
Resolves #5604

Added stale github bot config

---

Jenkins/performanceTests.bat

Working on #5180 (not really, but I didn't want to create a new issue and upgrade for this change).

Remove debugging code from jenkins script.

---

Models/PMF/Organs/Leaf.cs
Models/PMF/Organs/Nodule.cs
Models/PMF/Organs/PerennialLeaf.cs
Models/PMF/Organs/ReproductiveOrgan.cs
Models/PMF/Organs/Root.cs
Models/PMF/Organs/SimpleLeaf.cs
Models/PMF/Organs/SorghumLeaf.cs

working on #5651 
Delete redundant RemoveMaintenanceRespiration methods and put Maintenance respiration calculation in OnDoActualPlantGrowth for organs that have a MaintenanceRespirationFunction.  There are some organs that do not have a MaintenanceRespirationFunction.  This will need to be added if and when required.

Remove redundant methods

---

APSIM.Shared/Utilities/ReflectionUtilities.cs
Models/Core/VariableProperty.cs
Models/PostSimulationTools/SimulationStats.cs
Tests/UnitTests/APSIMShared/ReflectionUtilitiesTests.cs
Tests/UnitTests/UnitTests.csproj

And possibly others as well, since the changes to array handling are fairly generic. Note that the SimulationStats will still not work correctly if any of the field names contain spaces, however the UI will automatically trim any spaces immediately after a comma when you type in new values. So something like this should be fine:
Resolves #5680

Improved SimulationStats UI

---

Models/PostSimulationTools/PredictedObserved.cs

The variables shown in the 'field name to use for matching' dropdowns should be limited to fields which exist in both the predicted and observed tables. This was not the case previously.
Resolves #5689

Improvement to p/o UI

---

Models/Core/Apsim710File/Importer.cs

Resolves #5696
Not sure why we never previously added a SoilArbitrator automatically - I thought it had to be present in every simulation? I've changed the converter so it gets automatically added, so let me know if that's not right.

Fixed some bugs in the importer

---

APSIM.Shared/APSIM.Shared.csproj
APSIMRunner/APSIMRunner.csproj
ApsimNG/ApsimNG.csproj
Docs/CreateDocumentation/CreateDocumentation.csproj
Models/Importer/Importer.csproj
Models/Models.csproj
Tests/UnitTests/UnitTests.csproj

Resolves #5703. I didn't touch the windows installer, since it already seems to be installing the 4.6.2 runtime for some reason.

Bump .net version to 4.6.1

---

Models/Soils/Nutrients/Nutrient.cs

Resolves #5763. Not sure why this suddenly became a problem.

When rebuilding nutrient graph, reuse old arc/node locations.

---

APSIM.Shared/Utilities/ApsimTextFile.cs

Resolves #5776
Added code to mark and later delete blank columns when reading data from excel sheets
Updated the error message in the Excel Reader to provide a more generic message (relates to #5109)

Handle blank columns when reading Excel sheets

---

ApsimNG/Utility/Configuration.cs
ApsimNG/Views/EditorView.cs

Resolves #3876
Working on #5788
Accessible via the right-click context menu. Persists through restarts of apsim. Applies to the EditorView (so manager, report, operations, ...).

Allow users to customise the editor font

---

Models/Soils/SWIM/Swim.cs

Resolves #5804 
@hut104 Maybe it's worth adding some other error/bounds checks here too. If you let me know what you want I can add it in.

SWIM should throw an explicit error if KS not provided.

---

ApsimNG/Resources/Glade/ExplorerView.glade

Fixed gtk warning for invalid icon size

---

Models/Core/ApsimFile/Converter.cs
Models/PMF/Organs/EnergyBalance.cs
Models/PMF/Organs/Leaf.cs
Models/PMF/Organs/PerennialLeaf.cs
Models/PMF/Organs/SimpleLeaf.cs
Models/PMF/Organs/SorghumLeaf.cs

Resolves #3836
Looks like the other part of that issue (checking for null LightProfiles) has already been fixed.

Rename RadIntTot to RadiationIntercepted.

---

Docs/content/Usage/EditFile.md
Models/Core/ApsimFile/EditFile.cs
Models/Core/Run/Runner.cs
Models/Main.cs

Working on #5195 
This will improve performance in optimisation scenarios, as it saves us having to open/close the file more than once per iteration.

Editing a file via command-line should also run the file

---

ApsimNG/ApsimNG.csproj
ApsimNG/Resources/Glade/UpgradeView.glade
ApsimNG/Views/UpgradeView.cs

Working on #5344
@sarahcleary - fyi I've changed the user interface for the upgrade process. The license agreement which is displayed is now taken directly from the [license agreement in this repo](https://github.com/APSIMInitiative/ApsimX/blob/master/LICENSE.md), as the license agreements on the website are stored in .docx format and we also don't know whether the user is covered under a commercial vs non-commercial agreement (previously we always displayed the commercial license agreement).

Changed upgrade UI to use markdownview

---

Models/PMF/Arbitrator/Methods/NutrientConstrainedAllocationMethod.cs

This was causing some simulations to be quite sensitive to their initial conditions, and we were also getting different results depending on the runtime and OS on which they were run.
Working on #6107

Fixed a floating point error in nutrient constrained allocation method

---

Models/Core/IPlant.cs

Perhaps it would make sense to do the same to some of our other interfaces such as IClock, ISummary, ICanopy, etc. That is, if we don't care about losing the ability to have, say, a clock that's not also a model.

Changed IPlant to inherit from IModel

---

ApsimNG/Utility/WeatherDownloadDialog.cs

Don't allow weather download dialog's default size to exceed screen size

---

.vscode/tasks.json

VSCode default build task should build solution file.

---

Models/Resources/Wheat.json

Working on #6309 (it's a problem I noticed with the new property presenter. The cultivar name dropdown for wheat is two lines tall because of this alias).

Removed extra newline from wheat cultivar alias

---

ApsimNG/Views/TreeView.cs

@hol353 - I'm reverting the changes in #6351, as forcing the icon size to 24x24 doesn't work well on most displays. I'm actually not sure why the icons are so big in the gtk2 GUI, but I think the best way to imitate this in gtk3 builds will be to actually invest in some better icons.

Don't attempt to force treeview icons to 24x24px

---

ApsimNG/Views/CodeView.cs
ApsimNG/Views/MarkdownView.cs

I also added a ctrl-f shortcut to the markdown view to make it easier to search through the summary file.

Fixed keyboard shortcuts in gtk3 editor view

---

ApsimNG/Presenters/MainPresenter.cs

When clicking 'open example' default directory should always be examples path

---

ApsimNG/Presenters/MainPresenter.cs
ApsimNG/Utility/FileDialog.cs

Allow Windows users to open files with any extensions, not just .apsimx.

---

Models/Core/Run/SimulationGroup.cs
Models/Storage/CleanCommand.cs
Models/Storage/DataStoreWriter.cs
Models/Storage/IStorageWriter.cs
Tests/UnitTests/Storage/MockStorage.cs

Working on #6577.
@hol353 is there any reason in particular why you added the CleanCommand to the job manager's list of jobs, rather than the datastorewriter's internal list of jobs?

Add the ability for DataStoreWriter to run a clean command internally

---

APSIM.Shared/APSIM.Shared.csproj
APSIM.Shared/JobRunning/JobRunner.cs
ApsimNG/Commands/RunCommand.cs
ApsimNG/Interfaces/IMainView.cs
ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/MainPresenter.cs
ApsimNG/Resources/Glade/MainView.glade
ApsimNG/Resources/Style/global.css
ApsimNG/Views/MainView.cs
Models/Core/Run/GenerateApsimXFiles.cs
Models/Core/Run/Runner.cs
Models/Models.csproj
Tests/UnitTests/Core/Run/GenerateApsimXFilesTests.cs

Resolves #6556
Resolves #6600
- Progress bar and stop button are no longer shown in text area. They're shown in the status panel just above the textview widget
- Simulation status (ie "X of Y completed") is shown in a label to the right of the progress bar, above the text area
- Errors in the simulation are displayed in the text area as they occur
Other changes not really relevant to users:
- Fixed the "collection has been modified" error which was being thrown when updating simulation progress. (This was being handled internally anyway, so was only visible when running with a debugger.)
- Fixed the progress bar appearance in gtk3 builds. I've set it to a fixed 34px height. It would be better to have it expand to the same size as the stop button.

Rework how simulation progress is displayed in the UI

---

ApsimNG/Resources/Glade/UpgradeView.glade

Resolves #6641 
However, I must confess there are aspects of Gtk/Glade layout that I still don't understand. The Gtk2 and Gtk3 versions still look different, and I'm not sure why.

Minor change to widget height setting

---

Models/PMF/Phenology/Phases/GotoPhase.cs
Models/PMF/Phenology/Phases/IPhase.cs
Models/PMF/Phenology/Phenology.cs
Prototypes/TropicalPasture/TropicalPasture.apsimx

Resolves #6630 
See the change to Phenology.cs for the rationale behind this change.
I'm not sure if the GotoPhase's end stage name should be its PhaseNameToGoto (which is what it's set to in all existing instances of this class), or the start stage name of the target phase, which would make more sense to me based on what this class actually does.

Small tidy up of gotophase

---

ApsimNG/Intellisense/CodeCompletionService.cs

Working on #6681. I don't think this is likely to be a problem, although in the longer term a better fix might be desirable.

Manager completion: don't attempt to load System.Drawing.dll

---

Models/PMF/Arbitrator/Methods/C4NitrogenUptakeMethod.cs
Models/PMF/Arbitrator/SorghumArbitratorN.cs
Models/PMF/Organs/SorghumLeaf.cs
Models/PMF/Structure/LeafCulms.cs

working on #572
@hol353 Finally getting back to sorghum - I have reorganised the order according to the coding standards spec, which has created a lot of changes.  It should go green, if so, can you merge it. 
There are more changes to come but until this one is merged it will be hard to see what those changes are (trying to make it a bit easier).
I have mainly moved code around, changed the readonly getters to use lambdas and changed some public to private.
I still have to fix some capitalisations.
There are a few private variables in the wrong place - they will be extracted out in the next stage.
I will close the old pull request once I have made sure I have captured all the changes from it.

reorganizing code to current standards

---

ApsimNG/Utility/FileDialog.cs

Resolves #6660 
Things still don't work as well as I'd like, but I haven't been able to come up with anything better.

Add default save file extension only on Windows

---

APSIM.Server/ServerJobRunner.cs

Working on #6529
Probably not the perfect solution, but it does the job. Can't think of a better way without refactoring SimulationGroup.

Fixed a bug causing server to not clean datastore on reruns.

---

APSIM.Shared/Utilities/PipeUtilities.cs

Need to account for the possibility of a message being split across multiple datagrams.
Working on #6529.

Bugfix for reading from streams in pipeutils

---

ApsimNG/Utility/WeatherDownloadDialog.cs

Fixes if check when pressing "OK" button in download weather window.
You could have clicked "OK" without entering longitude (since it wasn't checking if anything was entered), which would result in an error.
Resolves #6901.

Fixing if check

---

ApsimNG/Utility/WeatherDownloadDialog.cs

Fixes url when using NASA POWER w/ CHIRPS rainfall (World Modellers) radio button
When inserting latitude and longitude you have to use "," as decimal placement instead of "." (an error will pop up). However worldmodel webiste needs to have "." instead of "," in it's url.
Resolves #6917

worldmodel url wants "." instead of ","

---

APSIM.Interop/Graphing/GraphExporter.cs

Resolves #6871, although I don't really understand why it needs to be done this way.

Turn off "UseTextShaping" when exporting plots to PNG.

---

APSIM.Shared/APSIM.Shared.csproj
APSIM.Shared/Containers/Docker.cs
APSIM.Shared/Containers/RDocker.cs
APSIM.Shared/Containers/Volume.cs
APSIM.Shared/Documentation/Extensions/ExtensionMethods.cs
APSIM.Shared/Interfaces/IR.cs
Examples/Optimisation/CroptimizRExample.apsimx
Models/Optimisation/CroptimizR.cs
Models/Resources/RScripts/read_croptimizr_output.r

Working on #6984.
I've made docker the default R engine for CroptimizR simulations only, but the user can revert to old behaviour by setting environment variable `APSIM_NO_DOCKER=1`. Should this be the other way around?
I've created an `IR` interface to abstract away the comms with R. This is implemented by the new `RDocker` class, but not by the old `R` class (which runs R code "natively"). It probably wouldn't be too hard to refactor the original R class so that it can implement the interface, but things still wouldn't quite be transparent to the caller; you need to be really careful with regards to file management when using docker.
When running a croptimizr simulation via docker, all dependent files (such as .met, .xlsx, etc) need to be in the same directory as the .apsimx file, and …

Allow apsim to spin up docker containers to run CroptimizR simulations

---

Setup/netcoreapp3.1/debian/buildDebianInstaller

Resolves #2604. (The other problems mentioned in that issue are either fixed or not relevant to the .net core builds.)

Fix executable file permissions in Debian installation.

---

Models/Core/ApsimFile/FileFormat.cs
Models/Soils/Chemical.cs
Models/Soils/Organic.cs
Models/Soils/Physical.cs
Models/Soils/Sample.cs

(Thickness is serialized instead.)
Working on #7030.

Soil depth should never be serialized to json.

---

Tests/UnitTests/Server/NativeSocketConnectionTests.cs

If a change breaks the protocol, these tests would previously deadlock.
Working on #6529.

Timeout for unit tests in NativeSocketConnectionTests

---

APSIM.Cli/Options/ImportOptions.cs
APSIM.Cli/Program.cs

Resolves #7163.
Example usage, assuming the `apsim` executable (`apsim.exe` on windows) is on path:
```
apsim import --help
apsim import /path/to/my/file.apsim
apsim import --recursive *.apsim
```

Add CLI option to import old .apsim files.

---

APSIM.Server/Sensibility/Logger.cs
APSIM.Server/Sensibility/SimulationChecker.cs
APSIM.Server/Sensibility/SimulationCheckerJobRunner.cs
APSIM.Server/Sensibility/SimulationResetException.cs
APSIM.Server/ServerJobRunner.cs
APSIM.Shared/Utilities/ReflectionUtilities.cs
ApsimNG/ApsimNG.csproj
ApsimNG/Commands/RunCommand.cs
ApsimNG/Menus/ContextMenu.cs
Models/Core/Run/IRunner.cs
Models/Core/Run/Runner.cs

Working on #6529.
New option in the GUI: right click -> verify server compatibility. This will run the simulation, serialize all the models, run the simulation again (without cloning), serialize again, and use the two serialized copies of the models to ensure that the models have all reset their state correctly. It's a bit crude, but should at least let you know if there are problems with the sims which will interfere with server runs.

Add ability to check if a simulation resets its state correctly

---

Models/Soils/SoilNitrogen/SoilNitrogen.Variables.cs

Resolves #7188 
I exposed a number of parameters that control N cycling in SoilNitrogen. Did this by converting fields into properties (simply by adding ```{ get; set; }``` after each name, so it should have minimal, if any, effect on the model performance.
I also made 'private' a few parameter that are not really used (codenitrification), so to reduce a bit the list of parameters from this model...

Exposing SoilNitrogen parameters

---

ApsimNG/Classes/ScriptCompletionProvider.cs
ApsimNG/Interfaces/IMethodCompletionView.cs
ApsimNG/Presenters/IntellisensePresenter.cs
ApsimNG/Views/MethodCompletionView.cs
ApsimNG/Views/PropertyView.cs

These were caused by double-disposal of ScriptCompletionProposal instances (once when the list containing the proposals is disposed (which doesn't set disposed on the proposal instances), then a second time when the GC kicks in).
Resolves #7191.
Edit: This PR contains a few fixes for some other problems which I noticed while debugging. See the individual commits for details.

Fixed GLib-GObject-CRITICAL messages while editing manager script

---

Models/Properties/AssemblyInfo.cs
Models/Report/EventReportFrequency.cs
Tests/UnitTests/Report/EventReportFrequencyTests.cs

Fixed reporting on events from models with names containing spaces

---

ApsimNG/Views/UpgradeView.cs

Working on #7089.
Previously, downgrades were always showing up. Note that this doesn't correct the problem in any existing builds of apsim, only builds which are created after this is merged.

Prevent downgrades from showing up incorrectly in upgrades GUI

---

ApsimNG/Presenters/MainPresenter.cs
Models/Core/ApsimFile/Converter.cs
Models/Soils/Standardiser/Layers.cs

This allows importing of APSIM Classic files in which the number of e.g. NO3 values does not match the number of soil layers. I encountered this in a whole series of files from an APSIM Classic power user, in which they had 11 soil layers but had only populated the top six layers with NO3 and NH4. These files failed to import, with no error message to give the user a clue as to why. In their research they did not need these deeper soil nitrogen values to be anything other than 0. I saw that there was already code to tolerate missing values in MapConcentration(), so have enabled this during the import.
Resolves #7238
I have also made a minor UI change, to set the last opened location after an import. This makes it much easier to import multiple files from the same location. Without the …

Classic import fix

---

ApsimNG/Utility/GtkUtilities.cs
ApsimNG/Views/PropertyView.cs

Resolves #7247. See commit messages for details, but the biggest problem was that we were destroying certain widgets which still had pending events in the events queue.

Bugfixes for some gui components

---

ApsimNG/Classes/ScriptCompletionProvider.cs
ApsimNG/Intellisense/CodeCompletionService.cs

- Displaying much more info now
- Metadata displayed near the cursor, rather than in top-left corner of screen
Resolves #7197.

Improvements for manager completion metadata

---

Models/PMF/Plant.cs

This PR adds an additional assignment in Plant.Sow() to keep SowingParameters.Population synchronized with the 'seeds' parameter when it is present.
Another fix could be to replace `SowingParameters.Population` references with `IPlant.Population`, however I have not been able to fix the issue doing this. I found relevant references in models:
- `PMF/Structure/Tillering/C4LeafAreaM.cs`
- `PMF/Structure/Tillering/C4LeafArea.cs`
- `PMF/Structure/Tillering/FixedTillering.cs`
Resolves #7298

Maintain initial Plant population when using 'seeds'

---

ApsimNG/Views/UpgradeView.cs

Resolves #7312 
Note that the upgrade mechanism is broken for versions generated after late April 2022. Holders of those versions will need to download a new version manually.
I hope to soon add some additional changes to make use of HttpClient rather than the now-obsolete WebRequest API. This will be to partially address the changes needed for issue #7139.

Make sure "versionNumber" is defined when doing upgrade.

---

Models/Optimisation/CroptimizR.cs

This PR adds an additional status update when running CroptimizR with Docker disabled. Currently the status will display "Installing R packages" while the optimization process is running. This adds a "Running Parameter Optimization" status update when the optimization process starts. This matches the behavior of the status display when Docker is used.
Resolves #7343

Improve CroptimizR status output

---

ApsimNG/Views/ExplorerView.cs

Resolves #7353.
It's perhaps not ideal to have this logic in ExplorerView. But I'm not sure of the implications of always setting this to true for all MarkdownView instances.

Set PropagateNaturalHeight to true for model description in GUI

---

Models/Core/ApsimFile/FileFormat.cs
Prototypes/SoilTemperature/SoilTemperature.apsimx

are serialised to .apsimx. Resolves #7376

Fix to ensure properties without description attribute (e.g. SWCON)

---

ApsimNG/Presenters/NewGridPresenter.cs

Working on #7392 
This doesn't address the core issue, but does help keep the GUI from crashing.

Catch exceptions caused by badly formed property values.

---

ApsimNG/Views/Sheet/Sheet.cs

Resolves #7405 
@hol353 - Can you please review this? I think I've preserved the original intent here, but I don't understand Sheet.cs well enough to be certain. My assumption is that the original problem was ambiguity about whether the "RowCount" property provides the number of rows in the data table or the number of rows potentially displayable by the view.

Fix problem with drawing grids with large numbers of rows.

---

APSIM.Cli/Program.cs
APSIM.Interop/Documentation/PdfWriter.cs
APSIM.Interop/Markdown/Renderers/PdfBuilder.cs

Resolves #7307 (as far as I can tell).
See commit messages for details. Wide tables should now be more readable, but they can still look odd if they are really wide, particularly in portrait documents. In the example below, the name, units, type, and settable columns can't actually be reasonably shrunk further because some cells further down contain long single words which can't be wrapped over multiple lines:
What I've done to work around this is make params/inputs/outputs documents landscape:
You might want to check that this is doing sensible things in other documents; I've not really tested this much - I only looked at AGPRyegrass (params/inputs/outputs) and AgPasture (standard).
Feel free to adapt/take/modify this as much as you want.

Improve table column width partitioning in autodocs

---

Docs/content/Contribute/CLI/BringUpToDate.md
Docs/content/Contribute/SourceTree/GetSource.md
Docs/content/Contribute/SourceTree/_index.md
Docs/docfx/index.md
README.md

The "Contribute" section was moved
from: https://apsimnextgeneration.netlify.app/development/contribute/*
to:   https://apsimnextgeneration.netlify.app/contribute/*
in #5629, and the old links return 404 Not Found.
Also change the domain name from "\*.netlify.com" to "\*.netlify.app" in a few places, since "\*.netlify.com" redirects to "\*.netlify.app".
Resolves #7468.

Fix broken links to the documentation website's "Contribute" section

---

Setup/apsimx.iss

e.g. UnderReview. 
Resolves #7478

Stop innosetup showing error if source directory doesn't exist

---

APSIM.Shared/Utilities/ReflectionUtilities.cs

Resolves #7464. (In short: Clone() breaks on assemblies from a non-default AssemblyLoadContext, because by default .NET's BinaryFormatter can only load assemblies from the default AssemblyLoadContext.)
---
Some comments on the implementation:
For general-purpose deserialization, there is no obvious way to specify the load context, because a composite object may contain objects from multiple assembly load contexts.
But in the special case of cloning (serialize-then-deserialize), there is an easy solution: cache the assemblies seen during serialization, and look them up in the cache during deserialization.
Resolving generic types can be complicated because the type arguments need to be resolved recursively, but fortunately the [overload of …

Fix ReflectionUtilities.Clone() when using a non-default AssemblyLoadContext

---

Models/Core/ApsimFile/Converter.cs

This change updates the PredictedObserved version upgrade to avoid calling `JObject.Value` on null values, failing on the current standard toolbox.
The logic of this method should be consistent with previous behavior- the method is refactored into a loop.
Resolves #7608

Fix PredictedObserved version upgrade

---

Models/Core/Apsim710File/Importer.cs

Error reporting in the importer would often itself throw a null reference error, concealing the error that actually occurred. Exceptions thrown during import should now display properly in the UI.
Resolves #7723

Fix error reporting in the importer.

---

APSIM.Documentation/Program.cs
APSIM.Interop/APSIM.Interop.csproj
APSIM.Interop/Documentation/Renderers/DirectedGraphTagRenderer.cs
APSIM.Interop/Drawing/Skia/SkiaContext.cs
APSIM.Interop/Graphing/GraphExporter.cs
APSIM.Interop/Graphing/IGraphExporter.cs
APSIM.Interop/Mapping/MapRenderer.cs
APSIM.Interop/Markdown/Renderers/Inlines/LinkInlineRenderer.cs
APSIM.Interop/Markdown/Renderers/PdfBuilder.cs
APSIM.Interop/Utility/ImageUtilities.cs
APSIM.Shared/APSIM.Shared.csproj
APSIM.Shared/Documentation/Image.cs
ApsimNG/ApsimNG.csproj
ApsimNG/Commands/RunCommand.cs
ApsimNG/Interfaces/IGraphView.cs
ApsimNG/Interfaces/IMapView.cs
ApsimNG/Presenters/DirectedGraphPresenter.cs
ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/MapPresenter.cs
ApsimNG/Utility/Configuration.cs
ApsimNG/Views/DirectedGraphView.cs
ApsimNG/Views/GraphView.cs
ApsimNG/Views/MapView.cs
Tests/UnitTests/APSIMShared/StreamExtensionTests.cs
Tests/UnitTests/Interop/Documentation/TagRenderers/GraphPageTagRendererTests.cs
Tests/UnitTests/Interop/Documentation/TagRenderers/GraphTagRendererTests.cs
Tests/UnitTests/Interop/Documentation/TagRenderers/ImageTagRendererTests.cs
Tests/UnitTests/Interop/Markdown/Renderers/Inlines/LinkInlineRendererTests.cs
Tests/UnitTests/Interop/PdfBuilderTests.cs

Resolves #7469.
Eliminates use of Windows-based elements of System.Drawing.Common, by using Gdk.Pixbuf instead of Image or Bitmap. Also converts mapping from SharpMap to Mapsui. [Mapsui](https://mapsui.com) was developed from SharpMap, but uses SkiaSharp for its rendering, and is more actively maintained and updated. Map retrieval is done asynchronously, and uses the same Brutile cachinbg mechanism as did Sharpmap.

Replace Bitmap and Image with Gdk.Pixbuf; replace SharpMap with Mapsui.

---

APSIM.Cli/APSIM.Cli.csproj
APSIM.Documentation/APSIM.Documentation.csproj
APSIM.Interop/APSIM.Interop.csproj
APSIM.Server/APSIM.Server.csproj
APSIM.Shared/APSIM.Shared.csproj
ApsimNG/ApsimNG.csproj
Models/Importer/Importer.csproj
Models/Models.csproj
Tests/UnitTests/UnitTests.csproj

Resolves #7745. Get rid of these errors:
```
Models -> /tmp/ApsimX/bin/Release/netcoreapp3.1/Models.dll
Models -> /tmp/ApsimX/bin/Release/netcoreapp3.1/osx-x64/Models.dll
APSIM.Interop -> /tmp/ApsimX/bin/Release/netcoreapp3.1/APSIM.Interop.dll
APSIM.Server -> /tmp/ApsimX/bin/Release/netcoreapp3.1/osx-x64/apsim-server.dll
ApsimNG -> /tmp/ApsimX/bin/Release/netcoreapp3.1/osx-x64/ApsimNG.dll
/usr/share/dotnet/sdk/7.0.102/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.ConflictResolution.targets(112,5): error NETSDK1152: Found multiple publish output files with the same relative path: /tmp/ApsimX/Models/obj/Release/netcoreapp3.1/apphost, /tmp/ApsimX/Models/obj/Release/netcoreapp3.1/osx-x64/apphost, /tmp/ApsimX/bin/Release/netcoreapp3.1/Models.deps.json, …
```

Changed project files to remove Jenkins error: NETSDK1152

---

ApsimNG/Views/Sheet/CellEditor.cs
ApsimNG/Views/Sheet/GtkExtensions.cs
ApsimNG/Views/Sheet/SheetEventKey.cs

Mainly related to the use of the numpad, although I've also added support for some other, more obscure keyboards. To be honest there is probably more to be done here: e.g. using tab/enter for grid cell navigation when *not* in edit mode (currently this does nothing).
Resolves #7738.

Fixes to cell editing in SheetView

---

Setup/netcoreapp3.1/macos/buildMacInstaller

Resolves #7765
This might fix #7765 but I don't have a mac to test on so don't really know for sure. I had thought `--self-contained` was true by default when publishing, but maybe that has changed in recent sdk versions.

MacOS installer: always build in self-contained mode

---

Models/Core/Locator.cs

Resolves #7803.
Not sure how those spaces got there in the first place, but the Locator wasn't handling them.

Fix problem with leading spaces in Simulation names

---

Models/Core/VariableExpression.cs

Also, allows for IFunctions to have their .Values() used in expressions. Previously, unknown types would silently substitute in scalar 0 when used in expressions. Doesn't address @peter-devoil's concerns about multiple 'as' variables with the same name being silently ignored. 
Working on #7835

Throw an error for unrecognized types in VariableExpression.

---

APSIM.Shared/Utilities/DataTableUtilities.cs
Tests/UnitTests/CommandLineArgsTests.cs

Resolves #7857 
- This makes text output not have fixed width columns.

Modified DataTableToText() to not pad values

---

Models/Core/Apsim710File/Importer.cs
Models/Management/Fertiliser.cs
Models/Resources/Fertiliser.json

This adds the UAN_N fertiliser previously available in APSIM classic. The nutrient fractions are pulled from the old XML definition [here](https://github.com/APSIMInitiative/APSIMClassic/blob/27396788a2c0fcc2750b72700d7fccf35fc7c7ea/Model/Fertiliser.xml#L95).
Resolves #7868

add UAN_N  fertiliser

---

ApsimNG/Presenters/SoilDownloadPresenter.cs

Resolves #7861
- A missing "level" in the XML caused a crucial function to skip when it was looking for a child with the name 'Soil'.
- Because soil was not a child, but it was present, it simply needed to be nested within a folder element for it to become a child.
- the folder lines where copied from ~ASRIS soils

Added XML wrapper for SLGA soils for conversion

---

ApsimNG/Views/XYPairsView.cs

Resolves #7655
- Makes the graph take up 2/3rds of the right side explorer pane.

changed XYPair.graphView height to 200

---

ApsimNG/Resources/Toolboxes/TrainingToolbox.apsimx

Resolves #7908
Renamed the Soils in Exercise 3 to Wheat and Barley to match exercises 1 & 2. Updated references from SoilNitrogen.

7908 Fixed Errors In Training Toolbox

---

ApsimNG/Presenters/ManagerPresenter.cs

Resolves #7924
The event to click another node is handled before the event to finish renaming the Manager node. So when the rename event tries to update the right view, its already potentially been changed.
I added a check in to make sure the ManagerView has an Editor attached when it tries to update the code view, which seems to have fixed the problem without causing other issues. I can still rename nodes and undo/redo the renaming events.

7924 Added check to see if ManagerView is set

---

Models/Graph/SeriesDefinition.cs

Resolves #7929 
This adds a try-catch around the function call before it goes into system code to update the data grid. When in visual studio debug mode it will still pause here (though this can be changed in your settings) as it is an exception that is thrown and not handled by the external code.
I've added an error message to inform the user which field is the problem so that the mistake is easier to fix.

7929 Catch for expection and better error message

---

ApsimNG/Presenters/SeriesPresenter.cs
ApsimNG/Views/SeriesView.cs

Resolves #7524
There were a few bugs happening here.
First, the X2 and Y2 field would only display if the Region was selected before the node was clicked in the tree, changing the graph type would not refresh the field's visibility. That was fixed by moving the ShowX2Y2 function call into DisableUnusedControls which is called both when the page is first made, and when the graphtype field is changed
To solve the actual reported bug, the X2 and Y2 field names are now null'ed if the fields are disabled, such as if the graph type is changed from region.
Lastly the X2 and Y2 field were appearing in the wrong order in menu (x, y, y2, x2), so I switched their positions around.

7524 X2Y2 field now controlled in DisableUnusedControls

---

Models/PMF/Organs/IRootGeometryData.cs
Models/PMF/Organs/NetworkZoneState.cs
Models/PMF/Organs/RootZoneState.cs

Resolves #1197 
Fixing a very old issue. Length property was replaced by RootLength (as highlighted in the issue) at some point, and all references to the Length property have since been cut. Ran some the related unit tests afterwards which all seemed to work, so this should be a simple change.

1197 Removed Length from Zone State Classes

---

ApsimNG/Menus/ContextMenu.cs

Resolves #7492 
The first commit directly fixes the problem outlined in the issue, users are now prompted to save if they try and make documentation on something like an example file.
The 2nd commit addresses a problem found during this where if you create documentation on a graph or a simulation node, you get an exception and an empty document. Investigating the code, it seems that cloning the node as part of this process, breaks the connections these nodes need to generate the graph pictures for documentation. _**My solution was to not clone the node if it's one of those, but that may not be the best solution.**_

7492 'Create Documentation' checks if user has saved

---

APSIM.Shared/Utilities/ApsimTextFile.cs

Resolves #7935
A weird little bug where the excel to table converter used by the weather class would only set the column name and not the column caption when reading from an Excel file. Ended up adding a loop right after it calls the system code to copy the name into the caption for each column.

7935 Column Captions set to Column Name after read

---

ApsimNG/Menus/ContextMenu.cs

Resolves #7495
Adds a simple check into the "Show Model Structure" and "Read Only" context menu options so that Cultivar nodes under a resource can be changed from read only and be edited like they are supposed to.

7495 Cultivars under a resource can now be edited

---

APSIM.Shared/Utilities/ApsimTextFile.cs

Resolves #7947
Weather constants would be read in with commas instead of periods when reading an excel file formatted for another region. 
This should have been handled by a localization function that is attached to the constant getter function, but it was instead just removing the , and combining the entire number. It's much safer to format it correctly when reading in the first place.

Replaced , with . when reading in weather constant

---

Models/Report/EventReportFrequency.cs

Resolves #7180 
This should fix the follow up problems that Adam reported. When it tries to make an event, if fails with the single token, it will then also try with the full line. If that also fails, then it throws an exception same as before.

7180 2nd check for events with space in name

---

Models/Functions/HoldFunction.cs
Prototypes/LeafApex/LeafApex.apsimx
Tests/UnitTests/Functions/HoldFunctionTests.cs

Working on #7350
The error exception was being discarded in the worker threads with an empty catch, now that will pass the exception up the line and it now gets to the GUI, halts the simulation and displays the error.
This might break a unit test if any had errors that were being hidden by this empty exception handler. Though that's a good thing, since these mistakes slow down the simulation by a huge amount and should be fixed.

7350 Exception is now thrown up the stack

---

Models/Functions/XYPairs.cs

Resolves #7967
Previously all XY pairs in a auto-doc would be rounded to 1 decimal place, which made graphs and tables not agree on the numbers. Now it will use up to 6 decimal places depending on what is needed.

Document XY will use up to 6 decimal places

---

APSIM.Shared/Utilities/ExpressionEvaluator.cs
Models/Functions/ExpressionFunction.cs

Resolves #7963
Max and Min functions in an expression now work similar to C and will take either an array of number, or two single numbers.

Allow Max and Min to take two doubles as well

---

ApsimNG/Presenters/GraphPresenter.cs

Resolves #6834
This prevents the graph from scaling down to small and showing variations in values that aren't actually there. Used a value of 1e-5 as the smallest scale it would allow.

6834 Added Minimum Scale for Graph Axis

---

ApsimNG/Views/AxisView.cs

working on #8001 
Not sure if this does exactly what is wanted. DateTime.TryParse seemed to be too aggressive about interpreting things as dates.

Prevent numbers from being parsed as dates.

---

Models/Resources/Eucalyptus.json

Resolves #4865
Followed the instructions from the issue to update the Eucalyptus resource so CourseRoot.CriticalNConc points to the correct MinimumNConc

4865 Change CriticalNConc to reference correct MinNConc

---

ApsimNG/Presenters/NewGridPresenter.cs
ApsimNG/Presenters/ProfilePresenter.cs
ApsimNG/Views/Sheet/MultiCellSelect.cs
Models/Soils/SoilCrop.cs

Resolves #8013
When someone tries to copy a soil from one apsimx project to another, if the layer count doesn't match, it will throw them a bunch of errors and give a blank screen. This will now handle it a bit more gracefully, modifying the soil to match the current Physical node structure, and alerting the user to what has happened with a pop-up message.
While I was there, I also added a fix to allow grid cells to be shift-selected in any order. So you can select cells from bottom to top or right to left instead of being forced to go left to right, top to bottom for it to work.

8013 Handle copying of Soil nodes

---

Models/Core/ScriptCompiler.cs

Resolves #8049 (hopefully)
Added a lock before the compiler checks if code already exists so that if it doesn't another threat won't check if the same code exists while it is already compiling that code. Will have to see how Jenkin's performance goes with this to see how much of a delay  this waiting adds.

8049 Added Lock around Script Compiling

---

Docs/content/Contribute/Compile/linux.md

Resolves #7998
Linux instructions on website were still referencing building with netcore3.1, went through them installing on a linux machine to see what needed to be updated and got apsim built.

7998 Updating Linux compile instructions on website

---

APSIM.Shared/Utilities/ApsimTextFile.cs
Models/Climate/Weather.cs
Models/Interfaces/IWeather.cs
Tests/UnitTests/Weather/WeatherTests.cs
Tools/CompareTestLogs.py

Resolves #8085
There are now two caches when reading weather data. The first is on the weather file which marks the date and file position of lines it reads. If you need to seek to a new position it now tries to find the closest position it has been before and works from there.
The weather also keeps a cache of every met data record it has already read. This means it doesn't need to re-read the file when looking at previous data, or if it's fetched future data and has then gotten to that future date during the same simulation.
Yesterday and Tomorrow's data is now grabbed when they are needed instead of being properties that are updated every day that is simulated. I may need to change that back for performance.
Based on the tests, it shows some values have changed. This is most likely …

8085 Getting Future Weather

---

Models/Storage/DataStoreWriter.cs

Resolves #8104 
StorageWriter previously used an EmptyJob to busy wait when it didn't have anything to write. An existing SleepJob class already existed, so that was added instead with a 10ms sleep delay.
No hit to performance that I could see, however as noted by Drew in #6772 this could be refactored in the future to actually solve the problem.

8104 StorageWriter Busy Waiting Fix

---

Models/Core/ApsimFile/Converter.cs

Resolves #8090
Resolves #8108
The JSON converter had a check to see if a soil had any solutes when doing the conversion. Since the SoilNitrogen solutes have their own types (SoilNitrogenNO3 etc), it wouldn't see them and add duplicates.
Fixed it so that it checks if a SoilNitrogen is present, and if so, does not try to add the new solutes. Also added in a check to add in default SoilNitrogen solutes in they happen to be missing.
This should resolve both issues, as file editing the duplication was the only reason 8108 was even possible.

8090 Fixed SoilNitrogen Duplicate Solutes

---

Models/Graph/SeriesDefinition.cs
Tests/UnitTests/Graph/SeriesTests.cs

Resolves #8096
**Ready to Merge**
Row filters do not support having wildcard characters in the middle of a string in a filter, so when we changed over to them, some filters (such as a graph in AgPasture) stopped working. This fix checks filter strings for wildcards in the middle and converts them into two checks that the row filter system can support.

8096 Handle Wildcards in middle of Filter strings

---

ApsimNG/Presenters/OperationsPresenter.cs
Models/Management/Operations.cs
Tests/UnitTests/Operations/Operations.cs

Resolves #8134
Parsing an Operation from a string has been moved to a static method in the Operation class instead of in the presenter. A set of unit tests has also been added to make sure it's working correctly.

8134 Operation Parsing

---

Models/Factorial/CompositeFactor.cs
Tests/UnitTests/Factorial/ExperimentTests.cs

Resolves #8129
**Ready to Merge**
A small change to exception throwing on Composite Factors, so that it only throws on non-memo children that haven't been listed in the Composite Factor list.
A unit test to check this was also added.

8129 Memo can be placed under composite factor with test

---

APSIM.Shared/Utilities/DateUtilities.cs

Resolves #8142
That issue was not happening on my system, but did happen for Julian. Checking the month lists, the Australian culture has changed back again to only having 3 letter abbreviations, which caused this edge case.
Shouldn't happen again now, and it seems like the 4 letter thing from before might have been a bug on there end.

Fixing Month Parsing for 4 letter months

---

APSIM.Shared/Utilities/DataTableUtilities.cs
ApsimNG/Utility/Excel.cs
Models/Summary.cs

Resolves #8146
Added sorting for the excel and csv exporting of the data tables, and for the summary export option. In the case of the excel and csv, if two sims have the same name (multiple entries) then they are sorted by Clock.Today if that is a column that exists.

8146 Exporting DataStore sorts by SimulationName

---

ApsimNG/Presenters/DocumentationPresenter.cs

Resolves #8193
Put an async handle around the markdown generation. This along with the changes from last week means there is very little lag when loading a Documentation Presenter window.

8193 Documentation Presenter markdown generation put into async function

---

Models/PostSimulationTools/PredictedObserved.cs
Models/Storage/DataStoreReader.cs
Tests/UnitTests/PostSimulationTools/SimulationComparisonTests.cs

Resolves #7841
It was possible for SimulationName to not show up in the PredictedObserved view as an option in the dropdowns. When loading directly from the database, some tables do not have SimulationName, but in that case it was supposed to be added dynamically.
This change manually adds it back in if it's missing. 
Also fixed another bug where under certain circumstances, the Datastore would try and add SimulationName and CheckpointName columns to a table that already had them. I simply added an extra check for those.

7841 Make sure SimulationName appears in PredictedObserved Dropdown

---

ApsimNG/Presenters/AddModelPresenter.cs
Models/Core/Apsim.cs
Models/PMF/Structure/HeightFunction.cs
Models/Soils/WaterModel/CNReductionForCover.cs
Models/Soils/WaterModel/CNReductionForTillage.cs

Working on #6706
Looking through an old issue and I noticed that models using the IFunction interface would always appear in the Add Model menu, even if they had been given a ValidParent tag to restrict them. Rewrote the function that handles valid parent checking so that it respects that and it cleans up most of the random classes that always show up in the add model menu.
After that only 3 models still appeared that shouldn't: Soils.WaterModel.CNReductionForTillage, Soils.WaterModel.CNReductionForCover and PMF.Structure.HeightFunction.
CNReductionForTillage and CNReductionForCover were only used under a WaterBalance node, so I gave them that parent.
Not sure what to do with HeightFunction however, as it does not seem to be used in any of our examples or validation simulations. The last …

6706 Models using IFunction can have valid parent restrictions

---

ApsimNG/Views/BubbleChartView.cs

Resolves #8200 
On windows carriage returns would be added to the rules and actions making them unparsable. It also caused blank lines to be added into these boxes every time they were opened, as both the newline and carriage characters were treated as new lines.

8200 Stops carriage returns from being added to Rotation Manager

---

Models/Functions/ExpressionFunction.cs

Resolves #8207
There was a check to see if a returned array was null, but not if the values inside it were NaN. This now throws an error instead of trying to do calculations with NaN values.

8207 Array values are checked in Expression Function

---

Examples/Barley.apsimx
Examples/Maize.apsimx
Examples/Mungbean.apsimx
Examples/Oats.apsimx
Examples/Soybean.apsimx
Examples/Wheat.apsimx

Resolves #8234
This pull requests standardises the simple crop simulations in Toowoomba (that use the `Dalby.met` weather file), including:
- [Barley](https://github.com/APSIMInitiative/ApsimX/blob/0fce476e9b16433dd2b1fa40047174cf04490c94/Examples/Barley.apsimx)
- [Maize](https://github.com/APSIMInitiative/ApsimX/blob/0fce476e9b16433dd2b1fa40047174cf04490c94/Examples/Maize.apsimx)
- [Mungbean](https://github.com/APSIMInitiative/ApsimX/blob/0fce476e9b16433dd2b1fa40047174cf04490c94/Examples/Mungbean.apsimx)
- [Oats](https://github.com/APSIMInitiative/ApsimX/blob/0fce476e9b16433dd2b1fa40047174cf04490c94/Examples/Oats.apsimx)
- [Soybean](https://github.com/APSIMInitiative/ApsimX/blob/0fce476e9b16433dd2b1fa40047174cf04490c94/Examples/Soybean.apsimx)
- …

Standardise examples

---

.editorconfig

resolves #8253
working on #1281
Warnings were cluttering up error window in VS. Will turn on warnings once StyleCop rules are being worked on in the future.

Disable stylecop directive and unused parameter warnings

---

ApsimNG/Presenters/ReportPresenter.cs

resolves #8309
The vertical position starts off not set making the common report and events windows take up the entire report view.
Added check if the position is not set yet, to make it a sufficient number to make all report views seen.

Report's vertical splitter position issue fix

---

Docs/content/Development/Software/CompileInCommandLine.md

resolves #8314 
dotnet publish commands removed target framework keyword for .NET 3 and added .NET 6.0 target framework keyword.

Build documentation updated to .NET 6.0 instructions.

---

ApsimNG/Classes/Property.cs
Models/Core/Model.cs
Models/Core/Scope.cs

Resolves #8324 
A bit of a weird bug where the FindAllInScope method didn't work when the calling manager script was located under a factor in an experiment. 
To fix this, if the script didn't have a simulation as an ancestor, it would then look for an experiment instead and use that to find the simulation model. Then when returning all models in scope, it would return the models in scope under the factor first, before then also returning the models under the simulation so the script could link to models back in the simulation. This is a bit slower, but also fairly rare to do, and better than modifying the existing FindAll function in the Scope class.

8324 Allow Manager scripts to link to models when used under a factor

---

ApsimNG/Presenters/WaterPresenter.cs
Models/Soils/Water.cs

resolves #8273
- removed a return statement that caused the depth of wet soil calculation to return after doing one loop.
- added null checks for several inputs in water node to solve exceptions occurring when fields are cleared.

Bug fix for water model percent full/depth wet soil calculation

---

ApsimNG/Presenters/PlaylistPresenter.cs
ApsimNG/Views/TreeView.cs
Models/Core/Run/Playlist.cs
Tests/UnitTests/Core/Run/PlaylistTests.cs

Resolves #8363 
Solves a couple of issues. The select node event in treeview is turned off when editing a node (was causing the presenter to be reloaded twice when editing a node).
A cache was added to playlist searching so if it has already search for a particular string, it stores the results and reads those back if that string is searched for again. This does mean the presenter has to clear the cache though when it opens (in case simulations have had their names changed in the GUI)
Lastly the async function was redesigned to only run one search at a time, and mark a flag for a pending search if another tried to run while one was still going. If a function ends and there was one pending, a new search is run then.

8363 Fix Playlist Crashes

---

ApsimNG/Utility/Configuration.cs

Resolves #8384 
Not sure if this is the best way of going about resolving the issue. I also notice there are a couple of other classes with destructors (DataStore and R), but after taking a brief look at them it seems unlikely that they would throw. Still, it may be better safe than sorry.

GC Crash fix.

---

ApsimNG/Views/TreeView.cs

Resolves #8391
Not 100% sure this will fix the problem, since it's such an intermittent bug and hard to test. But it seems that if clicking quickly in the tree view, it might be possible to have the OnBeforeLabelEdit and OnAfterLabelEdit events occur out of order, this then causes the CursorChanged event to get turn off and stops the right hand panel updating.
Manually disabling the OnAfterLabelEdit event did cause the same behaviour that we were seeing in this bug (view stops updating, but start working again after saving/refreshing the treeview).
This might be a fix that we just have to apply and then just wait and see if the bug still happens.
- 2nd attempt, first pull request was accidently branched off a working branch.

8391 Added flag around events to protect RightHandView events

---

ApsimNG/Resources/Glade/CLEMGridView.glade
ApsimNG/Utility/GtkUtilities.cs
ApsimNG/Views/CLEM/ActivityLedgerGridView.cs
ApsimNG/Views/ReportView.cs
ApsimNG/Views/TextAndCodeView.cs

Resolves #8402
CLEM uses a different system instead of explorerview for it's view. Made the function more generic so that it could work with clem views as well. Checked as many CLEM nodes as I could find in the examples and also fixed a glade reference bug introduced with the grid refactor.

8402 Changed GetBorderOfRightHandView to work with CLEM

---

Models/Soils/WaterModel/EvaporationModel.cs

Working on #8388 
My previous fix attempt (#8389) introduced a bug where EvaporationModel would run with wrong values after a reset under certain conditions. The other PR trying to fix my error (#8390) revealed a few tests are running without initialized Clocks, but that is another issue.

Attempt to fix reset error with evaporation model.

---

ApsimNG/Presenters/ReportPresenter.cs

resolves #8409
Path string was windows compatible but not Linux/Mac compatible.
Fixed issue with cross-platform pathing constructing function.

directory of common reporting variables path made cross-platform safe

---

ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Views/GraphView.cs
Models/Graph/SeriesDefinition.cs

Resolves #8395 
Previously the line type, marker type and colour type dropdowns would filter out points with a null value in the column if a "vary by" option was chosen. This would happen even if the row of data had an x and y value and could potentially be plotted. To fix this I made it so they would be plotted under a series named "null" so that it is obvious that the data is there, just missing a value to group it into a series.
To achieve a similar behaviour from before, a user filter can be used such as: Wheat.Phenology.CurrentStageName IS NOT NULL
And the null series will not be shown:
This solution also has the added benefit of not having the graphs crash or display everything in one series when it encounters a null value in a column like this. Obviously if the x or y values for a …

8395 Line, Marker and Colour dropdown on graphs no longer filter out data

---

ApsimNG/Presenters/PlaylistPresenter.cs
Models/Core/Run/Playlist.cs
Tests/UnitTests/Core/Run/PlaylistTests.cs

Resolves #8371
The playlist will now return the last list of simulation names to be searched instead of rerunning the search when running the simulations. You can only run the playlist when the node is selected, so it will have always been searched, if not, then it will do the search itself anyway.

8371 Remove Delay from Playlist Run button

---

ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/SeriesPresenter.cs

Resolves #8421
The provided file had an axis with set values that meant all the points were not visible on screen. This change will now provide an error if that is the case, and reset the axis if no points would be drawn. IF only some points are off screen, just a warning is displayed.
Also Series Presenter was clearing the status messages after the graph was drawn, which hides error messages from the graph. I've moved this clear to the start of the attach method so it does it before the graphs are drawn.

8421 Warns if points being graphed are outside the given axis values

---

ApsimNG/Views/TreeView.cs

Resolves #8454 
When dragging a node to duplicate it, it was possible for the name editing to start on the previous node. Then when you tried to rename the new node you just made, it would fire the renaming finished event on the original node instead.
This should fix it so that the node renaming is reset when dragging ends.

8454 Moved editting check code to drag end and reset variables

---

ApsimNG/Presenters/GraphPresenter.cs

Resolves #8464
PR #8421 added code to reset graph axis if there were no points visible on the screen, however if the data to be graphed contained a mix of NaNs and doubles, it would cause a stack overflow of it looping to reset the axis.
That reset has been removed now, and it will just warn the user that there are no points that can be graphed, leaving it for them to fix the axis. Also added in warnings to tell the user if the data they are graphing contains NaN values.

8464 Removed Graph Axis Reset, Added more NaN warnings

---

ApsimNG/Interfaces/IMainView.cs
ApsimNG/Presenters/MainPresenter.cs

Resolves #8478 
There was a typo where the wrong variable was being used for the splitter position, has been fixed.

8478 Fixed split screen splitter position

---

ApsimNG/Presenters/GridPresenter.cs
ApsimNG/Presenters/PropertyAndGridPresenter.cs

Resolves #8482
Presenter needed to attach an intellisense, it was removed in the grid refactor. None of the other models using this presenter should have a problem with this, since they either should have it too, or were built in a way that it doesn't matter.

8482 Attaches Intellisense back to PropertyAndGridPresenter

---

Models/Main.cs

resolves #8471
Fixed bug where the temp file was overwritten after a command change had already occurred when including a file using the cli apply switch.

Config file order bug fix

---

ApsimNG/Presenters/ExplorerPresenter.cs
ApsimNG/Views/TreeView.cs

Resolves #8505
I've still not been able to replicate this bug on my machine since I put in PR #8401, but considering it's still happening there must be something in particular that happens when the GUI is in use that is causing this.
I've gone through and followed the node selection events from the TreeView through to the RightHandPanel updates and done:
- Cleanup of times the event was disabled when it didn't need to be
- Changes so it is always enabled again when it is disabled, even if an error is thrown
- Removed an empty try-catch that was hiding errors
- Checked when right hand panel is updated to make sure it's being handled correctly
As with last time, we might need to merge this in and see if it's still happening to others. I'll leave the issue open until we've confirmed if this …

8505 Cleanup of node selection events

---

ApsimNG/Views/TreeView.cs

resolves #8508
The expanding of a node was causing the explorer view to scroll to the last child of the expanded node. Now it will scroll to show the first few children.

Node expanding now scrolls to show first few children rather than last.

---

ApsimNG/Presenters/GraphPresenter.cs

Resolves #8515
When a cell is fed through as null or empty, it gets converted to a NaN by the graphing code. This has to stay this way, but not all NaNs are bad so I've redesigned the messages it gives back.
Users are still informed of NaN values, but now they are told it could be caused by empty cells in the datastore, the errors are also broken up into points with only NaNs in the X, only NaNs in the Y or NaNs in both axis, with a count given to each.
That should hopefully make it more clear what is being reported and allow users to check their data to confirm it matches.

8515 NaN Error messages on Graphs

---

ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/ProfilePresenter.cs
ApsimNG/Presenters/WaterPresenter.cs
ApsimNG/Views/GraphView.cs

Resolves #8555 
When the axis are set by a presenter, the oxyplot AbsoluteMinimum and AbsoluteMaximum are now set that restrict how far someone can zoom out. This also means that if someone zooms in, they can now zoom back out to the starting bounds and reset the view correctly. Previously you'd have to click off the graph node to get back to the normal view.
While in that code, I also added a cursor change for when the mouse is hovering over an axis, to show that you can zoom a particular axis when the mouse is over it, which I don't think people realised before (and was noted as a bug in the issue).

8555 Limited zooming out on graph

---

Examples/RedClover.apsimx

I used the one in the redclover validation. They have the same user interface except now the user needs to specify fractions of biomass in each organ to remove. Previously these were defaults in each plant organ. It was decided to expose these to the user in the hope they would know how to set them.
Resolves #8353

Replaced the defoliation manager in redclover example 

---

APSIM.Cli/Program.cs
ApsimNG/Presenters/MainPresenter.cs
Models/Core/Apsim710File/Importer.cs
Tests/UnitTests/ImporterTests.cs

When importing old apsim files, don't stop import on manager compile errors.
Resolves #7300

Importing old apsim files works when manager errors encountered

---

Models/Soils/Chemical.cs

Resolves #8635
Chemical's GetStandardisedSolutes function uses a clone to make a copy of the solute to do layer mapping with. However, if the physical model link has not been set yet, then the StandardisedSolute cannot look up the layer structure. This change gives it back a reference to the parent soil so it can find the other models it needs.

8635 Standardised Solutes has link to parent

---

Models/Core/ApsimFile/Structure.cs

Resolves #8649 
After making changes to the unique name function, rename was seeing the name of the node it was renaming and adding a 1 to the new name every time. Rename now sends a temporary clone to unique name function and set the node name to empty so it can't conflict while it's testing.

8649 Stop rename from putting 1 on the end of everything

---

Examples/Optimisation/CroptimizRExample.apsimx
Models/Core/ApsimFile/Converter.cs
Models/Models.csproj

Resolves #8632
A few problems were encountered here:
- The converter to v171 would add a minSoilTemperature node even if one already existed with that name and cause a duplicate
- The croptimizR example would not run on linux because it was missing a .net library reference
- The croptimizR example's weather did not have have a %root% reference so when you saved it elsewhere it didn't run.
Fixed all these issues and was able to run the sim from the issue and the croptimizR example.

8632 CroptimizR Fixes

---

ApsimNG/ApsimNG.csproj

Resolves #8659
Not sure why this is throwing now, but it just needs a reference to that package in the NG packages list.

8659 Added packaging package

---

Models/Core/Apsim710File/Importer.cs
Models/Core/ApsimFile/Converter.cs

Resolves #8642 
There were other date formats accepted by classic's operations module (doy year), but I am not sure how widely used they were. I split date conversion into its own method so it will be easy to add them if desired. 
Also, not sure which file format version SwimWaterTable was removed in, so I stuck its deletion after the converter handles something with SwimSolutes.

8642 import issues

---

APSIM.Shared/Utilities/DBMerger.cs
APSIM.Shared/Utilities/SQLite.cs
Models/Storage/DatabaseTableDetails.cs
Models/Storage/WriteTableCommand.cs

Resolves #8533
Resolves #8625
It was possible for one thread to try and clean an sqlite database while another was still trying to read or write causing two transactions to try and run at the same time. SQLite would throw an exception with a variety of names when this happened.
Solution was to add a locking mechanism to the Begin and End calls to only allow one thread at a time to do a transaction, and then encapsulate the uses of those functions with try...finally blocks so that the locks would always unlock if and respond with the error message if an exception was thrown.

8533 Fixed "Not An Error" Exception

---

Models/Management/Manager.cs

Resolves #8673
To fix a file that was opened on the previous version and has Script children, open the file, save and close it and then when it's reopened everything should be correct again.

8673 Scrip Children Fix

---

Models/Soils/SWIM/Swim.cs

Resolves #8626 
The canola model has a canopy of type EnergyBalance under the shell organ, however when using swim, it cannot find the root plant node of canola when measuring the canopy.
I changed it to search for ancestors of type IPlant instead of just looking at the parent of the canopy, and that seems to have solved this error and lets swim work with canola.
@hut104 : It's not a big change, but you might want to check this before merge since it is a change to the swim code.

8626 Swim with Canola Error

---

Models/Core/Apsim710File/Importer.cs

Resolves #8681 
Pasting the data on to the new Solute objects seems to allow it to stick around through the conversion process.

Add method to copy EXCO and FIP data to NextGen.

---

ApsimNG/Presenters/GraphPresenter.cs

Resolves #8699 
In the axis setup Convert.ToDouble was throwing an exception when given a string value. String axis are handled elsewhere, so if a string is given here, it should just be set to 0 and not give an error.

8699 Stops exception thrown when using string axis

---

.gitignore
.vscode/launch.json
.vscode/tasks.json
ApsimNG/ApsimNG.csproj

Resolves #8764 
Some of these already existed in the repo from other vscode users, but this will let us have a unified set of configuration options for apsim debugging through vscode. I've added a ApsimNG: Debug config option that does a clean and build for debugging as @ric394 and I were encountering times when vscode wouldn't use the latest code changes when it built and ran without cleaning.

8764 Sharable vscode configuration files

---

ApsimNG/Presenters/SoilDownloadPresenter.cs
ApsimNG/Views/TreeView.cs

Resolves #8773
Two bugs here. One was a selection bug after adding a soil where a value could be null. The other was that soils with spaces at the end of their names broke the locator and make it impossible to interact with the soil.
Fixed both errors.

8773 Soil Download Errors

---

Models/Core/ApsimFile/Converter.cs

Resolves #8773
Some APSoil soils have NaN values in their Rocks array, this seems to happen when the physical thickness is different from the chemical thickness (when chemical has less elements). So I added a check to turn those NaNs into 0s in converter 65. 
I also noticed that it checked the length of the rocks array against physical, but then if it was less, set the rocks array length to the chemical length instead. This caused a crash in the remapping, as it didn't resize when it should have, as rocks needed to match the chemical thickness length, not physical in MapConcentration.
Seems to import the broken APSoil soils correctly now.

8773 NaN Correction and mapping length fix

---

ApsimNG/Utility/SettingsDialog.cs
ApsimNG/Views/MainView.cs
ApsimNG/Views/PropertyView.cs

Resolves #8810
Resolves #7581
Moved OSX dark mode check to settings panel instead of property view. This also fixed the syntax highlighting as well.

8810 Fixed PropertyView bug

---

ApsimNG/Presenters/DataStorePresenter.cs
ApsimNG/Resources/Glade/DataStoreView.glade
ApsimNG/Views/Sheet/PagedDataProvider.cs
Models/Storage/DataStoreReader.cs
Tests/UnitTests/Sheet/PagedDataProviderTests.cs

Resolves #8721
Resolves #8519
The rowid's were stored in a temporary table that was then used to get out a small subset of the entire data for the presenter. However, when they were stored (which happened every time the datastore was opened in the gui), they were not sorted and just broke the sorting that was supposed to happen.
I added an OrderBy to that sql code and simplified the part where it pulls out 50 rows and now it gets the correct 50 rows out for that offset into the data.
While I was there, I then also added a dropdown to the interface to allow sorting by any column. By default it will do a simulationID and Clock.Today, but this just gives the user the ability to sort on whatever column they want specifically.
These changes actually improved the performance, as now it only …

8721 Added OrderBy to DataStore presenter

---

ApsimNG/Presenters/ProfilePresenter.cs
ApsimNG/Presenters/WaterPresenter.cs
Models/Soils/Water.cs

Resolves #8832
The graph would draw from the crop LL to initial water value even if the initial water was relative to LL15 (which made it go backwards). This change makes the SoilCrop always colour in from LL15 so that you can see where the crop LL goes above and below the actual set water values.

8832 Fixing Water Graph On SoilCrop

---

ApsimNG/Presenters/ManagerPresenter.cs

Working on #8873
This issue isn't a bug, it just hasn't been implemented yet. This PR just hides the reformat code option so that nobody tries to use it thinking it will work.
Issue changed to improvement, we'll need to come back and sort this out properly in the future.

8873 Hide unfinished reformat option

---

.vscode/launch.json
Models/Main.cs

Resolves #8862
We use the CommandLineParser nuget package to handle command line arguments. It currently has a bug with the help and version auto-arguments that causes it to always print an error when those are used. 
https://github.com/commandlineparser/commandline/issues/630
I've basically done the same thing as suggested in that issue which is to just not print out the error on those two arguments. They shouldn't throw an error anyway and do still work.

8862 Version and Help cmd errors

---

APSIM.Shared/Utilities/DataTableUtilities.cs
Models/Utilities/GridTableColumn.cs

Resolves #8856
There was a comment next to the date parsing with "todo" that was causing an exception in the TreeProxy table where dates were used. So I finished that work up and the TreeProxy table can now be edited again.

8856 Fixes date crash from TreeProxy table

---

ApsimNG/Views/TreeView.cs

Resolves #8865
When showing a manager script, the script would grab the focus of the keyboard and block out keyboard controls for the node in the tree. This just adds a check to see if the double-click rename node has focus, and if not, give it focus so that you can click on the node to give it back keyboard focus without it going straight to renaming the node.

8865 Allow keyboard on manager node

---

Models/Management/FarmEconomics.cs

Resolves #8867
Adds more meaningful summary messages as well.

Stop econ data being wiped in every simulation

---

Models/Core/Simulation.cs
Models/Report/Report.cs
Models/Storage/CleanCommand.cs
Tests/UnitTests/Report/ReportTests.cs

Resolves #8838 
There were two things happening here. 
One was that the _Factors table was not being cleared at the start of a run, so running a simulation multiple times meant the table would just keep growing each time. That is despite having comments saying it should be cleared, so I added it to the list with _Messages and _IntialConditions to be cleared at the start of a run.
Then for the repeated lines, it turns out the factors were written for each report instead of for each simulation. So if a simulation had 4 reports, it would write the factors in 4 times to the table. To fix this I moved the code from Report over to simulation, however that may not be the most appropriate place for it, so would like some feedback.

8838 _Factors table fixes

---

ApsimNG/Presenters/ManagerPresenter.cs

Resolves #8859 
Compiling the script caused the property presenter to be looking at an outdated reference. Fixed that bug and did a general cleanup on the manager presenter.

8859 Manager Parameter Saving

---

Models/Agroforestry/TreeProxy.cs

Resolves #8856
A bad line of code was adding an empty row in when it saved. Added code to fix those empty lines and fixed the bug that was causing them.
Graphs are also now working again.

8856 TreeProxy Spatial Grid fix

---

APSIM.Shared/Utilities/WebUtilities.cs

Resolves #8893
Server is back up again now so it's a bit hard to test this PR. But next time it goes down it should now respond with a useful error message instead of trying to parse a html page.

8893 Check if an error page was returned

---

ApsimNG/Presenters/DataStorePresenter.cs
ApsimNG/Presenters/ExplorerPresenter.cs

resolves #8897 
- If a user clears the report filter field without pressing enter or clicking off the field, the temporarily saved report filters are not overwritten with "". This makes the deleted text reappear in the field.
- Link the saving of report Filters to the reportFiltersFields changed event rather than leave event.

Row filters now get saved appropriately

---

Models/Main.cs
Models/Options.cs
Tests/UnitTests/CommandLineArgsTests.cs

resolves #8480 
- Command line will have the option to modify the Verbosity level of the summary node from the command line.
`Models.exe file.apsimx --log error`
`Models.exe file.apsimx -l all`

Added log switch to command line 

---

Models/Graph/GraphPage.cs
Models/Graph/SeriesDefinition.cs
Tests/UnitTests/Graph/SeriesTests.cs

Resolves #8824 
This does fix the problem and forces an experiment factor to take prescience over a column from the datastore, but I want to do more testing on side effects this might have before it's merged.
I also added in a new exception message to tell you when you put a graph under a simulation that is under an experiment. Previously the message didn't help explain how to fix the problem.

8824 Factors and Data Columns

---

Models/Soils/SWIM/Swim.cs

Resolves #8941
Will check the FIP and EXCO arrays for values before trying to use them and give an error message if they can't be read.

8941 Added SWIM solute error message

---

ApsimNG/Presenters/TreeProxyPresenter.cs
Models/Agroforestry/TreeProxy.cs
Tests/UnitTests/Plant/TreeProxyTests.cs

Resolves #8856
I accidently flipped the temporal and spatial displays in the last fix, so I've reverted that here. I also checked that the provided simulation was able to edited and ran and it seems to be correct now.
Hoping this is the final fix this needs. We might need to look at a new structure for the TreeProxy data down the line as it doesn't fit into our GridTable system very well and needs a lot of converting work at the moment to make it work. That's where a lot of these bugs are coming from.

8856 Tree Proxy Revert and Fix

---

ApsimNG/Presenters/ProfilePresenter.cs

resolves #8906 
- Adds clearer explanation to physical nodes warning label.
- Makes the text red for better recognition.

make physical label red and add further explanation

---

Models/Core/ApsimFile/Structure.cs
Models/Core/Model.cs
Models/Soils/Nutrients/Nutrient.cs
Tests/UnitTests/Core/ApsimFile/StructureTests.cs
Tests/UnitTests/Core/ModelTests.cs

resolves #8943
- Extra checks have been added to prevent this bug from occurring.
- `Models.cs` was updated to allow models with no `[ValidParent()]` attributes to be handled properly.
- Tests updated to work with new functionality.
- `Nutrient`'s  had NutrientPatchManager added as valid parent.

Context menu allows pasting any model bug fix

---

Examples/Canola.apsimx

resolves #8958
- The canola example had the value `CanolaSoil` set for RelativeTo variable. This caused an issue where when searching for an appropriate CropSoil for the canola crop, it would be searching for CanolaSoilSoil. As the string `soil` is appended to the search string.

Fix relativeTo value in Canola example

---

Models/Core/ScriptCompiler.cs

Resolves #8956
Needed to provide a specific option to the emit step of compiling so that it will always output a cross-platform portable pdb 'file' with the symbols for a manager script.
It also had code in there to output the dll and xml for a script to %TEMP% when running the gui, however these files weren't actually used for anything (the code and pdb were loaded from data buffers) so I've disabled that with this so we aren't making hundreds of little script files that aren't used every time we run a simulation.
Have tested that System.Diagnositics.Debugger.Break() works on my system, so this should be good to go.

Found the correct option eventually

---

.vscode/launch.json
.vscode/tasks.json
Models/Core/ScriptCompiler.cs

Resolves #8956
As I've looked into how to make this work, I have also been doing a general cleanup of the script compiler code. Removing references to compiling VB script, making sure settings were right on the compiler and recreating Visual Studio's method for debugging in VS Code so we ca have proper breakpoints working.
I've also updated the launch.json and task.json to hopefully speed up and improve the general compiling of apsim so it's closer to what we are used to. Please keep on eye on this in case there is a problem.

8956 VSCode Breakpoints working in Manager Scripts

---

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx

Resolves #8977
The trigger will now not re-trigger during the delay to fertilizing, and an additional checkbox has been added so that it can be restricted to once per sowing or not. If not, the trigger can be fired again if the same conditions are met again after the fertiliser is applied.

8977 Updated "Fertilise when variable reaches threshold" script

---

Models/Soils/Water.cs

resolves #8993
- When calculations for various water properties is taking place water would search for a physical model located within a Simulation model. This is ok for water models that are descendants of a Simulation but not for ones that descendants of Experiments/Factors.
- A method has been created to find CropSoils appropriately.

Fix Water RelativeTo Bug for Soils in an Experiment

---

Models/Core/ScriptCompiler.cs

Resolves #8995
Visual studio needs a different setup to work than code, this allows both to debug correctly. Checked that manager debugger.break() works on both VS code and VS studio.

8995 Visual Studio Manager Fix

---

ApsimNG/Views/GraphView.cs

Resolves #9059 
I put the wrong index into the string array when fixing a bug here a few weeks ago, that has been fixed. I also found an existing bug with a string not being found that I solved as well.

9059 Graph with String axis fixed

---

ApsimNG/Presenters/ProfilePresenter.cs

resolves #8637
- The soil crop water graph used to  incorrectly show the LL relative to physical.LL15.
- The soil crop water graph now correctly shows the LL relative to the appropriate crop.LL

soil crops now show graph with PAW relative to the crop LL

---

DeepCloner.Core/DeepCloner.Core.csproj

Resolves #9154
After having a go at resolving the warnings, it's not really worth it. All of them are just complaints that a variable may be null when passed or used, and changing one causes a cascade of changes across the program.
So I've just silenced them for now so it doesn't bloat out our build messages. I also turned on "Treat Warnings as Errors" to make DeepCloner consistent with the rest of the apsim projects.

9154 Silence DeepCloner Warnings

---

Models/Core/ApsimFile/Converter.cs
Tests/UnitTests/Core/ApsimFile/ConverterTests.cs

Resolves #9116 
When you download an ASRIS file, the node sits under a parent, and then when using Models.exe --upgrade, it can't find the soil to upgrade it correctly. This fixes that.
It also changes the name of the CERESSoilTemperature node that is added to just be "Temperature" to match our other code.

9116 ASRIS xml format finds soil node

---

ApsimNG/Views/PropertyView.cs
Models/PostSimulationTools/ExcelInput.cs

Resolves #9052
Makes the input fields on the ExcelInput model into multi-line text boxes. Much easier to read now than one big long list in something like the Wheat validation.
I tried to avoid changing the model as much as possible here and do it all through GUI changes, as the underlying structure was already suitable for this, it just needed to be displayed better.
Might be worth pulling and testing as a GUI change though before it's merged.

9052 ExcelInput Multiline

---

ApsimNG/Views/BubbleChartView.cs
ApsimNG/Views/DirectedGraphView.cs

Resolves #9187
Not sure why GTK has suddenly stopped respecting the size of the drawing area in the paned window (maybe has to do with #9149 changing to the newer Paned object instead of HPaned and VPaned).
This change just gives the drawing area a default size so that it doesn't get squished.

9187 Unsquash Rotation Manager Presenter

---

ApsimNG/Views/ListView.cs

resolves #9188
Added check to ListView to stop hard crash in Experiment
- This checks if the DataTable has a Report-specific DataTable column before invoking drag start events

Experiment drag bug fix

---

ApsimNG/Views/TreeView.cs

resolves #9075
- Note: Does not solve the issue but instructs user on what to do when this error occurs.
- There's a lot going on here and will require some refactoring in the future to resolve correctly. Right now, it's not worth the time spent to correct.
- I'm not a fan of the manual memory management going on in the whole drag and drop process and I think it should be done in a more simple and robust manner.

Arithmetic overflow exception workaround for drag/drop of models

---

Models/Core/ConfigFile/ConfigFile.cs
Tests/UnitTests/CommandLineArgsTests.cs

resolves #9225 
Fixes an issue where if you had an add command in a config file such as `add [Simulation].Zone Soil`, the command would not work as intended. This has now been corrected.

CLI add command now works correctly with parent nodes with children

---

ApsimNG/Resources/Glade/WaterView.glade

Resolves #9195, but only in a minimalist way.

Give WaterView grid only the space it needs.

---

Models/Core/ConfigFile/ConfigFile.cs
Tests/UnitTests/CommandLineArgsTests.cs

Resolves #9258
To provide a filepath instead of a value in the commands txt, you can set the value like so:
```
[Simulation].Name=mytextfile.txt;
```
It will look for a semi-colon at the end (like when you do a replace action with a node from another file) and if a file with that name exists. If both are true, instead of using the text in that line, the text from the file is read in instead and entered as the value.
This lets you provide multi-line string inputs and larger values from a separate file instead of having to get it all into the commands.txt
A unit test was also created for this behaviour.

9258 Commands system Filepath for value

---

APSIM.Interop/Documentation/Extensions/ParagraphExtensions.cs
APSIM.Interop/Markdown/Renderers/PdfBuilder.cs
Models/Utilities/Extensions/FileExtensions.cs
Tests/UnitTests/Core/Run/GenerateApsimXFilesTests.cs
Tests/UnitTests/Interop/Markdown/Renderers/Blocks/ListBlockRendererTests.cs
Tests/UnitTests/Interop/PdfRendering/ParagraphExtensionsTests.cs

resolves #9243
Many of the pdf and markdown tests were inappropriately using Environment.NewLine when encountering a line ending. It was better to handle these with a concrete "\n" which works on both platforms.

9243WinOSFailingTests

---

Gtk.Sheet/Sheet.cs

resolves #9267
When setting the column widths in Sheet, if there was a single data row, the data rows columns were not included in the process of determining column width.
This meant that if you had a fairly short column header like 'Es' data would be hidden, if the data was longer than the header.
I made sure that when there is a single data row, that it always gets included for column width setting.

Put protection in for when there is only one row in the DataStore when setting column widths

---

ApsimNG/Presenters/SoilDownloadPresenter.cs

resolves #8864
Soils were being downloaded that did not contain a name. The names were being modified and if missing, caused a object reference exception.
Put protection around the offending code.

Add protection for when soils come in with no name

---

ApsimNG/Presenters/GridPresenter.cs

Resolves #9298
CroptimizR property changes don't need to update the grid as it passes back a non-IModel. So this just adds some protection to the grid presenter so it doesn't try and update the grid with a type it can't handle.

9298 Add protection to GridPresenter

---

ApsimNG/Interfaces/IEditorView.cs
ApsimNG/Views/EditorView.cs
ApsimNG/Views/ManagerView.cs

resolves #9278
This was a read-only issue.
This checks for a vertical scrollbar in the managers editor (meaning the script is quite long) and makes it do buffer checks before making text writable.
If however a manager's editor does not have a vertical scrollbar it will skip buffer checks and make the text writable.

Manager read only bug fix

---

ApsimNG/Views/ManagerView.cs

Resolves #9302
Previous fix would cause scrollbar to not show all contents when first opening a script. This PR reverts the code so that it again has a timer based system when it first loads so that it can refresh the scrollbars after the text buffer is fully loaded.

9302 Manager Fix loading

---

Models/Soils/SWIM/Swim.cs

Working on #9327 
SWIM now avoids calling TimeToMins unnecessarily.

Switch SWIM's time internal representation.

---

APSIM.Shared/Utilities/DateUtilities.cs
Tests/UnitTests/UtilityTests/DataUtilitiesTests.cs

Resolves #9367 
The regex used for detecting an ISO date was not flexible enough to see it when 2000-1-1 zeros were missing from the month and day. Fixed that and added unit tests for that edge case.

9367 ISO Date fix

---

APSIM.Server/ZMQ+msgpack/APSIM.ZMQServer.csproj
Models/Models.csproj

resolves #9387
resolves #9384
A missing package update was not allowing APSIM to build. This fixes the error that prevented building.

Update package references for MessagePack in required projects

---

ApsimNG/Utility/Configuration.cs
ApsimNG/Utility/SettingsDialog.cs
ApsimNG/Views/GraphView.cs

Resolves #9352
Adds a graph size option into the settings menu (settings are in the top bar on the first screen in apsimng). This then defines how big the graph should be when copied out of apsim.
Considered a few options for this, but this is the easiest way to make it completely customizable for whatever size and formatting users want in their graph, and still making it consistent every time they copy a graph. It will still default to 800x600 currently, but that can now be changed.

9352 Graph Size options

---

Models/CLEM/Activities/CLEMActivityBase.cs
Models/CLEM/Activities/CropActivityManageProduct.cs
Models/CLEM/Activities/LabourActivityTask.cs
Models/CLEM/Activities/PastureActivityManage.cs
Models/CLEM/Activities/ResourceActivityProcess.cs
Models/CLEM/Activities/RuminantActivityMove.cs
Models/CLEM/Common.cs
Models/CLEM/Groupings/RuminantFeedGroup.cs
Models/CLEM/Resources/LandType.cs

Resolves #9456
This fixes a missing harvest of a mixed/intercrop 2nd crop while labour allocation was ok
It also addresses an issue where an activity requested land after another activity was assigned all unallocated land.

Fixes missing harvest of 2nd crop in mixed cropping (CLEM)

---

APSIM.Documentation/Program.cs
APSIM.Documentation/WebDocs.cs

Resolves #9493
Need to keep the code for generating the old docs files until we are ready to put the new server live, otherwise the netlify site breaks.

9493 Restore code to generate old docs files

---

Models/Soils/MultiPoreWater/WEIRDO.cs

Resolves #9480
The gui has to call the PAWC and PAWCmm properties in weirdo, but these won't work if the model isn't linked. Following the same structure as the Water model (which also has this problem), if the model isn't linked it will find the Physical model it needs when the gui asks for it.

9480 Link Physical for WIERDO gui

---

APSIM.Documentation/WebDocs.cs
Models/Core/ApsimFile/FileFormat.cs
Models/Core/Run/SimulationGroup.cs
Models/Management/Manager.cs
Tests/UnitTests/Manager/ManagerTests.cs

Working on #9495
Manager scripts are now only compiled at initialisation if it is being loaded in a background thread. This makes them pre-load in the gui, but not preload for documentation or commandline uses. If you run the sim and it hasn't been preloaded, it will then compile it before running (there is a check for that in manager already).

9495 InitialiseModel now controls Manager scripts being compiled at init

---

APSIM.Cli/APSIM.Cli.csproj
APSIM.Documentation/APSIM.Documentation.csproj
APSIM.Interop/APSIM.Interop.csproj
APSIM.Shared/APSIM.Shared.csproj
ApsimNG/ApsimNG.csproj
Gtk.Sheet/Gtk.Sheet.csproj
Models/Models.csproj
Tests/UnitTests/UnitTests.csproj

Resolves #9478 
Doesn't fully resolve the underlying issues, but gives warnings rather than errors, allowing developers to update Visual Studio and still continue being able to build APSIM. Eliminating the warnings can be treated as a new separate issue (or issues).

Treat NU1902 and NU1903 as warnings rather than errors.

---

ApsimNG/Presenters/RunOnCloudPresenter.cs
ApsimNG/Resources/Glade/RunOnCloudView.glade

Resolves #9546 
This pull request fixes the immediate problem of an application crash, but could use a bit of refactoring since it places too much "view" logic in the "presenter". I think the refactoring can be addressed later with the issues listed in #6371,

Replace ComobBox with a Treeview for selection of Apsim version.

---

Setup/net8.0/windows/buildWindowsInstaller

Resolves #9503
Some of the paths didn't link correctly in the windows script, this fixes it.

9503 Updating windows installer paths

---

APSIM.Shared/Utilities/PathUtilities.cs
ApsimNG/Presenters/MetDataPresenter.cs
ApsimNG/Resources/Glade/TabbedMetDataView.glade
ApsimNG/Views/TabbedMetDataView.cs
Models/Climate/Weather.cs

Resolves #9248
Resolves #7120
This just tidies up the weather presenter/view so that users can see the filename, relative path and full path for the weather file they have selected. It also appends %root% to the start of the weather path if the simulation is using an example weather file, which previously saved an absolute path.
This should help with making sure the weather files are linked correctly when moving between people/computers, and gives a better idea to the user about why the path might be wrong and where the file should be.
Closing the 9248 as this addresses adding %root% to example weather files, and closing 7120 because we did move to a relative path system for this if the file is alongside/under the simulation, and this PR just helps illustrate that.

9248 Fixes Pathing in weather view, adds relative path alongside full path

---

APSIM.Shared/Documentation/CodeDocumentation.cs
APSIM.Shared/Utilities/DataTableUtilities.cs
ApsimNG/Presenters/DocumentationPresenter.cs

Resolves #9593
Resolves #9594
The fixes to get the Documentation View working again made it a little slow, so this improves the experience a bit. A cache is now used for method/variable lookup so it only needs to go loading the xml once, and the page load is split into 4 steps so it load gradually instead of waiting for everything and loading all at once.
Also fixed a bug in the datatable to markdown code that was causing newlines to break tables in the view.

9593 Documentation View Fixes

---

ApsimNG/Classes/CustomScriptCompletionProposal.cs

Resolves #9631 
This prevents manager completions from crashing the UI. The completion images still fail to properly display (as they did before) but I don't think that is an APSIM issue.
I favor making the assembly reference explicit here rather than relying on the behavior of null as first argument even though this wouldn't get inlined.

Quick fix to prevent Manager completion crash.

---

Models/CLEM/Extras/Transmutation.cs
Models/CLEM/ZoneCLEM.cs

Update validation rule and call Summary.WriteMessagesToDataStore() to ensure database is up to date before checking for validation errors.
Resolves #9644

Ensure CLEM.Transmutation.PacketSize provided is greater than 0

---

Prototypes/WheatSimpleLeaf/SimpleLeafImplementation/.ipynb_checkpoints/TempCleanup-checkpoint.ipynb

working on #7623 
Removed filters from two of the top level validation graphs.
Made all file pointers in wheat.apsim full paths (%root%\\Tests\\Validation\\Wheat\\) so wheat.apsimx can be duplicated in another location (for testing the simple leaf model) but still finds all the necessary files to run.

A few more tidy ups

---

.gitignore

resolves #9688
- add .env files to .gitignore to prevent sensitive information from being tracked
- update the Wheat documentation link for accuracy.

Update .gitignore and fix Wheat documentation link

---

APSIM.Documentation/WebDocs.cs

resolves #9516
References were being added as a nav bar element even if a references section was not present. This has now been corrected.

fix: removes references from doc page navbars where references is not a section in the page

---

Gtk.Sheet/Sheet.cs
Gtk.Sheet/SheetScrollBars.cs

resolves #9509
- this fixes an issue where the report table was not able to be fully seen because the horizontal scrollbar would not allow navigation to the end of the table.
- Note that if your column is too large for the scale of the program it will still be truncated as only whole columns can be viewed with GTK

fix: make sheets allow full table view via horizontal scrollbar

---

Models/Soils/SWIM/Swim.cs

Protect against NaNs in SWIM when using Log10 functions.

---

Models/Core/ApsimFile/Converter.cs

Skip doOutput when lowercasing arguments.

---

ApsimNG/Presenters/DocumentationPresenter.cs
ApsimNG/Presenters/GenericPresenter.cs

resolves #9697
Add a line at the top of the view to show the simple model type, enhancing clarity for users.
@par456 what do you think about this?

Display model type in DocumentationPresenter and GenericPresenter views

---

Models/Core/Apsim710File/Importer.cs
Tests/UnitTests/Core/ApsimFile/ConverterTests.cs
Tests/UnitTests/Core/ApsimFile/SoilMissingSolutesAndInitialWater.apsim
Tests/UnitTests/ImporterTests.cs

Resolves #9727 
Refactored the importer solutes code to handle if solutes is missing and give the new solutes the default values and layer structure from Water.
Also added default value of 100% full for initialwater if that node is missing from the apsim file. All defaults are based on what Apsim 7.10 uses as defaults for components when added new.

9727 Apsim Importer can handling missing soultes/initialwater

---

APSIM.Shared/Utilities/ExpressionEvaluator.cs

Resolves #9767 
When pasting from excel, these can be inserted.

Remove tabs in expression evaluator equations.

---

Models/Resources/Barley.json

resolves #9794 
Update the expression for Barley model protein calculation to use a divide function for greater protection against divide by zero issues

Fix protein expression calculation in wheat models

---

ApsimNG/Presenters/CheckpointsPresenter.cs

resolves #9790
Checkpoint presenter just needed to initialise the menu description args (context menu options) with an enabled option set to true to make it appear like it used to.

fix: add property to menu description args in checkpoint menu to show the 'show in graph?' option

---

Models/Climate/ControlledEnvironment.cs

Resolves #9705
Keeps the same behavior as before if the SubDailyTemperature field is unset.

Add ability to specify subdaily temperature values.

---

APSIM.Documentation/WebDocs.cs
Tests/UnitTests/Documentation/DocumentTests.cs

resolves #9804
Update citation processing to modify citation text from just a citation to a citation that is a link to the references section in the documentation. Add a test to verify this functionality.

Link citations to references in documentation

---

Models/Soils/WaterModel/CNReductionForTillage.cs
Models/Soils/WaterModel/Runoff.cs

Resolves #9724
Ready to merge. I removed the code from `RunoffModel` and tried to complete `CNReductionForTillage` in a way that does not need an extra event (`TillageCompleted`) to be published. If the event is implemented, these parameters can be removed from `RunoffModel` and moved to `CNReductionForTillage`. 
```
/// <summary>Cumulative rainfall below which tillage reduces CN (mm).</summary>
public double TillageCnCumWater { get; set; }
/// <summary>Reduction in CN due to tillage()</summary>
public double TillageCnRed { get; set; }
/// <summary>Running total of cumulative rainfall since last tillage event. Used for tillage CN reduction (mm).</summary>
public double CumWaterSinceTillage { get; set; }
```
In one example I used, this did not change results. The reason could be that …

Fix CN reduction for tillage

---

Models/Factorial/CompositeFactor.cs
Tests/UnitTests/Factorial/ExperimentTests.cs

resolves #9805 
Implement functionality to ignore lines that start with "//" in composite factor specifications, enhancing the parsing logic.

Add ability to ignore commented lines in composite factors specifications

---

Models/PMF/Phenology/Phases/BlankPhase.cs
Models/PMF/Phenology/Phenology.cs
Models/PMF/Phenology/Scales/ZadokPMF.cs

Resolves #9775
Rather than the approach Hamish used in #9781 to add a new phenology phase, ~~I've simply adjusted Phenology to return 'null' when the linked plant to it is not alive. It already returned null when phases weren't set or when the phase index was too big, so this shouldn't have too many knock on effects.~~
Then when other functions like getting the name, or emergence are called, they return sensible results if the phase is null.
Will test in validation and see what happens.

9775 Phenology Phase returns null when not alive

---

Models/AgPasture/PastureSpecies.cs
Models/PMF/Organs/GenericOrgan.cs
Models/PMF/Organs/HIReproductiveOrgan.cs
Models/PMF/Organs/Leaf.cs
Models/PMF/Organs/Nodule.cs
Models/PMF/Organs/PerennialLeaf.cs
Models/PMF/Organs/ReproductiveOrgan.cs
Models/PMF/Organs/Root.cs
Models/PMF/Organs/SimpleLeaf.cs
Models/PMF/Organs/SorghumLeaf.cs
Models/PMF/Plant.cs

Resolves #9809 
Organs have two Biomass component (Detached and Removed) to record daily values of biomass that are detached (going back to residue or FOM) or removed (harvested, taken off field). These were not being zeroed at the end of crop and thus making difficult to record these variables to track biomass fluxes.
I added a variable (hasJustBeenEnded) that is set to true on CropEnding and then used to zero the two Biomass components (OnDoDailyInitialisation).

Ensure detached and removed biomass are zeroed

---

Models/Management/BiomassRemovalEvents.cs
Models/Management/BiomassRemovalOfPlantOrganType.cs

resolves #9812
DataProvider requires models to have Display Attributes if they are to be displayed in a grid. I've done this for BiomassRemovalOfPlantOrganType.

Update display attributes for biomass removal properties

---

Models/Core/VariableProperty.cs
Models/PMF/Organs/Root.cs

Return an empty array rather than null if Zones are not yet initialised.

---

ApsimNG/Views/GraphView.cs

Resolves #9860
The graphing code produces Nan values in the x/y columns sometimes, and specifically with permutation experiments being graphed. When this happens, the Nan values get filtered out, and therefore the captions need to as well, otherwise the indexs don't line up.
This PR should fix it.

9860 Sim names on graphs works with permutations

---

ApsimNG/ApsimNG.csproj
Models/Models.csproj

Add GenerateRuntimeConfigurationFiles = True to csproj of APSIMNG and Models whivh have OutputType set as EXE
Resolves #9873

Adjust csproj settings to enable compile from empty build

---

Models/Soils/SoilCrop.cs

resolves #9880 
Only showing 1 decimal place is making evaluating soil libraries difficult. Changed this to 3 places.
@rcichota

Add more decimal places to the display of XF

---

Docs/content/Install/macos.md

resolves #9870
Clarify installation instructions for .NET on MacOS and add steps to modify the PATH if dotnet commands are not recognized.

Update documentation for .NET installation steps for MacOS

---

ApsimNG/Interfaces/MenuDescriptionArgs.cs
ApsimNG/Views/MenuView.cs

Resolves #9908
Eric found the problem and solved it in #9910 but the file where the fix was needed a refactor to get rid of stuff that wasn't needed. This included an interface IMenuView which was only used by one class, splitting MenuDescriptionArgs class into its own file and giving it a constructor to set its properties to default starting values instead of null.

9908 Refactor MenuDescriptionArgs to solve popup bug

---

APSIM.Documentation/Models/Types/DocSimulations.cs
ApsimNG/Classes/PropertyPresenterHelpers.cs
ApsimNG/EventArguments/NeedContextItemsArgs.cs
ApsimNG/Presenters/AddModelPresenter.cs
Models/Core/ApsimFile/Structure.cs
Models/Core/Folder.cs
Models/Core/Resource.cs
Models/Core/Run/SimulationDescription.cs
Models/Core/Run/SimulationGroup.cs
Models/Management/BiomassRemovalEvents.cs
Models/Optimisation/CroptimizR.cs
Tests/UnitTests/Documentation/DocumentTests.cs

Resolves #9864 
Rather than just solving this problem by putting yet another replacements check in where it was required, I did a small refactor instead.
I've added three functions under Folder that do the checking if a model is a folder that can be a Replacements, so that all the error checking and constraints we have on replacements is done in one place. 
New functions are:
- IsModelReplacementsFolder
- FindReplacementsFolder
- IsUnderReplacementsFolder
These are the 3 use cases in apsim for either checking if a folder is replacements, or to find the replacements folder, so now all references to replacements have to go through these functions. Not sure if this is the best place for it, I could see this in Structure instead, but that class is already quite large, and Replacements are …

9864 Simulation names don't conflict under replacements

---

Models/AgPasture/PastureSpecies.cs

Resolves #9921
The extra line seems to have been left behind when implementing the outputs for detached biomass. The duplication only happens on EndCrop. I believe this is something that is seldom used, luckily...

Remove duplicate instruction to return biomass

---

Models/AgPasture/SimpleGrazing.cs

Resolves #9930 
Now users can specify monthly minimum and maximum rotation lengths in TargetMass or Flexible grazing without triggering an “Index was outside the bounds of the array”.

Handle issue with rotation‐length in SimpleGrazing

---

Models/CLEM/Activities/CropActivityManageProduct.cs
Models/CLEM/Activities/PastureActivityCutAndCarry.cs
Models/CLEM/Resources/GrazeFoodStoreType.cs

Resolves #10022 
Adds new enum as property to allow user to select Add, Replace when reading in crop product data from input file.
Amount removed/destroyed is reported in ledger as "StoreCleared" transaction for complete accounting.

CLEM add switch to allow pasture and food store to be cleared on data import

---

Models/Core/VariableComposite.cs
Models/Core/VariableProperty.cs
Models/Management/Operations.cs

Resolves #10027
Initially I tried to make it so that VariablesProperties could only be written to if the setter was public, but this messed Links up pretty badly. property.GetSetMethod() is null for non-public setters (CanWrite && GetSetMethod() == null implies the existence of a non-public setter). This doesn't address other ways a user might get around visibility (cultivars and config files are two possibilities).

Operations no longer sets private properties.

---

APSIM.Shared/Graphing/Arc.cs
Models/CLEM/Activities/OtherAnimalsActivityBuy.cs
Models/CLEM/Activities/OtherAnimalsActivitySell.cs
Models/CLEM/Groupings/OtherAnimalsFeedGroup.cs
Models/CLEM/Resources/OtherAnimals.cs
Models/CLEM/Resources/OtherAnimalsTypeCohort.cs
Models/PMF/SimplePlantModels/ScrumCropInstance.cs
Models/Sensor/Spectral.cs

Resolves #10087
Some units were using System.Text.Json.Serialization rather than Newtonsoft.Json as the namespace for JsonIgnore.

Use correct namespace for JsonIgnore

---

APSIM.Core/ApsimFile/ManagerConverter.cs

Resolves #10208 
It looks like this keyword was missed when getting member declarations. In the future it might be useful to just have a set of keywords and compare instance names and type names against that.

Do not treat namespace declarations as members.

---

Models/Logging/InitialConditionsTable.cs

Resolves #10232
Not sure why this suddenly appeared, I wonder if the big refactor merged last week fixed an unknown bug that was stopping this.
Anyway, simple fix to just check if a string[] array index was empty before trying to convert it to a double, and avoiding that.

10232 Don't try to parse empty cells in array

---

.github/workflows/run-model-validations.yml

resolves #10305
This corrects the owner reference to the apsimplusr repo in the model validation GitHub workflow file.

correct the docker repo owner for apsimplusr

---

global.json

Resolves #10318
This was pinning apsim to a specific version of .net, removed to fix.

10318 Remove global.json

---

APSIM.Documentation/Models/Types/DocSubDailyInterpolation.cs
ApsimNG/Views/ExplorerView.cs
ApsimNG/Views/MarkdownView.cs
Models/Functions/SubDailyInterpolation.cs

Resolves #10360.
The problem was not with Dropdown widgets, but rather with excess space being used by the description above. There was already an attempt in ExplorerView.cs to deal with this, but because some layout in a Gtk TextView occurs using "idle" handlers rather than "event" handlers, that earlier fix did not always work.

Ensure Gtk has adequate time to display descriptions correctly.

---

APSIM.Shared/Utilities/SQLite.cs
ApsimNG/Views/DropDownView.cs
Tests/UnitTests/Storage/DataStoreReaderTests.cs

Resolves #10378 
The initial display is still rather slow when there are many items, but a wait cursor assures the user something is happening.
All items are listed and the scrollbar displays correctly.

Improve behaviour of DropDownView when dealing with long lists of items.

---

APSIM.Shared/Utilities/SQLite.cs

Resolves #10346
Continuing the patches for the SQLite error. It only seems to appear on the windows unit tests now, so hopefully this is the last fix needed to avoid those crashing.

10346 SQLite Error

---

APSIM.Core/Locate/Locator.cs
Tests/UnitTests/APSIM.Core/LocatorTests.cs

Resolves #10469
Bug was found in #10466 where the Physical node had been renamed and a function in Nutrient couldn't find it anymore.
This solves the bug in the locator and adds a unit test for that condition.

10469 Check model children types if searching by name fails

---

APSIM.Core/Locate/Locator.cs
Tests/UnitTests/APSIM.Core/LocatorTests.cs

Resolves #10471 
Split from #10438 so the locator changes aren't with the Oats validation changes.
Locator will now check if the text with [], matches a model name after failing to find an array property with that name.

10471 Locator finds model with brackets

---

Models/CLEM/Activities/RuminantActivityMilking.cs

Resolves #10517
Set Milking activity to manual and fire during the CLEMMilking event to ensure timing with suckling is correct

CLEM ensure milking activity happens during the milking event

---

.github/workflows/run-model-validations.yml

resolves #10523
Rather than url encode unsafe characters, this simply removes the [bot] suffix from the author string to prevent postats call failure in the model validation github workflow.
As mentioned in the linked issue, this prevented security and package updates fixes from completing.

Removes the string [bot] from the author string
