Models/Stock/stock.cs

working on #4617
Allow the setting of the Stock parameter file

Stock parameters

---

ApsimNG/ApsimNG.csproj
ApsimNG/Attributes/ContextMenuAttribute.cs
ApsimNG/Classes/PDFWriter.cs
ApsimNG/Commands/CreateFileDocumentationCommand.cs
ApsimNG/Commands/CreateParamsInputsOutputsDocCommand.cs
ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/ExplorerPresenter.cs
Docs/CreateDocumentation/Documentation.json
Docs/CreateDocumentation/Program.cs
Models/Clock.cs
Models/Core/Simulations.cs
Tests/Validation/Clock/Clock.apsimx

Add clock auto-documentation and refactored some doc code

---

Models/Core/ApsimFile/FileFormat.cs
Models/Core/ModelCollectionFromResource.cs

Allow users to add children to released models.

---

Models/Core/ModelCollectionFromResource.cs

Improved null handling in ModelCollectionFromResource

---

ApsimNG/Presenters/TablePresenter.cs
Models/Interfaces/IModelAsTable.cs
Models/Tests.cs

Fixed Tests model UI

---

Prototypes/Gliricidia/Gliricidia Validation.apsimx

Reduced N Fixation Rate

---

Jenkins/Installation/Jenkinsfile
Jenkins/deploy.bat

Only trigger netlify builds when a pull request is merged.

---

ApsimNG/Presenters/StockPresenter.cs
Models/Core/ApsimFile/Converter.cs
Models/Resources/AGPBrownTop.json
Models/Resources/AGPCocksfoot.json
Models/Resources/AGPKikuyu.json
Models/Resources/AGPLucerne.json
Models/Resources/AGPPaspalum.json
Models/Resources/AGPPhalaris.json
Models/Resources/AGPRedClover.json
Models/Resources/AGPRhodes.json
Models/Resources/AGPRyegrass.json
Models/Resources/AGPTallFescue.json
Models/Resources/AGPWhiteClover.json
Models/Resources/Barley.json
Models/Resources/Chicory.json
Models/Resources/Eucalyptus.json
Models/Resources/FodderBeet.json
Models/Resources/Maize.json
Models/Resources/Nutrient.json
Models/Resources/Oats.json
Models/Resources/OilPalm.json
Models/Resources/Plantain.json
Models/Resources/Potato.json
Models/Resources/RedClover.json
Models/Resources/SCRUM.json
Models/Resources/Slurp.json
Models/Resources/SurfaceOrganicMatter.json
Models/Resources/Wheat.json
Models/Resources/WhiteClover.json
Models/Stock/stock.cs

resolves #4434
Rename GenoTypes to Genotypes

Rename Stock property

---

APSIM.Shared/Utilities/ReflectionUtilities.cs
ApsimNG/Commands/AddModelCommand.cs
Models/Core/ApsimFile/Structure.cs
Tests/UnitTests/Core/ApsimFile/StructureTests.cs

Improved support for copying a simulations node into the UI.

---

Models/Core/ModelCollectionFromResource.cs
Tests/UnitTests/Resources/ResourceTests.cs
Tests/UnitTests/Resources/WheatModel.apsimx
Tests/UnitTests/UnitTests.csproj

Fixed bug where released models are saved in their entirety.

---

Models/PostSimulationTools/ExcelMultiInput.cs
Models/Storage/DataStoreReader.cs

Fixed table merging in ExcelMultiInput

---

Examples/SimpleGrazing.apsimx

Working on #4634
Includes Memo and an extra simulation for mixed species

 Tidying up SimpleGrazing example

---

Examples/SimpleGrazing.apsimx
Models/AgPasture/SimpleGrazing.cs
Models/Core/ApsimFile/Converter.cs
Models/Resources/AGPBrownTop.json
Models/Resources/AGPCocksfoot.json
Models/Resources/AGPKikuyu.json
Models/Resources/AGPLucerne.json
Models/Resources/AGPPaspalum.json
Models/Resources/AGPPhalaris.json
Models/Resources/AGPRedClover.json
Models/Resources/AGPRhodes.json
Models/Resources/AGPRyegrass.json
Models/Resources/AGPTallFescue.json
Models/Resources/AGPWhiteClover.json
Models/Resources/Barley.json
Models/Resources/Chicory.json
Models/Resources/Eucalyptus.json
Models/Resources/FodderBeet.json
Models/Resources/Maize.json
Models/Resources/Nutrient.json
Models/Resources/Oats.json
Models/Resources/OilPalm.json
Models/Resources/Plantain.json
Models/Resources/Potato.json
Models/Resources/RedClover.json
Models/Resources/SCRUM.json
Models/Resources/Slurp.json
Models/Resources/SurfaceOrganicMatter.json
Models/Resources/Wheat.json
Models/Resources/WhiteClover.json

Small changes to SimpleGrazing

---

ApsimNG/Interfaces/IStockView.cs
ApsimNG/Presenters/StockPresenter.cs
ApsimNG/Resources/Glade/StockView.glade
ApsimNG/Views/StockView.cs
Models/Stock/stock.cs

Stock component adding animal groups user interface working

---

ApsimNG/Presenters/AddModelPresenter.cs
ApsimNG/Presenters/ExplorerPresenter.cs
Models/Core/Apsim.cs

Need to take into account the model's resource name.
Resolves #4705

Fixed tree view icon name resolution algorithm

---

.gitignore

Don't ignore .csv files.

---

ApsimNG/Classes/PDFWriter.cs
ApsimNG/Commands/CreateParamsInputsOutputsDocCommand.cs
Docs/CreateDocumentation/Documentation.json
Models/Core/AutoDocumentation.cs

Tables in autodocs should wrap text

---

Tests/Validation/MicroClimate/MicroClimate.apsimx

Remove nutrient documentation from microclimate autodocs

---

Models/Plant/Phenology/Phases/GenericPhase.cs

Changed operator

---

Models/MicroClimate/MicroClimate.cs
Models/MicroClimate/MicroClimateZone.cs

Added threshold height option to MicroClimate for creating new layer

---

Models/Models.csproj
Models/Plant/Phenology/Scales/ZadokPMFWheat.cs
Models/Resources/Wheat.json

Wheat Heading

---

Models/PostSimulationTools/ExcelMultiInput.cs

Changes to excel multi input component

---

Models/AgPasture/PastureSpecies.cs
Models/Resources/AGPRyegrass.json
Models/Resources/AGPWhiteClover.json

Working on #4583 
PlantMinimumHeight was previously set at 300mm for both species. Now, with active competition in MicroClimate, the values were changed to 25mm for WhiteClover and 50mm for Ryegrass

Changed PlantMinimumHeight of Ryegrass and WhiteClover in AgPasture

---

ApsimNG/Presenters/PropertyPresenter.cs

PropertyPresenter should refresh the grid after model is changed

---

ApsimNG/Views/GridView.cs

Fixed report/CLEM grid colours in dark mode

---

Models/AgPasture/GenericTissue.cs
Models/AgPasture/PastureAboveGroundOrgan.cs
Models/AgPasture/PastureSpecies.cs

Fixed HarvestedWt from PastureSpecies when using SimpleGrazing

---

ApsimNG/Presenters/AddModelPresenter.cs
ApsimNG/Presenters/ExplorerPresenter.cs
Tests/UnitTests/ApsimNG/Presenters/AddModelPresenterTests.cs
Tests/UnitTests/ApsimNG/Utilities/UITestUtilities.cs
Tests/UnitTests/UnitTests.csproj

Fixed a bug in add model code

---

APSIM.Shared/Utilities/ApsimTextFile.cs
APSIM.Shared/Utilities/MathUtilities.cs

Added some extra math utilities for a weather data project

---

Models/Core/Apsim710File/Importer.cs

Fix importer for old apsim sims that have SWIM

---

APSIM.Shared/Utilities/DataTableUtilities.cs

Added some more DataTable utilities. Useful for managing weather files

---

ApsimNG/Classes/PDFWriter.cs
ApsimNG/Commands/CreateParamsInputsOutputsDocCommand.cs
Docs/CreateDocumentation/Documentation.json
Docs/CreateDocumentation/Program.cs
Models/Core/IVariable.cs
Models/Core/ModelCollectionFromResource.cs
Models/Core/Variable.cs
Models/Core/VariableComposite.cs
Models/Core/VariableExpression.cs
Models/Core/VariableMethod.cs
Models/Core/VariableProperty.cs

Changes to params-inputs-outputs autodoc

---

Prototypes/Grapevine/grapevine.apsimx

updated the budburst model

---

Models/Factorial/Experiment.cs

Experiment should be a scoped model

---

Models/Functions/LinearInterpolationFunction.cs

Linear Interpolation Autodoc

---

ApsimNG/Classes/PDFWriter.cs

Improved png file name uniqueness in auto-doc

---

Prototypes/Grapevine/grapevine.apsimx

working on #1292 
optimized the budburst target value

optimized the budburst target value

---

ApsimNG/Commands/RunCommand.cs
ApsimNG/Menus/ContextMenu.cs
Models/Core/Run/SimulationGroup.cs
Models/Core/Simulations.cs

Fixed checking of duplicate simulation names

---

Prototypes/Grapevine/grapevine.apsimx

working on #1292 
optimized the flowering and veraison target, and removed fruitset as it is an ambiguous phase

optimized the flowering and veraison target

---

Models/Core/Apsim710File/Importer.cs

Fix import old soils with missing values

---

APSIM.Shared/Utilities/MathUtilities.cs
Models/Report/ReportColumn.cs

Add a 'product' aggregator

---

Models/Resources/Nutrient.json
Models/Soils/Arbitrator/ZoneWaterAndN.cs

remove AvailableNO3 and AvailableNH4 from nutrient

---

Models/Soils/Standardiser/SoilDefaults.cs

Soil standardiser must standardise analysis' NO3N and NH4N properties.

---

Models/Soils/Nutrients/Nutrient.cs

fixed metadata

---

Models/Core/VariableProperty.cs

Fix to auto-doc object not set error

---

Models/Sensitivity/Morris.cs

Added some diagnostics to morris component.

---

Docs/CreateDocumentation/Documentation.json

Fixing doc list on web

---

APSIM.Shared/Utilities/SQLite.cs

Need to quote table names in sql queries

---

Examples/Tutorials/Lifecycle.apsimx
Models/Functions/VariableReference.cs
Prototypes/Grapevine/grapevine.apsimx
Tests/UnderReview/Chickpea/Chickpea.apsimx

Make VariableReference throw if can't find variable

---

Models/Core/VariableProperty.cs

Stop users indexing into element zero of an array in report

---

Tests/Validation/Eucalyptus/Eucalyptus.apsimx

Removed nutrient from Eucalyptus validation

---

ApsimNG/Commands/ChangeProperty.cs
ApsimNG/Menus/ContextMenu.cs

Allow users to set models read-only

---

Docs/CreateDocumentation/Program.cs

Reverted slash in auto-doc URL

---

Models/Plant/Organs/PerennialLeaf.cs

Protect divides in calculation of PerennialLeaf.LKE

---

Models/Weather/Weather.cs

update winter solstice calculation

---

Models/Functions/SupplyFunctions/RUECO2Function.cs

Lowered min acceptable co2 level to 300 ppm.

---

Models/Resources/Wheat.json

Moved wheat model from apsimx file to resource

---

Models/Models.csproj
Models/Plant/Arbitrator/OrganArbitrator.cs
Models/Plant/Arbitrator/PriorityArbitrator.cs

Grape vine development

---

Models/Plant/Plant.cs

Create SowingData in the constructor

---

Models/Core/ApsimFile/XmlToJson.cs
Tests/UnitTests/Core/ApsimFile/XMLToJSONTests_EnsureResidueTypesConverts.json

Fixed culture-related issue in xml to json converter.

---

Models/Sensitivity/Morris.cs

Morris should retry up to 10 times to generate paramter values.

---

Models/Core/Simulations.cs

Remove date from apsimx files.

---

ApsimNG/EventArguments/NeedContextItemsArgs.cs

Intellisense suggestions in report should be scoped

---

ApsimNG/Presenters/ProfileGridPresenter.cs

Implemented automatic empty row deletion in profile grids

---

ApsimNG/Views/GridView.cs

Fixed a few bugs in grids

---

ApsimNG/Presenters/GridPresenter.cs
Models/Soils/SWIM/SwimSoluteParameters.cs

Fixed some bugs in the swim UI

---

ApsimNG/Menus/ContextMenu.cs
Models/Main.cs

Allow /Edit option to insert models from an external file.

---

ApsimNG/Presenters/ProfilePresenter.cs
Models/Graph/Graph.cs
Models/Graph/Series.cs

Fixed a bug where profile graph doesn't appear

---

Models/Core/ModelCollectionFromResource.cs

Resolves #4855 
After discussion with @HamishBrownPFR we decided this would be the best solution to this issue.

Allow users to add editable crop models to a replacements node.

---

Models/Plant/Plant.cs

Resolves #4916 
This fixes errors when SimpleGrazing is used on PMF species

Changed unit from g/m2 to kg/ha of preRemovalBiomass of PMF species

---

Setup/apsimx.iss

Modify installer to handle non-administrator users

---

Models/Main.cs

Fixed bug in 'edit file' feature which reads the wrong file.

---

ApsimNG/Presenters/ReportPresenter.cs
ApsimNG/Utility/Configuration.cs
ApsimNG/Views/ReportView.cs

Report handle position should persist between restarts of apsim.

---

Models/Core/ApsimFile/Converter.cs

Fixed null error bug in converter.

---

Models/Main.cs
Tests/UnitTests/Core/ApsimFile/EditFileTests.cs

Improved edit file's model replacement capability

---

Models/AgPasture/PastureSpecies.cs
Models/Core/ApsimFile/FileFormat.cs
Models/Core/ModelCollectionFromResource.cs
Models/Plant/Plant.cs
Models/Soils/WaterModel/WaterBalance.cs
Tests/UnitTests/Resources/ResourceTests.cs
Tests/UnitTests/Resources/WheatModel.apsimx

Consider XmlIgnore and JsonIgnore when copying properties

---

Prototypes/Grapevine/grapevine.apsimx

working on #1822
removing the sowing operation and merged it with tree initialization

added variety options

---

ApsimNG/Presenters/InputPresenter.cs

Fixed file filter in input UI for reading csv files

---

Models/AgPasture/SimpleGrazing.cs

Added ProportionOfTotalDM to SimpleGrazing

---

Models/Stock/stock_intf.cs

resolves #4953
The othertag parameter now works correctly

Split events fixed

---

ApsimNG/Resources/Report.xshd
ApsimNG/Resources/SyntaxHighlighting/Report.xml

Added syntax highlighting to report for mean/stddev.

---

ApsimNG/ApsimNG.csproj
ApsimNG/Classes/PDFWriter.cs
ApsimNG/EventArguments/CustomDataEventArgs.cs
ApsimNG/Interfaces/IGraphPanelView.cs
ApsimNG/Interfaces/IGraphView.cs
ApsimNG/Presenters/GraphPanelPresenter.cs
ApsimNG/Views/GraphPanelView.cs
ApsimNG/Views/GraphView.cs
Models/Graph/GraphPanel.cs

More options for graph panel

---

Models/Functions/VariableReference.cs

Changed variable reference error message to include full path

---

ApsimNG/Utility/SoilDownloadDialog.cs

Soil downloader should be culture-sensitive

---

ApsimNG/Views/EditorView.cs

Added call to SetNotDirtyState when text is initially loaded.

---

ApsimNG/Commands/CreateFileDocumentationCommand.cs

When documenting a simulation, be sure to resolve replacements.

---

ApsimNG/Presenters/PropertyPresenter.cs
Models/Core/ModelCollectionFromResource.cs
Models/Core/Run/ModelReplacement.cs
Models/Core/Run/SimulationDescription.cs
Models/Soils/Soil.cs
Models/Soils/Standardiser/SoilStandardiser.cs
Tests/UnitTests/Core/Run/SimulationDescriptionTests.cs

UI fixes for handling of cultivars in replacements

---

Models/G_Range/G_Range.cs

Removed Description tag for LAI

---

Models/Resources/Wheat.json

Wheat FI renaming

---

Models/Storage/DataStoreReader.cs
Models/Storage/DataStoreWriter.cs

Fixed a bug which prevented old .apsimx files from being opened

---

Tests/Validation/Wheat/LN.met
Tests/Validation/Wheat/LV.met
Tests/Validation/Wheat/SN.met
Tests/Validation/Wheat/SV.met

Fixed units in some met files used in wheat test set

---

Models/AgPasture/SimpleGrazing.cs
Models/Plant/Plant.cs

Also fixed SimpleGrazing.GrazedDM variable.
Resolves #4992

Added reduce plant population to SimpleGrazing.

---

APSIM.Shared/JobRunning/JobRunner.cs
Models/Core/Run/Runner.cs

Resolves #4994, or at least I hope it does. I haven't seen the problem myself. @hut104 - let me know if this doesn't correct the problem.

Use lock when accessing SimsRunning

---

Models/Graph/DefaultPainter.cs
Models/Graph/Series.cs
Models/Graph/SeriesDefinition.cs

Fixed graphs with >1 checkpoint but no vary by settings

---

Models/Soils/SWIM/Swim.cs

Small changes to SWIM to fix old APSIM importing problems

---

APSIM.bib
Tests/UnderReview/Gliricidia/Gliricidia.apsimx

Change temperature responses

---

Models/Resources/Wheat.json

Clean up wheat phenology

---

APSIM.bib
Tests/UnderReview/Gliricidia/Gliricidia.apsimx

Gliricidia Autodoc additions 

---

ApsimNG/Classes/PDFWriter.cs
ApsimNG/Interfaces/IGraphView.cs
ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Presenters/LinearAfterThresholdPresenter.cs
ApsimNG/Presenters/MetDataPresenter.cs
ApsimNG/Views/GraphView.cs
Models/Graph/Series.cs
Models/Graph/SeriesDefinition.cs

Fixed marker size not having an effect on graphs

---

Prototypes/C4Maize/C4Maize.apsimx

Fixed some discrepancies in C4Maize test set

---

ApsimNG/Classes/Intellisense/EntityCompletionData.cs
ApsimNG/EventArguments/NeedContextItemsArgs.cs

Intellisense should show generic types using C# syntax.

---

Models/Factorial/Factors.cs

Factors should be a scoped model

---

ApsimNG/Views/HTMLView.cs

Resolves #3934 (as far as I can tell, anyway).

Fixed flicker in HTMLView in dark mode on windows

---

Tests/Validation/AgPasture/AgPasture.apsimx

Working on #4919 
Adding changes on SimpleGrazing for this smulation. Still needs the sensibility simulation

Updating AgPasture validation

---

Models/AgPasture/SimpleGrazing.cs

Trampling effect in SimpleGrazing

---

Models/Plant/Arbitrator/RelativeAllocationSinglePass.cs

Grape vine development  

---

Models/Plant/Organs/SorghumLeaf.cs
Models/Plant/Structure/Culm.cs
Models/Plant/Structure/LeafCulms.cs

Added LeafNo output to SorghumLeaf

---

Models/Graph/MultiDescriptorPainter.cs

Fix for Null reference in MultiDescriptorPainter

---

Models/Resources/AGPBrowntop.json

Fix AGPBrowntop again

---

Models/Plant/Organs/RootZoneState.cs
Models/Plant/Plant.cs
Models/Plant/PlantTypes.cs
Models/Plant/Structure/LeafCulms.cs

Implementing a skip-row configuration

---

ApsimNG/Classes/PDFWriter.cs
Tests/UnitTests/Storage/DataStoreWriterTests.cs

Resolves #5087 (I think)
Resolves #4796

When generating PDF files, always be explicit about page orientation.

---

Examples/CLEM/CLEM_Example_Cropping.apsimx
Models/CLEM/Activities/CLEMActivityBase.cs
Models/CLEM/FileCrop.cs
Models/CLEM/ZoneCLEM.cs

Fixed CLEM shortfall error with no Market 

---

Docs/content/Development/Contribute/SourceTree/Commit.md
Docs/content/Development/Contribute/SourceTree/GetSource.md

Resolves #5106 
I've removed references to APSIM.Shared and slightly tweaked some wording in other places.
Can change to working on if anyone thinks more changes are needed.

Removed APSIM.Shared instructions from git help info.

---

Models/Plant/OilPalm/OilPalm.cs

Move uncalled code into Sow method

---

Prototypes/Teff/Teff.apsimx

A few alterations to Teff re N dynamics and effects

---

Models/Stock/Genotype.cs

Added new parameters to stock genotype

---

Models/Core/Zone.cs
Models/Weather/SlopeEffectsOnWeather.cs

Fixed AspectAngle in SlopeAndAspect model

---

Setup/apsimx.iss

Have installer do (optional) file association.

---

ApsimNG/Presenters/MainPresenter.cs

Handle cancellation of application close more gracefully.

---

Models/Resources/Pinus.json

Copied Eucalyptus.json and called it Pinus.json

---

ApsimNG/ApsimNG.csproj
ApsimNG/Classes/PDFWriter.cs
ApsimNG/Presenters/MapPresenter.cs
ApsimNG/Views/HTMLView.cs
ApsimNG/Views/MapView.cs
ApsimNG/Views/WindowView.cs
Models/Functions/VariableReference.cs
Models/Map.cs

Resolves #3184
Note that if all markers are already visible onscreen, the map *shouldn't* zoom out.

Map should automatically zoom out to fit all markers

---

ApsimNG/Presenters/DataStorePresenter.cs

DataStorePresenter should inherit from GridPresenter

---

ApsimNG/Presenters/ProfileGridPresenter.cs

Profile Grid needs to update when child soilcrops are changed.

---

Tests/UnderReview/Nutrient/Nutrient.apsimx

working on #5137 
@hol353 please do not merge this as yet

Commit initial version of Horsham dataset

---

Models/Resources/Pinus.json

Changed all 'Eucalyptus' to 'Pinus'

---

Models/AgPasture/PastureAboveGroundOrgan.cs
Models/Stock/stock_padd.cs

Stops Stock failing when NaN value for N from AgPasture

---

Models/Plant/Organs/Leaf.cs

Corrected reporting to summary file of leaf biomass removal.

---

ApsimNG/Commands/RunCommand.cs
ApsimNG/Interfaces/IMethodCompletionView.cs
ApsimNG/Presenters/IntellisensePresenter.cs
ApsimNG/Views/MethodCompletionView.cs

Let's fix some memory leaks

---

Models/Manager.cs

Fix compile error.

---

ApsimNG/Presenters/OperationsPresenter.cs

Operations UI should be tab-friendly

---

APSIM.Shared/Utilities/ApsimTextFile.cs
APSIM.Shared/Utilities/StringUtilities.cs
ApsimNG/EventArguments/NeedContextItemsArgs.cs

Change met file reader to split units honouring brackets rather than quotes

---

Models/PostSimulationTools/SimulationStats.cs

Fixed SimulationStats - percentiles

---

ApsimNG/Utility/Colour.cs
ApsimNG/Views/MainView.cs

Make errors/warnings easier to see in dark mode.

---

Tests/UnitTests/ApsimXFiles/ManagerOverrides.apsimx
Tests/UnitTests/ManagerTests.cs
Tests/UnitTests/UnitTests.csproj

Working on #5202
This will run red initially because I haven't actually fixed the bug. I'm hoping it will be fixed by #5194

Added a test to reproduce a bug with manager scripts

---

Models/Plant/Biomass/Biomass.cs

Fixed digestibility in PMF

---

Models/Weather/SlopeEffectsOnWeather.cs

SlopeAndAspect: Removed unwanted parameters from user interface

---

Models/Plant/Phenology/Phases/EmergingPhase.cs
Models/Plant/Phenology/Phases/GerminatingPhase.cs
Models/Plant/Plant.cs
Tests/UnitTests/ForcedEmergence/ForceEmergenceFromManager.apsimx

Remove ForceEmergence events and replace with Emergence dates

---

Models/AgPasture/SimpleGrazing.cs

SimpleGrazing: Removed FractionDefoliatedNLostToCamps parameter

---

ApsimNG/Views/TreeView.cs

Fixed a crash related to renaming a model.

---

ApsimNG/Commands/RenameModelCommand.cs

Trim model names upon renaming in gui.

---

Models/Core/ModelCollectionFromResource.cs

Model resource shouldn't copy properties it can't read.

---

ApsimNG/Views/GraphView.cs

GraphView button press handler needs to allow for legends outside graph area

---

Models/Core/Run/ModelReplacement.cs
Models/Core/Run/PropertyReplacement.cs
Tests/UnitTests/Factorial/ExperimentTests.cs
Tests/UnitTests/Factorial/MultiPaddockFactorOverride.apsimx
Tests/UnitTests/UnitTests.csproj

Tentative fix for factor overrides in multi-paddock experiments

---

Models/Core/ApsimFile/EditFile.cs
Models/Core/VariableComposite.cs
Models/Main.cs
Models/Models.csproj
Tests/UnitTests/Core/ApsimFile/EditFileTests.cs

Working on #4905
Edit: also working on #5195

Edit file feature should work on resource models

---

Tests/UnitTests/Core/CommandLineOptionsTests.cs
Tests/UnitTests/UnitTests.csproj

Added a test for the /SimulationNameRegexPattern command-line switch.

---

Models/Core/Run/ModelReplacement.cs
Models/Core/Run/PropertyReplacement.cs
Tests/UnitTests/Factorial/MultiPaddockFactorOverride.apsimx

Fixed factor overrides in nested paddock scenarios.

---

APSIM.Shared/JobRunning/IJobManager.cs
APSIM.Shared/JobRunning/JobManager.cs
APSIM.Shared/JobRunning/JobRunner.cs
APSIMRunner/APSIMRunner.csproj
APSIMRunner/Client.cs
APSIMRunner/Program.cs
ApsimNG/Commands/RunCommand.cs
ApsimNG/Views/MainView.cs
Models/Core/Run/GenerateApsimXFiles.cs
Models/Core/Run/IReportsStatus.cs
Models/Core/Run/JobRunnerMultiProcess.cs
Models/Core/Run/Runner.cs
Models/Core/Run/SimulationGroup.cs
Models/Models.csproj
Models/Sensitivity/CroptimizR.cs
Models/Storage/DataStoreWriter.cs
Tests/UnitTests/Core/Run/RunnerTests.cs

Resolves #5211 
Resolves #4015
This will also be useful for #4333 and #5195.
- Added progress property to IRunnable
- Job progress is calculated internally by class Runner
- Runner also generates the status message shown next to the progress bar in the UI. The status message shows post-simulation tool status, and can also display custom messages generated by IRunnables (see e00bbf0)
- Implemented progress reporting for individual jobs when running via the multi-process runner (ie you can now see stepped progress when running the wheat example)

Refactored progress reporting

---

Tests/UnderReview/Gliricidia/Gliricidia.apsimx

Fixed N fixation graphs in gliricidia test set

---

Models/Stock/StockList.cs

Enables the purchasing of cows lactating with no calf at foot

---

Models/Factorial/CompositeFactor.cs

Improved error handling in composite factor

---

APSIM.Shared/Utilities/ProcessUtilities.cs
Models/Core/Run/JobRunnerMultiProcess.cs
Models/Sensitivity/CroptimizR.cs
Models/Utilities/R.cs
Tests/UnitTests/Core/ApsimFile/EditFileTests.cs

Allow R script execution to be aborted.

---

Models/Plant/Arbitrator/BaseArbitrator.cs
Models/Plant/Arbitrator/Methods/RetranslocationMethod.cs

TotalRetranslocation not calculated in Arbitrator

---

Models/Tests.cs

Tests component should document its children

---

ApsimNG/Classes/HtmlToMigraDoc.cs

Fixed bug in html -> migradoc converter

---

Models/Core/Zone.cs
Tests/UnitTests/Factorial/MultiPaddockFactorOverride.apsimx

Ensure that nested zones' total area does not exceed the area of their parent

---

Models/Core/ApsimFile/EditFile.cs
Tests/UnitTests/Core/ApsimFile/EditFileTests.cs

Fixed editing of manager scripts via /Edit option

---

Models/Stock/stock.cs
Tests/UserInterfaceTests/DeleteDBFile.cs

Re-initialise the random number generator at start of simulation.

---

ApsimNG/EventArguments/NeedContextItemsArgs.cs
Models/Soils/Soil.cs

Fixed bug in Intellisense and consolidated Soil.PAW properties.

---

Models/Core/Run/ModelReplacement.cs
Models/Plant/Cultivar/Cultivar.cs
Tests/UnitTests/Core/Run/MultipleReplacements.apsimx
Tests/UnitTests/Core/Run/SimulationDescriptionTests.cs
Tests/UnitTests/UnitTests.csproj

Fixed unnecessary calls to model.OnCreated caused by ModelReplacement

---

Models/AgPasture/SimpleGrazing.cs

Added a weighted grazing parameter to SimpleGrazing

---

Models/Soils/SoilTemp/SoilTemperature.cs
Prototypes/SoilTemperature/SoilTemperature.apsimx
Tests/Validation/SoilTemp/SoilTemp_ContinuousWheat.apsimx

Refactor SoilTemperature variable names to ApsimX conventions.

---

Models/Functions/HourlyInterpolation.cs

Add radiation interpolation method

---

Models/Functions/SigmoidFunction.cs

make the sigmoid function an Iindexfunction to use the air temperature interpolation as well

change sigmoid function into a Iindex function

---

APSIM.Shared/Utilities/SQLite.cs
Models/Storage/DataStoreReader.cs

DataStore should allow for column names containing square brackets

---

Models/PostSimulationTools/PredictedObserved.cs

This may slow down the merge, so it's disabled by default. Only really useful for graphing purposes, in order to, say, filter by a field (e.g. Das) which doesn't exist in the observed data.
Resolves #3140 and one of the issues mentioned in #5333.

Added option to PredictedObserved to add all columns into merged table

---

Models/Core/IModel.cs
Models/Core/Model.cs
Models/Core/Simulation.cs
Tests/UnitTests/Core/Run/SimulationTests.cs

Add a new virtual method called OnPreLink to Model

---

ApsimNG/Classes/PDFWriter.cs
Docs/CreateDocumentation/Documentation.json
Docs/CreateDocumentation/Program.cs
Models/Core/AutoDocumentation.cs
Models/Manager.cs
Tests/Validation/AgPasture/SpeciesTable.apsimx

Auto-generate ApgPasture species table for doc web site.

---

Models/Weather/Weather.cs

make it the same as in the R calculation

correct the winter solstice calculation

---

ApsimNG/Presenters/LegendPresenter.cs
ApsimNG/Resources/Glade/LegendView.glade
ApsimNG/Views/LegendView.cs
Models/Core/Locator.cs

Added an option the the UI to show graph legends outside graph area

---

ApsimNG/Presenters/ExplorerPresenter.cs

Fixed a bug where the context menu was not always updated

---

Models/MicroClimate/MicroClimate.cs
Prototypes/Orchard/Orchard.apsimx

revise the vine strip radiation interception based on Gou et al., 2017
make the code the same as in the publication and using the weighting factor for the radiation interception for the top part of the canopy. 
this works better when the canopy width is small as suggested by the author

revise the vine strip radiation interception based on Gou et al., 2017

---

Models/AgPasture/PastureBelowGroundOrgan.cs
Models/AgPasture/PastureSpecies.cs
Models/Resources/AGPBrowntop.json
Models/Resources/AGPCocksfoot.json
Models/Resources/AGPKikuyu.json
Models/Resources/AGPLucerne.json
Models/Resources/AGPPaspalum.json
Models/Resources/AGPPhalaris.json
Models/Resources/AGPRedClover.json
Models/Resources/AGPRhodes.json
Models/Resources/AGPRyegrass.json
Models/Resources/AGPTallFescue.json
Models/Resources/AGPWhiteClover.json

Also Fixed bug with n uptake - arbitrator.
Working on #5356

Changed AgPasture N uptake method to DefaultAPSIM rather than Basic 

---

Models/Plant/Organs/SorghumLeaf.cs
Prototypes/C4Maize/C4Maize.apsimx

Working on #572
@jbrider, I noticed that you changed maize's frost kill threshold to 1, but left sorghum's at -3.5. Is this deliberate?

Changes to sorghum/c4maize to mirror recent changes in classic

---

Models/Core/IReferenceExternalFiles.cs
Models/Factorial/CompositeFactor.cs
Models/Factorial/Factor.cs

Factor and CompositeFactor should implement IReferenceExternalFiles

---

Models/Resources/AGPBrowntop.json
Models/Resources/AGPCocksfoot.json
Models/Resources/AGPKikuyu.json
Models/Resources/AGPLucerne.json
Models/Resources/AGPPaspalum.json
Models/Resources/AGPPhalaris.json
Models/Resources/AGPRedClover.json
Models/Resources/AGPRhodes.json
Models/Resources/AGPTallFescue.json

Added AGP to AgPasture cultivars

---

Models/Storage/DataStoreWriter.cs
Tests/UnitTests/Storage/DataStoreWriterTests.cs

Removed date column from _Checkpoints table

---

Models/AgPasture/PastureSpecies.cs

So that manager scripts can change root parameters. Working on #5356

Added Root property to PastureSpecies 

---

Models/Core/Run/SimulationDescription.cs
Tests/Simulation/Infrastructure/DisabledReplacements.apsimx

Fixed disabling replacements node

---

Models/Storage/DataStoreWriter.cs

Fixed indexing error in checkpoint code

---

ApsimNG/Classes/Intellisense/CSharpCompletion.cs

Script intellisense should look in System.Data.dll as well

---

Models/PostSimulationTools/Filter.cs
Models/PostSimulationTools/SimulationStats.cs

Fixed bug in SimulationStats. Add column filter to Filter model

---

Models/Weather/WeatherSampler.cs

Leap years cause the check to fail. Resolves #4949

Weather sampler: Removed check for running out of met data.

---

Models/Weather/WeatherSampler.cs

so that climate controller works. Resolves #4949

Changed weather sampler to invoke PreparingNewWeatherData event

---

Models/Optimisation/CroptimizR.cs
Models/Resources/RScripts/OptimizR.r

Improved croptimizr support for reading from predictedobserved table

---

APSIM.Shared/Utilities/DBMerger.cs
ApsimNG/Cloud/Azure/AzureInterface.cs
ApsimNG/Cloud/DownloadOptions.cs
ApsimNG/Interfaces/ICloudJobView.cs
ApsimNG/Presenters/CloudJobPresenter.cs
ApsimNG/Presenters/RunOnCloudPresenter.cs
ApsimNG/Views/CloudDownloadView.cs
ApsimNG/Views/CloudJobView.cs
ApsimNG/Views/RunOnCloudView.cs
Models/Core/IReferenceExternalFiles.cs
Models/Core/Run/GenerateApsimXFiles.cs
Models/Core/Run/SimulationDescription.cs
Models/Core/Simulation.cs
Models/Factorial/CompositeFactor.cs
Models/Factorial/Factor.cs
Models/PostSimulationTools/ExcelInput.cs
Models/PostSimulationTools/Input.cs
Models/Weather/Weather.cs

Azure run on cloud fixes

---

APSIM.Shared/Utilities/SQLite.cs

Does using integer for SQLite boolean columns cause issues?

---

ApsimNG/Presenters/PropertyAndTablePresenter.cs

Fixed intellisense in dual grid view

---

Models/Utilities/R.cs

Attempt to create R package directory if it doesn't exist.

---

ApsimNG/Views/SeriesView.cs

Fixed help link in series view.

---

Models/Agroforestry/LocalMicroClimate.cs

Tree Proxy

---

APSIMRunner/Client.cs

Fixed deadlock in multi-process job runner

---

Jenkins/PullRequest/Jenkinsfile

Jenkins builds could run in release mode.

---

APSIM.Shared/JobRunning/JobRunner.cs
Models/Core/Run/JobRunnerMultiProcess.cs

Fixed deadlock in JobRunner (I hope)

---

ApsimNG/Views/ListView.cs

Fix Experiment view not showing anything

---

Models/Plant/Arbitrator/Methods/C4NitrogenUptakeMethod.cs
Models/Plant/Organs/Root.cs
Prototypes/C4Maize/C4Maize.apsimx

Move Links

---

Tests/UnderReview/Soybean/Soybean Example.apsimx
Tests/UnderReview/Soybean/Soybean.apsimx

Change Soybean Sample to be similar to Wheat example

---

Models/Core/ApsimFile/Converter.cs

Only run plant converter on scripts if there is a plant in the zone.

---

Models/PMF/Cultivar/Cultivar.cs
Models/PMF/OilPalm/OilPalm.cs
Models/PMF/Plant.cs

Removed Plant's Cultivars and CultivarList properties

---

ApsimNG/EventArguments/NeedContextItemsArgs.cs

Fixed minor bug in intellisense

---

Models/AgPasture/PastureBelowGroundOrgan.cs
Models/AgPasture/PastureSpecies.cs
Models/AgPasture/RootTissue.cs

Fixed Sow, Kill and EndCrop in AgPasture

---

Models/AgPasture/PastureBelowGroundOrgan.cs
Models/AgPasture/RootTissue.cs

Stop AgPasture sending roots to SurfaceOrganicMatter

---

Models/PostSimulationTools/Probability.cs

Resolves #4315...I think...
This may have adverse affects on probability components with the 'refresh data store' feature. However it's still better than what we had previously, where it was doing almost the exact opposite of what we wanted.

Fixed bug in probability model

---

Models/PMF/Organs/ReproductiveOrgan.cs

Removed unnecessary property and function

---

Models/PMF/Organs/Root.cs

Add incrementer

---

Models/PMF/Arbitrator/Methods/C4NitrogenUptakeMethod.cs
Prototypes/C4Maize/C4Maize.apsimx

Remove unnecessary link to root class

---

Models/Resources/Nutrient.json
Models/Soils/Nutrients/NutrientPool.cs
Tests/Validation/Nutrient/Nutrient.apsimx

Initial SoilP implementation for OM pools only

---

Models/AgPasture/PastureBelowGroundOrgan.cs
Models/AgPasture/PastureSpecies.cs
Models/AgPasture/RootTissue.cs
Models/Resources/AGPBrowntop.json
Models/Resources/AGPCocksfoot.json
Models/Resources/AGPKikuyu.json
Models/Resources/AGPLucerne.json
Models/Resources/AGPPaspalum.json
Models/Resources/AGPPhalaris.json
Models/Resources/AGPRedClover.json
Models/Resources/AGPRhodes.json
Models/Resources/AGPRyegrass.json
Models/Resources/AGPTallFescue.json
Models/Resources/AGPWhiteClover.json

AgPasture root organ refactor

---

ApsimNG/Presenters/GraphPanelPresenter.cs
ApsimNG/Presenters/GraphPresenter.cs
Models/Graph/EventNamesOnGraph.cs
Models/Graph/Graph.cs
Models/Graph/ICachableGraphable.cs
Models/Graph/IGraphable.cs
Models/Graph/Regression.cs
Models/Graph/Series.cs
Models/Graph/ShadedBarsOnGraph.cs
Models/Models.csproj
Tests/UnitTests/Graph/SeriesTests.cs

Refactor the graphing backend to use return values

---

Models/PMF/Plant.cs

Removed redundant constructor from plant.

---

Models/Graph/EventNamesOnGraph.cs

Fixed bug in EventNamesOnGraph

---

ApsimNG/Menus/ContextMenu.cs

When creating autodocs, only open the resultant file on windows

---

Models/Soils/WaterModel/WaterBalance.cs

WaterBalance model should use Runon

---

Models/Core/ModelCollectionFromResource.cs
Models/Core/Run/ModelReplacement.cs
Models/Soils/MultiPoreWater/WEIRDO.cs
Prototypes/WEIRDO/WEIRDO.apsimx
Tests/Simulation/Infrastructure/PlantInReplacements.apsimx

Fixed resource model's parameters not being correctly overriden

---

Examples/Tutorials/Lifecycle.apsimx
Models/Graph/GraphPanel.cs
Models/Graph/Regression.cs

These failing autodocs are causing upgrades to not be released.
Resolves #4982

Fix autodocs for several files

---

APSIM.Shared/Utilities/ReflectionUtilities.cs

Fixed a bug in SetValueOfFieldOrProperty function

---

ApsimNG/Presenters/GraphPresenter.cs

Fixed performance regression in graph code

---

Models/Core/AutoDocumentation.cs
Tests/Validation/MicroClimate/MicroClimate.apsimx

Fix autodocs

---

ApsimNG/Presenters/PropertyPresenter.cs

Fixed bug in organic UI

---

Models/Factorial/CompositeFactor.cs

Fixed CompositeFactor's IReferenceExternalFiles implementation.

---

Jenkins/Installation/Jenkinsfile
Jenkins/deploy.bat

Jenkins deploy job needs ftp creds to upload API docs.

---

Jenkins/deploy.bat

Fixed typo in jenkins script

---

Models/Manager.cs

Fixed a bug in manager script compilation

---

ApsimNG/Menus/ContextMenu.cs
Models/Manager.cs

Resolves #5634 
@hol353 - I'm not sure I like this approach. There is another (maybe better) solution to this issue - see #5634 for details. I didn't opt for this solution because it involves the OnCreated method.

Attempt to compile disabled managers when opening a file

---

Models/Core/ModelCollectionFromResource.cs
Tests/UnitTests/ApsimNG/Presenters/AddModelPresenterTests.cs

Fixed an issue with adding a resource model to replacements

---

Tests/UnderReview/Sorghum/SorghumExample.apsimx

Added sorghum example file

---

Jenkins/Installation/Jenkinsfile
Jenkins/deploy.bat

Minor tweak to jenkins script

---

Docs/static/theme-original/style.css

Tweaked code style in hugo theme

---

Models/PostSimulationTools/Filter.cs

Remove square brackets from filter strings

---

ApsimNG/Views/BubbleChartView.cs

Working on #3890 
Haven't yet implemented suggested changes for using a child manager for each arc, once a decision/consensus is reached I can go ahead and implement it.

Improvements to rotation manager UI

---

Models/PMF/Interfaces/IArbitration.cs
Models/PMF/Organs/GenericOrgan.cs

Maintenance respiration

---

Models/Soils/Nutrients/Solute.cs

Removed unnecessary autodoc comment from solute

---

Models/Soils/SoilsDataTable.cs

Reinstate site and layerno in APSoil soil data table to soil code

---

Models/PMF/Plant.cs

Fixed the Plant.SetEmergenceDate() function to work in other locales

---

ApsimNG/Views/GridView.cs

Working on #5590 
No idea if this fixes the problem or not, and if it does it's not a good solution.

Attempt to isolate the crashes in the gui

---

Examples/CLEM/CLEM_Example_Cropping.apsimx
Examples/CLEM/CLEM_Example_Grazing.apsimx
Models/CLEM/Activities/CLEMRuminantActivityBase.cs
Models/CLEM/Activities/CropActivityFee.cs
Models/CLEM/Activities/PastureActivityBurn.cs
Models/CLEM/Activities/PastureActivityCutAndCarry.cs
Models/CLEM/Activities/PastureActivityManage.cs
Models/CLEM/Activities/RuminantActivityBreed.cs
Models/CLEM/Activities/RuminantActivityFeed.cs
Models/CLEM/Activities/RuminantActivityGrazePastureHerd.cs
Models/CLEM/Activities/RuminantActivityGrow.cs
Models/CLEM/Activities/RuminantActivityManage.cs
Models/CLEM/Activities/RuminantActivityMilking.cs
Models/CLEM/Activities/RuminantActivitySellDryBreeders.cs
Models/CLEM/Activities/TruckingSettings.cs
Models/CLEM/Groupings/RuminantFeedGroup.cs
Models/CLEM/Groupings/RuminantFeedGroupMonthly.cs
Models/CLEM/Relationship.cs
Models/CLEM/Reporting/ReportPasturePoolDetails.cs
Models/CLEM/Resources/GrazeFoodStore.cs
Models/CLEM/Resources/GrazeFoodStoreFertilityLimiter.cs
Models/CLEM/Resources/GrazeFoodStoreType.cs
Models/CLEM/Resources/ResourcesHolder.cs
Models/CLEM/Resources/Ruminant.cs
Models/CLEM/Resources/RuminantFemale.cs
Models/CLEM/Resources/RuminantType.cs

Improved ruminant feed activity for overfeeding and reporting wastage

---

Models/Report/Report.cs

Include inner exception message in 'invalid report variable' exception

---

ApsimNG/Presenters/PropertyPresenter.cs

Allow property presenter to report base properties with description

---

Models/Utilities/R.cs

When detecting installed R version, use latest installed

---

Setup/apsimx.iss

Changed windows installer to uncheck 'create desktop icon' by default

---

Models/Soils/SWIM/Swim.cs

Make some SWIM properties publically settable

---

Tests/UnderReview/Chickpea/Hyderabad.met
Tests/Validation/FodderBeet/Cambridge.met
Tests/Validation/FodderBeet/Gore.met
Tests/Validation/FodderBeet/Hobart.met
Tests/Validation/FodderBeet/Matamata.met
Tests/Validation/FodderBeet/Methven.met
Tests/Validation/FodderBeet/Ohakune.met
Tests/Validation/FodderBeet/Ruakura.met
Tests/Validation/FodderBeet/Temuka.met
Tests/Validation/FodderBeet/Timaru.met
Tests/Validation/FodderBeet/Wanganui.met
Tests/Validation/Potato/SCRI_Dundee.met
Tests/Validation/Potato/SCRI_Dundee_dry.met

Resolves #5677
Resolves #5678
Resolves #5679

Fix coordinates in some met files

---

Models/CLEM/Activities/ResourceActivityProcess.cs
Models/CLEM/Activities/ResourceActivitySell.cs
Models/CLEM/Activities/TruckingSettings.cs
Models/CLEM/FileCrop.cs
Models/CLEM/RandomNumberGenerator.cs
Models/CLEM/Reporting/ReportResourceBalances.cs
Models/CLEM/Resources/AnimalFoodStoreType.cs
Models/CLEM/Resources/LabourType.cs
Models/CLEM/Resources/RuminantTypeCohort.cs

CLEM minor fixes and corrections to help system URI links

---

ApsimNG/Views/ListView.cs

Improve right clicking on multiple rows in list view

---

Models/Resources/Wheat.json

Remove useless cultivar parameter from Gamenya in Wheat.json

---

ApsimNG/Presenters/DownloadPresenter.cs
Models/Core/ApsimFile/Converter.cs

Improve soil download capabilities

---

ApsimNG/Resources/Glade/WeatherDownload.glade
ApsimNG/Utility/WeatherDownloadDialog.cs

Improve window sizing for weather download dialog

---

README.md

Update readme: add link to installer page

---

ApsimNG/Presenters/MapPresenter.cs
ApsimNG/Views/MapView.cs

Not needed anymore. Working on #3184

Remove old 'preview map autodocs' features

---

Models/Soils/LayerStructure.cs

Resolves #5726...as long as you're ok with the layer structure UI showing depths instead of thicknesses.

Added units to LayerStructructure properties.

---

Models/AgPasture/SimpleGrazing.cs

The counter was zeroing to -1 rather than 0 .
@MarkLieffering  - this should fix it.
resolves #5736

Fix the grazing day counter for SimpleGrazing

---

ApsimNG/Presenters/MetDataPresenter.cs

Show longitude in met UI

---

Models/Climate/ControlledEnvironment.cs

Fixed descriptions and units in controlled environment.

---

Models/PMF/Structure/Structure.cs

Fixed bug in leaf cohort

---

Models/Manager.cs
Models/Models.csproj
Models/Resources/Scripts/BlankManager.cs

Added default code to manager scripts

---

Models/Core/Run/SimulationGroup.cs

Fixed a bug where folder name is not saved to datastore

---

Models/Models.csproj

Remove reference to winforms from Models.csproj

---

Models/Functions/SoilFunctions/CERESDenitrificationModel.cs
Models/Functions/SoilFunctions/CERESDenitrificationTemperatureFactor.cs
Models/Functions/SoilFunctions/CERESDenitrificationWaterFactor.cs

Improved report-ability of ceres denitrification processes

---

Models/Soils/WaterModel/LateralFlow.cs
Models/Soils/WaterModel/WaterBalance.cs

Removed Slope property from WaterBalance

---

ApsimNG/Classes/PDFWriter.cs

Fixed a hang in mapview autodocs caused by no UI.

---

ApsimNG/Classes/Property.cs
ApsimNG/EventArguments/BubbleChartArgs.cs
ApsimNG/Interfaces/IBubbleChartView.cs
ApsimNG/Presenters/BubbleChartPresenter.cs
ApsimNG/Views/BubbleChartView.cs
Models/Interfaces/IBubbleChart.cs
Models/Management/RotationManager.cs
Prototypes/RotationManager/RotationManager.apsimx

Improvements to rotation manager

---

ApsimNG/Views/MapView.cs

Implemented collision detection between labels on map

---

Models/Optimisation/CroptimizR.cs

Optimiser needs to sanitise variable names properly

---

ApsimNG/Views/BubbleChartView.cs

Remove unused widgets from bubble chart view

---

Models/Report/ReportColumn.cs
Tests/UnitTests/Report/ReportTests.cs

Fixed reporting of array elements with index > 9

---

ApsimNG/EventArguments/NeedContextItemsArgs.cs

Fix null error in intellisense

---

Models/Soils/Soil.cs
Models/Summary.cs

Summary should not be responsible for checking soils at runtime

---

ApsimNG/ApsimNG.csproj
ApsimNG/packages.config

Add reference to BruTile nuget package

---

ApsimNG/Presenters/PropertyPresenter.cs

PropertyPresenter should allow for null lifecycle variables

---

Prototypes/C4Maize/C4Maize.apsimx
Tests/UnderReview/Sorghum/SorghumExample.apsimx

Working on #572. This mirrors the changes in APSIMInitiative/APSIMClassic#1888.

Changed sorghum phenology water stress

---

Models/Functions/SoilFunctions/CERESDenitrificationWaterFactor.cs
Models/Functions/SoilFunctions/CERESMineralisationWaterFactor.cs
Models/Functions/SoilFunctions/CERESNitrificationWaterFactor.cs
Models/Functions/SoilWaterScale.cs
Models/Soils/MultiPoreWater/WEIRDO.cs
Models/Soils/Standardiser/Layers.cs

Improvements to WEIRDO

---

Models/Core/AutoDocumentation.cs

GetSummary() method should strip consecutive spaces/newlines.

---

Models/PMF/Organs/RootZoneState.cs
Tests/Validation/System/Hudson/HudsonSWIM3.apsimx

Changed hudson swim simulation to use nutrient

---

ApsimNG/Classes/HtmlToMigraDoc.cs
ApsimNG/Views/MarkdownView.cs

Fixed a few bugs in markdownview

---

Models/Soils/SWIM/Swim.cs

Changed swim nodes to middle of layers

---

Models/Soils/MultiPoreWater/WEIRDO.cs

Correct PAWC calculation in weirdo

---

ApsimNG/Classes/HtmlToMigraDoc.cs

Fixed empty tables in autodocs.

---

ApsimNG/Presenters/LinearAfterThresholdPresenter.cs
Models/Functions/LinearAfterThresholdFunction.cs

Fixed gui for LinearAfterThresholdFunction

---

ApsimNG/ApsimNG.csproj
ApsimNG/Utility/MarkdownFindView.cs
ApsimNG/Views/EditorView.cs
ApsimNG/Views/MarkdownView.cs
ApsimNG/Views/SummaryView.cs

Added text search for markdownview

---

ApsimNG/Classes/HtmlToMigraDoc.cs
ApsimNG/Classes/PDFWriter.cs

Autodocs should accept images specified with a relative path.

---

ApsimNG/Resources/Glade/WeatherDownload.glade
ApsimNG/Utility/WeatherDownloadDialog.cs

Improvements to weather download dialog

---

Models/Soils/OutputLayers.cs

Fixed units on OutputLayers.PAW

---

Docs/CreateDocumentation/Documentation.json

Changed link to clem docs (http -> https)

---

Models/CLEM/Activities/RuminantActivityManage.cs

Allow user to disable mark for sale in ruminant manage CLEM

---

Models/Sensitivity/Morris.cs

Morris component should allow for aggregation variables which are dates

---

ApsimNG/Presenters/DocumentationPresenter.cs
ApsimNG/Presenters/TablePresenter.cs
Models/Core/ApsimFile/Structure.cs
Tests/UnitTests/ApsimNG/Presenters/TablePresenterTests.cs
Tests/UnitTests/UnitTests.csproj

Fixed a bug in table presenter where changes to grids weren't persistent

---

ApsimNG/Views/TreeView.cs

Changed character used for 'show documentation status'

---

Models/PMF/Arbitrator/Methods/NitrogenUptakeMethod.cs

Fixed an unprotected division in NitrogenUptakeMethod

---

ApsimNG/Resources/Glade/StringEntryForm.glade

UI improvements to add checkpoint feature

---

Models/PMF/Plant.cs

Improved plant's check for IsReadyForHarvesting

---

Models/Core/ApsimFile/Converter.cs
Models/Sensitivity/Sobol.cs

Make sobol more flexible in terms of table/variable

---

ApsimNG/Classes/Property.cs
Models/PostSimulationTools/PredictedObserved.cs

Property UI should always show selected value in dropdowns

---

ApsimNG/Interfaces/ITreeView.cs
ApsimNG/Presenters/ExplorerPresenter.cs
ApsimNG/Views/TreeView.cs

Expand parent when adding/dragging a model in the GUI

---

Models/PMF/Arbitrator/BiomassTypeArbitrator.cs

Slight tidy up of BiomassTypeArbitrator.

---

Models/Resources/RScripts/OptimizR.r

CroptimizR should ignore simulations for which there is no data

---

Tests/UnderReview/Soybean/Soybean.apsimx

Set 'include in documentation' to true on sobean model

---

Models/Agroforestry/LocalMicroClimate.cs
Models/Climate/BestiaPop.cs
Models/Interfaces/IWeather.cs

Make weather properties settable once more

---

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx

Add location information in the management toolbox

---

ApsimNG/Presenters/ManagerPresenter.cs
ApsimNG/Presenters/SimplePropertyPresenter.cs

Manager UI should be more tolerant of errors in script

---

Docs/CreateDocumentation/Documentation.json

Added micromet science docs to website

---

Models/Optimisation/CroptimizR.cs

CroptimizR should work with relative paths.

---

ApsimNG/Presenters/DataStorePresenter.cs
ApsimNG/Presenters/ReportPresenter.cs

resolves #5910, working on #5530

Report UI should only show data for current report

---

APSIM.Shared/Utilities/ReflectionUtilities.cs
ApsimNG/ApsimNG.csproj
ApsimNG/Classes/Property.cs
ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/MainPresenter.cs
ApsimNG/Utility/Configuration.cs
ApsimNG/Utility/SettingsDialog.cs
ApsimNG/Views/PropertyView.cs

Resolves #5553
Please don't merge yet - there are a few things I want to try and add on top of this. Let me know if this is basically what you guys had in mind.

Add autosave option and settings dialog, accessible from homescreen

---

ApsimNG/Presenters/CLEM/CLEMPresenter.cs
ApsimNG/Presenters/CLEM/CLEMSummaryPresenter.cs
ApsimNG/Presenters/CLEM/LabourAllocationPresenter.cs
ApsimNG/Presenters/CLEM/MessagePresenter.cs
ApsimNG/Presenters/CLEM/VersionsPresenter.cs
ApsimNG/Views/CLEM/CLEMView.cs
ApsimNG/Views/CLEM/ModelDetailsWrapperView.cs
Models/CLEM/CLEMModel.cs
Models/CLEM/FileCrop.cs
Models/CLEM/Reporting/ReportLabourRequirements.cs
Models/CLEM/ZoneCLEM.cs

Remove use of HTMLView from CLEM

---

ApsimNG/Presenters/CLEM/MessagePresenter.cs
ApsimNG/Views/MarkdownView.cs
Models/CLEM/Activities/RuminantActivityGrow.cs
Models/CLEM/Activities/RuminantActivityMove.cs

Implement absolute paths in links in markdown

---

Models/CLEM/Activities/ResourceActivitySell.cs
Models/CLEM/Activities/RuminantActivityFeed.cs
Models/CLEM/Groupings/RuminantFeedGroup.cs
Models/CLEM/IResourceType.cs
Models/CLEM/Resources/AnimalFoodStoreType.cs
Models/CLEM/Resources/CLEMResourceTypeBase.cs
Models/CLEM/Resources/CommonLandFoodStoreType.cs
Models/CLEM/Resources/EquipmentType.cs
Models/CLEM/Resources/FinanceType.cs
Models/CLEM/Resources/GrazeFoodStorePool.cs
Models/CLEM/Resources/GrazeFoodStoreType.cs
Models/CLEM/Resources/GreenhouseGasesType.cs
Models/CLEM/Resources/HumanFoodStoreType.cs
Models/CLEM/Resources/LabourType.cs
Models/CLEM/Resources/LandType.cs
Models/CLEM/Resources/OtherAnimalsType.cs
Models/CLEM/Resources/ProductStoreType.cs
Models/CLEM/Resources/ProductStoreTypeManure.cs
Models/CLEM/Resources/WaterType.cs

Fixed selling prop of harvest and animal overfeed wastage

---

Jenkins/Installation/Jenkinsfile

Jenkins release job needs to extract wheat NPI data

---

Models/Graph/Regression.cs

Hopefully fix wheat autodocs

---

Models/CLEM/Activities/RuminantActivityManage.cs

Improved sale of heifers to maintain small herds

---

APSIM.Shared/APSIM.Shared.csproj
APSIM.Shared/Extensions/TypeExtensions.cs
ApsimNG/Presenters/DocumentationPresenter.cs
ApsimNG/Views/MarkdownView.cs
Models/Core/AutoDocumentation.cs

Improvements to documentation presenter

---

Models/Main.cs
Models/Options.cs

Fix cli edit option

---

ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/ExplorerPresenter.cs

When dragging/copying models, expand children of the new parent.

---

ApsimNG/Views/PropertyView.cs

Fixed column spacing in property UI.

---

Models/PMF/Interfaces/IOrgan.cs
Models/PMF/Organs/GenericOrgan.cs
Models/PMF/Organs/HIReproductiveOrgan.cs
Models/PMF/Organs/Leaf.cs
Models/PMF/Organs/LeafCohort.cs
Models/PMF/Organs/Nodule.cs
Models/PMF/Organs/SimpleLeaf.cs
Models/PMF/Organs/SorghumLeaf.cs

Adding MaintenanceRespiration to IOrgan

---

ApsimNG/Classes/Property.cs
ApsimNG/Presenters/PropertyPresenter.cs

Fixed a freeze in PropertyView

---

ApsimNG/Presenters/DownloadPresenter.cs

Errors while downloading met data should be displayed in the UI.

---

ApsimNG/Presenters/CLEM/CLEMSummaryPresenter.cs
ApsimNG/Presenters/CLEM/LabourAllocationPresenter.cs
ApsimNG/Presenters/CLEM/MessagePresenter.cs
Models/CLEM/Activities/RuminantActivityHerdCost.cs

Update descriptive summary on click

---

ApsimNG/Utility/ColumnXYSeries.cs
ApsimNG/Views/GraphView.cs

Resolves #5988, Resolves #5987

Fixed tracker strings in bar graphs

---

ApsimNG/Presenters/ExplorerPresenter.cs

After clicking save in the UI, the right hand panel should be redrawn.

---

Models/Utilities/R.cs

When multiple versions of R are installed, use latest

---

Models/Core/Events.cs

Improved error message upon failing to connect event delegate to event.

---

Prototypes/Grapevine/grapevine.apsimx

correct the reseting time for BEN_TmaxIni

---

Models/Core/Run/SimulationDescription.cs

Fixed race condition in status reporting

---

ApsimNG/Presenters/MainPresenter.cs

Fixed UI file closing logic

---

ApsimNG/Presenters/GenericPresenter.cs
ApsimNG/Presenters/SummaryPresenter.cs
ApsimNG/Views/ExplorerView.cs
ApsimNG/Views/IntellisenseView.cs
Models/Core/Simulations.cs
Models/Stock/stock.cs

Removed more instances of htmlview

---

APSIM.Shared/Utilities/ExpressionEvaluator.cs

Resolves #3577
Can now guard against division by zero in report by using the inbuilt divide function:
```
divide([Wheat].Leaf.NDemand.Storage, [Wheat].Leaf.DMDemand.Storage) as Wheat.Leaf.NConc.Storage
```
Can also pass an optional third argument (defaults to zero) which is the return value to be used when the denominator is zero.

Fixed function calls in expression parser with >1 argument

---

Models/Resources/Wheat.json

Wheat.Phenology.FloweringDAS should reset at germination

---

Models/Storage/DataStoreWriter.cs

Improve datastore support of table names containing whitespace

---

ApsimNG/Presenters/DataStorePresenter.cs

After clicking on datastore, don't have any table selected by default.

---

ApsimNG/Classes/PDFWriter.cs

Added padding around auto-doc table column sizes

---

ApsimNG/Presenters/GraphPresenter.cs
Models/Core/AutoDocumentation.cs

Chart axis units

---

Models/Functions/PhaseLookup.cs
Models/PMF/Organs/Root.cs
Tests/UnderReview/Soybean/Soybean.apsimx

Initial refactoring of Root Autodoc

---

Models/PMF/Organs/SorghumLeaf.cs

Mirroring changes to sorghum leaf senescence made in old apsim

---

APSIM.bib
Models/Functions/SupplyFunctions/RUECO2Function.cs
Models/Functions/SupplyFunctions/RUEModel.cs
Models/Functions/SupplyFunctions/StomatalConductanceCO2Modifier.cs
Models/PMF/Organs/GenericOrgan.cs
Models/PMF/Organs/Root.cs
Models/PMF/Organs/SimpleLeaf.cs

Fix CO2 Impacts

---

Models/Functions/SigmoidFunction.cs

Remove duplicate code from sigmoid function

---

Models/Core/AutoDocumentation.cs
Models/PMF/Phenology/Phases/GenericPhase.cs

Added [DocumentMathFunction] to autodoc

---

Models/Functions/DemandFunctions/StorageNDemandFunction.cs
Models/Functions/SupplyFunctions/RUEModel.cs
Models/PMF/Organs/GenericOrgan.cs
Models/PMF/Organs/Nodule.cs
Models/PMF/Organs/ReproductiveOrgan.cs
Models/PMF/Organs/Root.cs

Fixed units in multiple classes

---

ApsimNG/Menus/ContextMenu.cs

DataStoreView should be redrawn after refreshing/emptying the datastore.

---

ApsimNG/Views/MapView.cs

Removed country names from mapview.

---

APSIM.bib
ApsimNG/Commands/BibTeX.cs
Models/Core/Folder.cs
Models/PMF/Plant.cs
Prototypes/Peanut/Peanut.apsimx
Tests/UnderReview/Soybean/Soybean.apsimx

Peanut Autodoc

---

Models/Core/AutoDocumentation.cs
Models/Functions/LinearInterpolationFunction.cs

Added DocumentChart macro to autodoc metalanguage

---

APSIM.bib

References for soybean documentation

---

ApsimNG/Views/MarkdownView.cs

Markdownview needs to account for hard vs soft line breaks.

---

ApsimNG/Commands/CreateParamsInputsOutputsDocCommand.cs

Proper rendering of markdown in summary tags for model description pdfs

---

ApsimNG/Presenters/LegendPresenter.cs
ApsimNG/Resources/Glade/LegendView.glade
ApsimNG/Views/DropDownView.cs
ApsimNG/Views/LegendView.cs
Tests/UnitTests/ApsimNG/Views/GraphViewTests.cs

Make legend orientation controllable from UI.

---

ApsimNG/Classes/Property.cs
ApsimNG/Presenters/ProfileGridPresenter.cs
Models/Soils/SoilCrop.cs

Show PAWC totals in profile grid.

---

ApsimNG/ApsimNG.csproj
ApsimNG/Presenters/MemoPresenter.cs
ApsimNG/Resources/Glade/MemoView.glade
ApsimNG/Views/TextInputView.cs

Resolves #6072, resolves #6075

Improvements to memo UI

---

Models/Grazplan/Supplement.cs
Models/Stock/AnimalGroup.cs
Models/Stock/Genotype.cs
Models/Stock/PaddockInfo.cs
Models/Stock/stock.cs
Models/Stock/stock_manage.cs
Models/Stock/stock_padd.cs
Models/Stock/stock_vars.cs

Added units to many properties

---

ApsimNG/Classes/Grid/GridColumn.cs
ApsimNG/Views/IntellisenseView.cs

Don't attempt to set gtktreeview columns to -ve fixed width.

---

Jenkins/runTests.bat
Models/app.config

Change to server GC mode by default

---

ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/ExplorerPresenter.cs

Improved copying/pasting of models in the simulations tree

---

ApsimNG/EventArguments/NeedContextItemsArgs.cs

Intellisense should fall back to a type name lookup before failing.

---

Models/CLEM/Reporting/ReportActivitiesPerformed.cs

Disabled clem summary outputs to get jenkins builds green again

---

ApsimNG/EventArguments/NeedContextItemsArgs.cs

Fixed intellisense for models under factors

---

Models/Soils/SWIM/Swim.cs

Fixed swim infinite loop

---

ApsimNG/Presenters/AxisPresenter.cs
ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Views/AxisView.cs
ApsimNG/Views/GraphView.cs

Bugfixes for ShadedBarsOnGraph

---

Models/Core/AutoDocumentation.cs

Fixed infinite loop in autodocs

---

ApsimNG/Presenters/GraphPresenter.cs
ApsimNG/Views/GraphView.cs

This fixes all of the formatexceptions showing up in jenkins logs.
Working on #5606

Fix FLN graphs in wheat docs

---

ApsimNG/Views/MarkdownView.cs

Fixed display of images in markdownview on windows

---

APSIM.Shared/Utilities/SoilUtilities.cs
Models/Soils/SWIM/Swim.cs
Models/Sugarcane/Sugarcane.cs

Removed remaining FindLayerNo methods

---

Models/Core/Locater.cs
Models/Report/Report.cs
Tests/UnitTests/Report/ReportTests.cs

Allow report variables to reference other report variables

---

ApsimNG/ApsimNG.csproj
ApsimNG/Classes/HtmlToMigraDoc.cs
ApsimNG/Classes/PDFWriter.cs
ApsimNG/Classes/ScriptCompletionProvider.cs
ApsimNG/Commands/CreateFileDocumentationCommand.cs
ApsimNG/Intellisense/CodeCompletionService.cs
ApsimNG/Main.cs
ApsimNG/Presenters/IntellisensePresenter.cs
ApsimNG/Views/CodeView.cs
ApsimNG/Views/GraphView.cs
ApsimNG/Views/ListButtonView.cs
ApsimNG/Views/MethodCompletionView.cs
ApsimNG/Views/TreeView.cs
Models/Models.csproj
Models/Summary.cs

Fixed some minor UI defects in gtk3 builds

---

ApsimNG/Presenters/XYPairsPresenter.cs
Models/Core/AutoDocumentation.cs
Models/Functions/LinearInterpolationFunction.cs
Tests/UnderReview/Chickpea/Chickpea.apsimx
Tests/UnderReview/Chickpea/Hyderabad.met
Tests/UnderReview/Chickpea/cooper.met

Cleanup of chickpea autodoc

---

ApsimNG/Utility/Configuration.cs
ApsimNG/Utility/ConfigurationConverter.cs

Small change to avoid "quiet" FileNotFound exceptions.

---

Models/Models.csproj

Turn on server mode GC in .net core builds

---

ApsimNG/Main.cs
Models/Core/ScriptCompiler.cs
Models/Main.cs
Models/Models.csproj

Fixed excelinput and some manager scripts in netcore builds

---

ApsimNG/Utility/Configuration.cs
ApsimNG/Utility/SettingsDialog.cs
ApsimNG/Views/CodeView.cs

Improved manager editor appearance in gtk3 builds

---

ApsimNG/Views/CodeView.cs
ApsimNG/Views/ColourDropDownView.cs
ApsimNG/Views/SeriesView.cs

gtk3 fixes

---

ApsimNG/Extensions/WidgetExtensions.cs
ApsimNG/Views/FolderView.cs
ApsimNG/Views/GraphPanelView.cs

Fixed layout of folder and graph panel UIs in netcore builds.

---

Jenkins/build.bat

Jenkins needs to build updater as well

---

ApsimNG/Resources/Glade/MemoView.glade
ApsimNG/Views/MarkdownView.cs
ApsimNG/Views/SummaryView.cs

Changed the way that markdownview is initialised

---

Models/Optimisation/CroptimizR.cs

CroptimizR needs to install remotes package

---

ApsimNG/Menus/ContextMenu.cs

Soil downloader should be enabled in .net framework builds.

---

ApsimX.sln
Docs/CreateDocumentation/CreateDocumentation.csproj
Jenkins/build.bat

Add CreateDocumentation and Updater back into solution file

---

ApsimNG/Resources/Glade/GridView.glade
ApsimNG/Resources/Glade/StringEntryForm.glade
ApsimNG/Utility/StringEntryForm.cs
ApsimNG/Utility/WeatherDownloadDialog.cs
ApsimNG/Views/GridView.cs
ApsimNG/Views/MarkdownView.cs

Misc UI bugfixes, mainly for gtk3 builds

---

Docs/CreateDocumentation/CreateDocumentation.csproj

Fixed CreateDocumentation output path

---

APSIM.Shared/Utilities/ProcessUtilities.cs
ApsimNG/Classes/HtmlToMigraDoc.cs

Resolves #6178
(I've also fixed the auto-opening of the pdf after it's generated, which was also previously failing.)

Fix autodoc generation on windows

---

Tests/Validation/WhiteClover/WhiteClover.apsimx

Fixed paths to met files in whiteclover validation file

---

ApsimNG/Classes/PDFWriter.cs
ApsimNG/Views/DirectedGraphView.cs

Implemented DirectedGraphView.Export() in gtk3 builds.

---

Models/Core/ApsimFile/FileFormat.cs

Improved serialization rules for resource models

---

ApsimNG/Extensions/PdfExtensions.cs

Fixed race condition in autodocs

---

ApsimNG/Views/GridView.cs

Improved initial sizing of fixed column in gridview

---

Jenkins/build.bat

Jenkins should set AssemblyVersion in ApsimNG as well as Models.

---

Models/Report/ReportColumn.cs

Fixed failure in report when run under invariant culture

---

ApsimNG/Views/TreeView.cs

Fixed a gtk warning which was occurring after searching in the treeview

---

Models/Grazplan/GrazSupp.cs
Models/Grazplan/Supplement.cs
Models/Stock/Genotype.cs

More units and descriptions

---

Models/PMF/Structure/LeafCulms.cs

Bring in ftn estimation code from old apsim

---

ApsimNG/Presenters/DownloadPresenter.cs

Changed soil downloader to use nutrient

---

Docs/CreateDocumentation/CreateDocumentation.csproj

Set CopyLocal to false on gtk-sharp.dll in CreateDocs project

---

ApsimNG/Presenters/DocumentationPresenter.cs
Models/Core/AutoDocumentation.cs

Improve layout of info generated by DocumentationPresenter

---

ApsimNG/Views/CodeView.cs

Fixed off-by-one error in .net core editorView

---

ApsimNG/Presenters/CLEM/CustomQueryPresenter.cs
ApsimNG/Presenters/CLEM/PivotTablePresenter.cs
ApsimNG/Views/CLEM/ActivityLedgerGridView.cs
ApsimNG/Views/CLEM/CustomQueryView.cs
ApsimNG/Views/CLEM/PivotTableView.cs
Models/CLEM/Reporting/CustomQuery.cs
Models/CLEM/Reporting/PivotTable.cs
Models/CLEM/Reporting/ReportActivitiesPerformed.cs

Fix for some CLEM reports not displaying properly

---

ApsimNG/ApsimNG.csproj

Re-add license file as embedded resource

---

ApsimNG/Commands/ChangeProperty.cs

ChangePropertyCommand shouldn't select the changed model

---

Models/PMF/Arbitrator/Methods/NitrogenUptakeMethod.cs

N Uptake Underflow

---

ApsimNG/Resources/Glade/GridView.glade
ApsimNG/Views/GridView.cs

Fixed a few bugs in gtk3 gridview

---

ApsimNG/Classes/ScriptCompletionProvider.cs
ApsimNG/Views/CodeView.cs

Changed manager completion provider's activation mode

---

NuGet.config

Add nuget as default package source

---

ApsimNG/Presenters/DataStorePresenter.cs
ApsimNG/Views/GridView.cs

Fixed a crash/freeze in datastore UI

---

Jenkins/PullRequest/Jenkinsfile

Force jenkins stages to run on physical build agents.

---

Tests/UnitTests/Storage/DataStoreWriterTests.cs

Tentative fix for an intermittently failing unit test

---

ApsimNG/Presenters/ExplorerPresenter.cs

Slight refactor of the file-saving code in ExplorerPresenter

---

APSIM.Shared/APSIM.Shared.csproj
ApsimNG/ApsimNG.csproj
ApsimNG/Extensions/WidgetExtensions.cs
ApsimNG/Presenters/CLEM/MessagePresenter.cs
ApsimNG/Presenters/ManagerPresenter.cs
ApsimNG/Presenters/PropertyMultiModelPresenter.cs
ApsimNG/Views/CodeView.cs
ApsimNG/Views/MarkdownView.cs
ApsimNG/Views/PropertyMultiModelView.cs
ApsimNG/Views/TextInputView.cs
Docs/CreateDocumentation/CreateDocumentation.csproj
Models/CLEM/Activities/RuminantActivityPredictiveStocking.cs
Models/CLEM/Activities/RuminantActivityPredictiveStockingENSO.cs
Models/CLEM/Reporting/ReportActivitiesPerformed.cs
Models/CLEM/Resources/SpecifyRuminant.cs
Models/Models.csproj
Tests/UnitTests/UnitTests.csproj

@lie112 just fyi, I've touched a few clem files, to fix some compiler warnings - mainly I've just removed the odd unused variable.

Fixed compiler warnings

---

ApsimNG/Presenters/CLEM/CLEMSummaryPresenter.cs
ApsimNG/Presenters/CLEM/LabourAllocationPresenter.cs
Models/CLEM/Common.cs
Models/CLEM/Reporting/ReportActivitiesPerformed.cs
Models/CLEM/Reporting/ResourceTransaction.cs
Models/CLEM/Resources/AnimalFoodStoreType.cs
Models/CLEM/Resources/CommonLandFoodStoreType.cs
Models/CLEM/Resources/EquipmentType.cs
Models/CLEM/Resources/FinanceType.cs
Models/CLEM/Resources/GrazeFoodStoreType.cs
Models/CLEM/Resources/GreenhouseGasesType.cs
Models/CLEM/Resources/HumanFoodStoreType.cs
Models/CLEM/Resources/LabourType.cs
Models/CLEM/Resources/LandType.cs
Models/CLEM/Resources/OtherAnimalsType.cs
Models/CLEM/Resources/ProductStoreType.cs
Models/CLEM/Resources/ProductStoreTypeManure.cs
Models/CLEM/Resources/RuminantHerd.cs
Models/CLEM/Resources/WaterType.cs

CLEM Refactor resource transaction to provide style and amount

---

Models/CLEM/Common.cs
Models/CLEM/Reporting/ResourceTransaction.cs
Models/Core/ScriptCompiler.cs

Fixed some compiler warnings which are now errors.

---

Models/Soils/SWIM/Swim.cs

Uncommented swims knowledge of irrigation

---

Models/CLEM/Activities/RuminantActivityManage.cs
Models/CLEM/Activities/RuminantActivityMarkForSale.cs
Models/CLEM/Common.cs
Models/CLEM/Resources/Labour.cs

Allow custom sale flag to be set when marking ruminants in CLEM

---

Docs/content/Usage/Memo.md

Tweak example in memo docs

---

ApsimNG/ApsimNG.csproj
ApsimNG/Views/MapView.cs

This entails providing a UserAgent, and caching downloaded files.
Working on #6171

Meet OpenStreetMap usage requirements.

---

Models/Core/AutoDocumentation.cs

Change autodocs to insert 2 newlines between array values

---

Models/Soils/IPhysical.cs
Models/Soils/Physical.cs
Models/Soils/Standardiser/Layers.cs

Implement MapConcentration on soil particle size properties

---

Models/Core/Alias.cs

Alias autodocs should show what it is an alias for.

---

Models/Core/ApsimFile/Converter.cs
Tests/UnitTests/Core/ApsimFile/ConverterTests.cs
Tests/UnitTests/Core/ApsimFile/Soil.json

Fixed converter code which adds initial water to soil.

---

ApsimNG/Menus/ContextMenu.cs
ApsimNG/Views/TreeView.cs

Fix toggling enabled on resource models in UI.

---

ApsimNG/Views/GridView.cs

Remove scrollbar from frozen column in gtk2 builds.

---

Models/Soils/SWIM/Swim.cs

Make pond outputtable
resolves #6305 
please merge this jenkins

Make Pond public

---

ApsimNG/Presenters/CLEM/ReportPivotPresenter.cs
Models/CLEM/Reporting/ReportPivot.cs

An inability to handle null / missing data under certain conditions was preventing the component from being generated.
Resolves #6283

Fixed ReportPivot data tab disappearing

---

ApsimNG/Menus/ContextMenu.cs

Don't call OnCreated() after enabling a model in the gui.

---

Models/Management/Manager.cs

Fixed bug in manager code for setting params in script

---

APSIM.bib

Add references to bib file for pinus model

---

Docs/content/Usage/Memo.md

Fixed typo in memo usage instructions.

---

Tests/Validation/Stock/Stock.apsimx

Upgrade stock validation to use nutrient.

---

ApsimNG/Views/IntellisenseView.cs

Fixed a gtk warning occurring when intellisense popup is shown

---

Docs/content/Development/_index.md

Added extra dot point to documentation as per RP suggestion.

---

Models/Graph/Regression.cs

Allow regression nodes to be placed directly on graphs

---

ApsimNG/Presenters/LegendPresenter.cs

Fixed initialisation of LegendView

---

APSIM.Shared/Utilities/ReflectionUtilities.cs
Models/Core/Apsim.cs

Fixed 'add model' bug on macos

---

ApsimNG/Interfaces/IPropertyView.cs
ApsimNG/Presenters/ManagerPresenter.cs
ApsimNG/Presenters/SimplePropertyPresenter.cs
ApsimNG/Views/PropertyView.cs

SimplePropertyPresenter: save changes when detached

---

Models/Core/Links.cs

Improved error message when ancestor link can't be resolved.

---

ApsimNG/Menus/ContextMenu.cs

Need to build manager scripts after enabling them.

---

ApsimNG/Commands/DeleteModelCommand.cs

Tweaked order of operations in delete model command

---

ApsimNG/Views/GraphView.cs

Don't draw a box around graph annotations

---

ApsimNG/Views/TreeView.cs

Increased icon size in treeview in gtk3 builds

---

ApsimNG/App.config
ApsimNG/ApsimNG.csproj

Changed ApsimNG project to use server mode GC

---

ApsimNG/Views/PropertyView.cs

Property UI should hide itself if no properties are visible

---

ApsimNG/Presenters/DataStorePresenter.cs
Models/Storage/DataStoreReader.cs

Fixes some DataStoreReader and Presenter bugs caused by my earlier PR.

---

ApsimNG/Presenters/GraphPanelPresenter.cs
Models/Storage/DataStoreReader.cs
Models/Storage/IStorageReader.cs
Tests/UnitTests/Storage/MockStorage.cs
Tests/UnitTests/TextStorageReader.cs

Fixed the GetSimulationID() function in DataStoreReader

---

ApsimNG/ApsimNG.csproj

Remove winforms reference from ApsimNG.csproj

---

APSIM.Shared/Utilities/MathUtilities.cs
Models/Graph/Regression.cs

Fixed a bug where regression line was longer than it should be

---

ApsimNG/Presenters/DataStorePresenter.cs

Fix row filter in report / data store presenter

---

Models/Core/ApsimFile/Converter.cs

Fixed converter function 127 when memo text is not set

---

Models/Map.cs

Map component should only display dots for enabled weathers

---

ApsimNG/Utility/FindAndReplaceForm.cs
ApsimNG/Views/CodeView.cs

Implement find/replace in .Net Core editing

---

Models/Graph/Regression.cs

Fixed wheat autodocs

---

Models/Storage/DataStoreReader.cs

Produce better error message when SimulationID column doesn't contain integer.
Resolves #6347

Fixed graph filters to allow SimulationName in filters.

---

ApsimNG/Presenters/MainPresenter.cs
Models/Core/Simulation.cs
Models/Core/SimulationException.cs
Models/Functions/AccumulateAtEvent.cs
Models/Functions/TrackerFunction.cs
Tests/UnitTests/Core/Run/SimulationTests.cs

Improved error handling when cleaning up after a simulation run

---

APSIM.Shared/Utilities/SQLite.cs
Models/Graph/SeriesDefinition.cs
Tests/UnitTests/TextStorageReader.cs

Fixed graph 'vary by' feature

---

ApsimNG/Views/PropertyView.cs

Fixed gtk warning in gtk2 builds.

---

Examples/Barley.apsimx

Corrected series name

---

Jenkins/Installation/Jenkinsfile
Jenkins/runTests.bat

This will fix CreateInstallation jobs on jenkins.
Working on #5606

Fixed output path in jenkins build script

---

ApsimNG/Classes/PDFWriter.cs
Docs/CreateDocumentation/Program.cs

Fixed path to apsim directory in CreateDocumentation project

---

Models/PMF/Cultivar/Cultivar.cs
Models/PMF/Cultivar/CultivarFolder.cs
Models/PMF/OilPalm/OilPalm.cs
Models/PMF/Plant.cs

Fixed cultivar names returned by Plant

---

APSIM.Shared/Utilities/ReflectionUtilities.cs

Fixed a bug in DynamicContractResolver

---

Models/Climate/Weather.cs
Models/PMF/Arbitrator/Methods/C4WaterUptakeMethod.cs
Models/PMF/Organs/SorghumLeaf.cs
Models/PMF/Phenology/Phases/EmergingPhase.cs
Models/PMF/Phenology/Phenology.cs
Models/PMF/Plant.cs
Models/PMF/Structure/LeafCulms.cs
Models/Soils/WaterModel/Runoff.cs

Fixed several models which weren't zeroing themselves correctly at start of simulation

---

Models/PMF/Organs/Leaf.cs
Models/Soils/SoilTemp/CERESSoilTemperature.cs

Get a wheat simulation running back-to-back without state carryover.

---

Models/Soils/SWIM/Swim.cs

Fix SWIM UI in .net framework builds.

---

Docs/content/Contribute/Compile/linux.md

Update linux compilation instructions

---

Models/Graph/EventNamesOnGraph.cs

Fixed event names on graph when under an experiment

---

Docs/CreateDocumentation/Documentation.json

Generate chickpea autodocs

---

ApsimNG/Menus/ContextMenu.cs
ApsimNG/Presenters/ExplorerPresenter.cs
Models/Core/Run/GenerateApsimXFiles.cs
Models/Management/Manager.cs
Tests/UnitTests/Core/Run/GenerateApsimXFilesTests.cs

Resolves #6404 
I've also changed the UI code here slightly so that the UI remains responsive (with a progress bar) while the .apsimx files are generated in the background.

Fixed bug in 'generate .apsimx files'

---

Setup/netcoreapp3.1/debian/buildDebianInstaller
Setup/netcoreapp3.1/macos/buildMacInstaller

Compress the debian/mac .net core installers

---

Models/Core/Run/SimulationDescription.cs
Models/Graph/Series.cs

Bandaid solution for 'X is not marked as serializable' error

---

APSIM.bib

Add some euc references to bib file for Phil

---

APSIM.Shared/Utilities/ReflectionUtilities.cs
Models/Core/VariableProperty.cs
Tests/UnitTests/Core/ApsimFile/EditFileTests.cs

Allow generic List/IEnumerable properties to be modified via CLI

---

Tests/Validation/Barley/Barley.apsimx

Add sowing report to all simulations.

---

Setup/Linux/BuildDeb.bat
Setup/osx/BuildMacDist.bat

Fixed a bug in Debian/MacOS installer scripts

---

ApsimNG/Views/BubbleChartView.cs

Improved the layout of the rotation manager UI in gtk3 builds.

---

APSIM.Shared/Utilities/ApsimTextFile.cs

Fixed a bug in the textfile reader's detection of end-of-file

---

ApsimNG/Intellisense/CodeCompletionService.cs

Don't include VisualBasic assemblies in code completion.

---

APSIM.Shared/Utilities/PathUtilities.cs
ApsimNG/Views/UpgradeView.cs

Fixed crashes which were occurring while upgrading on windows

---

Models/Resources/Barley.json
Tests/Validation/Barley/Barley.apsimx

Add emergence date for barley

---

APSIM.bib

Added references for pinus documentation to bib file

---

ApsimNG/Classes/PDFWriter.cs
ApsimNG/Presenters/FolderPresenter.cs
ApsimNG/Presenters/GraphPanelPresenter.cs
ApsimNG/Presenters/GraphPresenter.cs
Models/Core/ApsimFile/FileFormat.cs
Models/Core/Folder.cs
Models/Graph/EventNamesOnGraph.cs
Models/Graph/Graph.cs
Models/Graph/GraphPage.cs
Models/Graph/IGraphable.cs
Models/Graph/Regression.cs
Models/Graph/Series.cs
Models/Graph/SeriesDefinition.cs
Models/Graph/ShadedBarsOnGraph.cs
Models/Storage/DataStoreReader.cs
Models/Storage/IStorageReader.cs
Tests/UnitTests/Graph/SeriesTests.cs
Tests/UnitTests/GraphTests.cs
Tests/UnitTests/Storage/MockStorage.cs
Tests/UnitTests/TextStorageReader.cs

Speed up graphs in GUI

---

Models/Core/Run/SimulationGroup.cs
Models/Optimisation/CroptimizR.cs
Models/Storage/AddCheckpointCommand.cs
Models/Storage/CleanCommand.cs
Models/Storage/DataStoreWriter.cs
Models/Storage/IDataStore.cs
Models/Storage/IStorageWriter.cs
Models/Storage/WriteTableCommand.cs
Tests/UnitTests/Storage/DataStoreWriterTests.cs
Tests/UnitTests/Storage/MockStorage.cs

Datastore writer speedup

---

ApsimNG/Presenters/ProfileGridPresenter.cs
ApsimNG/Presenters/ProfilePresenter.cs
Models/Core/Run/SimulationDescription.cs
Models/Core/Simulation.cs
Tests/UnitTests/Core/Run/SimulationDescriptionTests.cs
Tests/UnitTests/Soils/SoilStandardiserTests.cs

- Disabled soils shouldn't cause errors when the simulation is run
- Need to be able to edit faulty soils in the gui
Resolves #6341

Fixed a few soil-related bugs

---

Models/Soils/SWIM/Swim.cs

Fixed SWIM layering

---

Setup/netcoreapp3.1/windows/apsimx.iss

Changed netcore windows installer to download/install gtk3 deps (if required)

---

Examples/Pinus.apsimx

Update Pinus documentation and create Pinus example

---

ApsimNG/Presenters/MainPresenter.cs
Models/Core/Run/SimulationGroup.cs
Models/Core/Simulations.cs

Remove accidentally-committed changes to Simulations class.

---

Jenkins/runTests.bat

Changed jenkins createinstall job to run .net core apsim

---

ApsimNG/Main.cs
ApsimNG/Resources/Style/global.css

Improve scrollbar appearance in gtk3 builds

---

Models/PMF/Library/BiomassRemoval.cs
Models/Surface/ResidueTypes.cs

Add explicit error message when PlantType is null

---

Models/Core/Simulations.cs

Need to always call Simulation.Prepare() before resolving links.

---

Models/Core/Run/SimulationGroup.cs
Models/Storage/DataStoreWriter.cs
Models/Storage/IStorageWriter.cs
Tests/UnitTests/Storage/MockStorage.cs

Allow DataStoreWriter to queue a clean operation without running it

---

ApsimNG/Classes/PDFWriter.cs
Models/Graph/SeriesDefinition.cs
Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx

Fixed broken graphs which were causing autodocs failures

---

ApsimNG/Presenters/ExplorerPresenter.cs

This only fixes the problem in gtk3 builds.
Working on #6590.

After opening a file, ensure that the root node is selected

---

ApsimNG/Views/LegendView.cs
ApsimNG/Views/TreeView.cs

Refactor TreeView, to avoid calls to TreeIter.Equals()

---

Docs/CreateDocumentation/CreateDocumentation.csproj
Docs/CreateDocumentation/Program.cs
Models/Storage/DataStoreReader.cs

Also fixed case sensitivity in DataStoreReader.GetData.
Working on #6591

Changed CreateDocumentation to command line app & added elapsed times

---

Models/Core/Simulations.cs

Working on #6591 (I won't say resolves, as this is basically a bandaid solution)

Manually stop the datastore writer before generating autodocs

---

Models/Graph/Graph.cs

Remove problem graph in wheat

---

ApsimNG/Views/MainView.cs

Don't allow unknown fonts to cause the UI to crash.

---

APSIM.Shared/Extensions/CollectionExtensions.cs
ApsimNG/Cloud/Azure/AzureInterface.cs
ApsimNG/Presenters/ExplorerPresenter.cs
Models/Core/Run/GenerateApsimXFiles.cs
Tests/UnitTests/Core/Run/GenerateApsimXFilesTests.cs

When generating .apsimx files, allow caller to specify number of sims per file

---

ApsimNG/Utility/FileDialog.cs

When saving files, apply the filter's file extension

---

Models/CLEM/Activities/RuminantActivityGrow.cs
Models/CLEM/CLEMModel.cs
Models/CLEM/Reporting/ReportResourceBalances.cs
Models/CLEM/Reporting/ReportResourceLedger.cs
Models/CLEM/Resources/Ruminant.cs
Models/CLEM/ZoneCLEM.cs
Models/Report/Report.cs
Tests/Validation/CLEM/CLEM_Sensibility_IndividualAnimal.apsimx

Provide a number of new properties to the ReportResourceBalanaces for economic reporting
Add memo to summary description and clean up Ruminant individual as added to Help system.
working on #6632

Updates the balance report for economic output

---

ApsimNG/Utility/FileDialog.cs

Fix bug with saving over existing files

---

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx

Update TreeManagement rule in management toolbox

---

Tests/UnderReview/Chickpea/Chickpea.apsimx

Replaced SoilNitrogen with Nutrient

---

Setup/netcoreapp3.1/windows/apsimx.iss

Fixed a bug in windows .net core installer

---

Models/Graph/GraphPage.cs
Models/Graph/Series.cs
Tests/UnitTests/Graph/SeriesTests.cs

Fixed a bug in GraphPage

---

Examples/Eucalyptus.apsimx
Examples/EucalyptusRotation.apsimx
Models/Resources/Eucalyptus.json
Prototypes/SoilTemperature/SoilTemperature.apsimx
Tests/Simulation/Initialisation/EucalyptusRotation.apsimx

Move eucalyptus model from replacements to resource file

---

Models/Resources/Chickpea.json

Updated the version number in chickpea resource file

---

CITATION.cff

Try again to get citation parsed

---

CITATION.cff

Remove quotes from citation file.

---

ApsimNG/Views/Sheet/PagedDataProvider.cs
Models/Graph/Regression.cs
Models/Storage/DataStoreWriter.cs
Models/Storage/WriteTableCommand.cs

Resolves #6699
Resolves #6697
This is basically a bandaid. We really need more informative errors in the graphing pipeline, however I don't have time to do that right now.

Fixed 'x is empty' error in p/o graphs

---

ApsimNG/Presenters/MainPresenter.cs
Models/Core/ApsimFile/FileFormat.cs
Models/Storage/DataStore.cs

Files should open in GUI despite errors in .db file

---

Models/Core/Events.cs

Add more helpful error message for invalid event handler delegate types

---

ApsimNG/Views/Sheet/SheetWidget.cs

Fixed a crash caused by resizing SheetWidget to small sizes

---

ApsimNG/Presenters/MainPresenter.cs

Improved resource path resolution in 'upgrade files' feature

---

Jenkins/Installation/Jenkinsfile
Jenkins/runTests.bat

Release builds need to extract cornsoy dataset to build autodocs.

---

Models/Core/IReferenceExternalFiles.cs
Models/Core/Simulations.cs

Disabled models can't reference external files.

---

Models/PMF/Organs/EnergyBalance.cs

EnergyBalance zero variables

---

ApsimNG/Commands/RunCommand.cs
ApsimNG/Menus/ContextMenu.cs

Ensure that simulation errors are always displayed in GUI runs

---

Models/Core/Run/SimulationGroup.cs
Tests/UnitTests/Core/Run/RunnerTests.cs
Tests/UnitTests/Storage/MockStorage.cs

Only run post-simulation tools if they are in scope of a simulation which was run

---

Examples/Pinus.apsimx

Copied TreeThinning and modified as TreeThinningFromAboveOrBelow and included it unused in the BFG simualtion for the validation and used as a modified Control treatment in the example.
Working on #6058

Pinus modifications to address review comments and finalise for release

---

Examples/Pinus.apsimx

Working on #6746
Merge please
In the example, I removed the Pinus model from Replacements and updated the version in the base simulation.
Improved the Note

Pinus example update

---

Models/Climate/Weather.cs
Models/Interfaces/IWeather.cs

CO2 should be read from met file (if available)

---

Models/AgPasture/GenericTissue.cs
Models/AgPasture/PastureAboveGroundOrgan.cs
Models/AgPasture/PastureBelowGroundOrgan.cs
Models/AgPasture/PastureSpecies.cs
Models/AgPasture/RootTissue.cs

Working on #6767 
Starting with changes aimed at tidying up the code a bit, fixing type, deleting superfluous comments and updating doco tags. Also deleted a few variables/parameters no longer used.
Few minor changes to variable names to come

Update and fixes to AgPasture

---

APSIM.Shared/Utilities/MathUtilities.cs
Models/Soils/SWIM/Swim.cs

Fixed a problem with SWIM divide tolerance

---

Models/Core/Locator.cs
Tests/UnitTests/Core/LocatorTests.cs

Fixed reporting of properties of abstract properties

---

Tests/UnitTests/Core/SimulationResetTests.cs

Prevent simulation reset tests from running unnecessarily

---

Models/Core/ScriptCompiler.cs

Allow manager scripts to references System.IO.Pipes.dll

---

Setup/netcoreapp3.1/macos/launcher.sh

Mac installer launcher script should set GSETTINGS_SCHEMA_DIR

---

Setup/netcoreapp3.1/macos/buildMacInstaller

Need to publish Models project after others when building OSX installer

---

ApsimNG/Views/Sheet/PagedDataProvider.cs
Models/Storage/DataStoreReader.cs

Allow for spaces in DataStore table names.

---

ApsimNG/Commands/RunCommand.cs
ApsimNG/Presenters/MainPresenter.cs

Fixed race condition in simulation error reporting in GUI.

---

Examples/CLEM/CLEM_Example_Cropping.apsimx
Examples/CLEM/CLEM_Example_Grazing.apsimx
Models/CLEM/Activities/RuminantActivityBreed.cs
Models/CLEM/ZoneCLEM.cs

Fixed passing null male when no inheritance needed

---

Docs/content/Contribute/Compile/linux.md
Setup/netcoreapp3.1/debian/control

Update debian binary package dependencies

---

ApsimNG/Views/GridView.cs

Fixed GridView cell selection in empty but expandable grid

---

ApsimNG/Menus/MainMenu.cs
ApsimNG/Views/SeriesView.cs

Fixed help buttons in gui.

---

APSIM.Documentation/Models/DocumentationTable.cs
APSIM.Documentation/Program.cs

Don't rely on relative paths in documentation website.

---

ApsimNG/Presenters/CultivarPresenter.cs

Fixed bug which prevents editing an empty cultivar.

---

APSIM.Server/ApsimServer.cs
APSIM.Server/Cli/GlobalServerOptions.cs
APSIM.Server/IO/NetworkConnectionManager.cs

Apsim server: allow user-configurable number of pending connections
