APSIMInitiative/ApsimX

ApsimNG/Views/CLEM/CLEMView.cs, ApsimNG/Views/CLEM/ModelDetailsWrapperView.cs, ApsimNG/Views/MarkdownView.cs, ApsimNG/Views/PropertyView.cs
=> Implement padding to property and markdown presenter

ApsimNG/Resources/Style/global.css, ApsimNG/Views/PropertyView.cs
=> Fixed separator lines' background colour in property UI.

Models/Soils/Nutrients/Nutrient.cs
=> Fixed location of solute nodes in nutrient directed graphs

APSIM.Shared/Utilities/DataTableUtilities.cs, Models/Graph/GraphPage.cs, Tests/UnitTests/Graph/SeriesTests.cs, Tests/UnitTests/Storage/MockStorageReader.cs
=> Allow tables with no SimulationID column to be shown on graphs

Models/Graph/Series.cs
=> Bugfix for EventNamesOnGraph

Models/Core/Folder.cs, Models/Core/Simulation.cs
I think this is going to be a problem with the new autodocs system...
Resolves #6894.
=> Maps should be included in autodocs in more contexts.

ApsimNG/Menus/ContextMenu.cs
=> Improvements to 'excel export' feature

ApsimNG/Presenters/XYPairsPresenter.cs, ApsimNG/Views/GridView.cs
=> Improvements to XYPairs UI

ApsimNG/Views/CodeView.cs
=> Fixed completion items involving swim3

ApsimNG/Presenters/FolderPresenter.cs
=> Don't attempt to draw graphs if file doesn't contain a datastore.

ApsimNG/Presenters/FolderPresenter.cs, ApsimNG/Views/GraphView.cs
=> Disable zooming with scroll wheel on graphs in folder

APSIM.Shared/Utilities/ExpressionEvaluator.cs
=> Added ceil function to report's expression parser

Models/PMF/Organs/Root.cs
=> Fix NUptakeLayers

ApsimNG/Presenters/GraphPanelPresenter.cs
=> Fixed graph panel not using cache when fixing axes

Models/Mapping/Coordinate.cs
Working on #6891 
But there are other problems to be fixed when running under Windows.
=> Allow map coordinates to deserialize.

Models/Resources/Barley.json
=> Add alias for barley cultivar

Models/CLEM/Activities/CropActivityManageCrop.cs, Models/CLEM/Activities/CropActivityManageProduct.cs, Models/CLEM/Market.cs, ModelsAndNGSolution.slnf
=> CLEM correct descriptive summary for market model

Models/Resources/Eucalyptus.json, Models/Resources/Pinus.json
=> Explicit name inserted for fine root

Models/AgPasture/PastureSpecies.cs
=> Make PastureSpecies a scoped model

ApsimNG/Presenters/SummaryPresenter.cs, Models/Summary.cs
=> Summary GUI shouldn't show an error when DB is missing

Models/Models.csproj
Resolves #6957 
The actual fix is in the first commit...I decided to clean up a few redundant parts of the file while I was here.
=> Ensure that sqlite binary is copied when executing a dotnet publish command

ApsimNG/Views/CodeView.cs
=> Better default editor style on windows

ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Presenters/ReportPresenter.cs, ApsimNG/Presenters/SoilDownloadPresenter.cs, ApsimNG/Utility/FileDialog.cs, ApsimNG/Views/CodeView.cs, ApsimNG/Views/MainView.cs, ApsimNG/Views/UpgradeView.cs
=> Changes to user settings should be saved immediately

ApsimNG/Presenters/CLEM/MessagePresenter.cs, Models/CLEM/Activities/CropActivityManageProduct.cs, Models/CLEM/Activities/ResourceActivityManageExternal.cs, Models/CLEM/Activities/RuminantActivityBreed.cs, Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/Activities/RuminantActivityPredictiveStockingENSO.cs, Models/CLEM/DataReaders/FilePricing.cs, Models/CLEM/DataReaders/FileSQLitePasture.cs, Models/CLEM/Extras/Transmute.cs, Models/CLEM/Extras/WarningLog.cs, Models/CLEM/Groupings/FilterByProperty.cs, Models/CLEM/Market.cs, Models/CLEM/Reporting/ReportPivot.cs, Models/CLEM/Resources/CLEMResourceTypeBase.cs, Models/CLEM/Resources/ResourcesHolder.cs, Models/CLEM/Resources/RuminantType.cs, Models/CLEM/Resources/RuminantTypeCohort.cs, Models/CLEM/ZoneCLEM.cs
Resolves #6976
Updates CLEM message presenter to take advantage of new message reporting to summary with MessageType
=> Warning reporting

Models/Core/ApsimFile/Converter.cs
=> Fixed bug in forages converter

APSIM.Interop/Documentation/PdfWriter.cs, ApsimNG/Views/UpgradeView.cs, Setup/netcoreapp3.1/debian/buildDebianInstaller, Setup/netcoreapp3.1/macos/buildMacInstaller
=> Changes to support incrementing version number

Models/Graph/SeriesDefinition.cs, Tests/UnitTests/Graph/SeriesTests.cs, Tests/UnitTests/TextStorageReader.cs
=> Fix bug where the graph doesn't display due to exception

APSIM.Cli/Program.cs
=> Added CLI run functionality for apsim.dll

Models/Graph/GraphPage.cs
=> Graphing error messages should mention checkpoint name.

ApsimNG/Presenters/MainPresenter.cs
Resolves #5955. Also relevant to #6999, which is what prompted me to finally implement this.
=> Better display of composite exceptions in the GUI

ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Views/UpgradeView.cs
=> Fix upgrade UI - custom build can be detected by Build == 0

Tests/Validation/SoilArbitrator/SoilArbitrator.apsimx
=> Fix graph colours in soil arbitrator graphs.

Models/Core/ApsimFile/Converter.cs
=> Fixed upside-down soil graphs in GUI

Models/Soils/InitialWater.cs
Resolves #7012 
@hol353 - how is this supposed to work? Has this ever worked?
=> Fixed crash caused by adding initial water to GUI.

Models/Management/Irrigation.cs
=> Fix for IrrigationApplied variable when 2 irrigations happen on same day

Tests/UnitTests/Server/ManagedSocketConnectionTests.cs, Tests/UnitTests/Weather/WeatherTests.cs
=> Fixed race condition in weather file unit test.

Models/PostSimulationTools/SerialPostSimulationTool.cs, Tests/UnderReview/Sorghum/Sorghum.apsimx
=> Speedup for sorghum validation

Tests/Validation/Nutrient/Nutrient.apsimx
=> Fixed output in Nutrient test for Incubation experiment

Models/CLEM/Groupings/FilterByProperty.cs, Models/CLEM/Groupings/FilterGroup.cs, Models/CLEM/Reporting/ReportResourceBalances.cs, Models/CLEM/Resources/GrazeFoodStoreType.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantHerd.cs
=> Fix errors thrown by CLEM custom reports

Models/CLEM/Activities/ActivityTimerInterval.cs, Models/CLEM/Activities/OtherAnimalsActivityBreed.cs, Models/CLEM/Activities/RuminantActivityHerdCost.cs, Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/Activities/RuminantActivityMarkForSale.cs, Models/CLEM/Common.cs, Models/CLEM/Extras/Validation.cs, Models/CLEM/Resources/RuminantType.cs, Models/CLEM/ZoneCLEM.cs
=> Use HerdChangeReason flag throughout CLEM

APSIM.Interop/Graphing/CustomSeries/ColumnXYSeries.cs
Resolves #5615 (the bar chart problem is the only item in this issue which hasn't already been fixed).
=> Fixed tracker labels in bar graphs

APSIM.Interop/Drawing/IDrawContext.cs, APSIM.Interop/Drawing/Skia/SkiaContext.cs, APSIM.Interop/Visualisation/DGObject.cs, ApsimNG/Views/Sheet/CairoContext.cs
=> Directed graphs in GUI should use the user-selected font.

Setup/netcoreapp3.1/debian/buildDebianInstaller, Setup/netcoreapp3.1/macos/buildMacInstaller
=> Use full version in Linux/mac releases

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/GraphPanelPresenter.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Views/GraphPanelView.cs, ApsimNG/Views/GraphView.cs
- Make better use of new GraphPage API
- Speed up axis standardisation
Resolves #6942.
Working on #572.
=> Graph panel improvements

Models/Factorial/Factor.cs, Tests/UnitTests/Factorial/FactorTests.cs
=> Bugfix + unit test for unbounded factor specification.

ApsimNG/Main.cs
=> Slight improvement to logging when running gui.

ApsimNG/Presenters/GraphPresenter.cs
=> Fix graph annotation colours in dark mode

Models/Summary.cs, Tests/UnitTests/SummaryTests.cs
=> Allow summary to write messages during the Completed event

ApsimNG/ApsimNG.csproj, ApsimNG/Interfaces/IMainView.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Views/MainView.cs, ApsimNG/Views/PropertyView.cs
=> Improve focus/selection handling in property UI

Models/CLEM/Activities/LabourActivityFeedTargetPurchase.cs, Models/CLEM/Activities/LabourActivityFeedToTargets.cs, Models/CLEM/Activities/ResourceActivityFee.cs, Models/CLEM/Activities/ResourceActivitySell.cs, Models/CLEM/Resources/FinanceType.cs, Models/CLEM/Resources/Labour.cs, Models/CLEM/Resources/LabourType.cs
=> Allow cohort based feeding of people and fix feeding logic during validation

APSIM.Shared/Utilities/SoilUtilities.cs
Working on #7030
@hol353 - this isn't ideal, but it does help. Let me know what you think.
=> Alleviate floating point arithmetic problems in soil depth strings

APSIM.Shared/Properties/AssemblyInfo.cs, APSIM.Shared/Utilities/StreamReaderRandomAccess.cs, Tests/UnitTests/APSIMShared/StreamReaderRandomAccessTests.cs
=> Bugfix + unit test for random access stream reader

Models/PostSimulationTools/Filter.cs
=> Filter GUI should allow column filter to be input as one value per line

ApsimNG/Views/MainView.cs
=> Ensure that calls to hide the progress bar in GUI occur on main thread.

ApsimNG/ApsimNG.csproj
=> Use same version of GtkSourceSharp and GtkSharp.

Models/Core/ApsimFile/Structure.cs, Tests/UnitTests/Core/ApsimFile/StructureTests.cs
=> Ensure that models added to simulation at runtime can cause errors

ApsimNG/Views/DirectedGraphView.cs
=> Fixed colours in directed graphs in light mode

ApsimNG/Hotkeys/Hotkey.cs, ApsimNG/Hotkeys/IHotkey.cs, ApsimNG/Hotkeys/IHotkeySource.cs, ApsimNG/Hotkeys/KeyboardShortcutsView.cs, ApsimNG/Hotkeys/Sources/MainMenuHotkeys.cs, ApsimNG/Menus/MainMenu.cs, ApsimNG/Resources/MenuImages/Run.svg, ApsimNG/Views/HelpView.cs
Resolves #6257.
Also added keyboard shortcuts info to the help button on the home screen (@byzheng fyi).
=> F5 to run from anywhere

Setup/netcoreapp3.1/windows/apsimx.iss
=> Bump gtk runtime version downloaded by installer.

APSIM.Server/APSIM.Server.csproj, APSIM.Server/Cli/GlobalServerOptions.cs, APSIM.Server/Properties/AssemblyInfo.cs, APSIM.Server/Properties/AssemblyVersion.cs, ApsimNG/Properties/AssemblyInfo.cs, Models/Properties/AssemblyInfo.cs, Models/Properties/AssemblyVersion.cs
=> Fixed server backlog CLI option initialiser

ApsimNG/Presenters/CLEM/PropertyCategorisedPresenter.cs, Models/CLEM/Activities/LabourActivityFeedTarget.cs, Models/CLEM/Activities/LabourActivityFeedToTargets.cs, Models/CLEM/Groupings/FilterByAttribute.cs, Models/CLEM/Groupings/FilterByProperty.cs, Models/CLEM/Groupings/FilterGroup.cs, Models/CLEM/Groupings/SortByAttribute.cs, Models/CLEM/Groupings/SortByProperty.cs, Models/CLEM/Groupings/SortRandom.cs, Models/CLEM/Groupings/TakeFromFiltered.cs, Models/CLEM/Interfaces/IFilterGroup.cs, Models/CLEM/Reporting/ReportResourceLedger.cs, Models/CLEM/Resources/LabourType.cs, Models/CLEM/Resources/RuminantHerd.cs, Models/CLEM/ZoneCLEM.cs, Models/Clock.cs
=> Human feeding implements energy target based feeding of households

Models/Core/SimulationException.cs, Tests/UnitTests/APSIMShared/ReflectionUtilitiesTests.cs
=> Fixed binary deserialization of SimulationException.

APSIM.Server/RelayServer.cs
=> Change server to allow for per-pod port number

ApsimNG/Views/GridView.cs
=> Fixed crash caused by double-disposal of accelerators in GridView

Models/Soils/SWIM/Swim.cs
=> Added flow, leach and subsurfacedrain solute variables to swim

ApsimNG/Views/CodeView.cs
=> Fixed scrolling in manager editor after clicking enter

ApsimNG/Menus/MainMenu.cs, ApsimNG/Views/CodeView.cs
=> Fix hotkey conflicts in editor view

Models/Management/Operations.cs
(e.g. RemoveBiomass in AgPasture) from operations.
Resolves #7132
=> Add ability to call overloaded methods

APSIM.Server/IO/NativeCommunicationProtocol.cs, Tests/UnitTests/Server/NativeSocketConnectionTests.cs
=> Add array support to apsim server feature.

ApsimNG/Presenters/SummaryPresenter.cs, Models/Summary.cs
=> Allow SummaryPresenter to display in the absence of any simulations.

ApsimNG/Presenters/PropertyMultiModelPresenter.cs, Examples/CLEM/CLEM_Example_Cropping.apsimx, Examples/CLEM/CLEM_Example_Grazing.apsimx, Examples/CLEM/CLEM_Sensibility_HerdManagement.apsimx, Models/CLEM/Activities/ActivityTimerCropHarvest.cs, Models/CLEM/Activities/CropActivityFee.cs, Models/CLEM/Activities/CropActivityManageCrop.cs, Models/CLEM/Activities/CropActivityManageProduct.cs, Models/CLEM/Activities/CropActivityTask.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantHerd.cs
=> Allows crop tasks between multi-harvest crops

Models/CLEM/Activities/RuminantActivityBuySell.cs, Models/CLEM/Extras/TransmuteRuminant.cs, Models/CLEM/Groupings/FilterGroup.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantHerd.cs, Models/CLEM/Resources/RuminantType.cs
=> Fixes dynamic animal pricing by head, weight, fixed

ApsimNG/Interfaces/IAxisView.cs, ApsimNG/Views/AxisView.cs, Examples/Tutorials/Report.apsimx, Models/AgPasture/SimpleGrazing.cs, Models/Functions/CSharpExpressionFunction.cs, Models/PMF/Interfaces/IFunction.cs, Models/Report/DateReportFrequency.cs, Models/Report/EventReportFrequency.cs, Models/Report/ExpressionReportFrequency.cs, Models/Report/Report.cs, Models/Resources/Scripts/CSharpBooleanExpressionTemplate.cs, Tests/Validation/Stock/Stock.apsimx
and fixes bug in scaling date axes. Resolves #7155
=> Added conditional reporting frequencies to report model. 

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Views/TreeView.cs
=> Treeview should grab focus after adding a model

ApsimNG/Presenters/MemoPresenter.cs
=> Fixed help button in markdown view

ApsimNG/Menus/MainMenu.cs
=> Save apsimx file when running from main menu

APSIM.Documentation/Models/DocumentationTable.cs, APSIM.Shared/Utilities/WebUtilities.cs, ApsimNG/Presenters/RunOnCloudPresenter.cs, ApsimNG/Views/HelpView.cs, ApsimNG/Views/UpgradeView.cs, Docs/content/ModelDocumentation/_index.md, Docs/docfx/index.md
=> Updating various links to point to new builds api

ApsimNG/Menus/ContextMenu.cs
=> Allow any model to be documented from gui

APSIM.Server/IO/NativeCommunicationProtocol.cs, APSIM.Shared/Utilities/PipeUtilities.cs, Tests/UnitTests/Server/NativeSocketConnectionTests.cs
Context: I have implemented a client, but couldn't receive variables that were dates or strings. This fixes that, at least for me.
Working on #6529
=> Create an APSIM Server protocol for sending strings and dates

Models/Report/DateReportFrequency.cs, Models/Report/EventReportFrequency.cs, Models/Report/ExpressionReportFrequency.cs
...as it was broken by recent changes to reporting code. See commit message for the reasoning behind this change.
Working on #6529.
=> Fixed reporting in apsim server runs

APSIM.Shared/Utilities/StringUtilities.cs
=> Fixed RemoveAfter and GetAfter stringutilities

Models/Functions/ExpressionFunction.cs, Models/Soils/Nutrients/CarbonFlow.cs, Models/Soils/Nutrients/Nutrient.cs
=> More consistency with memo documentation in nutrient docs.

Setup/netcoreapp3.1/macos/Info.plist
=> Fixed icon file name for mac installer

Models/Core/ApsimFile/XmlToJson.cs
=> Fix xml to json converter bug with case of soil crop parameterisations

ApsimNG/Classes/Property.cs, ApsimNG/Views/PropertyView.cs, Models/AgPasture/SimpleGrazing.cs
I still think this is probably a mistake and this PR shouldn't be merged. But it's here if you want it...
Resolves #7154.
=> Re-implement EnabledCallback feature in property presenter

Models/Functions/AccumulateAtEvent.cs, Models/Functions/AccumulateByDate.cs
=> Zeroed the accumulated values in 2 functions

ApsimNG/Views/MarkdownView.cs, Models/Core/AutoDocumentation.cs
=> Fixed sizing of model description in property UI

ApsimNG/Views/UpgradeView.cs
=> Fixed downgrading

Docs/content/ModelDocumentation/_index.md
=> Fixed link to documentation API endpoint from netlify site

Docs/content/Contribute/Compile/linux.md, Docs/content/Contribute/Compile/osx.md, Docs/content/Contribute/Compile/windows.md
=> Update compilation instructions

ApsimNG/Classes/Property.cs
=> Properties in settings dialog enabled by default.

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Menus/MainMenu.cs
=> Don't attempt to run empty folders

APSIM.Shared/Utilities/ProcessUtilities.cs
=> Fixed ProcessWithRedirectedOutput on MacOS

APSIM.Server/ApsimServer.cs, APSIM.Server/Program.cs, APSIM.Server/RelayServer.cs, APSIM.Server/ServerJobRunner.cs, APSIM.Shared/JobRunning/IRunnable.cs, APSIM.Shared/JobRunning/JobRunner.cs, APSIM.Shared/JobRunning/JobRunnerSleepJob.cs, Models/Core/Run/EmptyJob.cs, Models/Core/Run/SimulationDescription.cs, Models/Core/Simulation.cs, Models/Optimisation/CroptimizR.cs, Models/Report/ReportColumn.cs, Models/Storage/AddCheckpointCommand.cs, Models/Storage/CleanCommand.cs, Models/Storage/DeleteCheckpointCommand.cs, Models/Storage/DeleteRowsCommand.cs, Models/Storage/EmptyCommand.cs, Models/Storage/RevertCheckpointCommand.cs, Models/Storage/WriteTableCommand.cs, Tests/UnitTests/APSIMShared/MockJob.cs
=> Fixed a bug in report aggregation when using apsim server.

Models/Functions/SoilFunctions/CERESNitrificationModel.cs
=> created properties for michelis menton parameters

ApsimNG/Views/UpgradeView.cs
=> Fixed syntax in 'are you sure' dialog when upgrading

Models/Core/Zone.cs, Tests/UnitTests/SummaryTests.cs
=> Write a warning message if simulation doesn't contain microclimate

ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Views/TreeView.cs
=> Fixed drag-and-drop in GUI on MacOS

Models/Core/Locater.cs, Models/Core/Locator.cs, Tests/UnitTests/Report/ReportTests.cs
=> Fixed a bug in which report ran successfully when it should have failed

ApsimNG/Resources/Glade/InitialWaterView.glade
=> Increase initial width of initial water text input

ApsimNG/Presenters/AddModelPresenter.cs
=> Add model presenter: filter textbox grabs focus by default

ApsimNG/Classes/Property.cs, ApsimNG/Views/PropertyView.cs, Models/Core/Attributes/DisplayAttribute.cs
=> Provides ability to hide property widgets via VisibleCallback

Models/Report/ExpressionReportFrequency.cs
=> Fix bug in report frequency expression

Models/Soils/SWIM/Swim.cs, Prototypes/SWIM/SWIM3_Testing.apsimx
=> Fixing errors in initial Suction estimates

Models/Soils/SWIM/Swim.cs
=> fix to stop swim destroying water table pressure profiles

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx, Models/Soils/SWIM/Swim.cs
Also Added water table bottom BC to swim. 
Working on #1254
=> Added folders and updated scripts in manager toolbox.

Models/Functions/HourlyInterpolation.cs, Models/Functions/LinearInterpolationFunction.cs, Models/Functions/WeightedTemperatureFunction.cs
=> fixing inconsistencies with XYPairs presenter and documentation

Models/Core/Folder.cs, Models/Functions/CSharpExpressionFunction.cs
=> fixed harvest date

Models/Resources/Maize.json
=> New U.S. maize cultivars

Models/Utilities/R.cs
=> Don't  bother with trying to download and install R.

Setup/netcoreapp3.1/debian/buildDebianInstaller
=> Fixed bug in debian installer generator script

ApsimNG/Views/UpgradeView.cs
Working on #7039 
I'm hoping this will resolve the issue, but installer issues can be tricky to debug...
=> Change working directory from which installer is run

APSIM.Interop/Graphing/GraphExporter.cs, APSIM.Shared/Documentation/Graph.cs, APSIM.Shared/Graphing/IGraph.cs, Models/Functions/WeightedTemperatureFunction.cs, Models/Functions/XYPairs.cs, Models/Graph/Graph.cs, Tests/UnitTests/Interop/PdfBuilderTests.cs
to help with tracking down failed graphs on Jenkings
working on #7358
=> Added some diagnostics to documentation creation

Models/PMF/Plant.cs
resolves #7008
Added 'mm' units to row spacing on sowing.
It doesn't enforce that the units are in mm though.
=> Rowspacing units fix

ApsimNG/Presenters/FolderPresenter.cs, ApsimNG/Views/GraphView.cs
=> Graphfolder scroll

Models/Soils/TabularData.cs
=> Ensure the units displayed by GUI are updated when changed by the user.

Models/Core/ApsimFile/FileFormat.cs
=> Fix for problem with saving some .apsimx files

APSIM.Documentation/Models/DocsFromFile.cs, APSIM.Documentation/Models/DocumentationTable.cs, APSIM.Documentation/Models/ParamsDocsFromFile.cs, APSIM.Documentation/Program.cs, Models/Core/AutoDocumentation.cs
=> Model documentation-added ability to link to model videos

ApsimNG/Presenters/AddModelPresenter.cs, ApsimNG/Presenters/ExplorerPresenter.cs, Models/Core/ApsimFile/FileFormat.cs
=> Fixed add model function and icons in add model

Models/CLEM/Activities/ActivityFee.cs, Models/CLEM/Activities/CLEMRuminantActivityBase.cs, Models/CLEM/Activities/RuminantActivityBreed.cs, Models/CLEM/Activities/RuminantActivityBuySell.cs, Models/CLEM/Activities/RuminantActivityFeed.cs, Models/CLEM/Activities/RuminantActivityGrazePastureHerd.cs, Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/Activities/RuminantActivityMilking.cs, Models/CLEM/Activities/RuminantActivityShear.cs, Models/CLEM/Groupings/RuminantFeedGroup.cs, Models/CLEM/Reporting/ReportResourceShortfalls.cs, Models/CLEM/Resources/GrazeFoodStoreType.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantHerd.cs, Models/CLEM/Resources/RuminantTypeCohort.cs
=> Improved handling of weaners and orphans

ApsimNG/Presenters/DirectedGraphPresenter.cs, ApsimNG/Presenters/SoilDownloadPresenter.cs, Models/Core/ApsimFile/Converter.cs
=> Fixes for soil downloader

Models/CLEM/Activities/RuminantActivityGrazePastureHerd.cs, Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/Reporting/ReportPivot.cs
=> Fixes issues with poor suckling/weaner growth

Models/Soils/Nutrients/Nutrient.cs
=> Fix TotalC output in Nutrient so that carbon mass balance is maintained

Models/CLEM/Reporting/ReportPivot.cs, Models/CLEM/ZoneCLEM.cs, Models/Storage/DataStore.cs, Models/Storage/IDataStore.cs, Tests/UnitTests/Storage/MockStorage.cs
=> Implement fixes for pivot reports in experiments

Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/Activities/RuminantActivityPurchase.cs, Models/CLEM/Extras/Relationship.cs, Models/CLEM/Reporting/ReportResourceBalances.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantHerd.cs, Models/CLEM/Resources/RuminantTypeCohort.cs
=> Updated Ruminant Purchase activity in CLEM

ApsimNG/Menus/ContextMenu.cs
=> Fix show model strucutre only shows one level of models.

Models/Utilities/Accumulator.cs
=> Fix variable accumulator

Setup/netcoreapp3.1/debian/buildDebianInstaller, Setup/netcoreapp3.1/macos/buildMacInstaller, Setup/netcoreapp3.1/windows/apsimx.iss
=> Second attempt at creating releases when UnderReview folder is missing

Setup/netcoreapp3.1/windows/apsimx.iss
=> Third attempt to get releases working again

Models/Core/ApsimFile/Converter.cs
=> Stopped two water nodes and multiple solutes from being added to a soil.

ApsimNG/Presenters/AddModelPresenter.cs
=> Fixed 'Add Model' command - not adding resource models correctly

APSIM.Shared/Utilities/DataTableUtilities.cs, APSIM.Shared/Utilities/Extensions.cs, APSIM.Shared/Utilities/SoilUtilities.cs, ApsimNG/Presenters/NewGridPresenter.cs, ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Presenters/WaterPresenter.cs, ApsimNG/Views/Sheet/CellEditor.cs, ApsimNG/Views/Sheet/DataTableProvider.cs, ApsimNG/Views/Sheet/GtkExtensions.cs, ApsimNG/Views/Sheet/ISheetEditor.cs, ApsimNG/Views/Sheet/MultiCellSelect.cs, ApsimNG/Views/Sheet/SheetEventKey.cs, ApsimNG/Views/Sheet/SingleCellSelect.cs, Models/Soils/LayerStructure.cs, Models/Soils/TabularData.cs
Resolves #7435
Resolves #7392
Resolves #7425
Resolves #7418
=> Fix editing of soil grids in GUI

Models/CLEM/Activities/LabourActivityFeedTargetPurchase.cs, Models/CLEM/Activities/LabourRequirement.cs, Models/CLEM/Activities/RuminantTrucking.cs, Models/CLEM/Interfaces/ICLEMDescriptiveSummary.cs, Models/PMF/Cultivar/Cultivar.cs
rather than System.Text.Json. Resolves #7444
=> Changed some JsonIgnores to use the Newtonsoft.Json package

ApsimNG/Menus/ContextMenu.cs
=> Option to create manager snippet code for a model in GUI

Models/PMF/Organs/SorghumLeaf.cs, Models/PMF/Structure/LeafCulms.cs, Models/PMF/Structure/Tillering/DynamicTillering.cs
=> Sorg fixes

ApsimNG/Presenters/NewGridPresenter.cs, ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Resources/Glade/ProfileView.glade
=> Added layer counter to soil profile grids in GUI

APSIM.Shared/Utilities/StringUtilities.cs, Models/Factorial/Factor.cs
=> Better error reporting when parsing range-based factors

ApsimNG/Menus/ContextMenu.cs, Models/Core/ApsimFile/Converter.cs, Models/Soils/Soil.cs, Models/Soils/Water.cs
=> Soils fixes

ApsimNG/Utility/WeatherDownloadDialog.cs
=> Improving weather download dialog

Models/Stock/AnimalGroup.cs
=> Stock conception rates

Examples/Mungbean.apsimx
=> Simplified Mungbean Example

Models/PMF/Plant.cs
=> Plant.IsEnding is not reset at sowing

Models/CLEM/Activities/ResourceActivityExternalMultiplier.cs, Models/CLEM/DataReaders/FileResource.cs, Models/CLEM/Reporting/ReportResourceShortfalls.cs, Models/CLEM/Resources/CLEMResourceTypeBase.cs
=> Allow specifying of external resources managed

ApsimNG/Presenters/SoilDownloadPresenter.cs, ApsimNG/Resources/Glade/DownloadSoilView.glade, ApsimNG/Views/EditView.cs, ApsimNG/Views/ListView.cs
=> Soil downloads work better

Models/Soils/Water.cs
=> Help Water.cs find the "right" Physical and SoilWater nodes.

ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Resources/Glade/ProfileView.glade, ApsimNG/Views/GraphView.cs
=> Provide a "splitter" in ProfileView

Models/Core/Locator.cs, Models/Core/Model.cs
=> Include disabled items when locating by path.

Models/Surface/SurfaceOrganicMatter.cs
=> Standing/Lying SurfaceOrganicMatter Outputs

Models/PMF/Phenology/Phases/GenericPhase.cs
=> Fix to Generic Phase

ApsimNG/Classes/Property.cs, ApsimNG/Classes/PropertyPresenterHelpers.cs, Models/Core/Attributes/DisplayAttribute.cs, Models/Functions/AccumulateAtEvent.cs, Models/Functions/AccumulateByNumericPhase.cs, Models/Functions/AccumulateFunction.cs, Models/Functions/PhaseLookupValue.cs
=> drop down menues

ApsimNG/Presenters/ExplorerPresenter.cs, Models/Core/Locator.cs
=> Clean up locator cache when nodes are deleted or renamed.

ApsimNG/Presenters/NewGridPresenter.cs, ApsimNG/Presenters/ProfilePresenter.cs, Models/Soils/Chemical.cs, Models/Soils/Solute.cs
=> Added profile graphs for solutes.

Models/PMF/Phenology/Phases/GenericPhase.cs
=> Fix GenericPhase 

Models/Resources/Canola.json
=> renamed [Canola] to [Plant]

Models/Core/ApsimFile/Converter.cs
=> Added some additional, rarely needed, conversions.

Models/CLEM/Activities/ActivitiesHolder.cs, Models/CLEM/Activities/CLEMActivityBase.cs, Models/CLEM/Activities/PastureActivityManage.cs, Models/CLEM/Activities/RuminantActivityGrazePasture.cs, Models/CLEM/Activities/RuminantActivityGrazePastureHerd.cs, Models/CLEM/Activities/RuminantActivityMove.cs, Models/CLEM/Common.cs, Models/CLEM/Groupings/Filter.cs, Models/CLEM/Groupings/FilterByProperty.cs, Models/CLEM/Reporting/ReportActivitiesPerformed.cs, Models/CLEM/Reporting/ReportGrazingEfficiency.cs, Models/CLEM/Reporting/ReportResourceShortfalls.cs, Models/CLEM/Resources/ResourceRequests.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Timers/ActivityTimerPastureLevel.cs, Models/CLEM/Timers/ActivityTimerResourceLevel.cs
=> Improved grazing efficiency report

ApsimNG/Views/CLEM/ActivityLedgerGridView.cs, Models/CLEM/Activities/CLEMActivityBase.cs, Models/CLEM/Activities/LabourRequirement.cs, Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/DataReaders/FileSQLitePasture.cs, Models/CLEM/Reporting/ReportActivitiesPerformed.cs
=> Handles non transmutable shortfalls in pasture initialisation

Models/PMF/Phenology/CAMP/CAMP.cs
Resolves #7699
@hut104 this will fix the problem you found with FLN
=> zero long Pp accumulation

Models/CLEM/Activities/ActivitiesHolder.cs, Models/CLEM/Activities/CLEMActivityBase.cs, Models/CLEM/Activities/RuminantActivityBuySell.cs, Models/CLEM/Activities/RuminantTrucking.cs, Models/CLEM/Common.cs, Models/CLEM/Reporting/ReportActivitiesPerformed.cs, Models/CLEM/Timers/ActivityTimerRuminantLevel.cs
=> Fixes loading cattle on trucks logic

APSIM.Cli/APSIM.Cli.csproj, APSIM.Interop/APSIM.Interop.csproj, APSIM.Server/APSIM.Server.csproj, APSIM.Shared/APSIM.Shared.csproj, APSIM.Shared/Utilities/Firebird.cs, ApsimNG/ApsimNG.csproj, ApsimNG/Cloud/Azure/AzureInterface.cs, ApsimNG/Intellisense/CodeCompletionService.cs, ApsimNG/Intellisense/Extensions/CompletionItemExtensions.cs, ApsimNG/Presenters/IntellisensePresenter.cs, ApsimNG/Utility/FindAndReplaceForm.cs, Models/Models.csproj, Models/Utilities/R.cs, Tests/UnitTests/Interop/Markdown/Parsers/Inlines/ReferenceInlineParserTests.cs, Tests/UnitTests/Interop/Markdown/Renderers/Blocks/CodeBlockRendererTests.cs, Tests/UnitTests/Interop/Markdown/Renderers/Inlines/AutolinkInlineRendererTests.cs, Tests/UnitTests/Interop/Markdown/Renderers/Inlines/CodeInlineRendererTests.cs, Tests/UnitTests/Interop/Markdown/Renderers/Inlines/HtmlInlineRendererTests.cs, Tests/UnitTests/UnitTests.csproj
=> Update Nuget packages as much a possible for .Net core 3.1

Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/Reporting/ReportResourceLedger.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantType.cs, Models/CLEM/ZoneCLEM.cs
=> Apply correct parameter to ruminant energy equation

APSIM.Cli/APSIM.Cli.csproj, APSIM.Documentation/APSIM.Documentation.csproj, APSIM.Interop/APSIM.Interop.csproj, APSIM.Server/APSIM.Server.csproj, APSIM.Shared/APSIM.Shared.csproj, ApsimNG/ApsimNG.csproj, Models/Importer/Importer.csproj, Models/Models.csproj, Tests/UnitTests/UnitTests.csproj
=> Fix install builds on Jenkins

Models/PMF/Cultivar/Cultivar.cs, Models/PMF/Plant.cs
Working on #7734 
OilPalm also uses Cultivar objects, but it doesn't look like that plant is ever meant to be ended so I didn't make any changes.
=> Undo cultivar changes on plant ending.

ApsimNG/Views/MapView.cs
=> Interact with the GUI on the main thread.

Examples/Tutorials/EventPublishSubscribe.apsimx
=> Added event subscribe example to tutorials.

Models/Functions/SoilFunctions/CERESDenitrificationModel.cs
Resolves #7696
May additional resolve some issues in #6458
=> Added attributes to enable modifiying of denitrifaction rate 

Models/Core/Apsim.cs
=> Add Folder to add model context menu

Models/Soils/WaterModel/WaterBalance.cs
=> Remove read only argument to allow SoilWater node to become editable.

Models/CLEM/Activities/RuminantActivityGrow.cs
=> Check and clean up ruminant growth component 

Models/AgPasture/SimpleGrazing.cs
=> Added FractionDefoliatedBiomassToSoil to SimpleGrazing

ApsimNG/Views/Sheet/SingleCellSelect.cs
=> Fix to allow grid copy / paste

Models/Soils/Physical.cs
=> Fix PAWC column in Physical node

ApsimNG/Presenters/WaterPresenter.cs, ApsimNG/Resources/Glade/WaterView.glade, Models/Soils/Water.cs
=> Allows editing of initial PAW in Water node under soil.

Examples/Wheat.apsimx
This reverts commit b209308efdb46e8a00082e0e02dbf0bf15780f74.
=> Revert "Delete Wheat.apsimx"

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
=> Added centre pivot irrigation manager script to management toolbox

ApsimNG/Resources/Style/global.css
Resolves #7647
Full credit to @zur003 for finding the required css statement to enable this functionality.
=> Enable DropDownView scrollbar functionality

Models/Core/Run/SimulationGroup.cs
=> Detect duplicate soils in a zone.

APSIM.Shared/JobRunning/JobRunner.cs, Models/Core/Run/Runner.cs, Models/Core/Run/SimulationGroup.cs
when stop button is pressed.
Resolves #7801
=> Added code to gracefully shutdown datastore writer

Models/PMF/Organs/HIReproductiveOrgan.cs, Models/PMF/Organs/ReproductiveOrgan.cs
Resolves #5528
@hut104 @hol353 Does it matter if the properties are cleared instead of reinitialised?
=> Issue #5528 fix

Models/Summary.cs
=> Remove redundant messages() function

Models/PMF/SowingParameters.cs
=> Removed all defaults from all properties in SowingParameters.cs

Models/Core/ApsimFile/Converter.cs
=> Fix to get more APSIM 7.10 soils imported correctly

APSIM.Shared/Utilities/MathUtilities.cs, Models/Utilities/Accumulator.cs
=> Small changes to get YP running Next Gen

ApsimNG/Utility/Configuration.cs
=> added default true value to Muted property

Docs/content/Development/Software/CompileInCommandLine.md
=> Add documentation for publish apsim ng

Models/Soils/WaterModel/WaterTable.cs
=> Prevent dry soils from reporting a water table depth of 0.

Models/CLEM/Activities/RuminantActivityBuySell.cs, Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/Extras/WarningLog.cs, Models/CLEM/Reporting/SummariseRuminantHerd.cs
=> Refactor herd adjustment at start of simulation

ApsimNG/Resources/Glade/DownloadSoilView.glade
Resolves #7822 
- Improves clarity on search terms.
=> Updated label for soil download glade

Models/Interfaces/ISurfaceOrganicMatter.cs, Models/Surface/SurfaceOrganicMatter.cs
=> modified parameters and specs

Models/Functions/AccumulateByNumericPhase.cs
=> Still display stage name in AccumulateByNumericPhase

Models/PMF/Structure/Tillering/C4LeafArea.cs, Models/PMF/Structure/Tillering/DynamicTillering.cs
=> fix for invalid leaf sizes

Models/Core/ModelOverrides.cs
=> changed model override to only be child of plant

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/SoilDownloadPresenter.cs
=> empty paste issue corrected with if statement

ApsimNG/Menus/ContextMenu.cs
=> Fixed manager snippet full path bug

ApsimNG/Views/Sheet/SheetWidget.cs
=> removed GrabFocus from initialise method

Models/Core/IPlant.cs, Models/PMF/Plant.cs
=> Modified Plant.cs to have same value as IPlant for rowConfig value

ApsimNG/Intellisense/CodeCompletionService.cs
Resolves #7893.
Well, it works, although I don't really understand synchronization contexts enough to explain _why_ it works. Perhaps @hol430 could review this. How did you work out how to use code completion? It doesn't seem to be documented by Microsoft.
=> Fix problem with code completion service.

Tools/SoilNitrogenToNutrient.py
=> SoilNitrogenToNutrient python script added, Wheat.apsimx updated

ApsimNG/Commands/RenameModelCommand.cs
=> Fixing Undo not selecting node

Examples/Grapevine.apsimx, Tools/SoilNitrogenToNutrient.py
=> 7806 Grapevine Example updated to remove SoilNitrogen

Examples/Grapevine.apsimx, Tools/SoilNitrogenToNutrient.py
Resolves #7806
FOM.N was not converted right, correction has been made.
=> Correction for FOM.N

Models/Clock.cs, Models/Soils/Solute.cs
=> Added solute diffusion

Models/PMF/Plant.cs
=> Added StartPodDevelopment event to plant

ApsimNG/Resources/Style/global.css
resolves #2475
@HamishBrownPFR I'm not sure if this a concern anymore, but just in case, I've gone and made the change.
=> Make explorer view scrollbar wider

ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Presenters/SoilDownloadPresenter.cs, ApsimNG/Presenters/WaterPresenter.cs, ApsimNG/Resources/Glade/ProfileView.glade, ApsimNG/Views/Sheet/SheetWidget.cs, ApsimNG/Views/ViewBase.cs, Models/PMF/Arbitrator/Methods/C4WaterUptakeMethod.cs
Resolves #7454 
This was a big old issue that had lots of little things that needed updating. I split each issue that was fixed across a different commit.
This pull request, combined with the other two that were done previous on this issue, should now resolve all the problems that were identified. **Main thing to check is how I implemented the graph on the SoilCrop node and if that is correct.**
=> 7454 Soil Interface

Models/PMF/Organs/SorghumLeaf.cs, Models/PMF/Structure/LeafCulms.cs
=> Enable setting of FertileTillerNumber

Models/CLEM/Reporting/ReportRuminantHerd.cs, Models/CLEM/Resources/IndividualAttribute.cs
=> Improve attribute value handling for genetics in CLEM

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/error-report.yml, .github/ISSUE_TEMPLATE/new-feature.yml, .github/ISSUE_TEMPLATE/question.yml
Resolves #7952 
We'll start with these and update as needed in the future.
=> Four issue templates to remind people to add info

ApsimNG/Presenters/DataStorePresenter.cs, ApsimNG/Presenters/ExplorerPresenter.cs, ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Presenters/ReportPresenter.cs
=> Add ability to retain report column and row filters on save

Models/Soils/Solute.cs
=> added "initialValuesConverted" column to summary file

Tests/UnitTests/CommandLineArgsTests.cs
Resolves #7977
It was in UnitTests/CommandLineArgs
=> Removed Writelines commands

Models/Management/RotationManager.cs
=> Fix RotationManager transition messages

ApsimNG/Views/EditorView.cs
Resolves #7986 
Following the implementation in TextInputView.
=> Allow Report, Manager and Operations components to have their font modified

Models/Core/ApsimFile/Structure.cs
=> Fix error in maximum number of zones

ApsimNG/Presenters/GraphPresenter.cs
=> Don't reset min/max if already set.

APSIM.Interop/Mapping/MapRenderer.cs, Tests/UnitTests/Core/ApsimFile/FileFormatTests.cs
=> Jenkins fails

Models/Core/Apsim710File/Importer.cs, Models/Soils/Chemical.cs
=> Added CEC back into APSIM. Needed for volatilisation and biochar

ApsimNG/Presenters/SoilDownloadPresenter.cs
=> Fix slga initial water nodes not having thickness values

APSIM.Shared/APSIM.Shared.csproj
Resolves #8014
Did a search of the project for any other references to netcore or net 3.1, nothing else important came up.
=> 8014 Changed that property to just net 6.0

Models/PMF/Organs/Root.cs
=> Removed unnecessary function from root class

Models/Agroforestry/AgroforestrySystem.cs, Models/Agroforestry/LocalMicroClimate.cs, Models/Agroforestry/TreeProxy.cs
=> agroforestry using directives updated

Models/Aqua/FoodInPond.cs, Models/Aqua/PondWater.cs, Models/Aqua/Prawns.cs, Models/Aqua/WaterPropertiesData.cs
=> updated aqua directory using directives

ApsimNG/Presenters/SoilDownloadPresenter.cs
Also added some missing SoilCrops
Resolves #7890
=> Added initial values to water when downloading soil.

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
=> Added fertilise on event and variable trigger

Models/PMF/Phenology/Phases/DAWSPhase.cs, Models/PMF/Phenology/Phases/EmergingPhase.cs, Models/PMF/Phenology/Phases/EndPhase.cs, Models/PMF/Phenology/Phases/GenericPhase.cs, Models/PMF/Phenology/Phases/GerminatingPhase.cs, Models/PMF/Phenology/Phases/GotoPhase.cs, Models/PMF/Phenology/Phases/GrazeAndRewindPhase.cs, Models/PMF/Phenology/Phases/IPhase.cs, Models/PMF/Phenology/Phases/IPhaseWithTrarget.cs, Models/PMF/Phenology/Phases/LeafAppearancePhase.cs, Models/PMF/Phenology/Phases/LeafDeathPhase.cs, Models/PMF/Phenology/Phases/NodeNumberPhase.cs, Models/PMF/Phenology/Phases/PhotoperiodPhase.cs, Models/PMF/Phenology/Phases/SimpleLeafAppearancePhase.cs, Models/PMF/Phenology/Phases/StartPhase.cs, Models/PMF/Phenology/Phases/VernalisationPhase.cs, Models/PMF/Phenology/Phenology.cs, Models/Resources/Grapevine.json, Tests/UnitTests/Functions/HoldFunctionTests.cs, Tests/Validation/SoilWater/SoilWater.apsimx
=> Improved emergence detection in Phenology

ApsimNG/Presenters/SummaryPresenter.cs
resolves #8033 
- bug was caused by referencing an index of object that did not exist.
=> fixed summary file crash bug

ApsimNG/Presenters/SoilDownloadPresenter.cs
=> Added Euc and SCRUM soil crops parameterisations into ISRIC soils

Models/PMF/Organs/Leaf.cs, Tests/Validation/SWIM/SWIM.apsimx
=> Remove FRGR property from Leaf

Models/PMF/Phenology/Phenology.cs, Models/PMF/Plant.cs, Models/PMF/PlantTypes.cs
=> Removed SimpleFruitTree specific code in phenology

Models/Functions/CSharpExpressionFunction.cs
=> Removed unique naming of scripts in CSharpExpressionFunction

Models/Core/VariableProperty.cs
Working on #8050
Just adds a useful error message for situations where people try to change a variable that is read only. Leaving as Working on as to not close their question.
=> Better Error message around variable changing

Models/Functions/DeltaFunction.cs, Models/Functions/DemandFunctions/PartitionFractionDemandFunction.cs
=> Functions tidy up

Models/AgPasture/SimpleGrazing.cs
=> Fixed SimpleGrazing not removing biomass from plant model

Models/PMF/PlantTypes.cs
resolves #8074.
Will need to fix error in test set if any throw
=> Add error message to residue so it throws if attempting to set invalid fractions

Models/CLEM/Activities/CLEMRuminantActivityBase.cs, Models/CLEM/Activities/RuminantActivityBreed.cs, Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/Groupings/SortByAttribute.cs, Models/CLEM/Interfaces/IIndividualAttribute.cs, Models/CLEM/Resources/IndividualAttribute.cs, Models/CLEM/Resources/IndividualAttributeList.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantTypeCohort.cs, Models/CLEM/Resources/SetAttributeFromHerd.cs, Models/CLEM/Resources/SetAttributeWithProperty.cs
=> Added genotype expression variability to CLEM

ApsimNG/Presenters/SummaryPresenter.cs, Models/PMF/Biomass/CompositeBiomass.cs, Models/PMF/Organs/Leaf.cs, Models/PMF/Organs/PerennialLeaf.cs, Models/PMF/Organs/SimpleLeaf.cs, Models/PMF/Organs/SorghumLeaf.cs, Models/PMF/Plant.cs
=> Ondophenology

APSIM.Shared/Utilities/DateUtilities.cs
=> DateUtilities method added to truncate any 4-letter months

Models/Soils/WaterModel/EvaporationModel.cs
(e.g. summer / winter turnover). 
Resolves #8112
=> In soil evap, added code to reset sumes1 and 2 when U changes 

Models/PMF/Phenology/Phases/GotoPhase.cs
=> Fixed goto phase so that it doesn' throw when phenology is missing.

Models/PMF/Library/BiomassRemoval.cs, Models/Surface/SurfaceOrganicMatter.cs
Also added better reporting, in summary file, of add/remove biomass from SOM
Resolves #8060
=> Added a remove method to SOM.

APSIM.Shared/Utilities/DateUtilities.cs
Resolves #8124
The date parsing functions now return an error message as part of the DateAsParts object instead of throwing exceptions. The GetDate functions can then handle that error and ValidateDateString can check if a date will parse, without actually throwing an exception.
=> Parsing returns error message instead exception

Models/PMF/Organs/Cohorts.cs, Models/PMF/Organs/PerennialLeaf.cs
=> Remove biomass in perennial leaf wasn't updating live and dead pools

ApsimNG/Views/MainView.cs
Resolves #8131
**Ready to Merge**
Should help your problem Dean, and save you having to always drag the pane down when opening apsim.
=> 8131 Moved Output Pane Start Position

Models/Core/Folder.cs
=> Add IPlant as a valid parent for a folder

Models/Resources/Wheat.json
=> Remove [Wheat] refs

Models/PMF/Cultivar/Cultivar.cs
=> Added default constructor to cultivar so that Add Model works.

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExplorerPresenter.cs, Models/Core/ApsimFile/FileFormat.cs, Models/Core/Resource.cs
=> Removed ReadOnly context menu option. Rewritten ShowModelStructure.

APSIM.Documentation/Models/DocumentationTable.cs, APSIM.Documentation/Program.cs
=> Added timings to autodoc log on jenkins

ApsimNG/Presenters/GraphPresenter.cs
=> 8169 Graph Axis only change if too small, not always

ApsimNG/ApsimNG.csproj, NuGet.config
=> Changed OxyPlot.GtkSharp3 to use the nuget preview rather than myget.

ApsimNG/Views/MarkdownView.cs
Working on #8193 
This branch is an attempt at speeding up MarkdownView's rendering by avoiding GTK invocations and allocations unless necessary. This seemed to speed up the rendering from ~300 ms to ~35 ms (at least measured on my machine) for table heavy DocumentationPresenter nodes, albeit with some slight differences in tabstop sizes (commonly 0 pixels and no greater than 2 pixels from what I have seen -- well below table padding). There is probably more to be done here, I am not sure whether or not altering fontCharSizes and nonASCIICharSizes needs to be locked.
=> Markdown view changes

Models/Core/AutoDocumentation.cs
Working on #8193 
An attempt at resolving the first part of the linked issue. Seems to speed up the drawing of a DocumentationPresenter by a noticeable amount.
=> Cache xml comments for quicker access.

APSIM.Shared/Utilities/DateUtilities.cs, Tests/UnitTests/UtilityTests/DataUtilitiesTests.cs
=> 8205 Dates trimmed correctly

Models/Interfaces/ISurfaceOrganicMatter.cs, Models/Surface/SurfaceOrganicMatter.cs, Tests/UnitTests/Surface/MockSurfaceOrganicMatter.cs
=> Add a fractionStanding argument to SurfaceOrganicMatter.Add method

Models/Management/BiomassRemovalEvents.cs
Resolves #8236
Quick fix, should be no errors.
=> 8236 BiomassRemovalEvents now looks for Replacements Folder

Models/Management/BiomassRemovalEvents.cs
=> BiomassRemovalEvents not broadcasting events

.github/ISSUE_TEMPLATE/jenkins.yml, .github/ISSUE_TEMPLATE/refactor.yml
resolves #8235 
Templates added for submitting of issues into GitHub.
=> Jenkins and Refactor issue templates

Models/Soils/Nutrients/Nutrient.cs, Models/Soils/SWIM/Swim.cs, Models/Surface/SurfaceOrganicMatter.cs, Tests/Validation/SWIM/SWIM.apsimx
Also fixed surface residue actual decomposition when SWIM is in the simulation
Resolves #8260
=> Fixed nutrient.mineralisedN output.

Models/Lifecycle/PlantOrganFunctionalDimensionReduction.cs, Models/PMF/Interfaces/IPlantDamage.cs, Models/PMF/Plant.cs
=> Remove Plant.ReduceCanopy method

Models/AgPasture/PastureSpecies.cs, Models/PMF/Interfaces/IPlantDamage.cs, Models/PMF/Plant.cs
=> Removed Plant.AssimilateAvailable

Models/AgPasture/PastureSpecies.cs, Models/Lifecycle/PlantAssimilateConsumption.cs, Models/Lifecycle/PlantOrganFunctionalDimensionReduction.cs, Models/PMF/Interfaces/IPlantDamage.cs, Models/PMF/Plant.cs
Also removed Plant.RemoveAssimilate method.
Resolves #5473
=> Removed Plant.ReduceRootLengthDensity to root. 

Models/PMF/BiomassArbitration/Organ.cs, Models/PMF/Organs/GenericOrgan.cs, Models/PMF/Organs/HIReproductiveOrgan.cs, Models/PMF/Organs/Leaf.cs, Models/PMF/Organs/Nodule.cs, Models/PMF/Organs/PerennialLeaf.cs, Models/PMF/Organs/ReproductiveOrgan.cs, Models/PMF/Organs/Root.cs, Models/PMF/Organs/SimpleLeaf.cs, Models/PMF/Plant.cs
=> Removed Plant.IsEnding property

.github/ISSUE_TEMPLATE/new-common-report-event-variable.yml
working on #8227 
Need template submitted before new report changes submitted as the final URL for the template is needed for a link.
=> Add new report common event/variable issue template

Docs/content/Usage/met/_index.md
=> Add a link to docs

Models/AgPasture/SimpleGrazing.cs
=> Remove exception when less biomass grazed than requested - not needed

Models/PMF/Organs/GenericOrgan.cs
=> fixing respiration bug

Models/Soils/SWIM/HyProps.cs, Models/Soils/SWIM/Swim.cs, Tests/Validation/SWIM/SWIM.apsimx
=> Change SimpleTheta to avoid cubic approximations where not required.

ApsimNG/Views/MarkdownView.cs, ApsimNG/Views/UpgradeView.cs, LICENSE.md, README.md
resolves #8310 
* Most requested changes are already complete.
* This PR just includes the changes required for the ApsimX upgrade modal as well as an update to the ApsimX repo README.
=> Update licence text in upgrade modal + readme updates

Models/Core/ApsimFile/Converter.cs
resolves #8308
* Added a simple check for an existing Nutrient in any parent that contains a SoilNitrogen node. This should solve the problem of a duplicate Nutrient node being added to a Soil Node and causing an exception.
=> Added check for existing Nutrients in converter function 166

ApsimNG/Views/PropertyView.cs, Models/PostSimulationTools/PredictedObserved.cs
=> Empty drop down box options for PredictedObserved Node

ApsimNG/Views/ListView.cs
=> 8328 Fix for Tree View crashing when adding node

Models/CLEM/Resources/CLEMResourceTypeBase.cs, Models/CLEM/Resources/Labour.cs
=> CLEM fixed reporting in labour ledger problem.

APSIM.Interop/APSIM.Interop.csproj, APSIM.Shared/APSIM.Shared.csproj, ApsimNG/Presenters/ReportPresenter.cs
resolves #8334
- also updated vulnerable nuget packages (SkiaSharp) that had severe vulnerabilities.
=> Newly added report line now becomes highlighted

APSIM.Shared/Utilities/DateUtilities.cs, ApsimNG/Presenters/OperationsPresenter.cs, Models/Management/Operations.cs, Tests/UnitTests/Operations/Operations.cs
Resolves #8333 
Parsing error message would display when writing comments. Has been fixed to parse a bit smarter.
=> Fixed parsing to give better errors

APSIM.Shared/Utilities/ApsimTextFile.cs
=> 8338 Change file reader to use DateUtilities class

Models/PMF/Arbitrator/OrganArbitrator.cs
=> change defaults for FN

APSIM.Shared/Utilities/SoilUtilities.cs, Models/PMF/Organs/Root.cs
Resolves #8361.
I added WFPS as a method in SoilUtilities because it may be useful by itself in the future.
=> Wet root fraction

ApsimNG/Presenters/PropertyPresenter.cs, Models/Core/Attributes/DisplayAttribute.cs
=> Substitute sub-property option for Property Presenter

Models/Soils/Nutrients/Nutrient.cs
=> Fixed Nutrient.FOM reporting zeros

Models/Soils/Solute.cs
=> Fixed solute to perform its calculations daily

Models/Soils/WaterModel/EvaporationModel.cs
=> Removed unused code in evaporation model

ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Views/Sheet/Sheet.cs, ApsimNG/Views/Sheet/SheetScrollBars.cs, Models/ForageDigestibility/Forages.cs
Resolves #8382
Fixes the datastore scrollbar issue and also a forages bug that was stopping it from displaying under certain conditions.
=> 8382 Datastore Scrollbar Fix

ApsimNG/Views/GridView.cs
=> Fix to gridview to find ExplorerView in XYPairs views

Models/Soils/WaterModel/EvaporationModel.cs
=> Change initialization date in EvaporationModel.

ApsimNG/Presenters/MainPresenter.cs, ApsimNG/Views/ReportView.cs
=> 8411 Stores slider percentage as int

Models/Sugarcane/Sugarcane.cs
=> make CropConstants and CultivarConstants public in Sugarcane

Models/Surface/SurfaceOrganicMatter.cs
Resolves #8373 
Implemented new function as described in the issue. Just check that I've assigned the variables to the correct values, as I had to guess a little bit.
Based the code off what was written in the manager script that Val provided.
=> 8373 Add new version of AddFaeces to SOM

ApsimNG/Views/AxisView.cs
resolves #8399 
Clicking away from the series node to the tree after changing any axes input details will now save changed values.
=> 8399 graph axis changes not saved

Models/Soils/Water.cs
resolves #8393 
When LL limits where being set, a FindInScope method was used to find the appropriate SoilCrop node to get this data from.
As there were many SoilCrops in scope, incorrect SoilCrops where being referenced causing problems when doing calculations.
To resolve the issue, a more specific FindAncestor<Soil>().FindDescendant<SoilCrop>() was used to resolve this problem.
=> 8393 initial water relative to crop fix

APSIM.Shared/Graphing/Axis.cs, ApsimNG/Interfaces/IAxisView.cs, ApsimNG/Interfaces/IGraphView.cs, ApsimNG/Presenters/AxisPresenter.cs, ApsimNG/Presenters/GraphPanelPresenter.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Presenters/LinearAfterThresholdPresenter.cs, ApsimNG/Presenters/MetDataPresenter.cs, ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Presenters/WaterPresenter.cs, ApsimNG/Presenters/XYPairsPresenter.cs, ApsimNG/Resources/Glade/AxisView.glade, ApsimNG/Views/AxisView.cs, ApsimNG/Views/GraphView.cs
=> 6122 Added button to graph axis to show the title as one line

Models/Graph/Regression.cs
=> Fix Graph axes bug where NaNs as axes values caused exception

Models/Surface/SurfaceOrganicMatter.cs
=> Avoid cloning to speed SurfaceOrganicMatter up.

Models/AgPasture/SimpleGrazing.cs, Models/ForageDigestibility/ModelWithDigestibleBiomass.cs
=> Fixes for simple grazing to avoid DM mass balance errors

Models/CLEM/Activities/RuminantActivityBreed.cs, Models/CLEM/Activities/RuminantActivityGrow.cs, Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/Reporting/ConceptionStatusChangedEventArgs.cs, Models/CLEM/Reporting/SummariseRuminantHerd.cs, Models/CLEM/Resources/Ruminant.cs, Models/CLEM/Resources/RuminantFemale.cs, Models/CLEM/Resources/RuminantHerd.cs, Models/CLEM/Resources/RuminantMale.cs
=> Updated pregnancy status report for CLEM

Setup/net6.0/macos/buildMacInstaller
=> fix buildMacInstaller

Models/Soils/Solute.cs, Tests/UnitTests/Soils/SoilStandardiserTests.cs
=> Change default no3/nh4 value to use below sample depth

APSIM.Shared/Utilities/MathUtilities.cs, ApsimNG/Interfaces/IGraphView.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Utility/AreaSeriesWithTracker.cs, ApsimNG/Utility/LineSeriesWithTracker.cs, ApsimNG/Views/GraphView.cs
=> 8460 Graphs only show one demical place

ApsimNG/Views/TreeView.cs
Resolves #8505
Resolves #8473
This fixes the related renaming bug that was happening in this issue.
=> 8505 Fixing renaming while saving bug

.gitignore, Models/Core/Simulations.cs, Models/Main.cs, Models/Options.cs, Tests/UnitTests/CommandLineArgsTests.cs
=> Command line switch added allowing the listing of all files as is

ApsimNG/Views/ManagerView.cs
Resolves #8569
Not the final solution, but will get it functioning again while I track down the actual problem.
=> Quick Fix for this bug by just switching pages when it loads

ApsimNG/Classes/Property.cs, ApsimNG/Classes/PropertyPresenterHelpers.cs, Models/Core/Attributes/DisplayAttribute.cs, Models/Functions/AccumulateFunction.cs, Models/Functions/DeltaFunction.cs, Models/Functions/HoldFunction.cs, Models/Functions/MovingAverage.cs, Models/PMF/Phenology/Phases/DAWSPhase.cs, Models/PMF/Phenology/Phases/GotoPhase.cs
=> Phase drop downs

ApsimNG/Resources/CommonReportVariables/CommonReportingVariables.json, Models/Core/ApsimFile/Structure.cs, Models/Soils/NutrientPatching/NutrientPatchManager.cs, Models/Soils/Nutrients/Nutrient.cs, Models/Soils/Nutrients/OrganicFlow.cs, Tests/UnitTests/Resources/totalc.apsimx, Tests/UnitTests/Soils/NutrientTests.cs, Tests/UnitTests/UnitTests.csproj
=> Fix Nutrient so that TotalC is not null on start of first day

Models/Clock.cs, Models/Report/Report.cs, Tests/UnitTests/Core/Run/RunnerTests.cs, Tests/UnitTests/Core/Run/SimulationTests.cs, Tests/UnitTests/FertiliserTests.cs, Tests/UnitTests/MockSummary.cs, Tests/UnitTests/Report/ReportTests.cs, Tests/UnitTests/Stock/StockTests.cs, Tests/UnitTests/Weather/WeatherTests.cs
=> Added a StartOfFirstDay event to clock

Models/PMF/Organs/SimpleLeaf.cs
=> SimpleLeaf Issues

Models/PMF/Organs/Leaf.cs, Models/PMF/Organs/LeafCohort.cs, Tests/UnitTests/Plant/PlantTests.cs
=> Fixed leaf detachment

Models/Core/Apsim710File/Importer.cs, Models/Core/ApsimFile/Converter.cs
=> Fix solute depth

Models/Agroforestry/TreeProxy.cs, Tests/UnitTests/Plant/TreeProxyTests.cs
=> Change TreeProxy to do N uptake in SetActualNitrogenUptakes method

Tests/UnitTests/Plant/TreeProxyTests.cs
=> Fixed compile problem in unit tests

Models/Resources/Canola.json
Update minimum N concentration for grain in canola.json from 0.05 to 0.02
resolves #8595
=> Update canola grain minimum n concentration

ApsimNG/Presenters/MetDataPresenter.cs
Resolves #8590
Quick fix to the weather graphs so they work with the zoom changes from the other week.
=> 8590 Added axis limits to Weather Graphs

Docs/content/Usage/server.md, Tests/Simulation/ZMQ-Sync/ZMQ-Interactive.py
=> Update server docs

Models/Core/Run/Playlist.cs
=> 8628 Serializable tag missing from playlist search class

Models/PostSimulationTools/ExcelInput.cs
=> 8621 excel sheet names

Models/Management/BiomassRemovalEvents.cs, Models/PMF/Phenology/Phenology.cs, Models/PMF/SimplePlantModels/StrumTreeInstance.cs, Models/Resources/Grapevine.json
working on #8175
Add base winter cover for evergreen tree crops
Allow setting harvest and prune dates from STRUM instance or manager
=> Fix biomass removal bugs.

APSIM.Shared/Utilities/SoilUtilities.cs, Models/Soils/Soil.cs, Models/Soils/SoilTemp/SoilTemperature.cs, Tests/UnitTests/APSIMShared/SoilTests.cs
=> Added initialisation from GUI. Added reset method.

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ExplorerPresenter.cs, Models/Core/ApsimFile/Structure.cs, Models/Core/Locator.cs
=> 8649 GUI searchs models not properties, children cannot be named same as properties

APSIM.Shared/Utilities/ReflectionUtilities.cs, ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/ManagerPresenter.cs, ApsimNG/Views/ManagerView.cs, Examples/Tutorials/PredictedObserved.apsimx, Models/Core/ApsimFile/FileFormat.cs, Models/Factorial/CompositeFactor.cs, Models/Management/Manager.cs, Tests/UnitTests/Manager/ManagerTests.cs
Resolves #8652
Keeps the compiled script component explicity, doesnt wipe Children[].
Needs an extra look please @par456
=> compiled script kept explicit

Models/AgPasture/PastureSpecies.cs
=> Fixed DefoliatedDigestibility and HarvestedME in AgPasture

Tests/Validation/System/LincolnRotation2017/RainshelterRotationSim.apsimx
=> fixed output and graphs

Models/AgPasture/PastureSpecies.cs
=> Fixed Harvestable.Digestibility output in AgPasture

Models/Options.cs
=> :bug: Set edit-use-config and run-use-config as deprecated

Models/Management/Manager.cs
working on #8673
remove any manager child with a name containing "Script"
=> More fixes for script children

Models/AgPasture/SimpleGrazing.cs
=> Fix to allow fraction excretedN to dung to be blank

Models/Core/ApsimFile/Converter.cs
=> Changed APSIM to import rocks, if present, from APSOIL

Examples/Peanut.apsimx
=> 8758 Fixed broken peanut example graph

ApsimNG/Presenters/AxisPresenter.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Views/AxisView.cs
Resolves #8694 
Just made the parser a bit smarter so it doesn't crash while you're typing in a date.
=> 8694 Added text handling for axis min/max with date

Models/Core/Apsim710File/Importer.cs
Resolves #8742
Folders with and uppercase F weren't seen as folders by the importer and weren't imported.
=> 8742 Importer allows for both folder and Folder xml name

APSIM.Interop/Drawing/IDrawContext.cs, APSIM.Shared/Utilities/MathUtilities.cs, APSIM.Shared/Utilities/SoilUtilities.cs, ApsimNG/ApsimNG.csproj, ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Views/Sheet/CairoContext.cs, ApsimNG/Views/Sheet/CellEditor.cs, ApsimNG/Views/Sheet/DataTableProvider.cs, ApsimNG/Views/Sheet/DefaultCellPainter.cs, ApsimNG/Views/Sheet/ISheetDataProvider.cs, ApsimNG/Views/Sheet/PagedDataProvider.cs, ApsimNG/Views/Sheet/SingleCellSelect.cs, Models/Core/VariableProperty.cs, Models/PostSimulationTools/PredictedObserved.cs, Models/Soils/Physical.cs, Models/Utilities/GridTable.cs, Models/Utilities/GridTableColumn.cs, Prototypes/PigeonPea/PigeonPea.apsimx, Tests/UnitTests/APSIMShared/SoilTests.cs
=> Soil defaults

ApsimNG/Utility/LineSeriesWithTracker.cs, ApsimNG/Views/GraphView.cs, Models/Core/ApsimFile/Structure.cs
=> Fix duplicate sibling name issue + handling for empty datetime cell in excel sheet when graphing

Models/Resources/Eucalyptus.json
=> 8786 Removed Pinus reference from Eucalyptus

Models/Core/Locator.cs
=> 8800 Don't change the name when looking for models

ApsimNG/Views/GraphView.cs
=> 8805 Fix Scatter Error Graphs

ApsimNG/Views/PropertyView.cs
resolves #8756 
- stops issues with OxyPlot graphs on MacOS systems.
- also removes the dark mode in general as it was not working.
=> Remove dark mode from MacOS

.vscode/launch.json
=> 8829 Tidied up VSCode builds

Models/Core/ApsimFile/Converter.cs
=> 8840 Soil Import error fix

Models/Functions/SoilWaterScale.cs, Models/PMF/Organs/Root.cs, Models/Resources/Wheat.json
=> 8819 Root Growth Changes

Models/Core/ApsimFile/Converter.cs
=> Small fix to previous pull request about --upgrade CLI switch

ApsimNG/Utility/GtkUtilities.cs, ApsimNG/Views/ExplorerView.cs, ApsimNG/Views/MainView.cs, ApsimNG/Views/MapView.cs
Resolves #8854
Most of the work was already here to make the map scale up and down. Just had to hook up some events to detect when dividers were moved and do the calculation for the part of the window where the map sits.
=> 8854 Map scales with window

ApsimNG/Menus/MainMenu.cs, ApsimNG/Presenters/MemoPresenter.cs, ApsimNG/Views/HelpView.cs, ApsimNG/Views/SeriesView.cs
resolves #8886 
The URLs on APSIM.info will need attention as well.
=> Fix dated website URLS in the UI.

Models/Climate/Weather.cs
=> Allow for fetching from constant

Models/Climate/Weather.cs
=> 8817 Weather Path check

ApsimNG/Presenters/ProfilePresenter.cs
resolves #8906
#Notes
- This only shows in the physical node.
=> Add warning about red values to ProfilePresenter

Models/Core/Run/Playlist.cs
=> Playlist search accepts decimals.

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx, Examples/AgPasture.apsimx
=> Add more options to the renew pasture manager

ApsimNG/Presenters/TreeProxyPresenter.cs, Models/Agroforestry/TreeProxy.cs, Tests/UnitTests/Plant/TreeProxyTests.cs
Resolves #8856
Also added new unit test to that if someone breaks it again we'll know right away.
=> 8856 Fixed null bug in TreeProxy 

Models/Soils/NutrientPatching/NutrientPatchManager.cs, Models/Soils/NutrientPatching/OrganicPoolPatch.cs, Models/Soils/Nutrients/Nutrient.cs, Models/Soils/Solute.cs
=> Nutrient patches: Fix solute initialisation. Fix residue decomposition.

Models/Soils/Physical.cs, Models/Soils/SoilTemp/SoilTemperature.cs
=> Fixed clay silt sand defaults

Models/Soils/SoilTemp/SoilTemperature.cs
=> Fixed silt/clay typo

Docs/content/User_tutorials/Module3/ModuleThreeTutorial.md
resolves #8965 
- Added missing step.
=> Updated module 3 and added missing report step

ApsimNG/Views/PropertyView.cs
Resolves #8970 
I couldn't replicate the error with one of my files, but I've added some more protection to the lines where this error was thrown, so hopefully that fixes it.
=> 8970 Null Widget

Models/Core/Events.cs, Models/Core/Scope.cs
This reverts commit 030022ccbc1f8113497585c9597d9631754ddfda.
Resolves #8981
=> Revert "Speedup to scoping / events"

ApsimNG/Views/PropertyView.cs, ApsimNG/Views/TreeProxyView.cs, Models/Agroforestry/TreeProxy.cs
Resolves #8856
I can't seem to break it anymore and was able to go through the list of instructions provided and have it work. Hopefully we've caught everything in this now.
=> 8856 Tree Proxy Copy Paste

.vscode/launch.json
Resolves #8956
I have rolled back my branch to when it was still running well and just fixed this flag that was set wrong. We can worry about the manager script performance later, but this solves the original issue,.
=> 8956 Allow Manager Debugging

ApsimNG/Presenters/SummaryPresenter.cs, Models/Core/Events.cs, Models/Core/Scope.cs, Models/Management/RotationLogger.cs
=> Speedup scoping

Models/Core/ScriptCompiler.cs
=> 8995 Revert ScriptCompiler debug to use stream

ApsimNG/Presenters/ProfilePresenter.cs, ApsimNG/Presenters/WaterPresenter.cs
Resolves #8968
When we get around to redoing the graphs, we'll need to revisit that graphing events system we are using here.
=> Physical and Water Graph Copying

ApsimNG/Views/TreeView.cs, Models/Core/ApsimFile/Structure.cs
Resolves #9009 
One bug I found when checking out this issue, there may be more.
=> 9009 Rename Checks

ApsimNG/Views/GraphView.cs
Resolves #8994 
Function now takes all the axis in together and acts on them as one. So if a datetime is missing or a value is invalid, it removes it from all axis, not just one.
=> 8994 Rewrote GetDataPointValues to fix Graphs

ApsimNG/Views/MarkdownView.cs
=> 9011 Memo List formatting

Models/ForageDigestibility/Forages.cs
Resolves #9012
A blank like was being added by the gui each time it was opened or editted.
=> 9012 Remove Blanks from Forage Table

APSIM.Shared/Utilities/CodeFormatting.cs, ApsimNG/Presenters/ManagerPresenter.cs, Models/Management/Manager.cs, Tests/UnitTests/Manager/ManagerTests.cs
Resolves #8873
Disabled this menu option a few weeks ago because it wasn't finished. Working on getting it to do what we want.
Basic formatting it complete, need to work on edge cases now by reformatting a bunch of different scripts.
=> 8873 Reformat Script Option

ApsimNG/Presenters/MetDataPresenter.cs
Resolves #9018 
Was throwing an error after the recent change to check that graph axis match in length, turns out the Y axis was holding daily averages instead of monthly, so was actually graphing incorrectly.
This should fix it.
=> 9018 Weather Graph Y axis fix

ApsimNG/Views/DirectedGraphView.cs
=> Make sure only a single arc is selected on click.

Models/Main.cs, Models/Options.cs, Tests/UnitTests/CommandLineArgsTests.cs, Tests/UnitTests/Resources/TwodisabledSimsOneEnabled.apsimx
=> added new switch to only show enabled sims + test

Models/Soils/Physical.cs
resolves #9020
FIndInScope strikes again!
This was just finding the first water in scope, this is not ideal for experiment configurations.
=> physical models under an experiment no longer reference base sims' water

Models/Climate/WeatherSampler.cs, Tests/UnitTests/Weather/WeatherSamplerTests.cs
=> Add water year capability

Models/Core/Folder.cs
=> 8608 Hide properties on Folder

Models/Soils/SWIM/Swim.cs
=> Exposed eo_time and eo_durn in SWIM model

Models/Main.cs
resolves #9032
Removes redundant error message
=> No redundant missing argument error message

ApsimNG/Menus/MainMenu.cs
=> 9048 Throw if example is not saved when run

ApsimNG/Menus/MainMenu.cs
Resolves #9048
The wrong variable was referenced by the other PR (#9049), this should resolve the problem correctly.
=> 9048 Fix running without saving

ApsimNG/Classes/Property.cs, ApsimNG/Classes/PropertyPresenterHelpers.cs, Models/Core/Attributes/DisplayAttribute.cs
=> Add drop down list to give Deropapy crop names

Models/PMF/Organs/Leaf.cs
=> Stop leaf reporting a positive value if plant is not alive

APSIM.Shared/Graphing/DirectedGraph.cs, ApsimNG/Presenters/DirectedGraphPresenter.cs
Resolves #9069
I apparently broke the DirectedGraphPresenter that Nutrient uses when updating the BubbleChartPresenter #8350 a few months ago. Went through and updated this presenter so it works on the new code.
=> 9069 Updated DirectedGraph to new BubbleChart code

ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Presenters/InputPresenter.cs, ApsimNG/Views/Sheet/Sheet.cs, Models/PostSimulationTools/Input.cs
resolves #9051
This node should be deprecated and csv observed input functionality moved into ExcelInput node.
=> Fix Input node. No longer has null object exception.

Models/Functions/DeltaFunction.cs, Models/Functions/MovingAverage.cs, Models/Functions/OnEventFunction.cs, Models/Management/BiomassRemovalEvents.cs, Models/Management/BiomassRemovalOfPlantOrganType.cs, Models/PMF/Phenology/Phases/DAWSPhase.cs, Models/PMF/Phenology/Phases/PhaseChangedType.cs, Models/PMF/Phenology/Phases/StartGrowthPhase.cs, Models/PMF/Phenology/Phenology.cs
=> Tweeks to functions and phenology to get Deropapy working

Examples/BiomassRemovalFromPlant.apsimx, Models/Management/BiomassRemovalEvents.cs, Models/PMF/BiomassArbitration/BiomassArbitrator.cs, Models/PMF/BiomassArbitration/EnergyBalance.cs, Models/PMF/BiomassArbitration/Organ.cs, Models/PMF/BiomassArbitration/RootNetwork.cs, Models/PMF/Organs/NetworkZoneState.cs
=> Modificatins to biomass classes to facilitate Dero impelmentation

ApsimNG/Presenters/ProfilePresenter.cs
=> Allow warning text to wrap, if necessary.

APSIM.Interop/Visualisation/DirectedGraphRenderer.cs, ApsimNG/Interfaces/IBubbleChartView.cs, ApsimNG/Presenters/BubbleChartPresenter.cs, ApsimNG/Views/BubbleChartView.cs, ApsimNG/Views/DirectedGraphView.cs, ApsimNG/Views/PropertyView.cs
Resolves #9113
Solves the four bugs that were listed in the issue. All presenter/view bugs.
=> 9113 Fixing a variety of small bugs in BubbleChart

ApsimNG/Presenters/AnnotationPresenter.cs
=> Correct property name for chart annoation position.

Models/PMF/Arbitrator/RetranslocateNonStructural.cs
=> changed error messages

ApsimNG/Presenters/CLEM/CLEMPresenter.cs, ApsimNG/Presenters/CLEM/MessagePresenter.cs, ApsimNG/Presenters/CLEM/ModelDetailsWrapperPresenter.cs, Models/CLEM/Activities/RuminantActivityBreed.cs, Models/CLEM/Reporting/SummariseRuminantHerd.cs, Models/CLEM/Resources/RuminantFemale.cs, Models/CLEM/Resources/RuminantHerd.cs, Models/CLEM/ZoneCLEM.cs
Resolves #9045 
Also addresses aspects of #8997
=> Female.NumberOfBirthsThisTimeStep fixes

Models/PMF/Organs/GenericOrgan.cs
=> Error in Wheat arbitration

Models/Storage/DataStoreWriter.cs
Working on #9174 
Swaps the list for a queue, which helps with both memory and running time. I wonder if it might also improve the #8759 situation. Doesn't do anything to address Summary slowing long term simulations down.
=> Change from a list to a queue in DataStoreWriter.

ApsimNG/Presenters/SoilDownloadPresenter.cs
Resolves #9137 
Changed to https for apsoil requests, also did some checking for other bugs encountered when testing.
=> 9137 Soil Download Issue

ApsimNG/Presenters/GridPresenter.cs
=> 9184 Fixed context menu for units on Solute grid

ApsimNG/Views/BubbleChartView.cs, ApsimNG/Views/DirectedGraphView.cs
Resolves #9187
Switched to using expand=true instead of fixed width
=> 9187 Redid Bubblechart size change

ApsimNG/Presenters/SoilDownloadPresenter.cs
=> 9179 Check if Soil has temperature before adding another

Gtk.Sheet/PagedDataProvider.cs, Tests/UnitTests/Sheet/PagedDataProviderTests.cs
=> Fixed filtering DataStore by SimulationName

ApsimNG/Presenters/GridPresenter.cs
=> Fix unneeded redrawing of grid.

ApsimNG/Views/UpgradeView.cs
=> Fix problem with calling async download.

APSIM.Shared/Containers/Docker.cs
=> Fixed kill container problem at end of Croptimizr

ApsimNG/Presenters/CLEM/ActivityLedgerGridPresenter.cs, ApsimNG/Presenters/CLEM/LabourAllocationPresenter.cs, ApsimNG/Presenters/CLEM/MessagePresenter.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Utility/Configuration.cs, ApsimNG/Utility/ConfigurationConverter.cs, ApsimNG/Utility/SettingsDialog.cs, ApsimNG/Views/DirectedGraphView.cs, ApsimNG/Views/EditorView.cs, ApsimNG/Views/GraphView.cs, ApsimNG/Views/TreeProxyView.cs
resolves #9112
- resolves the 'half-theme' issue with various views.
=> 9112 dark mode fixes

ApsimNG/Presenters/ManagerPresenter.cs, ApsimNG/Views/MarkdownView.cs
=> Small adjustments to avoid Gtk critical (but non-fatal) errors.

Models/Functions/FrostHeatDamageFunctions.cs
=> Export number of frost and heat events

ApsimNG/Presenters/MetDataPresenter.cs
resolves #9235
Added legends to three graphs: 
- Monthly rainfall 
- Temperature
-  Radiation
=> Add legends to Weather graphs

Models/Management/RotationManager.cs
Resolves #9246
Rotation manager was trying to evaluation blank line for a condition, just added a check so it won't do that.
=> 9246 Rotation Condition skip blank line

Models/Surface/SurfaceOrganicMatter.cs
Can this be merged please. It fixes the immediate issue but there are bigger problems with SurfaceOrganicMatter that need addressing. 
resolves #9264
=> Actually ADD (!) NH4 to SurfaceOrganicMater

Models/Main.cs
Resolves #9251
In certain configurations, the temp apsimx file that were created would open a datastore, but never close it. So when it came to clean up the files, it would get stuck trying over and over to close the datastore while it sat open.
Along with fix this, I also cleaned up the deletion code and prevented it from running infinitely in the future, and generally made it a bit smarter about how it did it.
=> 9251 Temp files cleanup correctly

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
resolves #9261
Suggestions applied to the management toolbox.
=> 9261ManagerTweaks

Examples/Optimisation/CroptimizRExample.apsimx
=> Met file relative path in CroptimizR example.

Models/Core/Simulation.cs, Models/Factorial/Experiment.cs, Models/Optimisation/CroptimizR.cs
=> 9291 Adds croptimizR as parent option for simulation and experiment

Models/PostSimulationTools/PredictedObserved.cs
=> 9284 Improved datastore messages

Models/Core/VariableExpression.cs
Resolves #9280
When evaluating an expression, if a variable didn't exist, it would return null, but it would also return null if the variable was correct, but had a value of null.
This change just breaks up the checks to give a better error message.
Ideally it would be good for our expressions to handle nulls (so if you sum a Null, it appears as an empty cell without an error), but to do that would be a dangerous change for very little gain.
=> 9280 New Error message for NULL results

ApsimNG/Presenters/GraphPresenter.cs
resolves #9309
Error bars now fully show on graph.
=> 9309GraphAutoSizeErrorBarBug

Gtk.Sheet/Data/ClassWithOneListProperty.cs, Tests/UnitTests/Sheet/ClassWithOneInstanceTests.cs
=> Fixed delete row on grids using ClassWithOneListProperty

APSIM.Shared/Utilities/MathUtilities.cs, Models/Graph/Regression.cs
Working on #9349 
I will be happy to revert any chance that seems undesirable.
=> Cleanup of 'Regression' and 'MathUtilities' classes

ApsimNG/Views/ListView.cs
Resolves #9365 
Edit: this now also resolves #9219 - the problem was in the same code that I had already changed in this PR, so I committed the bugfix to this branch to avoid merge conflicts.
=> Fixed a crash when double clicking on an experiment view

APSIM.Shared/Utilities/SoilUtilities.cs, Models/AgPasture/SimpleGrazing.cs, Models/AgPasture/UrineDungReturn.cs
=> Fixed the issue with urine being added at the wrong depth in the soil

Models/Functions/SoilWaterScale.cs
=> Change SoilWaterScale to use live SAT and DUL values

Models/Surface/SurfaceOrganicMatter.cs
=> Added incorporated variables to Surface OM.

Models/Functions/MovingSum.cs
=> MovingSum can have its capacity changed by a cultivar.

Models/PMF/Cultivar/Cultivar.cs
=> Allowed cultivars to be added to agpasture

Models/Functions/SoilFunctions/CERESDenitrificationWaterFactor.cs
resolves #9409
Exception message was misleading. This has now been updated to reference the proper model.
=> Fixed negative array index exception message

APSIM.Documentation/Models/AutoDocumentation.cs, APSIM.Shared/Utilities/DataTableUtilities.cs, Models/Climate/Weather.cs, Models/Interfaces/ISoilTemperature.cs, Models/Interfaces/ISoilWater.cs, Models/Interfaces/IWeather.cs, Models/Soils/Organic.cs, Models/Soils/WaterModel/SaturatedFlow.cs, Tests/UnitTests/Soils/MockSoilTemperature.cs
Working on #4080
* Fixed bug in auto-doc - not finding models.exe
* Added useful DataTableUtilities.ReadDataTable method for manager scripts.
* Made small number of weather variables settable.
* Added some units to various interfaces.
* Fixed a bug in SaturatedFlow that was throwing when KS is an empty array.
=> Assorted improvements for Crop2ML project

APSIM.Shared/Utilities/ApsimTextFile.cs, APSIM.Shared/Utilities/StringUtilities.cs, Docs/content/Usage/commandLine/command-line-how-to.md, Models/Core/ConfigFile/ConfigFile.cs, Models/Core/ConfigFile/Instruction.cs, Models/Main.cs, Tests/UnitTests/CommandLineArgsTests.cs, Tests/UnitTests/Utilities.cs
Resolves #9411
Also did a refactor of parts of this code to make it easier to expand and removed bunch of unnecessary code that we had utilities functions for.
=> 9411 Added naming to Apply commands

Models/Core/Links.cs, Models/Functions/SoilFunctions/CERESDenitrificationModel.cs
Working on #9170
Just the change to make it an IFunction and to make it to link by name as well as child as we discussed. Should be right to merge. No linking change or allowing manager scripts.
EDIT:
After thinking about this some more, I also PMF'd CERESDenitrificationModel (since it's also just an IFunction) and therefore this PR wouldn't need to be merged in for @hrpasl to work on this. 
We could still merge this to fix some bad code, but having this whole thing as PMF nodes might be better for working on it as well. Let me know what you think.
=> 9170 Making denitrification properties

Models/Functions/ArrayFunction.cs, Models/Functions/SoilFunctions/CERESNitrificationModel.cs
=> Changed nitrification to work with a child ArrayFunction.

Models/PMF/Organs/Root.cs
=> Fixed root detached variable for PMF plants

Models/Soils/SoilTemp/SoilTemperature.cs
=> Soil temperature

APSIM.Shared/Utilities/ApsimTextFile.cs, APSIM.Shared/Utilities/DateUtilities.cs
=> Adds DateUtilities to ApsimTextFile.cs

ApsimNG/Presenters/SoilDownloadPresenter.cs
resolves #9457
Updated the geocoding key
=> Update the geocoding key

ApsimNG/Presenters/SoilDownloadPresenter.cs, ApsimNG/Utility/WeatherDownloadDialog.cs
resolves #9457
Added missing ampersand to geocoding api call.
=> Fix geocoding issue

Models/Soils/SWIM/Swim.cs
=> Exposed 2 SWIM vapour flow variables

Setup/net6.0/debian/buildDebianInstaller, Setup/net6.0/macos/buildMacInstaller, Setup/net6.0/windows/apsimx.iss, Setup/osx/BuildMacDist.bat, Setup/osx/BuildMacDist.sh
Resolves #9481
Should fix the problem with the build system.
=> 9481 Fix build files to located .bib

ApsimNG/Resources/Toolboxes/ManagementToolbox.apsimx
Resolves #9476
Decided to add this to the toolbox instead of the wheat example since it may be usable in other crops as well.
=> 9476 Added Set Emergence script to management toolbox

Docs/README.md, Docs/_redirects, Docs/content/ModelDocumentation/_index.md
=> added _redirects file to make netlify redirect to new documentation site.

Models/Management/Manager.cs
Resolves #9508
When adding the ability to load apsimng without compiling scripts the other day in #9498, it uncovered a bug that previously caused scripts to double compile at the same time if you opened and ran a file too quickly (since the script would be compiling in a background thread from load, and then again when run was pressed in the foreground).
The solution was to just add a lock around the compiler function, so that if it is currently compiling, the other thread can't get in and start a 2nd round of compiling and cause this error.
=> 9508 Add lock around compiling script to prevent threading error

Docs/_redirects, Docs/content/ModelDocumentation/_index.md
=> second attempt at creating a redirect to new documentation site

README.md
resolves #9517
This adds dynamic status badges to the repo readme file.
=> Netlify and Jenkins build status badges

APSIM.Documentation/Models/Types/DocSimulations.cs, APSIM.Documentation/WebDocs.cs
=> Add Sorghum DCaPST handling to documentation + GetPage tidy up

Models/AgPasture/SimpleGrazing.cs
=> Fix faulty logic on grazing trigger biomass in SimpleGrazing

Models/AgPasture/SimpleGrazing.cs
=> Hide a feature not yet ready for release in SimpleGrazing

Models/Core/ConfigFile/ConfigFile.cs, Models/Core/Overrides.cs
Resolves #9553
Resolves #9548 
Ready to merge. Config now can handle empty lines and multi-line specifications.
=> Fix handling of factors' Specifications in config file.

Models/Core/ConfigFile/ConfigFile.cs
Resolves #9560
Ready to merge.
=> Override commands must work with absolute paths

Models/Graph/SeriesDefinition.cs
=> Allow filters to match regardless of case.

Setup/net8.0/windows/buildWindowsInstaller
Resolves #9503 
Created a new script for deploying windows for the new deploy pipeline.
=> 9503 New windows installer script

Gtk.Sheet/Gtk.Sheet.csproj
=> 9503 Add flag to avoid .net 8 warning

Setup/net8.0/windows/buildWindowsInstaller
=> 9503 Fixes for signing paths

Models/CLEM/Activities/CLEMRuminantActivityBase.cs, Models/CLEM/Activities/PastureActivityCutAndCarry.cs, Models/CLEM/Activities/RuminantActivityGrazeAll.cs, Models/CLEM/Activities/RuminantActivityGrazePasture.cs, Models/CLEM/Activities/RuminantActivityGrazePastureHerd.cs, Models/CLEM/Activities/RuminantActivityHerdCost.cs, Models/CLEM/Activities/RuminantActivityManage.cs, Models/CLEM/Activities/RuminantActivityMarkForSale.cs, Models/CLEM/Activities/RuminantActivityMilking.cs, Models/CLEM/Activities/RuminantActivityShear.cs, Models/CLEM/Activities/RuminantActivityTag.cs, Models/CLEM/Activities/RuminantActivityWean.cs
=> Update to fix multi-herd simulations in CLEM

ApsimNG/Menus/ContextMenu.cs, ApsimNG/Presenters/DocumentationPresenter.cs
resolves #9528
Enhance the handling of model visibility in the context menu and improve error handling during documentation loading. This addresses issues with hidden model structures and ensures a smoother user experience.
=> Refactor context menu model visibility and improve error handling when showing Model description in view

ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Views/GraphView.cs, Docs/content/Usage/graphs/DatetimeXAxes.md, Docs/content/Usage/graphs/_index.md
resolves #9475 
Enhance clarity and functionality of the GraphView and GraphPresenter. Introduce interval handling for datetime x axes and provide documentation on interval details.
=> Refactor GraphView and GraphPresenter for datetime x axes intervals

.vscode/launch.json, Models/Functions/AccumulateByNumericPhase.cs, Models/Functions/AccumulateFunction.cs, Models/PMF/BiomassArbitration/Organ.cs, Models/PMF/HarvestingParameters.cs, Models/PMF/Organs/GenericOrgan.cs, Models/PMF/Organs/HIReproductiveOrgan.cs, Models/PMF/Organs/Leaf.cs, Models/PMF/Organs/Nodule.cs, Models/PMF/Organs/PerennialLeaf.cs, Models/PMF/Organs/ReproductiveOrgan.cs, Models/PMF/Organs/Root.cs, Models/PMF/Organs/SimpleLeaf.cs, Models/PMF/Organs/SorghumLeaf.cs, Models/PMF/Plant.cs
Resolves #9434
Makes Accumulator better match original functionality when it was attached to the harvesting event
=> 9434 Move Biomass removal check to organs

Models/Functions/AccumulateFunctionGeneral.cs
that can be configured to do the job of most the other accumulate functions
working on #9613
Still need to write a converter to move the existing accumulate functions onto this generic function then deprecate the other
=> Add general accumulate functions 

Models/PMF/Phenology/CAMP/CAMP.cs, Models/PMF/Phenology/CAMP/CalcCAMPVrnRates.cs, Models/PMF/Phenology/Scales/ZadokPMFWheat.cs, Models/Resources/Wheat.json, Prototypes/CroptimizR/template.apsimx
working on #7623
Need to remove hard coded paths from source code to facilitate model restructuring
=> Remove hard coded references from classes 

Models/Resources/Grapevine.json
Working on #9559
add a new grapevine cultivar name
=> add a new grapevine cultivar

APSIM.Shared/Utilities/ApsimTextFile.cs, Models/Soils/SoilTemp/SoilTemperature.cs
=> SoilTemp2 changes

ApsimNG/Presenters/ManagerPresenter.cs
=> 9628 Manager reformats whats on screen when reformatting script

Models/Functions/SoilFunctions/CERESDenitrificationModel.cs
=> Added the new carbon function

Docs/content/User_tutorials/Module1/ModuleOneTutorial.md
working on #9667
Corrected phrasing of 2 lines
=> Update ModuleOneTutorial.md working on #9667

Examples/Tutorials/SlowReleaseFertiliser.apsimx, Models/Management/Fertiliser.cs, Models/Management/FertiliserPool.cs, Models/Management/FertiliserType.cs, Tests/UnitTests/FertiliserTests.cs
=> Added age to FertiliserPool. Made FertiliserPool a model.

Docs/content/User_tutorials/Module2/ModuleTwoTutorial.md
working on #9670 
Added two sub-steps asking to remove the Report Variable [Weather].Rain from the report in Clay Residue and Clay Chickpea Residue simulations
=> Add detail to ModuleTwoTutorial.md

APSIM.Documentation/Models/Types/DocZadokPMFWheat.cs, Models/PMF/Phenology/Scales/ZadokPMFWheat.cs
resolves #9626
Including this doc in the docs.apsim.info site will come in another PR for the APSIM.Docs repo.
=> refactor: add stage names and mappings for Zadok stages in wheat model

Models/Management/FertiliserPool.cs, Tests/UnitTests/FertiliserTests.cs
=> Release rate changed to be fraction of initial application amount

Models/Soils/SWIM/Swim.cs
=> SubDailyIrrigation Fix

Models/Graph/GraphPage.cs
=> Added ability for a regression to be a direct child of graph

Models/Resources/Canola.json
Resolves #9735
Changed it from a multiline comment to a single line comment and now it works.
=> 9735 Fixed Canola Hyola450_TT cultivar comment

Models/Core/Run/SimulationGroup.cs
=> Stop disabled tests from running

ApsimNG/Commands/ReplaceModelCommand.cs, ApsimNG/Presenters/GridPresenter.cs, ApsimNG/Views/MenuView.cs
=> Undo doesn't work with ReplaceModelCommand instances

ApsimNG/Presenters/ReportPresenter.cs
=> Changed report event panel to show variables in intellisense.

Models/AgPasture/PastureSpecies.cs
=> Fixed connection between AgPasture and SoilArbitrator N arbitration

Tests/Simulation/SoilNitrogenPatch/PatchyMcPatchFace.apsimx
=> Fix patching stats

Models/Surface/SurfaceOrganicMatter.cs
=> Added a bool verbose property to stop large summary files

Models/Soils/SoilStandardise.cs
=> Fix to CEC soil standardiser

Models/Core/ApsimFile/FileFormat.cs
Resolves #9786
When loading a file that doesn't have a Simulations as the root node (such as an APSoil soil), it will now be appended as a child of a Simulations when it's loaded.
Also cleaned up ReadFromFile function which was duplicating functionality that was already been done in ReadFromString which it calls.
=> 9786 Add simulations if it's not the root node

Models/Resources/Wheat.json
=> Add preliminary cultivars

ApsimNG/Presenters/SoilDownloadPresenter.cs
resolves #9793
Add a check for both CERES and regular soil temperature models before initializing a SoilTemperature model
=> Refactor soil temperature model initialization

ApsimNG/Presenters/GenericPresenter.cs
resolves #9799
Correct the formatting of the model type display in the GenericPresenter to improve readability.
=> Fix model type display formatting in GenericPresenter

Models/AgPasture/UrineDungPatches.cs
=> Get patches talking to the right type of dung

ApsimNG/Interfaces/IGraphView.cs, ApsimNG/Presenters/GraphPresenter.cs, ApsimNG/Utility/LineSeriesWithTracker.cs, ApsimNG/Views/GraphView.cs, Models/Graph/SeriesDefinition.cs
=> 9837 Adds simulation name to tooltip when clicking on graph points

Models/Core/ApsimFile/JsonUtilities.cs, Models/Main.cs, Models/Options.cs, Tests/UnitTests/CommandLineArgsTests.cs
resolves #9823
Adds an switch that enables a user to fetch a apsimx file version number
=> Models file version number switch

Models/Functions/SubdailyDeWit.cs
Resolves #9728 
This uses the max and min temperatures of the adjacent days, similar to the Gourdriaan method.
=> Add in subdaily DeWit function.

Models/PMF/Organs/Leaf.cs
=> Make NewLeaf EventHandler type

Docs/content/TechnicalInformation/Versioning.md, Docs/content/TechnicalInformation/_index.md
=> apsim software and file versions and quirks documentation

README.md
=> Elaborate on AI acronyms in README.md

.vscode/launch.json
=> 9886 Release build shouldn't look for debug symbols

Models/Core/ApsimFile/Structure.cs, Models/Core/Folder.cs
=> 9859 Allow folders under any parent

Models/PMF/Cultivar/Cultivar.cs
=> Add oilpalm as a valid parent for cultivar model

README.md
=> 9944 Add empty line to readme to reset POStats

Examples/BiomassRemovalFromPlant.apsimx, Models/Functions/OnEventFunction.cs, Models/Management/BiomassRemovalEvents.cs, Models/PMF/Phenology/Phenology.cs, Prototypes/SCRUM/SCRUM.apsimx
=> A few more fixes to BiomassRemovalEvent

Models/PMF/Organs/SimpleLeaf.cs
=> Add functionality so biomass removals affect LAI and cover

Models/Core/VariableProperty.cs
=> Try to avoid recursion when setting values of Objects from strings.

Prototypes/Rice/rice.apsimx
=> Upgrade rice prototype to version 195.

Examples/AgPasture.apsimx, Models/AgPasture/PastureSpecies.cs
=> Add cultivar support to AgPasture

Models/Surface/OMFractionType.cs, Models/Surface/SurfOrganicMatterType.cs, Models/Surface/SurfaceOrganicMatter.cs
=> SurfaceOrganicMatter: Fixed Incorporated output. Added Removed output.

Models/PMF/Phenology/Phases/GotoPhase.cs, Models/PMF/Phenology/Phenology.cs, Prototypes/DEROPAPY/Deropapy.apsimx
=> Append "GoTo_" to EndStage name for GotoPhase

Models/AgPasture/SimpleGrazing.cs
=> Added error when SimpleGrazing is not at top level of sim

Models/Soils/Soil.cs
=> Added extra soil checks

Models/AgPasture/SimpleGrazing.cs
=> Changed test to apply only for explicit patches

APSIM.Core/Nodes/Node.cs, Models/Core/Simulations.cs
=> Fix Node.FileName not being updated on SaveAs

APSIM.Shared/Utilities/DateUtilities.cs, Tests/UnitTests/UtilityTests/DataUtilitiesTests.cs
=> 10029 Fix Date code to handle NZ localization change

APSIM.Core/ApsimFile/FileFormat.cs, APSIM.Core/Nodes/ICreatable.cs, APSIM.Core/Nodes/Node.cs, Models/Core/Model.cs, Models/Management/Manager.cs, Tests/UnitTests/Manager/ManagerTests.cs
=> Fix manager not saving updated parameter values

APSIM.Core/Nodes/Node.cs, Tests/UnitTests/APSIM.Core/ApsimFile/StructureTests.cs
=> Ensure copy-paste of model sets Node.Compiler in pasted model.

Models/Management/Manager.cs, Tests/UnitTests/Manager/ManagerTests.cs
=> Stop removing manager parameters on failed compile.

ApsimNG/Resources/Glade/ProfileView.glade, ApsimNG/Views/GraphView.cs
=> 10143 Fix Graphs in ProfilePresenter

ApsimNG/Presenters/GraphPresenter.cs
=> 10122 Fix Axis bounds setting

Models/Resources/WinterCereal.json
=> Add resource for WinterCereal

ApsimNG/Presenters/SoilDownloadPresenter.cs
=> 10156 Fix and Simplify APSoil soil downloading

Models/Resources/WinterCereal.json
=> remove [Wheat] references

Tests/UnitTests/Plant/PlantTests.cs
=> Test for Leaf model type and use appropriate parameter test

APSIM.Core/Nodes/Node.cs, APSIM.Core/Nodes/NodeExtensions.cs, ApsimNG/Commands/RenameModelCommand.cs, ApsimNG/EventArguments/NeedContextItemsArgs.cs, ApsimNG/Presenters/ExplorerPresenter.cs, Models/Core/Structure.cs, Tests/UnitTests/APSIM.Core/NodeTreeTests.cs
=> Fixed node rename and intellisense

ApsimNG/Presenters/XYPairsPresenter.cs
=> Fix XYPairs presenter

ApsimNG/Classes/Property.cs, Models/Management/BiomassRemovalEvents.cs
Resolves #10243 
Resolves #10015 
A combination of changes from other changes caused the issues we were seeing here, this has the view working again.
=> 10243 BiomassRemovalEvents Fix grid and phenology dropdown

Models/MicroClimate/MicroClimateZone.cs
=> Fix for MicroClimate for plants that go dormant e.g. clover

Models/Functions/ExpressionFunction.cs, Models/PMF/Phenology/Scales/Age.cs
=> Small fixes

ApsimNG/EventArguments/NeedContextItemsArgs.cs, Tests/UnitTests/APSIMNG/IntellisenseTests.cs
=> Fix intellisense bug and add unit test

Models/Sugarcane/Sugarcane.cs
=> Improved error message when ratoon cultivar is missing.

APSIM.Core/ApsimFile/FileFormat.cs, Tests/UnitTests/APSIM.Core/ApsimFile/FileFormatTests.cs
=> Stop serialisation of links and jsonignores

.github/workflows/run-model-validations.yml
resolves #10303
This is a required file to use the new build system github workflow.
=> add the model validation workflow file

.github/workflows/run-model-validations.yml, README.md
=> Get correct PR in validation GitHub workflow

.github/workflows/run-model-validations.yml
=> Get pr number using label index

.github/workflows/run-model-validations.yml
=> another attempt at PR number fetching for github workflow

.github/workflows/run-model-validations.yml
resolves #10303
This should be the last workflow file configuration required for now.
=> Set job count

Models/ForageDigestibility/Forages.cs, Tests/UnitTests/Stock/ForagesTests.cs
=> Stopped forages parameterisations multiplying.

ApsimNG/Presenters/AddModelPresenter.cs
=> Fix add model in GUI

.github/workflows/run-model-validations.yml, APSIM.Shared/Utilities/SQLite.cs, APSIM.Workflow/WorkFloFileUtilities.cs
resolves #10367
resolves #10346
=> Add workflow condition to stop triggers

ApsimNG/Presenters/ProfilePresenter.cs, Models/Soils/SoilStandardise.cs, Tests/UnitTests/Soils/SoilStandardiserTests.cs
=> Dewonkyify soil models that don't have thickness specified

.github/workflows/run-model-validations.yml, APSIM.Workflow/FileSplitter.cs, Tests/Validation/Wheat/split.json
Working on #9617
Adding logging information for github workflow
=> 9617 File Splitting for Wheat Validation

ApsimNG/Presenters/ProfilePresenter.cs
=> Guard against "physical" being null

.github/workflows/run-model-validations.yml
=> Ensure we are in the repo directory for master merge

.github/workflows/run-model-validations.yml
working on #10487
More git history may prove helpful when trying to merge in master branch
=> Attempt providing more git history for merge

.github/workflows/run-model-validations.yml
working on #10487
This is a small addition to help with validation workflow speed.
=> Split the FAR validation as part of the validation workflow

APSIM.Server/V1/APSIM.Server.csproj, ApsimNG/Presenters/SummaryPresenter.cs
Resolves #10483
dependabot didn't quite get it right
=> Update Kubernetes and replace obsolete "IsNullOrEmpty" test

APSIM.Workflow/FileSplitter.cs, ApsimNG/Presenters/GraphPanelPresenter.cs, ApsimNG/Utility/Graph.cs, Models/Core/Apsim.cs, Models/Core/IModel.cs, Models/Core/Model.cs, Models/Core/Run/SimulationGroup.cs, Tests/UnitTests/Core/LinksTests.cs, Tests/UnitTests/Utilities.cs
=> Remove ParentAllDescendants method from IModel and Model.

Models/Factorial/Factor.cs, Tests/UnitTests/Factorial/FactorTests.cs
=> 10535 Fix creation of Checkpoints

Models/Core/Apsim.cs, Models/Core/IModel.cs, Models/Core/Model.cs, Models/Core/Structure.cs, Tests/UnitTests/APSIM.Core/ApsimFile/StructureTests.cs, Tests/UnitTests/APSIM.Core/ModelTests.cs, Tests/UnitTests/SummaryTests.cs
Merge 2 implementations of IsChildAllowable into one.
Working on #9939
=> Remove IsChildAllowable from IModel and Model. 

.github/workflows/scripts/enable-azure-pool-autoscaling.sh, .github/workflows/scripts/start-azure-pool.sh
resolves #10579
This PR adds in the required braces to fix this issue.
=> Fix bash variable expansion in validation workflow bash files

.github/workflows/run-model-validations.yml
Working on #10579
New workflow is not working, restoring old version so it can run again.
=> 10579 Revert github workflow for now

Models/Resources/WinterCereal.json
=> Stem partition fraction a function of haun stage in early growth
